### PR TITLE
Start adding windows shares config. Remove a logger.ERROR I was using…

### PR DESCRIPTION
**Pull request by miigotu**
… for debug in t411

Fixes #

Proposed changes in this pull request:
-
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
@sharkykh just need to work on the html/js and it will be done =P
Im taking a break from it, there are no links to it yet to effect end users, but it is at `/config/shares`
The form doesnt work yet.

**Comment by sharkykh** [comment]
Tried to work on that earlier today. I used to know a bit more in terms of web design a few years back, but now - only the basics, and even that...
Seriously. I was like sitting with the code in front of me and didn't even know where to start.
_\*sigh\*_

**Comment by miigotu** [comment]
Yeah its nbd, its something for sort of a when I have time ill mess with it. Because really if someone is using sickrage with windows and they want to use shares they should be able to figure something out. There are plenty of guides and issues explaining exactly what they need to do

**Pull request merged**
