### PR TITLE
Origin/wdtv dots in metadata

### PR DESCRIPTION
**Pull request by pjg101**
Fixes #
## 
## 
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by pjg101** [comment]
Sorry..  ignore this request. I was messing around with SourceTree.Too many years on SVN and CVS :)

```
  From: SickRage <notifications@github.com>
```

 To: SickRage/SickRage SickRage@noreply.github.com 
Cc: pjg101 peterjgreen@yahoo.com
 Sent: Monday, 29 February 2016, 0:21
 Subject: Re: [SickRage] Origin/wdtv dots in metadata (#1083)

Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked   
-  Give a description on what the PR is for.
-  Make sure your PR is based on the DEVELOP branch
-  Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
  Please make sure you also read contribution guide and followed all of the steps.Thanks!—

**Comment by OmgImAlexis** [comment]
Please don't open PRs against master also this wouldn't be accepted since you're adding code that's not needed like the check to see if your branch is checked out. If you want to work on code without the error just enable `DEVELOPER` in the `config.ini` file.

**Comment by pjg101** [comment]
And as I said directly after I did it, this was accidental. 
Regards

**Pull request closed without merging**
