### PR TITLE
Remove duplicate function definition

### PR DESCRIPTION
**Pull request by MGaetan89**
The `to_int` function is redundant, as we have a `try_int` function, which is tested.
I also used the `try_int` function in a couple more places.

### CODE REVIEW

**Comment by miigotu** [comment]
Only curious about the to_int in config, are we sure that is right?

**Comment by MGaetan89** [comment]
I guess it is.
What's bugging you about it?

**Comment by miigotu** [comment]
Idk, the to_int in config comes from the lib for handling config. Just felt like thats the one it should use lol. Its ok though.

**Comment by MGaetan89** [comment]
I didn't know that it came from a lib.
`to_int` and `try_int` have almost the same code (just syntactic differences). So it should still work as before.

**Pull request merged**
