### PR TITLE
Filter commits in grunt/exec/git_list_changes task

### LINKED ISSUE #3631: Warn user when show skipped during add show search due to already in show list
When adding a show that already exists the search will skip shows that have already been added without any hint of this to the user unless they then check the logs. It would be nice to have a message above or under the search list in Add Shows that says pre-existing item(s) were skipped
Would come in nice for large libraries where a user may not realize a show has already been added and think its an issue with the indexer not finding the show.

Branch: master
Commit: 1d28b358576b35b101bb0f662858ae5296d2ef8b
OS:  Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with 
What you did: Tried to add existing show
What happened: Search Results reports "No results found, try a different search." Even though it actually did find a result and skipped it.
What you expected: Warn that a show, or what show(s), was skipped. "No results found, try a different search. 1 show skipped, view log"

Logs:
```
INFO     Thread-18 :: Skipping Re:CREATORS in the search results because it's already in your show list
```

### PR DESCRIPTION
**Pull request by sharkykh**
@miigotu 
This will fix the automated changes list generator for the publish task.
It will ignore the commits merged by **merge-commits**, but it will keep the actual merge commits.
## For example, the next version:
Unwanted commits marked with `-`, merge commits marked with `+`
[[Comparison on Github](https://github.com/SickRage/SickRage/compare/v2017.06.05-1...b5ae6efbe48c8150b4120b6ba4881024c049d6a3), but it's easier to see with a graphical git client..]
```diff
Fix qBittorrent (#3836)
Try and fix multiple desktop notifications (#3837)

[... skipping ...]

Re-apply isort (#3908)
Swap jshint with xo (+2 more small fixes) (#3916)
- fix base linting issues with core.js
- fix more core.js linting issues
- fix even more core.js linting issues
- CI: Stop if any of the tests fail
- CI: Try and fix AppVeyor
Switched to use sickbeard's TMDB API key. (#3920)
- Merge branch 'develop' into lint_corejs
- finish core.js linting
- Try out harmony branch for grunt-contrib-uglify
- CI: Fixes
- Review
- More lint
- Simplify filter_functions in shows list tablesorter
- Uglify using new plugin (need to do vender.min.js too)
- Uglify bower (maybe move this to a separate PR)
Docker support (#3901)
- switch click and change to on
- change $(this) to $(event.currentTarget)
- switch e to event, switch prop checked to native checked
- switch click and change to on (not core.js)
- More e to event
- Merge branch 'develop' into lint_corejs
- Update minified core
+ Merge pull request #3919 from SickRage/lint_corejs
- Merge branch 'develop' into lint_js-click-to-on
+ Merge pull request #3922 from SickRage/lint_js-click-to-on
- lint formwizard
- lint bookmarkscroll
- lint scrolltopcontrol
- Remove bower install from AppVeyor
core.js: Switch .checked on jQuery elements to .is('checked') (#3926)
- Fixes for formwizard.js
- Merge branch 'develop' into lint-js_libs
+ Merge pull request #3923 from SickRage/lint-js_libs
```

### CODE REVIEW

**Comment by sharkykh** [comment]
Well, I wanted it to automatically fetch the correct titles, but I can't right now.

**Comment by sharkykh** [comment]
> @sharkykh `grunt publish` is no longer working, can you look into that?

@miigotu 
What exactly doesn't work? Try with `-v` for verbose output...
I can't actually use these tasks so I don't know.

**Comment by miigotu** [comment]
"Warning: Task "ci" not found. Use --force to continue."

**Comment by sharkykh** [comment]
@miigotu Oh, right. This is because of the move to yarn. Give me a minute...

**Comment by sharkykh** [comment]
For now you can just remove `'ci'` from line 54 in `Gruntfile.js` because the equivalent is just `xo` for javascript lint (which is good at the moment)

Or run `grunt newrelease genchanges` which is the same thing.

**Comment by miigotu** [comment]
the ci task used to also run the python tests before allowing publish

**Comment by sharkykh** [comment]
@miigotu Nope, never did.
It used to run `jshint` and `mocha`.

**Pull request merged**
