### PR TITLE
Responsive ui - round 2

### PR DESCRIPTION
**Pull request by beschoenen**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by beschoenen** [comment]
@miigotu I want to try and make a material design theme for SickRage, what do i need to do register a new theme in SickRage?

**Comment by miigotu** [comment]
Just make a copy of the slick folder and rename it

**Comment by beschoenen** [comment]
I don't want to redo all the view, just some css.

Edit: Okay, i just added an `<option>` in the config page.

Also,
You can merge this, just keep the branch.

**Comment by miigotu** [comment]
you will have to rebase this branch now due to squash-and-merge feature of github.

**Pull request merged**
