### PR TITLE
NZB splitter updates

### PR DESCRIPTION
**Pull request by labrys**
@miigotu If you wouldn't mind taking a look at this before merging.  There are a couple of regex's that still need cleaning up and double check my logic for stupid mistakes since I'm pushing this while tired :P

### CODE REVIEW

**Comment by MGaetan89** [comment]
Can you rename the file in a separate PR (or don't rename it at all)? Because now it is not easy to review what you did from GitHub.
And @miigotu will probably complain because you have 6 commits in your PR :P

**Comment by labrys** [comment]
It ain't rebased yet.  And sorry git-extensions and PyCharm see it as a rename so the rename wasn't an issue here.  I'll change that shortly.

**Comment by labrys** [comment]
Pushed again without the file rename.

**Comment by miigotu** [comment]
Other than that regex likely failing on specific filenames it looks good for rebase and merge.

**Pull request merged**
