### PR TITLE
Refactor myDB variables

### PR DESCRIPTION
**Pull request by labrys**
Refactor `myDB` => `main_db_con`
Refactor `myDB` => `cache_db_con`
Refactor `myDB` => `failed_db_con`
Add prefix `test_` to `<dbname>_db_con` in tests

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
wtf is with the my prefix anyways? lol
I would say for examply `main_db_con` (main db connection)

**Comment by labrys** [comment]
@miigotu lol i agree, just wasn't going to change too much.. ill refactor again before merging this.

**Comment by miigotu** [comment]
Yeah, the `my` implies that it is a mySQL connection, which is misleading.

**Comment by labrys** [comment]
Approved with new names

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/767/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Pull request merged**
