### PR TITLE
Py3 - Finally

### LINKED ISSUE #6545: Python 3 support!
Hi Guys.

Is there any word on if-and-when SickChill will be usable in Python 3? 

I maintain a package for QNAP NAS users and my Python 2.7.16 source has just become unavailable. :disappointed:   

So, looking to create a Py3 version just as soon as it's possible. 

Thank you.

### PR DESCRIPTION
**Pull request by miigotu**
Fixes #6545 

In Progress:
- Fixing tests and providers, finding bugs

Done:
- Get running on python3
- Removed encode/decode trash
- Removed workarounds for windows for features added in python3 specifically for windows
- Removed SSL hacks
- Removed locale hacks
- Removed encoding Kluge hack
- Removed exception formatting hack
- Remove python2 support (supporting both will be a nightmare, maybe a backport will be possible)
- Handled trait API module
- jsonrpclib-pelix
- bencodepy
- Rework logger to use standardized logging
- remove old qbittorent and make new the default
- add new support for rtorrent and only support the new version
- refactor into sickchill from sickbeard module
- handle adba

To-Do:
- Check that python3 exists before allowing update in old mainline
- add new support for rtorrent and only support the new version
- remove old kodi, make kodi12+ default
- use logger args rather than .format

### CODE REVIEW

**Comment by OneCDOnly** [comment]
It works! Now running in QTS 4.2.6 on my old QNAP TS-559 Pro+

Worthy of a screenshot I say :smile: 

screenshot

BTW: the version number error is because I'm only doing a very shallow clone. This will be fixed when I re-add my code to clone from the current commit back to the last tag. :wink:

**Comment by OneCDOnly** [comment]
@miigotu with regard to Watcher3, [here's the issue](https://github.com/barbequesauce/Watcher3/issues/79) dealing with Py3.8

**Comment by miigotu** [comment]
Btw, the docker image built too xD `docker run -it sickchill sickchill/sickchill:py3-again`

**Comment by OneCDOnly** [comment]
@miigotu just following-up on that version error. For testing, I'm back on my Debian 10.4 workstation running Python 3.7.3

Cloning with: `git clone --branch py3-again --single-branch http://github.com/sickchill/sickchill.git`
Then execute: `python3 sickchill/SickBeard.py `

I get:
screenshot
The version error has changed. Any thoughts?

**Comment by miigotu** [comment]
@OneCDOnly yep, return value of the git command is messing up. I'll fix it tonight probably (currently working on unfucking the logging init and loading of clients/providers/notifiers even though they are working)

**Comment by OneCDOnly** [comment]
Confirmed: version now looks good. Nice work! :nerd_face: 

screenshot

**Pull request merged**
