### PR TITLE
Ability to use DSM for nzb's

### PR DESCRIPTION
**Pull request by miigotu**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

Show error messages for error codes returned from DSM according to DSM docs
Check DSM version, and fix the download location if it is absolute on DSM6

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by neoatomic** [comment]
Been testing the DSM6 branch.
The GUI section has some issues, under DS the sabnzb settings are shown. also under the NZBget section. I just added the settings and tried to test. And indeed got it working after some messing around. :)

First if there is no custom download path filled in the search settings than it doesn't work. : 

```
2016-03-25 15:27:28 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [Usenet-Crawler] :: Checking if we should keep searching after we've found South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN
2016-03-25 15:27:28 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-25 15:27:28 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading a result from Usenet-Crawler at https://www.usenet-crawler.com/getnzb/1528282a7f082de9b50c4e0b73e318b9.nzb&i=233093&r=**********
2016-03-25 15:27:28 DEBUG    SEARCHQUEUE-MANUAL-75897 :: GET URL: https://www.usenet-crawler.com/getnzb/1528282a7f082de9b50c4e0b73e318b9.nzb&i=233093&r=**********
2016-03-25 15:27:28 DEBUG    SEARCHQUEUE-MANUAL-75897 :: No parent path provided in South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN.nzb, unable to get permissions from it
2016-03-25 15:27:28 INFO     SEARCHQUEUE-MANUAL-75897 :: Saved result to South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN.nzb
2016-03-25 15:27:29 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Checking if we should stop searching for a better quality for for episode South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN
2016-03-25 15:27:29 DEBUG    SEARCHQUEUE-MANUAL-75897 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> South Park - 19x10 - PC Principal Final Justice - 1080p WEB-DL
2016-03-25 15:27:30 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Transaction with 1 queries executed
```

Then i added the custom path `public/Download` (dropped the /volume1/ ) and that worked, and the nzb was sent to DS. However DS didn't download the files from the usenet-server. It told me it was a "broken" link. See the first download in de screenshot. 

``` 
2016-03-25 15:30:54 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [Usenet-Crawler] :: Checking if we should keep searching after we've found South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN
2016-03-25 15:30:54 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-25 15:30:55 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': 'public/Download', u'uri':...
2016-03-25 15:30:55 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

As i had a fresh install of DSM6 i hadn't added the Usenet server to DS... So i did add that and did another manual search.

```
2016-03-25 15:35:25 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [Usenet-Crawler] :: Picked South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN as the best
2016-03-25 15:35:25 DEBUG    SEARCHQUEUE-MANUAL-75897 :: [Usenet-Crawler] :: Checking if we should keep searching after we've found South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN
2016-03-25 15:35:25 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-25 15:35:25 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': 'public/Download', u'uri':...
2016-03-25 15:35:25 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
2016-03-25 15:35:25 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Checking if we should stop searching for a better quality for for episode South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN
2016-03-25 15:35:25 DEBUG    SEARCHQUEUE-MANUAL-75897 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> South Park - 19x10 - PC Principal Final Justice - 1080p WEB-DL
2016-03-25 15:35:26 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Transaction with 1 queries executed
```

This time the nzb was snatched and sent to DS, and the download started. (see second download in the screenshot)

So when possible we need to do a (api) check to see if a Usenet server is added in DS. And if not give an appropriate log message.

Lastly i tried the same again with the full path in SR. (/volume1/public/Download)
That isn't working...

```
2016-03-25 15:50:31 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-25 15:50:31 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public/Download'...
2016-03-25 15:50:31 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-25 15:50:31 INFO     SEARCHQUEUE-MANUAL-75897 :: {u'success': False, u'error': {u'code': 403}}
```

Some other tings we might can look-into to are:

* See if labels like TV can be set for a download or if script can be run etc. (have to check the doc's if possible)
* Checking the downloaded progress of the snatched file over the api. 
(If that could be done than we can fully automate the PP process.)

DS is actually an modified/extended Transmission version.



naamloos

**Comment by miigotu** [comment]
I still have several things to sort out with this. I can simplify the who dsm6 check by simply trying to send it with whatever location we have and if it error 403's adjust the location and try again. All of that excess code can be removed.

About the ui, I didnt grunt it yet so you arent seeing the settings for DSM. However I need to rethink all of that since the user might have another client selected for torrents and that will break atm.

**Comment by neoatomic** [comment]
That might work. Only concern i have is will it use an additional/extra API call as the URL is two times sent to DS. I will have to test that.

Here are some more error codes, hope you can add those as well for support purposes. :)

```
For:
SYNO.DownloadStation.Task

            400: 'File upload failed',
            401: 'Max number of tasks reached',
            402: 'Destination denied',
            403: 'Destination does not exist',
            404: 'Invalid task id',
            405: 'Invalid task action',
            406: 'No default destination',
            407: 'Set destination failed',
            408: 'File does not exist'

For : 
SYNO.API.Auth

            400: 'No such account or incorrect password',
            401: 'Account disabled',
            402: 'Permission denied',
            403: '2-step verification code required',
            404: 'Failed to authenticate 2-step verification code'

In case you cant split them up because the have the same error code than. : 
Custom : 

            400: 'File upload failed OR No such account or incorrect password',
            401: 'Max number of tasks reached OR Account disabled',
            402: 'Destination denied OR Permission denied',
            403: 'Destination does not exist OR 2-step verification code required',
            404: 'Invalid task id OR Failed to authenticate 2-step verification code',
            405: 'Invalid task action',
            406: 'No default destination',
            407: 'Set destination failed',
            408: 'File does not exist'

```

**Comment by miigotu** [comment]
I will add the extra code descriptions.

As for the extra api call, it will only try it the first time after changing the location, because it will set the sickbeard.TORRENT_DIR to the proper value on a successful second try (which would then be saved on shutdown), so the next time the first try will succeed.

With all of that extra code I added it does the same thing, except it takes 2 extra api calls instead of one.

win-win situation if just using an eafp approach saves dozens of lines of code, takes one less api call, and ends up being more reliable.

I think I need to break out the username/password/host settings for DSM into their own in order to simplify the settings for nzb through DSM, so that it doesnt interfere with the possibility of using DSM for nzb while still using a different torrent client/settings.

**Comment by neoatomic** [comment]
Thinking, if we require users to fill in the DS settings under the Torrent section, then that would also mean they have to `Enable`  Torrents in SR.  (otherwise the cant fill it in.)
Its something i dont like. :(  And it will get confusing and also populate the torrent providers in the (long) provider list.

**Comment by miigotu** [comment]
Not necessary anymore, my last commits fixed that problem. After this is tested and its ready

**Comment by neoatomic** [comment]
Tested the latest DSM6 branch again.
Found 2 small bugs, but all is working.

Branch: dsm6
Commit: 1e26cc76cce39fa505e08a00a38f0d853f88f837

First the DS NZB cleint : 

The description of the link in the GUI is wrong. It states : `URL to your Synology DS (e.g. http://localhost:8000/) `
But the port should be 5000 (8000 is the old port that isn't used as far as i know.)
Just to be sure it tested, and the `test connection` wasn't working and a manual search did trow the below error. (Might want to add a log line about wrong URL/port if it occurs.? )

``` 
2016-03-26 19:53:58 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.Uncensored.1080p.WEB-DL.AAC2.0.H264-NTb[rartv] from Rarbg
2016-03-26 19:53:58 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-26 19:53:58 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 144, in snatchEpisode
    dlResult = client.sendTORRENT(result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 209, in sendTORRENT
    if not (self.auth or self._get_auth()):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/download_station_client.py", line 142, in _get_auth
    self.response = self.session.get(self.urls['login'], params=params, verify=False)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 578, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /webapi/auth.cgi?session=DownloadStation&account=**********&version=2&format=cookie&passwd=********&api=SYNO.API.Auth&method=login (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fdce85b3310>: Failed to establish a new connection: [Errno 111] Connection refused',))

```


Test 1 
NZB Client **without ** path set in SR. (off-course path set in DS itself, otherwise it wont work :) )
Working (sent & nzb is downloading)

Test 2
NZB Client with full root path /volume1/public/Download
Working (sent & nzb is downloading)

Bug found : 
Only the GUI path field in the Torrent client gets reset to public/Download. On the nzb client its still stays /volume1/public/Download. 
Looks to me that both are using the same config.ini entry.? Or it does reset the wrong path entry (DS torrent client).

```
2016-03-26 19:33:23 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-26 19:33:23 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-26 19:33:23 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public/Download'...
2016-03-26 19:33:23 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-26 19:33:23 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'public/Download', u'uri'...
2016-03-26 19:33:24 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

Test 3
Torrent client with full root path. /volume1/public/Download
Working (sent & torrent is downloading)

```
2016-03-26 19:39:53 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.Uncensored.1080p.WEB-DL.AAC2.0.H264-NTb[rartv] from Rarbg
2016-03-26 19:39:53 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-26 19:39:54 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public/Download'...
2016-03-26 19:39:54 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-26 19:39:54 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'public/Download', u'uri'...
2016-03-26 19:39:55 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

Test 4 
Torrent client **without ** path.
Working (sent & torrent is downloading)

```
2016-03-26 19:44:21 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.Uncensored.1080p.WEB-DL.AAC2.0.H264-NTb[rartv] from Rarbg
2016-03-26 19:44:21 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-26 19:44:21 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public/Download'...
2016-03-26 19:44:21 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-26 19:44:21 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'public/Download', u'uri'...
2016-03-26 19:44:22 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

Test 5
Torrent client with path /volume1/public/ (dropped the sub folder to emulate normal/common situation/setup.)
Working (sent & torrent is downloading)

```
2016-03-26 19:48:37 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.Uncensored.1080p.WEB-DL.AAC2.0.H264-NTb[rartv] from Rarbg
2016-03-26 19:48:37 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-26 19:48:37 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public', u'uri':...
2016-03-26 19:48:38 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-26 19:48:38 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'public', u'uri': u'magne...
2016-03-26 19:48:38 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

**Comment by neoatomic** [comment]
Did a quick test. Seems that the ds nzb client is using the URL from the ds torrent client.

Some DS API python stuff i found. : 

https://github.com/gspanos/synopy
http://downloadstation.jroene.de/downloadstation

**Comment by miigotu** [comment]
Calm down, lol, it is t finished yet

**Comment by miigotu** [comment]
will work on this more tonight. its a pain in the ass since Im only using one instance of the DSM client. I think I might need to create a second instance of the client class in order to be able to keep the settings separate. Its quite complicated to keep them merged. The downside is that then you MUST set the settings separately, upside is that you could even send NZB to one nas and torrent to another nas if you had 2x nas.

Quite a few dilemmas here

**Comment by piejanssens** [comment]
This will always require monitoring of the download folder (= spinning up disks), right?
I'm not aware that DS could trigger nzbToMedia upon completion.

**Comment by miigotu** [comment]
It would work with torrentToMedia just fine

**Comment by miigotu** [comment]
@neoatomic can you test again please?

**Comment by miigotu** [comment]
@djoole you could checkout this branch and try it out, 
From my last commit:

```
If a word is in the global ignored words and in the show's required words, it is required
If a word is in the global required but in the show's ignored, it is ignored
```

In other words, show specific settings override the global setting.

**Comment by neoatomic** [comment]
All is working/looking fine. :+1: 

NZB client without custom download path.
Working.

```
2016-03-31 14:21:15 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-31 14:21:15 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-31 14:21:16 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'session': u'DownloadStation', u'api': u'SYNO.DownloadStation.Task', u'version': u'1', u'uri': u'...
2016-03-31 14:21:16 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

NZB client with custom download path. 
Working.

```
2016-03-31 14:03:56 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN from Usenet-Crawler
2016-03-31 14:03:56 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-31 14:03:56 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public/Downloads...
2016-03-31 14:03:56 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-31 14:03:56 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'public/Downloads', u'uri...
2016-03-31 14:03:57 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

Torrent client without custom download path. 
Working.

```
2016-03-31 14:22:26 INFO     SEARCHQUEUE-MANUAL-75897 :: Downloading South.Park.S19E10.Uncensored.1080p.WEB-DL.AAC2.0.H264-NTb[rartv] from Rarbg
2016-03-31 14:22:26 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-31 14:22:26 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'session': u'DownloadStation', u'api': u'SYNO.DownloadStation.Task', u'version': u'1', u'uri': u'...
2016-03-31 14:22:27 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

Torrent client with custom download path. 
Working.

```
2016-03-31 14:17:39 DEBUG    SEARCHQUEUE-MANUAL-75897 :: Calling DownloadStation Client
2016-03-31 14:17:39 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': '/volume1/public/Downloads...
2016-03-31 14:17:39 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"error":{"code":403},"success":false}
2016-03-31 14:17:39 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Requested a POST connection to url http://localhost:5000/webapi/DownloadStation/task.cgi and data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'public/Downloads', u'uri...
2016-03-31 14:17:40 DEBUG    SEARCHQUEUE-MANUAL-75897 :: DownloadStation: Response to the POST request is {"success":true}
```

**Comment by neoatomic** [comment]
Just tested HTTPS ( https://localhost:5001/ ) and that is also working fine. :+1:

**Pull request merged**
