### PR TITLE
Add custom_url option for kat and tpb, set them like "http://kat.cr" …

### PR DESCRIPTION
**Pull request by miigotu**
Use the official urls by default, can type in a mirror url in the "Custom url" field of the provider's setting if the official one is blocked for you.

Fixes https://github.com/SickRage/sickrage-issues/issues/7

This is the initial step towards having a list that autoselects the best mirror.

This does not mask the custom url from logs (intentionally) and also updates the href url you are taken to when clicking on the provider icon.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
It'd be a good idea to either link to https://kastatus.com/ or list the official mirrors and others we know that work with SickRage on the wiki.

**Comment by miigotu** [comment]
Eventually we can either do one of two things:

Include a preset list of mirrors, maybe 5, selectable with a dropdown and have the last option as "Custom"

Include a list internally and autoselect the best one every time one fails. (no gui setting)

**Comment by OmgImAlexis** [comment]
A mix of both would be good. We could try to auto select and if all fail then log it as an error and ask them to try a custom one.
If they have a custom one we'd use that though.

**Comment by miigotu** [comment]
Sure, just still unsure of a reliable, clean, and stable way of implementing the auto-select just yet. When the vision comes to me I will create that masterpiece =P

**Comment by OmgImAlexis** [comment]
Sounds good.

**Comment by fernandog** [comment]
What about adding a test button with a fixed search string?

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked
- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
Ouch, might need to run separate bots

**Pull request merged**
