### PR TITLE
Fix scene search

### PR DESCRIPTION
**Pull request by h3llrais3r**
Fix for scenario explained at

I'm not sure it this is the way to go, but I think we should compare the
scene season if we are searching in scene mode... otherwise you'll never
get a match during the initial search because the normal season is
compared with the scene season.

Hopefully this doesn't brake anything else... I only fixed this specific scenario... but I think it shoud no have impact on other scenario's...

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Please dont link that other repo on this repo, thanks for the PR though.

**Comment by h3llrais3r** [comment]
I didn't want to repeat the whole issue description, that's the only reason why I linked to the comment in the repo.

**Comment by miigotu** [comment]
no worries

**Pull request merged**
