### PR TITLE
fixed restart.js not reloading after restart

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This still needs some work but at least it now actually reloads when trying to do a restart. This should also work for the update restart page.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
@miigotu is it failing because of the `core.min.js`?

**Comment by miigotu** [comment]
Github has been having backend issues with webhooks tonight

**Comment by miigotu** [comment]
@OmgImAlexis if you rebase on develop and fix the conflicts it might run the tests =P, not sure though

Or, PR from a different branch than your develop branch.

**Comment by OmgImAlexis** [comment]
There's no conflicts that I can see and I added this after doing a `git fetch upstream && git reset --hard` on my dev branch.

Even now, I tried rebasing and it does nothing.

**Pull request closed without merging**
