### PR TITLE
Add media_format optional parameter for show.getposter api command.

### PR DESCRIPTION
**Pull request by darklow**
Proposed changes in this pull request:
- Adds feature to retrieve thumbnail size poster through API

Currently there is no way to retrieve thumbnail size poster in API. ShowPoster media class already has this functionality and all that is needed is to add same param to API.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Need to add `desc` to that new dict

**Comment by darklow** [comment]
@miigotu ouch sorry, I did tested my changes, but misunderstood little how description should be added for params. I created a commit which adds proper description: https://github.com/darklow/SickRage/commit/9120480c43eae8bd9c6c11f03ddb1005232a6fcc
Usually new commit automatically appear to PR, but I guess because this commit is already merged it won't happen. Should I create a new branch and new pull request?

**Comment by miigotu** [comment]
yep a new PR is ok.

**Comment by miigotu** [comment]
Also, you could add `banner` as an option I think

**Comment by darklow** [comment]
`banner` has its own API. But I could add same `media_format` for `ShowBanner` webapi as well.
https://github.com/SickRage/SickRage/blob/master/sickbeard/webapi.py#L2283
https://github.com/SickRage/SickRage/blob/master/sickrage/media/ShowBanner.py#L37

**Comment by miigotu** [comment]
There you go, add it for banner too if you want =P

**Pull request merged**
