### PR TITLE
django-like Site messages

### PR DESCRIPTION
**Pull request by miigotu**
Add a site messaging system similar to django messages, whom can be dismissed.
    Also, use a notification modal instead of alerts
    Use jquery post instead of jquery get for most calls from core.js.... post doesnt cache response data

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by ahyear** [comment]
hello,
why did you remove the like to the update? I think it was very useful.

Thank you.

**Comment by miigotu** [comment]
I didnt remove the link, I removed the duplicate messages when the number of commits behind changed.

image

**Comment by ahyear** [comment]
oh yes sorry ! my bad!
was thinking about this commit 3bb721f03367cd2f9e034ba24e60ec1fdd471811 but the response to my question is IN the commit ^^

**Pull request merged**
