### PR TITLE
Add pip support

### PR DESCRIPTION
**Pull request by satreix**
As mentionned here https://github.com/SickRage/sickrage-issues/issues/390.

To setup the venv:

```
virtualenv -p python2 venv
source venv/bin/activate
pip install requirements.txt
```

I did not remove any packages from _/lib_ just yet but that is where I want to go. :smile:

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by MGaetan89** [comment]
Isn't the file `requirements.txt` missing?

**Comment by satreix** [comment]
> Isn't the file requirements.txt missing?

I did not remove any packages from /lib just yet. I got told not in the following issue not to make to big of a diff: SickRage/sickrage-issues#390.

**Comment by MGaetan89** [comment]
I know, but in your example commands, you used `pip install requirements.txt`, but there is no `requirements.txt` in the SickRage project anymore (unless it is not at the root?).

**Comment by satreix** [comment]
Stupid me :stuck_out_tongue_closed_eyes: You are right.

https://github.com/satreix/sickrage-community/commit/d0d023b7440934e7a0dc35ad1b1b497c90e795f8 should fix the issue.

**Comment by satreix** [comment]
@miigotu `DO NOT MERGE` ?

**Comment by fernandog** [comment]
this label is for no one merge until @miigotu check/aprove the PR

**Comment by fernandog** [comment]
@satreix can you create the requirements.txt based on the /lib ?

**Comment by satreix** [comment]
@miigotu ech beats us to it.
https://github.com/SiCKRAGETV/SickRage/blob/updates-122415/requirements.txt

**Comment by labrys** [comment]
@satreix except he didn't do it right.

**Comment by satreix** [comment]
@labrys how so?

**Comment by miigotu** [comment]
@satreix ech is jumping the gun. Forcing pip locks out over half of his potential users. He just doesnt think things through whatsoever.

**Comment by satreix** [comment]
How is `pip` locking people out people? Is you package manger locking you out of anything?
I do not get it :disappointed: .

**Comment by duramato** [comment]
@satreix There are some systems that unfortunally cant run pip

**Comment by satreix** [comment]
For the systems that do not support `pip`, offer a way to package the dependencies another way (script?) or just release pre-built package (through Github releases), possibly build through Travis.

:snake: :heart: :package: , thus `pip` is still the way to go.

**Comment by labrys** [comment]
@satreix Yes PIP is the way to go, but not without having a complete solution in place first was the point that was being made.  PIP should be the default when it's available on a system, which is why I really like where you're going with this. :+1:

**Comment by satreix** [comment]
So what is the next step on this PR? :smile:

**Comment by labrys** [comment]
@satreix Have you removed all PIP requirements from the lib directory, ran setup and thoroughly tested that all elements are still functional?

**Comment by satreix** [comment]
Anything I touch (and revert for this matter) blows the testsuite to :hankey: 

For exemple installing `requests` with `pip` and running the tests gives:

```
FAIL: test_scene_ex_babylon_5 (scene_helpers_tests.SceneExceptionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../tests/scene_helpers_tests.py", line 158, in test_scene_ex_babylon_5
    self.assertEqual(sorted(scene_exceptions.get_scene_exceptions(70726)), ['Babylon 5', 'Babylon5'])
AssertionError: Lists differ: [] != ['Babylon 5', 'Babylon5']

Second list contains 2 additional elements.
First extra element 0:
Babylon 5

- []
+ ['Babylon 5', 'Babylon5']

======================================================================
FAIL: test_scene_ex_by_name (scene_helpers_tests.SceneExceptionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../tests/scene_helpers_tests.py", line 165, in test_scene_ex_by_name
    self.assertEqual(scene_exceptions.get_scene_exception_by_name('Babylon5'), (70726, -1))
AssertionError: Tuples differ: (None, None) != (70726, -1)

First differing element 0:
None
70726

- (None, None)
+ (70726, -1)

----------------------------------------------------------------------
Ran 369 tests in 13.070s

FAILED (failures=2, skipped=171, expected failures=3)
E
======================================================================
ERROR: test_all (__main__.AllTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/all_tests.py", line 75, in test_all
    sys.exit(-1)
SystemExit: -1

----------------------------------------------------------------------
Ran 1 test in 16.773s

FAILED (errors=1)
```

I have no idea what is going wrong here.

**Comment by labrys** [comment]
@satreix I wouldn't worry about that one,  Also I wouldn't rely on the tests for functionality either they are still way underrepresented.

**Comment by satreix** [comment]
Ok. It statrts to break for real when touching `tornado`:

```
Traceback (most recent call last):
  File "tests/all_tests.py", line 59, in setUp
    self.suites = self._get_test_suites()
  File "tests/all_tests.py", line 111, in _get_test_suites
    return [unittest.defaultTestLoader.loadTestsFromName(file_string) for file_string in self.module_strings]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File ".../tests/notifier_tests.py", line 42, in <module>
    from sickbeard.webserve import Home
  File ".../sickbeard/webserve.py", line 85, in <module>
    from tornado.routes import route
ImportError: No module named routes
```

The package does not publish routes anymore it seams.

**Comment by labrys** [comment]
@satreix I would just make note of any requirement that doesn't work easy and just go down the list one at a time.  We can then go back and troubleshoot those that don't.

**Comment by satreix** [comment]
So far the bad guys are:

```
dogpile
tornado
```

and the good one:

```
babelfish==0.5.5
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2015.11.20.1
coverage==4.0.3
coveralls==1.1
docopt==0.6.2
guessit==1.0.2
html5lib==0.9999999
httplib2==0.9.2
lockfile==0.12.2
Mako==1.0.3
markdown2==2.3.0
MarkupSafe==0.23
oauth2==1.9.0.post1
pbr==1.8.1
pyasn1==0.1.9
PySocks==1.5.6
python-dateutil==2.4.2
rarfile==2.7
requests==2.9.1
simple-json==1.1
simplejson==3.8.1
singledispatch==3.4.0.3
six==1.10.0
SQLAlchemy==1.0.11
stevedore==1.10.0
tvdb-api==1.10
Unidecode==0.4.18
wheel==0.24.0
```

(those include `coveralls` requirements :disappointed: )

**Comment by labrys** [comment]
@satreix you available to talk in irc?

**Comment by satreix** [comment]
Yes, which channel/serv ?

**Comment by duramato** [comment]
@satreix #sickrage-issues over on freenode

**Comment by nikcub** [comment]
any updates on this? 

I think it's a good idea - pip is now being distributed by default in a lot of places, and where it isn't it's just an "easy_install pip" away. Rather than dealing with GitHub users can install with:

pip install sickrage

there can be an alternate download with packages bundled

**Comment by satreix** [comment]
Echelon moved over to `pip` already. Just saying.

**Comment by miigotu** [comment]
And Echelon has been MIA again for 4 months, with a package that doesnt run. Just saying.

**Comment by satreix** [comment]
My point being: if we want to go the `pip` way (which to me and a couple of others is the right way to go), we could take a look at what he did there.

**Comment by miigotu** [comment]
We absolutely cant, he is forcing users to run as root, fucking with their environment and all kinds of garbage. Echelon is a joke.

**Comment by nikcub** [comment]
is this closed for this pull or closed to the concept of migrating to pip?

there might have been something I missed, but I think there are a lot of advantages to using a proper dependency manager (keeping up with updates, patches, security issues, etc.) and then a packaging tool for dist

**Comment by satreix** [comment]
I havent looked at how he does it.
But `pip` is ready to run in userland so that should not be a problem, right?

**Comment by miigotu** [comment]
There are distributions who cannot install pip. Echelon is installing pip/setuptools from inside SR (thus requiring root access, and can he really be trusted that the code on github is what is in his pip sources? who knows).

Also, no requirements.txt is necessary, we have a setup.py.  When it comes down to it users will be able to  pip install --user sickrage-ng with no root, or be able to use included libs.

This is nowhere near a priority, since there is no reason to break 70,000 working installs.

**Comment by satreix** [comment]
@miigotu having vendored lib in this repository is really bad. It make the work of keeping up with our dependencies a nightmare.
- Is there a complete list somewhere of the platforms sickrage is supposed to run on ?
- Is there a way to test those as part of the CI/CD process ?

**Comment by miigotu** [comment]
Its not that bad, in fact its only a few lines missing from setup.py. The lib dir will remain in the source regardless, since it wont effect pip whatsoever, and the lib dir wont be included with the pip build.

SigkRage actually already builds into an egg with setup.py, and can be installed that way.

**Pull request closed without merging**
