### PR TITLE
Enable cookies field for all TorrentProviders, if they have the provi…

### LINKED ISSUE #1892: Torrentday no longer working
Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/89676eb74a3fc9f765f17db291c9134df2537e38
OS: Linux-3.18.10-armv7l-with-glibc2.4 (openelec, raspberry pi 2)
What you did: Manually download show as it didn't automatically
What happened: couldn't find the show on torrentday, checked the website and its up. They may have tweaked their website
What you expected: to download automatically or to successfully manually download it

BTW: I seen the post from earlier today about torrentday but I am not in the UK and can access torrentday.com and classic.torrentday.com so its a separate problem.
Logs:

    2016-05-30 19:25:35 INFO SEARCHQUEUE-MANUAL-277165 :: Unable to find a download for:     [Silicon Valley - S03E06 - Bachmanity Insanity]

### PR DESCRIPTION
**Pull request by p0psicles**
Fixes #1892 

Proposed changes in this pull request:
## 
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

Enable cookies field for all TorrentProviders, if they have the provider.enable_cookies attribute set.
- Can be used to set the uid and pass cookies for TorrentDay.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by p0psicles** [comment]
Someone test this. Also please test if an rss torrent provider, which needs cookie authentication still works.

**Comment by bitzorro** [comment]
dont know if its a bugg but after a restart of sickrage, the cookie info has moved up to the Api key field!?

**Comment by bitzorro** [comment]
is this the correct way to enter the cookies?
"uid=1111111;pass=1111111111111111111111111"

thanks, its working!!

**Comment by VeNoMouS** [comment]
Shouldnt that be a dict of a dict? any additional added cookies are going to be overwritten if their cookie name is the same for another site/provider...

**Pull request merged**
