### PR TITLE
fix for bold fonts being used where normal should

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@OmgImAlexis 

can you remove  this too? all settings descriptions are using the wrong font
@duramato 

image

**Comment by OmgImAlexis** [comment]
@fernandog what's the selector for that? The screenshot doesn't really show where that was removed or what font it falls back to.

**Comment by fernandog** [comment]
/css/style.css?2920

also affects viewlogs are @duramato mentioned

**Comment by OmgImAlexis** [comment]
@fernandog I need something like this `.ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header {`.

**Comment by fernandog** [comment]
@OmgImAlexis this #config span.component-title ?

**Comment by fernandog** [comment]
@OmgImAlexis can yo inspect element in chrome to make sure?

line 1920 of style.css:

``` css
/* =======================================================================
bootstrap Overrides
========================================================================== */

body {
    padding-top: 60px;
    overflow-y: scroll;
    #font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #000;
}
```

**Comment by fernandog** [comment]
@OmgImAlexis I tried add font: inherit in style.css for "select" and it seems it worked. it override the jquery (to fix the font-family in jquery custom)

**Comment by OmgImAlexis** [comment]
@fernandog that removes all of the fonts from the whole of SickRage, that isn't a fix at all.

**Comment by fernandog** [comment]
I don't know exactly what I did it only changed the "select" font

**Comment by miigotu** [comment]
All this fuss over fonts is super silly.

**Comment by OmgImAlexis** [comment]
@fernandog you disabled the whole font family.

**Comment by labrys** [comment]
This thread is font-astic... and it was all started by a **bold** move.

**Comment by fernandog** [comment]
@OmgImAlexis and worked!

That fix issues in viewlog. Settings and etc

**Comment by duramato** [comment]
@labrys 
Slow clap

**Pull request merged**
