### PR TITLE
Fix HorribleSubs search with group constraint

### PR DESCRIPTION
**Pull request by beschoenen**
This PR fixes searches for the HorribleSubs provider when the user has a sub group constraint for HorribleSubs.

Detecting the group fails cause the provider doesn't include its own name in releases.

(Also tested without group constraint and still works)

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
what is a sub group constraint ?

**Comment by beschoenen** [comment]
A wanted group

**Comment by h3llrais3r** [comment]
Nice, thanks for this.
I saw this was a problem when I fixed the provider, but didn't had the time yet to fix this. 😄

**Comment by sharkykh** [comment]
@h3llrais3r If this fixes the issue, mark it as approved, so @beschoenen can merge it.

**Comment by h3llrais3r** [comment]
@sharkykh I can't approve anymore... 😞

**Comment by sharkykh** [comment]
@h3llrais3r That's because @miigotu has great timing

**Pull request merged**
