### PR TITLE
Update webserve.py - update backlog SQL statement

### PR DESCRIPTION
**Pull request by GoodOmens83**
Stolen from here: SiCKRAGETV sickrage-issues #3727

No idea if you need air date and name (as it seems like only season, status, and episode are used).  I understand there is a effort to go through and make all sql statements more efficient but this is a good low hanging fruit.

### CODE REVIEW

**Comment by fernandog** [comment]
missing spaces: PEP8
status,season,episode,name,airdate >> status, season, episode, name, airdate

**Comment by GoodOmens83** [comment]
Ah my apologies.

**Comment by miigotu** [comment]
Double FROM in the SQL. I will close this because Im working on also cleaning up the code in mako just a bit right now.

**Comment by coderbone** [comment]
airdate and name are required by the mako template

if you've got other optimization goodies like this waiting in the wings bring 'em on otherwise I fear I'm going to sit here and find/report them all over again :)

**Comment by miigotu** [comment]
Huh? lol

I was only referring to this part of your commit:

``` sql
airdate FROM tv_episodes FROM tv_episodes WHERE
```

**Comment by coderbone** [comment]
That may have been GoodOmen83 with the double FROM, I was just noting that the list of fields was minimized fairly carefully.

Sorry, not trying to be pedantic, just being sure we do this carefully as a lot of people will be running this code soon.

Looking forward to seeing the impact of other sql optimization, just this simple one has had my pi running for 3 days without going into swap.

**Comment by GoodOmens83** [comment]
Lol. Thanks for repeatedly calling out my typo.

**Comment by coderbone** [comment]
Hello chaps.... I have another two small sql query changes that are giving solid improvements on my setup... the methodology was to put some calls to time.time() in db.py and when the delta was over some threshold the traceback.format_stack() is dumped into the log, this zeroed in on two things.

Both changes are in processTV.py, the first change only requests the location field from tv_shows instead of *, this took the query from about 1.2 seconds on average down to 0.15 seconds on average.

The second change combines two queries into one, each took about 1.5 seconds on average, now just one that takes that long.

In git diff format my suggested changes are:

``` diff
index 93832ae..46d745e 100644
--- a/sickbeard/processTV.py
+++ b/sickbeard/processTV.py
@@ -346,7 +346,7 @@ def validateDir(path, dirName, nzbNameOriginal, failed, result):

     # make sure the dir isn't inside a show dir
     myDB = db.DBConnection()
-    sqlResults = myDB.select("SELECT * FROM tv_shows")
+    sqlResults = myDB.select("SELECT location FROM tv_shows")

     for sqlShow in sqlResults:
         if dirName.lower().startswith(
@@ -492,16 +492,16 @@ def already_postprocessed(dirName, videofile, force, result):

     # Avoid processing the same dir again if we use a process method <> move
     myDB = db.DBConnection()
-    sqlResult = myDB.select("SELECT * FROM tv_episodes WHERE release_name = ?", [dirName])
+    sqlResult = myDB.select("SELECT * FROM tv_episodes WHERE release_name = ? OR release_name = ?", [dirName, videofile.rpartition('.')[0]])
     if sqlResult:
         #result.output += logHelper(u"You're trying to post process a dir that's already been processed, skipping", logger.DEBUG)
         return True

     else:
-        sqlResult = myDB.select("SELECT * FROM tv_episodes WHERE release_name = ?", [videofile.rpartition('.')[0]])
-        if sqlResult:
-            #result.output += logHelper(u"You're trying to post process a video that's already been processed, skipping", logger.DEBUG)
-            return True
+#        sqlResult = myDB.select("SELECT * FROM tv_episodes WHERE release_name = ?", [videofile.rpartition('.')[0]])
+#        if sqlResult:
+#            #result.output += logHelper(u"You're trying to post process a video that's already been processed, skipping", logger.DEBUG)
+#            return True

         #Needed if we have downloaded the same episode @ different quality
         #But we need to make sure we check the history of the episode we're going to PP, and not others
```

**Comment by labrys** [comment]
@coderbone You could always submit a PR :smiley:

**Comment by Arcanemagus** [comment]
Also a hint: If you wrap that block in this:
```diff
<your diff here>
```

Then it will automatically colorize it and won't try to format it as markdown :wink:

**Comment by fernandog** [comment]
done lol

**Comment by miigotu** [comment]
@coderbone I have added a slightly modified version of those optimizations in https://github.com/SickRage/SickRage/commit/53a797eedd04339bff78697283bb54d432c46294

**Comment by coderbone** [comment]
@labrys, fair enough.  I've not crossed that rubicon... when I posted the snippet I didn't think it was going to turn into a horrible jumble.

**Comment by miigotu** [comment]
Done most of the rest here: https://github.com/SickRage/SickRage/pull/371

**Pull request closed without merging**
