### PR TITLE
use also /etc/os-release to check Distro in debian-ubuntu-install.sh

### PR DESCRIPTION
**Pull request by kyuuk**
#[8171](https://github.com/SickChill/sickchill/discussions/8171#discussioncomment-3728967)

Proposed changes in this pull request:
- Check distro with /etc/os-release for debian like distros like raspbian/osmc

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
This doesn't work, maybe you can switch it around and check Ubuntu first, and then try Debian.

image

**Comment by miigotu** [comment]
image

**Comment by miigotu** [comment]
Also, be careful to always make PR to develop, not master =P It takes awhile to remember to do that but super important. I always check the base branch before merging luckily :wink:

**Comment by kyuuk** [comment]
> Also, be careful to always make PR to develop, not master =P It takes awhile to remember to do that but super important. I always check the base branch before merging luckily 😉

ah sorry for that, i guess i was too hasty 😜

**Pull request merged**
