### PR TITLE
Fix unmatched div end tag

### PR DESCRIPTION
**Pull request by daviddotcs**
Fixes # n/a

Proposed changes in this pull request:
- Add a missing div start tag for banner/poster schedule view whose absence results in an unnecessary horizontal scrollbar appearing.
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by beschoenen** [comment]
Which tag do you think was unopened?

**Comment by daviddotcs** [comment]
Sorry, I didn't have it quite right the first time. The `</div>` removed from line 453 in my latest commit was the unopened tag I was referring to. It was only opened by the tag on line 337 in the cases where that code path was reached.

**Comment by beschoenen** [comment]
I looked at it myself and came up with this,
https://github.com/SickRage/SickRage/pull/1804/commits/58bb5ada3d430cf055225ab401d0c4e4d1538bae#diff-4487c969c7b0ea0f783f0c3cc8543ca5R307
Line 307-334

**Comment by miigotu** [comment]
Done in #1804

**Pull request closed without merging**
