### PR TITLE
Fix stupid regex not matching the show name, and added a new stupid w…

### PR DESCRIPTION
**Pull request by duramato**
…ith season to conform with certain scene releases 

Fixes issue from IRC

Open for suggestion on a name for the new regex

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by TJSoler** [comment]
```
Postprocessing results
Processing folder /share/MD0_DATA/Download/TVShows/Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR]
PostProcessing Path: /share/MD0_DATA/Download/TVShows
PostProcessing Dirs: [u'Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR]']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing folder Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR]
Unable to match aaf-sns03e15.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e03.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e10rp.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e05.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e04.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e08.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e13.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e06.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e01.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e09.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e11.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e12.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e07.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e14.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e16rp.mkv to a show in your database. Parser result: None
Unable to match aaf-sns03e02.mkv to a show in your database. Parser result: None
Unable to match Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR] to a show in your database. Parser result: Supernatural S - [ABS: [3]] [ANIME VER: -1] [ABD: False] [ANIME: True] [whichReg: ['anime_codec_crc']]
Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR] : No processable items found in folder
Successfully processed
```

**Comment by duramato** [comment]
@TJSoler Should REALLY be fixed now, sorry about the hassle.

**Comment by TJSoler** [comment]
Perfect

```
2016-07-29 19:51:42 DEBUG    Thread-13 :: Using cached parse result for: aaf-sns03e06
2016-07-29 19:51:45 INFO     Thread-13 :: Processing succeeded for /share/MD0_DATA/Download/TVShows/Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR]/aaf-sns03e06.mkv
2016-07-29 19:51:45 INFO     Thread-13 :: Processing /share/MD0_DATA/Download/TVShows/Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR]/aaf-sns03e01.mkv (None)
2016-07-29 19:51:46 DEBUG    Thread-13 :: Analyzing name aaf-sns03e01.mkv
2016-07-29 19:51:55 DEBUG    Thread-13 :: Parsed aaf-sns03e01 into sn - S03E01 [GROUP: aaf] [ABD: False] [ANIME: False] [whichReg: ['stupid_with_denotative']]
2016-07-29 19:51:57 DEBUG    Thread-13 :: Found release name aaf-sns03e01
2016-07-29 19:52:10 DEBUG    Thread-13 :: Using cached parse result for: aaf-sns03e01
2016-07-29 19:52:13 DEBUG    Thread-13 :: Using cached parse result for: aaf-sns03e01
2016-07-29 19:52:14 DEBUG    Thread-13 :: Moving then symbolic linking file from /share/MD0_DATA/Download/TVShows/Supernatural.S03.1080p.BluRay.x264-aAF [NO RAR]/aaf-sns03e01.mkv to /share/TVShows/Supernatural/S03/Supernatural.S03E01.1080p.BluRay-aaf.mkv
```

Working like a charm  @duramato

**Comment by stephenknoth** [comment]
lets name it big boi lettuce regex

**Pull request merged**
