### PR TITLE
Created Torrent9 provider

### LINKED ISSUE #2104: Provider cpasbien and torrent9.tv
since few time, lot of link torrent of cpasbien website are linked on torrent9.tv

Can you add torrent9.tv in the torrent liste tracker plz ?

Thanks

### PR DESCRIPTION
**Pull request by Djang0**
Fixes #2104

Proposed changes in this pull request:
- New torrent9 provider
- was not able to produce yaml
-

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

https://github.com/SickRage/SickRage/issues/2104
http://feathub.com/SickRage/SickRage/+518

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by Djang0** [comment]
@miigotu Hi not sure you did, but if you merge this pull request, you might want to integrate this one as well : https://github.com/SickRage/SickRage/pull/2681
which contains some fixes by @magicseb

**Comment by miigotu** [comment]
This PR is made to the wrong branch, and #2681 includes everything from this PR. Its still under debate whether to add that provider.

**Comment by Djang0** [comment]
I agree. May I bring to your attention that cpasbien was the only clean and rich provider for french speaking. But it is now not being updated anymore, actually visiting cpasbien with a tablet simply redirect you to torrent9.

**Comment by Jamyz** [comment]
@Djang0 it's true. I put torrent9.py and modified __init__.py and add torrent9.
But he can't snatch nothing.... What is wrong ? I need to edit 
tests/sickrage_tests/providers/torrent/parsing_tests.py
and
tests/sickrage_tests/providers/torrent/cassettes/torrent9.yaml
too
????

**Comment by Djang0** [comment]
Hi @Jamyz you should take the following pull request into account: https://github.com/SickRage/SickRage/pull/2681
It contains fixes by @magicseb ... I was a bit too quick to make my pull request, that's why I previously suggested @miigotu to merge #2681 
It is working for me.

**Comment by miigotu** [comment]
This PR is REPLACED by #2681

**Pull request closed without merging**
