### PR TITLE
added more css to bower, removed unused fonts/libs

### PR DESCRIPTION
**Pull request by OmgImAlexis**
@fernandog apparently we still need the jquery-ui css file as we use a custom version of it for the tabs in the config pages. I'd be hesitant on editing it though as it's a minified file and that means it won't actually show changes on git/github.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
@OmgImAlexis css and vender use the fonts/glyphicons/halflings. This PR causes a lot of render errors

**Comment by OmgImAlexis** [comment]
They should all be copied via the copy function in Grunt?

If I missed them I can fix that. They shouldn't be in the lib directory though.

**Comment by miigotu** [comment]
Here are some of them:
image

**Comment by OmgImAlexis** [comment]
Is it actually missing them or is it just showing in the console?

**Comment by labrys** [comment]
@OmgImAlexis This PR broke formatting on the APIBUILDER.

**Comment by OmgImAlexis** [comment]
@labrys I'll look into it. I told @MGaetan89 that `apibuilder` should have used bower like everything else.

**Pull request merged**
