### PR TITLE
Fix core.js import when DEVELOPER mode is enabled

### PR DESCRIPTION
**Pull request by Nyaran**
core.js is not found when DEVELOPER mode is enabled

Proposed changes in this pull request:
- Use static_url method

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
Hey, can you go to https://github.com/Nyaran/SickChill/settings/actions and make sure you have this setting set?
image

**Comment by Nyaran** [comment]
> Hey, can you go to https://github.com/Nyaran/SickChill/settings/actions and make sure you have this setting set?
> image

Yes, is set :(

Screenshot_2020-08-24 Nyaran SickChill

**Comment by miigotu** [comment]
@Nyaran so it was a mistake on my end. ff961508ad5c0488d2d04f421d25794c1591d179

**Comment by Nyaran** [comment]
> @Nyaran so it was a mistake on my end. [ff96150](https://github.com/SickChill/SickChill/commit/ff961508ad5c0488d2d04f421d25794c1591d179)

It's running! 🙌

**Pull request merged**
