### PR TITLE
Fix for issue 8058 - Subtitle search + History

### LINKED ISSUE #8058: Some Automatic Subtitle search: TypeError: tuple indices must be integers or slices, not str'
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch:** master
**Commit:** d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5
**Version:** 2022.07.20
**Database Version:** 44.5
**Python Version:** 3.9.5 (default, Nov 23 2021, 15:27:38) [GCC 9.3.0]
**SSL Version:** OpenSSL 1.1.1f 31 Mar 2020
**Locale:** en_US.UTF-8

**OS:** Ubuntu 20.04.4 LTS (Linux-5.4.0-122-generic-x86_64-with-glibc2.31)
**Browser:** Google Chrome 104.0.5112.81 64-bit
**What you did:** Open sickchill and saw multiple error in the loggin 
**What happened:** Logging indicated the following: the multiple error with Error: tuple indices must be integers or slices, not str
**What you expected:** no errors
**Extra:** When I looked in the media folder, the subtitle was downloaded but not shown in SickChill, I deleted the subtitle file in de media folder and did manual subtitle search, the subtitle was downloaded but not show in Sickchill (Little country flag, not even after a Re-scan)

The logs does not give more error details than what is show below(Like Tracebacks or some sort)

I saw #8051 and checked the file subtitles.py, on row 257 I got `                f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores.res}/{scores.percent}% (min={scores.min}/{scores.min_percent}%)"` (With all the spaces before it) just as it should

I Hope I gave enough information, if not please let met know.

Thanks

Logs:
```
2022-08-09 16:56:47 INFO :: FINDSUBTITLES :: Searching for missing subtitles of Chicago Fire S05E04
2022-08-09 16:56:47 DEBUG :: FINDSUBTITLES :: Checking subtitle candidates for Chicago Fire S05E04 (Chicago.Fire.S05E04.Nobody.Else.Is.Dying.Today.mkv)
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: Could not search in podnapisi provider. Discarding for now
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1955368016 is: 771/48% (min=213/13%)
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1955368015 is: 768/47% (min=213/13%)
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1956518372 is: 768/47% (min=213/13%)
2022-08-09 16:56:48 ERROR :: FINDSUBTITLES :: Unable to find subtitles for Chicago Fire S05E04. Error: tuple indices must be integers or slices, not str
```

### PR DESCRIPTION
**Pull request by avdleeuw**
Fixes #8058

Proposed changes in this pull request:
- Change History.py to use the correct way to index the tuple used

- [ X ] PR is based on the DEVELOP branch
- [ X ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ X ] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by BKSteve** [comment]
https://github.com/SickChill/SickChill/commit/167cad96a9ebe687f05b03c1b62fc8a2a991a795
fixed this

**Comment by avdleeuw** [comment]
@BKSteve : This was **not** fixed by https://github.com/SickChill/SickChill/commit/167cad96a9ebe687f05b03c1b62fc8a2a991a795 

That fix only applies to subtitles.py, while the same issue applies to the History.py file, which wasn't fixed, hence this pull request. 

If you look at the loglines at the issue, you'll see this: 

```
022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1956518372 is: 768/47% (min=213/13%)
2022-08-09 16:56:48 ERROR :: FINDSUBTITLES :: Unable to find subtitles for Chicago Fire S05E04. Error: tuple indices must be integers or slices, not str
```

The first line is showing because of fix https://github.com/SickChill/SickChill/commit/167cad96a9ebe687f05b03c1b62fc8a2a991a795

However, the program still gets an exception because of the issue in History,py. 
To recreate this issue, make sure you have the 'log downloaded Subtitle on History page?'  enabled.

**Comment by BKSteve** [comment]
Supplemental change to `history.py` to align with `subtitles.py` change.

**Comment by miigotu** [comment]
I added this to another commit because build was failing here. Thanks for the find.
https://github.com/SickChill/SickChill/commit/83989af06d3bb16e6dfee0ad0183ad022d97a53e

**Comment by miigotu** [comment]
Now to figure out why python3. 9 is trying to format the code different than 3.10 or 3.8 smh.

**Pull request closed without merging**
