### PR TITLE
Update poetry.lock fix math

### LINKED ISSUE #7603: Python Permission Denied - Develop dd376be
Latest update to develop Edit: dd376be4e5a29d105ae98b2c82e0a1ca3a2939fd

Gives permission denied and invalid version errors.
Running SC on SynoDSM with `sickchill_x64-6.1_20210729-22.spk`

### PR DESCRIPTION
**Pull request by BKSteve**
Fixes #7603

Can't do maths on a wildcard number.

### CODE REVIEW

**Comment by miigotu** [comment]
>=3.6.1 please

**Comment by BKSteve** [comment]
`3.6.1` it is, at least now.

**Comment by miigotu** [comment]
We need to get the tests/builds working again. *sigh*

**Comment by BKSteve** [comment]
Not familiar with the concept and method

**Comment by BKSteve** [comment]
`Dependabot` killed this fix with #7610 and returned it to `3.6.*`

Bump cachecontrol from 0.12.6 to 0.12.7 (#7597)

**Comment by miigotu** [comment]
Yeah the fix cannot be editing poetry.lock, need to fix the parsing of it

**Comment by BKSteve** [comment]
I was reading up on the dependabot and how it works and considered hitting the revert button and the reopen the `0.12.6 - 7` but then saw the update to `0.12.8` and checked it. Saw they had fixed the issue they'd created by the bad maths/logic and commented over there. 
Yep, still learning. Thanks for the patience.

**Pull request merged**
