### PR TITLE
Add support for pre-executed scripts in subtitles

### PR DESCRIPTION
**Pull request by oskarirauta**
This is a duplicate of: https://github.com/SickRage/SickRage/commit/18b3e02f673c5d7fdea9ff053e094d14a01a93bd

but this time, it's a pull request for develop branch.

Description:
This patch adds new option for pre-executing scripts when searching
subtitles. Filename of media is sent as an argument for the script.

This allows one to use 3rd party utilities to enable even more sources
for subtitles. Or if for some case, one needs to do some pre-processing
before fetching/searching for subtitles.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by oskarirauta** [comment]
Guideline has now been followed..

**Comment by OmgImAlexis** [comment]
@oskarirauta you need to rebase from develop. I'm guessing either you originally did this from master or forgot to squash.

**Comment by oskarirauta** [comment]
Yes I did this from master :(

**Comment by OmgImAlexis** [comment]
`git rebase develop` **should** fix it.

**Comment by oskarirauta** [comment]
Done

**Comment by fernandog** [comment]
@oskarirauta what is your use case for this?

@medariox

**Comment by miigotu** [comment]
Hey, dont click "update branch" in github, it just adds another commit lol. I can still merge it even if it says out of date, just worry about if it says conflicts =P

**Comment by oskarirauta** [comment]
Sorry, my bad. Wanted to see that it's still compatible with changes..

Lähetetty iPhonesta

**Comment by medariox** [comment]
I don't see anything wrong with this, just one more option in subtitles. :sweat: 
@oskarirauta 
Like @fernandog already asked, what is the use case for this?

**Comment by oskarirauta** [comment]
I want to use external utility for downloading subtitles from sites other than ones included. Changes for subliminal are more difficult, so for me, this allows me to run custom periscope to downloading subtitles from these external sites. But your mileage for usage may vary.

Lähetetty iPhonesta

**Comment by fernandog** [comment]
which provider? afaik periscope it not maintained anymore

**Comment by oskarirauta** [comment]
I just created aika new fork of it, providing subtitle search from subsearch.org which is where mistä Finnish subtitles are found from. And ofcourse, one can make their own plugin if they want to, I decided To use something pre-existing. Custom usage.

Lähetetty iPhonesta

**Comment by fernandog** [comment]
Please rebase

Also add "subtitles_pre_scripts=None" to the end in webserve.py

@miigotu @medariox @labrys any comments?

**Comment by oskarirauta** [comment]
Sorry, my bad - missed that one. Updated and rebased.

**Comment by labrys** [comment]
@oskarirauta I don't see a reason for a new method to run pre sub scripts when over 90% of the code is identical to the existing method for post sub scripts.  The existing method should be modified to be usable for both cases to make maintenance easier and the existing method more useful.

**Comment by oskarirauta** [comment]
That would be battery. I made this earlier a feature request, but decided To give something instead of just asking, but since sickrage sinut familiar for me from past, I simplified this. It works, but I don't say it couldn't be better- this is a base for this feature.

But post script execution as pre-script is not that straight forward- some options posted as arguments are about existing subtitles. Pre script assumes that subtitles are missing. Post script feature would had been ok for me, if it would had been executed also if subtitles are missing, but they execute only when they where found.

Lähetetty iPhonesta

**Comment by miigotu** [comment]
Can you fix the conflicts? Thanks

**Comment by oskarirauta** [comment]
Sorry, no, since I went to camp sonarr...

Lähetetty iPhonesta

**Comment by miigotu** [comment]
no problem.

**Pull request closed without merging**
