### PR TITLE
Fix #3832

### LINKED ISSUE #3832: qbittorrent: Unable to send Torrent
Hi,

Since updating to qbittorrent v3.3.13, I am unable to send to webui. I think something has changed in webui. Authentication is fine i have tested it, changed it and verified it by logging into the webui. 

Branch/Commit: master/10a0c3012e600ed61cdff6a6108b2bb55062907b
OS: Windows 10
What you did: Manual search eposide to transfer via webui to qbitorrent
What happened: torrent not send to qbitorrent webui
What you expected: torrent send to qbitorrent webui
Logs: https://pastebin.com/pJUPeimj

### PR DESCRIPTION
**Pull request by sharkykh**
- Add Origin & Referer headers to support CORS (as per version 3.3.13): Fixes #3832 ~(issue mysteriously disappeared, contacted Github)~
- Fix torrent actions (pausing, setting label, etc.) by fixing the verification of torrent addition (wasn't actually working)

**Tested against qBittorrent v3.3.13**

### CODE REVIEW

**Comment by JeremyTBradshaw** [comment]
Quick question for you, could I just replace qbittorent_client.py and parser.py in my master branch based install in order to get my qbittorrent 3.3.13 install working?  Or would I need to switch completely over to the develop branch?

**Comment by miigotu** [comment]
Youd have to switch or just wait for a few days until it is released to master.

**Comment by JeremyTBradshaw** [comment]
Thanks. Switched and it works perfectly.  I'll keep an eye out for the master update.

**Comment by harmsey** [comment]
I feel real dumb but am new how do you switch to develop? I go to advanced in sickrage and all there is in the drop down is master...

Edit NVM apparently I just had to sign in and then develop was there.

**Comment by JeremyTBradshaw** [comment]
You can switch to develop under Settings cogwheel -> General -> Advanced Settings tab -> GitHub section ->branch -> checkout branch.

**Comment by PinaColonic** [comment]
Been on Dev stream for over a month to get this fix for Qbit, hoping it makes it to master soon...thanks for the fix.

**Comment by larryd85** [comment]
i used the installer for windows, am having this issue, and i cant switch to Dev stream without getting errors starting the sickrage service now.

**Comment by OmgImAlexis** [comment]
Please open an issue if you need help this isn't the place for it.

**Pull request merged**
