### PR TITLE
Remove dead providers bluetigers btdigg ilovetorrents

### PR DESCRIPTION
**Pull request by a10kiloham**
Fixes #

Proposed changes in this pull request:
-
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
btdigg and ilovetorrents still work

**Comment by a10kiloham** [comment]
doh. there's some serious IP blocking going on in Europe. had no idea :(

**Comment by duramato** [comment]
Ilovetorrents is pay2leech just like bitsoup was and should be removed, btdigg is also unreachable?

**Comment by miigotu** [comment]
image

**Comment by duramato** [comment]
That's not https://btdigg.org the original one is well dead ,that's btdig.com a new clone. Also not the one used in sickrage lol

**Comment by miigotu** [comment]
Damn, I must be slipping ha. Re-added a new PR for this since the branch is deleted.

**Comment by a10kiloham** [comment]
Sorry I deleted the branch out of shame before :)

**Comment by miigotu** [comment]
@bobbysteel yeah sorry, you were correct.

**Comment by a10kiloham** [comment]
no worries, i thought i was just out of the game. :)

**Pull request closed without merging**
