### PR TITLE
'is not' being used where '!=' should have been which causes the netw…

### PR DESCRIPTION
**Pull request by coderbone**
…ork timezome table in cache.db to be rebuilt repeatedly

```
http://stackoverflow.com/questions/2209755/python-operation-vs-is-not
```

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by coderbone** [comment]
so my orig PR was done from code I'd branched from the develop branch... presumably my error was during the creation of the PR rather than the usage of branching during the coding/testing phase

**Comment by labrys** [comment]
@coderbone You are correct that your original PR was just PR'd against the wrong branch.  However your current PR is based on an older develop branch.  Rebase this on the latest dev so I can merge this.

**Comment by coderbone** [comment]
hmmm, so I pushed the 'Update branch' button on this and my other PR... totally trivial in both cases as I'd only touched files that had not been touched in any one else's activities since my last rebase (which was only a few hours ago). 

given that my PRs were against files that were untouched since my last rebase (only a few hours old) the need to do an additional rebase seems odd... doesn't this lead you into a vicious cycle of bouncing everything with a rebase squash?  I'll go and do some reading on my own, not asking you to provide my education :)

**Comment by labrys** [comment]
@coderbone If you could rebase this instead of the Update button, as the update causes a superfluous merge commit in the history.  As for the extra rebase it can be a pain at at times with the rate of updates we go through, however it helps keep everything clean.  Here's some information to get you started on reading about status checks.

**Comment by miigotu** [comment]
Will do this rebase for you.

**Pull request closed without merging**
