### PR TITLE
Add midgetspy back to copywrite, because echelon sent a DMCA.

### PR DESCRIPTION
**Pull request by miigotu**
True original license is here: https://github.com/midgetspy/Sick-Beard/blob/development/COPYING.txt
This is a fork of a fork, of an open source project. Very little code matches SickRageTV or Sick-Beard any more, if any,

```
Hi there,

I'm contacting you on behalf of GitHub Support because we've received a DMCA takedown notice regarding the following content:

https://github.com/SiCKRAGE/SiCKRAGE

You can view the notice and the details of the requested changes below.

In this case only certain files were identified as allegedly infringing. Since it's not possible to disable individual files within a GitHub repository, we're giving you a 24 hour opportunity to remove the content named in the takedown. Please follow the steps in the following article to remove the content from the history:

https://help.github.com/articles/remove-sensitive-data

Once you've done that, please reply to this message to confirm the change. If we don't hear from you that a change is made within the next 24 hours, we will need to disable the entire repository according to our GitHub DMCA Takedown Policy, which you can find here:

https://help.github.com/articles/dmca-takedown-policy/

If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described on the DMCA Takedown Policy page.

PLEASE NOTE: It is important that you reply within 24 hours to confirm whether you have made the requested changes. If you do not, the repository will be disabled.

---

Original content can be found at:

https://github.com/SiCKRAGETV/SiCKRAGE

Original license can be found at:

https://github.com/SiCKRAGETV/SiCKRAGE/blob/master/COPYING.txt

SiCKRAGE software within the SiCKRAGE project to be included in or made
subject to any GPL or LGPL license, or indeed any other open source license

SiCKRAGE and the original code has not been provided or its use authorized,
this is a violation of my copyright. I have a good faith belief the
distribution of SiCKRAGE includes content of which the distribution is not
authorized by the copyright owner, it's agent, or the law.

The repositories listed below are infringing upon my work by removing my
name as the original author of the software and removing links back to the
original source code within the repository which is a violation of the GPL
v3 license that it is licensed under.

Infringing content - as of the repository's creation and every subsequent
commit, including all:

https://github.com/SiCKRAGE/SiCKRAGE

https://github.com/SickRage/SickRage/commit/94628db86dbc528a3ba5092b22bc7858365632b2

https://github.com/SickRage/SickRage/commit/946481ac36e5fc056ac5e7a9ec9fda357c821dce

https://github.com/SickRage/SickRage/commit/d8fc1f1c8b0bf2430774608c24c1bba1b28d76b3

https://github.com/pymedusa/Medusa

https://github.com/pymedusa/Medusa/commit/94628db86dbc528a3ba5092b22bc7858365632b2

https://github.com/pymedusa/Medusa/commit/d8fc1f1c8b0bf2430774608c24c1bba1b28d76b3

https://github.com/SickGear/SickGear

https://github.com/SickGear/SickGear/commit/4c8c6b21d531850b44c18ab9fc5cf664922a0f86

I have a good faith belief that use of the copyrighted materials described
above on the infringing web pages is not authorized by the copyright owner,
or its agent, or the law. I have taken fair use into consideration.

I swear, under penalty of perjury, that the information in this
notification is accurate and that I am the copyright owner, or am
authorized to act on behalf of the owner, of an exclusive right that is
allegedly infringed.

I have read and understand GitHub's Guide to Filing a DMCA Notice

Pursuant to the Digital Millennium Copyright Act (17 U.S.C. § 512(c)), the
above mentioned pages/repos/forks need to be expeditiously removed or
access-of disabled.

Contact Info:

Phone Number - [private]

Electronically Signed:

[private]
```

### CODE REVIEW

**Comment by miigotu** [comment]
@SickRage/collaborators @SickRage/moderators

**Comment by miigotu** [comment]
My response:
```
This DMCA notice is invalid, as the original creator is:
@midgetspy (Nic Wolfe - nic@wolfeden.ca)

and the original license is at:
 https://github.com/midgetspy/Sick-Beard/blob/development/COPYING.txt 

Very little code is still shared with any of the forks any more, and the complaint does not originate from the copyright holder.

However, I have made changes to add the original author back to the license file, rather than it just being in history:
https://github.com/SickRage/SickRage/pull/3938
```

**Comment by miigotu** [comment]
@JackDandy - echelon has named SickGear in this DMCA
@p0psicles - echelon has named Medusa in this DMCA
@midgetspy - please advise?

**Comment by miigotu** [comment]
@sharkykh `grunt publish` is no longer working, can you look into that? For now I will just cherry-pick this to master.
Edit: Cherry-Picked - 832ccb445f8eaadef783eddb51880d67d1a77b3d

**Comment by midgetspy** [comment]
echelon has [an identical commit in his repo](https://git.sickrage.ca/SiCKRAGE/sickrage/commit/fed6fbb515f9aead22c18eb6c02246675ba3c03b#0716c3c614c9da2fbb847d78c911b806a3ec00be_3_1), I guess I should DMCA him also? Lol, what a dick.

Anyway IANAL but I believe the original copyright is supposed to stay and any additional copyright can be added (as you did in 832ccb4). I'm not sure if you're supposed to put his name in as well, given that he didn't attribute properly in the first place either. *shrug*

**Comment by OmgImAlexis** [comment]
@midgetspy could Medusa, SickGear and Sickrage/Sickage get a formal notice from you that we're not infringing incase this shit happens again?

**Comment by miigotu** [comment]
@OmgImAlexis @JackDandy if you could, please also add Nic back to the copyright in your repos and link the commit here? I'd like to document this all in one place. FWIW idc if I'm even in the license file, it was just to prevent ech from doing something like this in the first place when we forked.

**Comment by JackDandy** [comment]
SickGear never removed [the original Sick-Beard credits](https://github.com/SickGear/SickGear/blob/master/COPYING.txt#L634-L655) so no files are required for change in this regard.  A prime reason for forking was that Echel0n refused to credit @midgetspy for Sick-Beard when we insisted, his action was strongly disapproved of as dishonest at best. As it turns out, it's far worse now.

**Comment by midgetspy** [comment]
@OmgImAlexis I'm not sure what constitutes a formal notice but I can affirm that as the original author of the Sick Beard project I have no issues with the licensing or copyright of Medusa, SickGear, or SickRage.

**Pull request merged**
