### PR TITLE
Integrate Codecov

### PR DESCRIPTION
**Pull request by sharkykh**
@miigotu Just in case you want to do this...

Proposed changes in this pull request:
- Switching over to Codecov for coverage.

Codecov will allow us to **[merge coverage data from multiple CIs](https://github.com/lemurheavy/coveralls-public/issues/613).**
And if I'm not wrong, it looks like it's much more configurable than coveralls...
Also won't spam PRs with comments, it will update the first (and only) comment instead.

- [x] Initial .codecov.yaml - tested on my fork
- [ ] Enable GitHub integration
- [ ] Test push
- [ ] Test PR

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by sharkykh** [comment]
Quick note. 
It doesn't seem like it works correctly on AppVeyor ATM.
(I'm on mobile but) I saw some errors in the codecov section of the build(s).

**Comment by miigotu** [comment]
As soon as you have this exactly how you want/think it should be, let me know. We can always go back to coveralls if necessary.  But next time, before you spend a bunch of time on something let me know first in case its something I dont think we should do. I wouldn't want you to waste your time!

**Comment by sharkykh** [comment]
Thank you for caring!
It was supposed to be a quick and seamless transition.
I am unsure as to why the **exact same** command works Travis but errors on AppVeyor.

**Comment by miigotu** [comment]
image

**Comment by miigotu** [comment]
The appveyor build isnt registering any test results, only build results. I think I have the yml correct but maybe not.

**Comment by miigotu** [comment]
And, maybe you need some of these vars?
https://github.com/codecov/codecov-bash/blob/master/env#L116

**Comment by sharkykh** [comment]
>The appveyor build isnt registering any test results, only build results. I think I have the yml correct but maybe not.

It's weird, yes, but I don't believe it's a real issue...

> And, maybe you need some of these vars?
https://github.com/codecov/codecov-bash/blob/master/env#L116

I am passing them in tox with `CI APPVEYOR APPVEYOR_*`.

There was one thing I didn't try - passing a private repo token.
[Here](https://github.com/codecov/codecov-python#ci-providers) it says you need it,
but in the repository settings on codecov.io it says otherwise:
> Repository Upload Token
The token below is used exclusively for uploading coverage reports.
**Note: Token not required for public repositories uploading from Travis, CircleCI or AppVeyor.**

And what I meant by errors was this:
```
 C:\projects\sickrage$ C:\projects\sickrage\.tox\tox\Scripts\codecov.EXE -e TOXENV 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
abort: no repository found in 'C:\projects\sickrage' (.hg not found)!
abort: no repository found in 'C:\projects\sickrage' (.hg not found)!
File not found - '*.gcno'
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.5
==> Detecting CI provider
    AppVeyor Detected
    Error running `git log -1 --pretty=%B`: None
==> Preparing upload
    Error running `cd C:\projects\sickrage && git ls-files`: None
    Error running `git ls-files`: None
    Error running `cd C:\projects\sickrage && hg locate`: None
    Error running `hg locate`: None
==> Processing gcov (disable by -X gcov)
    Executing gcov (find C:\projects\sickrage -type f -name '*.gcno'  -exec gcov -pb  {} +)
    Error running `find C:\projects\sickrage -type f -name '*.gcno'  -exec gcov -pb  {} +`: None
==> Collecting reports
    Detecting .bowerrc file
    .bowerrc detected, ignoring /bower_components
    Generating coverage xml reports for Python
    + C:\projects\sickrage\coverage.xml bytes=1102739
==> Appending environment variables
    + TOXENV
==> Uploading
    .url https://codecov.io
    .query package=py2.0.5&service=appveyor&job=miigotu%2Fsickrage%2F378&commit=b1cd2c65ee4df3f6ffb60c3f51ffe120edec493a&build=cq55q0u098mem2kp&slug=SickRage%2FSickRage&pr=3461&branch=develop
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/SickRage/SickRage/commit/0db395df4fa5183edcc58064e51f819427d780bb
___________________________________ summary ___________________________________
  py27-windows: commands succeeded
```

**Comment by miigotu** [comment]
AHHH, I know why.... 
image

Might also need to remove this from yml for appveyor:
```yaml
shallow_clone: true
```

**Comment by sharkykh** [comment]
Let's see

**Comment by miigotu** [comment]
If you notice on the previous build appveyor log does not git clone, this one did. So the project was not a repo for codecov lib to check info on

**Comment by miigotu** [comment]
silly binsearch....

**Comment by miigotu** [comment]
appveyor is taking a really long time to do builds, need to get that down some, maybe even limit it to just testing x86

**Comment by sharkykh** [comment]
Ok this looks much better now, the coverage data is more alike than before.
And yeah... It's like 7-8 min

**Comment by miigotu** [comment]
I would rather make sure SR still runs on an x86 machine, since the travis tests run on x64 we dont get any x86 there

**Comment by sharkykh** [comment]
Oh okay. Also you see I edited my comment... :p

**Comment by sharkykh** [comment]
Do you want me to add coveralls again (so it keeps running too for now) and then you just merge this to develop and see how it goes?

**Comment by miigotu** [comment]
Im fine with just this for awhile. If it doesnt work out its easy to switch back later

**Pull request merged**
