### PR TITLE
Re-enable Strike provider

### PR DESCRIPTION
**Pull request by duramato**
The site search gives a 500 , to "blow away" copytight trolls but the api is alive and kicking
"Proof": https://getstrike.net/api/v2/torrents/search/?phrase=Gotham.S01E01

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
We didnt disable this because it was dead, we disabled it for safety of our users. Strike owner is under heavy legal fire (and even after that they will stay out to get him)

**Comment by duramato** [comment]
@miigotu the court trial has ended for aurous , and strike stuff got resolved when he removed download links from the results

**Comment by miigotu** [comment]
That doesnt mean he is not still a target. They know they can never collect on the lawsuit.

This isnt like TPB where users know they should protect themselves.

**Pull request closed without merging**
