### PR TITLE
Fix Travis build failing, Remove Womble

### PR DESCRIPTION
**Pull request by sharkykh**
Proposed changes in this pull request:
- Fix jshint warnings, and grunt for the latest f62162f35779b360c9938cb6d0f7f44603c228e2.
Initially I missed running the build commands by mistake.
- Update Feed Parser test to replace Womble with BinSearch, in order to fix Travis-CI's builds not passing
because [Womble has been shut down](https://www.reddit.com/r/usenet/comments/5l6soy/farewell_wombles_nzb_index/).
- Remove Womble's NZB Index provider (for the same reason)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Pushed to master also.

Have to work on the site_messages implementation a bit. Getting multiple notices for updates and getting key errors on pop =P

**Comment by miigotu** [comment]
@sharkykh I cant enter my github credentials anymore, there is an error there somewhere.
image

**Comment by sharkykh** [comment]
Found the issue.. Couple of minutes

**Comment by sharkykh** [comment]
@miigotu  do I need to do bower & grunt every time or does TravisCI do that?

**Comment by miigotu** [comment]
Travis does it but doesnt commit it to the repo. You have to do it each time

**Pull request merged**
