### PR TITLE
change yggtorrent url

### LINKED ISSUE #4772: Yggtorrent credential error
No torrent can be downloaded from Yggtorrent: can this be related to the change in their URL redirection as explained on main page:
Important Announcement : Yggtorrent.is domain has just been removed from the Google France index, we will redirect the site to the subdomain ww1.yggtorrent.is 

Branch/Commit:Master -  v2018.06.10-1
OS: Linux
Browser:
What you did: Downloading a torrent using working credentials with yggtorrent as search provider
What happened: getting error Invalid username or password. Check your settings
What you expected: Torrent do be downloaded and sent to torrent server
Logs:
```
2018-06-14 12:22:47 WARNING  SEARCHQUEUE-MANUAL-322399 :: Torrent file content is empty
2018-06-14 12:22:47 WARNING  SEARCHQUEUE-MANUAL-322399 :: Invalid username or password. Check your settings
2018-06-14 12:22:47 INFO     SEARCHQUEUE-MANUAL-322399 :: Downloading Genius.S02E05.-.Picasso.Chapitre.5.2018.FRENCH.TVRip.SD.x264-NoTag from YggTorrent
2018-06-14 12:22:47 INFO     SEARCHQUEUE-MANUAL-322399 :: [YggTorrent] :: Quality of Genius.S02E05.-.Picasso.Chapitre.5.2018.FRENCH.TVRip.SD.x264-NoTag is SDTV
2018-06-14 12:22:47 WARNING  SEARCHQUEUE-MANUAL-322399 :: [YggTorrent] :: Invalid username or password. 

```

### PR DESCRIPTION
**Pull request by djoole**
Fixes #4772 #4770

Proposed changes in this pull request:
- Change of url to 'https://ww1.yggtorrent.is/'

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gfediere** [comment]
could you please merge to fix auth issues ?

**Review by czotti — APPROVED** [review]

**Comment by SkYNewZ** [comment]
please
```
2018-07-10 18:24:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2018-07-10 18:24:28 INFO     SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: Found result The.Flash.2014.S04E01.FRENCH.720p.HDTV.x264-SH0W at https://yggtorrent.is/engine/download_torrent?id=277963
2018-07-10 18:24:28 INFO     SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: Quality of The.Flash.2014.S04E01.FRENCH.720p.HDTV.x264-SH0W is 720p HDTV
2018-07-10 18:24:28 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading The.Flash.2014.S04E01.FRENCH.720p.HDTV.x264-SH0W from YggTorrent
2018-07-10 18:24:29 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Invalid username or password. Check your settings
2018-07-10 18:24:29 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Torrent file content is empty

```

**Review by SkYNewZ — APPROVED** [review]
URL ok

**Comment by djoole** [comment]
@miigotu can you merge people are getting impatient :)

**Comment by SkYNewZ** [comment]
Wainting it : https://github.com/SkYNewZ/SickRage/commit/0498c9058183a8b9bc673ff4c961e8b06f81dafe

And it fix this issue :+1:

**Comment by djoole** [comment]
I haven’t been following the dev team actuality. Are there current problems? It seems they are not so reactive than before to take care of issues and PR...

**Review by antoineguilbert — APPROVED** [review]

**Pull request merged**
