### PR TITLE
Custom Background, fix file browser bug when browsing for files (not dirs)

### PR DESCRIPTION
**Pull request by miigotu**
@h3llrais3r

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by h3llrais3r** [comment]
Ah... it's a new feature. 😄 
I think we will have to make choices and take something from all 3 PR's.
If we use tabs, this will not have a lot of added value...
And I don't want a background of another show on my home screen... but that's just my opinion. 😉

**Comment by miigotu** [comment]
Lol its not an image for a different show, that was just the image I used to test it. You pick any background image you want for SR.
image

**Comment by h3llrais3r** [comment]
But even then... I like that the show fanart is shown as background on the show details, but I have no need to have a background for the rest. 😉 It makes the pages more 'noisy'.
But of course, this is again a matter of taste.

**Comment by miigotu** [comment]
Yeah its just an easy feature to put in with very little code, and nothing to worry about it breaking anything. Younger users will appreciate it a lot =P

**Comment by h3llrais3r** [comment]
@miigotu It's not working since you forgot to minify your core.js and commit it as core.min.js. :rofl:

**Comment by miigotu** [comment]
yeah, set developer = 1 in your config.ini, I dont always minify until merge to master, and developer mode works with pretty js

**Comment by h3llrais3r** [comment]
Thanks! Nice tip. 👍

**Pull request merged**
