### PR TITLE
Clean up some of that log spam

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
Removing this wont help us debug when cache.db is corrupt as SR wont create name cache.
-        logger.log(u"Building internal name cache for " + show.name, logger.DEBUG)

**Comment by miigotu** [comment]
It isnt removed, it is commented out. If it is ever needed it can be uncommented.

Besides, there are logs just before this that let you know the name cache is being updated, and one for success for each show, so that is all that is needed along with checking the status page for the show queue in SR to debug it.

`logger.log(u"Internal name cache for " + show.name + " set to: [ " + u', '.join([key for key, value in nameCache.iteritems() if value == show.indexerid]) +" ]", logger.DEBUG)
`

**Comment by fernandog** [comment]
Ok

**Pull request merged**
