### PR TITLE
Create gists as secret instead of public

### PR DESCRIPTION
**Pull request by fernandog**
``` python
    def create_gist(self, public, files, description=github.GithubObject.NotSet):
        """
        :calls: `POST /gists <http://developer.github.com/v3/gists>`_
        :param public: bool
        :param files: dict of string to :class:`github.InputFileContent.InputFileContent`
        :param description: string
        :rtype: :class:`github.Gist.Gist`
        """
```

https://github.com/SickRage/SickRage/blob/develop/lib/github/AuthenticatedUser.py#L453

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
What's the point in this considering the link is going to be posted publicly anyway?

**Comment by fernandog** [comment]
@OmgImAlexis you can open only if you have a link

if some ones is trying to use gist search to find passwords or whatever, if is 'public' your gist will appear there

**Comment by OmgImAlexis** [comment]
It might as well be the same though, people can just use google to search since it'll be index as it's posted publicly. Just seems pointless.

**Comment by fernandog** [comment]
yes. but new gists wont be possible to do that

**Comment by Arcanemagus** [comment]
@fernandog The point is that the link will still be publicly posted here, so making it a "secret" gist wouldn't really change anything.

**Comment by duramato** [comment]
It reduces the chaces of it beeing crawled, by beeing public on gist it can be crawled from gist and from the issue its posted . By beeing private it can only be crawled from the issue its on

**Comment by miigotu** [comment]
I agree with all of you in this case. Yes it doesnt make it absolutely private, but it does make it slightly less likely to be found.

PPL wont be able to abuse github gist search to find passwords, but google can. Though google will give it a lower ranking because of less linkbacks.

**Pull request merged**
