### PR TITLE
Make black hole working again

### PR DESCRIPTION
**Pull request by DutchEngineer**
Fixes #
## 
## 
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

Make black hole working again

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
This doesn't necessarily make it work again, you are dependent on torrents existing on the site and if they don't exist on others most likely they don't on itorrets either
And iir itorrets got removed becouse it was asking for a captcha or something like that

**Comment by DutchEngineer** [comment]
It works perfectly for me at the moment. I can only find them if I uncommit the itor line.

**Comment by miigotu** [comment]
Who cares if it is enabled =P. Lets see if it causes problems.  Im also working on a libtorrent based solution, but I need to make it use proxy before I can even think about adding it

**Pull request merged**
