### PR TITLE
Bitcannon isnt public

### PR DESCRIPTION
**Pull request by duramato**
Its a private run torrent indexer
https://github.com/SickRage/sickrage-issues/issues/763

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
Build failing `The command "cd .build && npm install && bower install && cd .." failed and exited with 1 during .`

**Comment by OmgImAlexis** [comment]
You need to do this against dev.

**Comment by duramato** [comment]
Total fail lol

**Pull request closed without merging**
