### PR TITLE
Group french team fansub

### PR DESCRIPTION
**Pull request by FireBladeNooT**
I've tested all examples with regular expression website. They works but i'm not sure about ".*" to ignore end of file characters.
I remove "anime_Kaerizaki-Fansub" and "anime_ISLAND" because they works with this regular expression (as well as they works before).
An improvement can be done for "[Z-Team][DBSuper.pw] Dragon Ball Super - 028 (VOSTFR)(720p AAC)(MP4)" because extra_info take "720p AAC" and it should be better with only "720p" I guess (Quality will be unknown?).

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
This needs to be against develop, not master.

**Comment by FireBladeNooT** [comment]
Hello,
could you explain what I've do wrong with my modifications (or request)?
Because name parser of anime french fansub doesn't works.

Sincerly

Date: Sun, 31 Jan 2016 03:52:35 -0800

**Comment by OmgImAlexis** [comment]
You need to open the PR against the develop branch, not the master branch.

**Comment by FireBladeNooT** [comment]
Thanks

**Pull request closed without merging**
