### PR TITLE
Newpct encondig

### PR DESCRIPTION
**Pull request by snamds**
Change to skip some weird characters found in the provider titles

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
encoding to cp1252 makes the problem worse.

**Comment by snamds** [comment]
Worse?
What encoding do you want me to use?
I've used 1252 because the exception I got was this:

2016-09-03 20:01:11 ERROR    SEARCHQUEUE-BACKLOG-290853 :: [Newpct] :: [4219585] Exception while searching Newpct. Error: UnicodeEncodeError('charmap', u'The.Walking.Dead.Michonne.\x96.A.Telltale.Miniseries.Episode.1.[PCDVD.Crack.CODEX]SPANISH.AUDIO-NEWPCT', 26, 27, 'character maps to <undefined>')
Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\search.py", line 489, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "C:\SickRage\SickRage\sickrage\providers\GenericProvider.py", line 180, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRage\SickRage\sickbeard\name_parser\parser.py", line 461, in parse
    name, file_name_result or dir_name_result))
  File "C:\SickRage\Python\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\x96' in position 26: character maps to <undefined>
2016-09-03 20:01:11 DEBUG    SEARCHQUEUE-BACKLOG-290853 :: [Newpct] :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\search.py", line 489, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "C:\SickRage\SickRage\sickrage\providers\GenericProvider.py", line 180, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRage\SickRage\sickbeard\name_parser\parser.py", line 461, in parse
    name, file_name_result or dir_name_result))
  File "C:\SickRage\Python\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\x96' in position 26: character maps to <undefined>

**Comment by miigotu** [comment]
encoding it to 1252 breaks it for every linux user. It needs to stay as unicode.

**Comment by snamds** [comment]
It wasn't unicode before. This web uses 1252 charset

**Comment by duramato** [comment]
A more apropria te solution would be for you to change your sys language and not encode with cp1252 and with the replace arg.

**Comment by miigotu** [comment]
@snamds if it wasnt unicode you wouldnt be able to `.encode` it, you would only be able to `.decode` it if it had a codeset. This masks the problem. Regardless if a site uses 1252, requests converts it to unicode for us so we dont have to worry about encoding in the provider. The problem is somewhere else.

**Comment by miigotu** [comment]
Notice the `u` before `u'The.Walking.Dead.Michonne.\x96.A.Telltale.Miniseries.Episode.1.[PCDVD.Crack.CODEX]SPANISH.AUDIO-NEWPCT', 26, 27, 'character maps to ')` which designates unicode.

The `\x96` in that string is an invalid character, which came from the site.

**Pull request closed without merging**
