### PR TITLE
Some minor fixes for #3185

### PR DESCRIPTION
**Pull request by sharkykh**
Fixes commit 6de1af71e566ef222d788e18172b0436f6e0e10b.
I was getting an exception: 'unicode' object is not callable, on line 389.
I missed that second parentheses when I fixed it while developing.

And also, somehow missed setting the token in config.ini to the correct key.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by sharkykh** [comment]
Oh man,
I also forgot to run grunt
So hold on on the merge to master

**Comment by sharkykh** [comment]
@miigotu I guess it's too late now
I'm sorry about the mess :slightly_frowning_face: 
Do you want me to do a new pull request of https://github.com/sharkykh/SickRage/commit/eb51ea9d81b9bf9ddb0087c91d6912ad4d2b70d8 ?

It's not something urgent. 2 JSHint warnings fixed and a run of grunt

**Comment by sharkykh** [comment]
Also the reason travis-ci is failing is Womble's NZB provider.
https://www.reddit.com/r/usenet/comments/5l6soy/farewell_wombles_nzb_index/
Should we remove this provider? Or at least the test?

**Comment by miigotu** [comment]
sure make a new PR and ill merge it to master after... I already merged dev to master

**Comment by miigotu** [comment]
And no, its definitely not too late for me. Im usually up until 7am haha

**Comment by sharkykh** [comment]
Well I live halfway across the world from you,
so for me it's actually 11am :)

**Pull request merged**
