### PR TITLE
Option to restrict backlog searches to 'missing' episodes only

### PR DESCRIPTION
**Pull request by deepseth**
Vaguely relates to #5207
Backlog searches for any missing episodes. It also searches for any episodes that are downloaded that don't match an allowed quality. What if we don't care about what quality existing files are at, and only care about new downloads matching a particular quality matrix?

E.g. We have no objection to episodes from the 1990s being in SD, but we want new episodes from 2020 to come down in HD (and not SD). Backlog doesn't understand this, and continues to hammer backlog approved providers to try and replace the early episodes anyway.

How about we make backlog not care about 'not allowed' quality downloads, and only focus on missing episodes, and make this a not-default-enabled option?

Proposed changes in this pull request:
- New configuration variable to track this (default=off)
- Updates to front end to allow this to be toggled
- Updates to backend to honour this toggle

- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by deepseth** [comment]
This was remarkably unpainful to try and do, despite having limited python knowledge and no prior experience with this codebase. Kudos to the authors.

**Comment by miigotu** [comment]
Im down to allow another attempt at this, it was implemented several times before in very hacky ways and caused havoc. Could this be an int maybe and only skip episodes older than x number of days or years? 0 would skip all replacements, 1 would skip anything from last year or older, etc.

**Comment by deepseth** [comment]
That'll be possible based on air date I guess, but not based on downloaded date. Whatever the default is, should not change current default behaviour or it'll screw people up who aren't expecting this, so I guess it needs to be two parameters, as a default = 0 is just asking for trouble (0 == False, someone will trip over that later and use == instead of ===). One paramter to enable (what I've already done), and one to provide a time limit.

The limit I guess should be days, months or years. I'm gonna start with it being days for now, based on the original feature request, and set the default value to 7 days (which only matters if the feature is enabled, which by default it is not)

This is going to be based on airdate, as there's no way to be based on downloaded date (that I can see). Any episode that doesn't have an air date defined will fall into the ignored category.

**Comment by miigotu** [comment]
Air date is the best I think except for old shows someone just added =P but yeah enable/disable and a range with a default to disabled.

**Comment by deepseth** [comment]
> except for old shows someone just added

I have no idea how to account for that, hence making the point explicit. If that's a requirement, then the age limit can't be done, and we stop at on or off as it is now.

That said, I don't think that's a problem. It doesn't ignore 'missing', only 'allowed'. If an old show has been added and an unapproved quality download has been found and is there, then it's there. Happy days.

If the goal is to improve the quality of the downloaded episodes, then this feature probably isn't for that person.


Actually, can we just hijack Backlog search day(s) (sickbeard.BACKLOG_DAYS) for this?

**Comment by miigotu** [comment]
This entire feature should already be working if a person has a custom quality with only items selected in the allowed list and none selected in the preferred list btw

**Comment by miigotu** [comment]
The way it works currently, it will allow anything in the allowed list but will continue to try to match a quality in the preferred list if the preferred list has selections, otherwise stick with the first found allowed found,

**Comment by deepseth** [comment]
Look at a show that you have stored in e.g. SD DVD, and specify 720p HDTV as an allowed quality only. No preferred qualities selected.

All episodes of that show that do not match the allowed quality, now get listed in the manage/backlogOverview screen, and the show gets matched and triggered during a backlog search.

This prevents that from occurring.

The way you described is what my expectations were, but it didn't seem to be happening like that, which is why I wrote this. I also *hate* when default behaviour changes out from underneath me, hence making this an option rather than fixing the 'bug'.

**Comment by miigotu** [comment]
Well of course if you change the quality it will start looking for something that matches allowed xD. Anyways, im ok with this being added as-is I guess

**Comment by deepseth** [comment]
Ah sorry, I wasn't sufficiently clear again.

In my case, I batch added a bunch of existing shows to be tracked by Sickchill. They all defaulted to be added as quality HD, but a bunch of old shows are in DVD quality. As a result, they all got added to backlog searches, and continued to be backlog searched for over a week, resulting in rate limit hits.

Anyway, if you're happy as-is, then I'm happy to stop too! :-)

**Comment by miigotu** [comment]
Only worry about the airdate option if you feel you need it, I think its a good PR as it is either way. Thanks.

**Comment by miigotu** [comment]
I get a little nitpicky sometimes and I shouldnt xD

**Pull request merged**
