### PR TITLE
Update download_station.py for Destination

### LINKED ISSUE #7062: Problem sending files to downloadstation 3.8.16-3566
Branch/Commit: master/latest
OS: Synology
Browser:
What you did: Backlog a serie
What happened: Download are not started
What you expected: Download starts
Logs:
```
2021-03-31 11:39:27 INFO :: SEARCHQUEUE-BACKLOG-375655 :: Invalid parameter
2021-03-31 11:39:27 DEBUG :: SEARCHQUEUE-BACKLOG-375655 :: DownloadStation: Response to the POST request is {"error":{"code":101},"success":false}
2021-03-31 11:39:27 DEBUG :: SEARCHQUEUE-BACKLOG-375655 :: DownloadStation: Requested a POST connection to url http://localhost:32768/webapi/DownloadStation/task.cgi and data: {'api': 'SYNO.DownloadStation.Task', 'version': '3', 'method': 'create', 'session': 'DownloadStatio...
2021-03-31 11:39:27 DEBUG :: SEARCHQUEUE-BACKLOG-375655 :: Result Hash is 54cfd78da273b9f2e2dd6c1c26bea9f498df5928
2021-03-31 11:39:26 DEBUG :: SEARCHQUEUE-BACKLOG-375655 :: Calling DownloadStation Client
```

### PR DESCRIPTION
**Pull request by BKSteve**
Add code to get default_destination from Downloadstation since API change.
This pushes the default destination back into the Search Settings>Torrent Search>Downloaded files location if it's found as blank.

Fixes #7062 #7101

Proposed changes in this pull request:
- covers the addition of code to get default_destination
- aggressive change, simplifies and removes code and library imports
- further code reductions.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
I will check this out later today. Thanks for putting in the effort.

**Comment by miigotu** [comment]
Sorry I haven't gotten to this yet. I had to recover files on a friend's PC and set up a dual boot and try to make it as easy to switch to Linux from windows as possible for him. Almost done that but I'm sooo tired with all I've been doing. I'll get to this soon I promise.

**Comment by BKSteve** [comment]
> 
> 
> Sorry I haven't gotten to this yet. I had to recover files on a friend's PC and set up a dual boot and try to make it as easy to switch to Linux from windows as possible for him. Almost done that but I'm sooo tired with all I've been doing. I'll get to this soon I promise.

Not a problem gives me more time to test the changes and contemplate why some of the other code was written. Some more stuff can probably be cleaned up too.
I went with WSL to us Linux on my Windows machine rather than dual boot, but that depends on what your needs are.

**Comment by miigotu** [comment]
I'm trying to get him to switch over permanently to Linux, so dual boot and then transition to just a windows vm, and then to wine, and then to no windows at all like me haha

**Comment by miigotu** [comment]
Btw, it would be better if torrentday changes were in a separate PR, combining two different change sets into one PR is usually not good for future review

**Comment by BKSteve** [comment]
newbie. still at the bottom of the learning curve

**Comment by BKSteve** [comment]
I'm such a newb. I tried to pull the td.py change from this one (looks to be successful). 
Still trying to work out how to send it as a separate pull.
Maybe time to RTFM.

**Comment by miigotu** [comment]
I made some changes here for it, can you enable maintainer update to your PR? 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by BKSteve** [comment]
Sorry, I just killed it all off and recreating.
Don't know what I'm doing in Git and windows Github Desktop.

 #7146 for Download Station
#7145 for TorrentDay

**Comment by miigotu** [comment]
I have one more thing to add back in, will do it shortly

**Pull request closed without merging**
