### PR TITLE
Group french team fansub

### PR DESCRIPTION
**Pull request by medariox**
Replaces https://github.com/SickRage/SickRage/pull/897

From @FireBladeNooT

> I've tested all examples with regular expression website. They works but i'm not sure about .\* to ignore end of file characters.
> 
> I remove anime_Kaerizaki-Fansub and anime_ISLAND because they work with this regular expression (as well as they works before).
> 
> An improvement can be done for [Z-Team][DBSuper.pw] Dragon Ball Super - 028 (VOSTFR)(720p AAC)(MP4) because extra_info take 720p AAC and it should be better with only 720p I guess (Quality will be unknown?).

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
If this works, go ahead =P

**Comment by labrys** [comment]
@medariox if you wouldn't mind waiting just a little while till i get a chance to review it.. it looks like it might be a little too greedy on the matching, but i just glanced at it.

**Comment by medariox** [comment]
Sure @labrys, just let me know when you're done.

**Comment by labrys** [comment]
Since we match regex's in order it should be fine.

**Comment by medariox** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/901/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Pull request merged**
