### PR TITLE
feat(interface): add wire frame for a new web server and front end framework, coexists with tornado

### PR DESCRIPTION
**Pull request by miigotu**
using jinja2 on flask, leveraging webpack, bootstrap5, and an undetermined javascript (react or jquery?)

enabled by command line argument: --flask, --flask-host [optional, default: sickchill host], --flask-port [ optional, default: sickchill port + 1]

Signed-off-by: miigotu <miigotu@gmail.com>

### CODE REVIEW

**Comment by miigotu** [comment]
@daviegravy Here it is so far. I did have react added but it seemed like super overkill, because we already have the templating and routing with jinja2 and flask? Native bootstrap that uses popper or jquery even might still be the better option for us, and it would be less to learn in one go lol.

Unless you think react or angular would be beneficial somehow?

For now just PR to the frontend branch =P

**Comment by daviegravy** [comment]
Both React and Angular have benefits.  
To quote a key concept comparision between Angular and Bootstrap found here https://flatlogic.com/blog/angular-vs-bootstrap-6-key-differences-pros-and-cons/#:~:text=js%2C%20React%2C%20etc.,dynamic%20pages%20with%20TypeScript%20opportunities.

> The main task that Angular helps to solve is building a dynamic interface by providing tools to manipulate and update data on the screen easy and fast.  The primary goal of Bootstrap is to provide tools that help developers to create beautiful responsive UI. You don’t have to write CSS or JavaScript to get the good-looking interface, as well as you don’t need to worry about the display of your web app on different screens because Bootstrap has already taken care of it.

And then there's React, which I quote from https://radixweb.com/blog/react-vs-angular#react comparing React to Angular

> React offers an easy debugging process. The code is reusable. It’s easy to learn because of its easy and simple design. It allows developers to migrate an app in React very easily. It supports both Android and iOS platforms. ReactJS is view-oriented. It has faster updates with both server-side and front-end support. It supports a React Native library that offers efficient performance.

I would be ok with learning either one as they are both in demand in industry.  The only issue will be time.  Angular or React, I would have to learn some of the nuisances of building apps in Angular and how to properly use the React library, whereas with Bootstrap, I could start developing within its full potential on day 1.  I'm currently supporting and developing a Bootstrap 4 framework with jQuery at work so that's all fresh on my mind.

**Comment by miigotu** [comment]
react definitely is the one gaining the most momentum to supercede jQuery. The part that I saw I didn't like is all of the examples are showing a template being built in the react router endpoint for each page, rather than jinja2 templating handling the html and objects coming from python.

Im not hoping for js to create all of the content, but more so to make the stuff that's already there do things.

With jQuery, we called a method on the server to return JSON or whatever we needed for the view.

Angular has the same problem in all of the examples I read, they were creating the entire template in the router, essentially being the view and the controller.

I'm open to try any of them, but maybe we should do only a page or two and decide if we want to stick with that, try another, or the old tried and true jQuery?

I'd definitely like to use Jinja templates extensively, with fragment blocks broken out for example to show a show as a list item or a poster view or whatever on the shows page. It's just easy to edit and more people with less experience will be able to contribute in the future. I don't want everyone to be an expert in js development or react in general to be able to help.

**Comment by daviegravy** [comment]
So in essence Angular is out because we really don't need a full fledged web framework because Jinga will produce our desired markup.  I agree, React should be out for the same reason.  I think we should go with the latest Bootstrap 5 for all the primary UI components and jQuery/JS to handle any data processing not done natively within the templates.  I'll pull down the repo later tonight and get started.  You may have to help me along with some of the structure, any runtime stuff, any testing/dev processes or tools you might utilize to help get me up to speed.

**Comment by miigotu** [comment]
I think a lot of people use react/angular to get jsx, which we have working currently because of webpack.

So you should be able to `yarn` then `yarn build:dev` to build everything.

I use jetbrains, mostly pycharm but sometimes the full ide or webstorm. If you contribute for awhile I can get you a full product license for all jetbrains products because they sponsor SC as  OSS that way.

Any questions I should be able to help you with, but check out the frontend directory. The frontend/shows.py is routes for that blueprint, which uses the frontend/templates for markup and jsx.

**Comment by miigotu** [comment]
I'm actually surprised I was able to get it working as far as I did. I tried dozens of times to convert our existing UI to use webpack when bower was deprecated and failed.

**Comment by miigotu** [comment]
I think xo/eslint config needs updated for webpack, per https://github.com/xojs/xo readme

With these:
https://webpack.js.org/configuration/resolve/
https://github.com/import-js/eslint-plugin-import/blob/main/resolvers/webpack/README.md

As well as maybe updating webpack config to load for xo:
https://github.com/Semigradsky/xo-loader
https://github.com/nstanard/xo-webpack-plugin

Webpack will probably catch errors when building, xo will probably just enforce a code style I guess.

**Comment by daviegravy** [comment]
I'm having a little bit of trouble using git to get this frontend branch.  Can you give me the rough steps I need to do in order to accomplish getting this pulled down.  I've never used git other than the few commands to update SickChill.  

I think I messed up doing a clone because when I run git branch, I only see master listed.  Thanks for your help.

**Comment by daviegravy** [comment]
Maybe I didn't screw it up this time.  Please tell me if any of this is incorrect.  

I did the following:
git init
git remote add origin *sickchill_git_url*
git fetch origin frontend
git pull origin frontend

Do I need to checkout frontend or what do I need to do in order to start developing.  Also what should I do when I'm ready to show you or update the branch?

Thanks!

**Comment by miigotu** [comment]
You would first fork to your own GitHub from the main repo page here.

Then you clone your own repo to your PC, which will already have the branches from upstream.
```bash
git clone github.com/daviegravy/sickchill.git
cd sickchill
git checkout frontend
make changes
git commit -asm "message" (or explicitly add files to the commit with git add filename and then got commit -asm "message")
git push origin
```
When you are ready to merge to changes back to upstream:
Open PR to sickchill/sickchill:frontend

**Comment by daviegravy** [comment]
when I try to do the clone command I get the following:

$ git clone https://github.com/daviegravy/sickchill.git
Cloning into 'sickchill'...
remote: Repository not found.
fatal: repository 'https://github.com/daviegravy/sickchill.git/' not found

It did bring up my credential manager and I got that all satisfied, but when it passes me back to my command I get the messages above.

**Comment by daviegravy** [comment]
Ok, I went out and created the repo sickchill in my GitHub account and now when I run the clone it tells me I have cloned an empty repository.

**Comment by daviegravy** [comment]
Well I reverted back to the commands I posted that allowed me to successfully download the repository.  I installed yarn and ran the yarn build:dev.  How exactly do I start this instance of SickChill?  I know before when y'all had trouble with the service stuff, I would just run python SickChill.py on the command line and it would spawn all the processes, webhost and whatnot, but when I attempt run this instance using the same command, I get the following:

`Traceback (most recent call last):
  File "C:\Users\dwaterson\Documents\sc\SickChill.py", line 14, in <module>
    import sickchill.start
  File "C:\Users\dwaterson\Documents\sc\sickchill\__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\Users\dwaterson\Documents\sc\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "C:\Users\dwaterson\Documents\sc\sickchill\show\indexers\handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "C:\Users\dwaterson\Documents\sc\sickchill\logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'`

I suspect I messed up something with my git since I'm seeing this github reference in the output.  Sorry I'm such a hassle.  I literally know nothing of what I'm doing right now.  I've never used git and I've always just installed SickChill on windows using the installer and never had to do much manual intervention so I'm kinda just doing things blindly.

**Comment by miigotu** [comment]
@daviegravy delete the repo you created in your GitHub, and fork SickChill to yours (that's what creates it on your account)

Screenshot_20221013-194009

We don't provide dependencies with the source, so you have to set it up for development:
```bash
(After you cloned and entered the SC dir)
pip install poetry
npm I -g yarn
yarn --dev
poetry install --with speedups --with frontend # this will install dependencies in a virtualenv as editable 
.venv/bin/SickChill
```

**Comment by miigotu** [comment]
I'm going to merge this isn't the main branch, because without the args it won't even be ran (and even if it fails to import it won't cause a problem). This will help me avoid conflicts when things are updated in the main branches

**Comment by miigotu** [comment]
You can open pull requests right to the develop branch whenever you have any pages or fixes done.

**Comment by daviegravy** [comment]
Sorry I haven't replied in a few days.  Weekend was busy.  I've followed your instructions and have been able to get all the way to past the poetry command.  It looks like it downloaded and installed all the dependencies. It shows Installing the current project: sickchill (2022.10.13).  The issue is I try to run the .venv/bin/SickChill and I get not a valid command.  Hence, I'm using Windows to do all this so please consider that.  .venv and venv both were invalid.  What do I need to do on this last step after running the poetry command on a Windows machine?  Thanks @miigotu !

**Comment by miigotu** [comment]
You can use poetry to run it `poetry run sickchill `

This way poetry automatically activates the venv it created for SC

**Comment by daviegravy** [comment]
It works!  Thank you @miigotu.  Thank you for your patience.  I will get started reviewing the UI and making some assessment.

**Comment by daviegravy** [comment]
@miigotu Can you provide me some preliminary system structure details?  You mentioned the following:

> Any questions I should be able to help you with, but check out the frontend directory. The frontend/shows.py is routes for that blueprint, which uses the frontend/templates for markup and jsx.

I'm not seeing any frontend directory.  If you can briefly tell me what files and their respective paths I need to be focusing on, that would great.  Thank you!

**Comment by miigotu** [comment]
It only exists in the develop branch so far.

Check git branch for what branches you have (forking should have given you all branches from the main repo)

If so:
`git checkout -b frontend origin/develop`
If not:

```bash
git remote add upstream https://github.com/sickchill/sickchill.git
git fetch upstream
git checkout -b frontend upstream/develop
```

Once you are on a new branch based on develop, the frontend directory will be there.

**Comment by daviegravy** [comment]
Dude, this git shit is wild.  I had to add the upstream but it worked and I now see the frontend.  Once again, thanks for your patience.

**Comment by miigotu** [comment]
I've been using git since before it was publicly released lol so it's second nature to me

**Comment by daviegravy** [comment]
Ok,

I've been reviewing the frontend directory structure.  I've tried hitting the route for the shows template that currently defined out in the frontend but I get page cannot be found.  Is there some trick to getting this page to show up in SickChill?  Thanks @miigotu

**Comment by miigotu** [comment]
You have to either set an environment variable or add a cli arg. poetry run sickchill --flask --flask-port 8090

**Comment by miigotu** [comment]
See original comment here

**Comment by daviegravy** [comment]
It seems to still be spawning SC on port 8081

C:\Users\daviegravy\Documents\sc\sickchill>poetry run sickchill --flask --flask-port 8090
2022-10-20 13:11:24 INFO :: MAIN :: Starting SickChill [2022.10.13] using 'C:\Users\daviegravy\AppData\Local\sickchill\sickchill\config.ini'
2022-10-20 13:11:24 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/

**Comment by miigotu** [comment]
Tornado is still started on the default/configured port, and flask will be started on default port+1 or whatever port you tell it to.

This way, you can reference the pages in tornado of you need to, and still have the flask server up.

So if tornado is on 8081, flask will be on 8082 by default if you specify --flask, or --flask-port if you provided it.

**Comment by daviegravy** [comment]
So I went ahead and re-ran the command with just --flask
`poetry run sickchill --flask`
and just let the default port of 8082 be assigned to the Flask server.  I'm unable to resolve http://localhost:8082/ or any route from there such as http://localhost:8082/shows

I did a netstat -a to see if anything was listening on port 8082 and nothing is listening other than the Tornado server on 8081.  Am I doing something wrong?  Will there be any logging output when Flask is running to give me some verification that it is running?

**Comment by miigotu** [comment]
I can add some logging around it. But I suspect the flask dependencies are not installed, because currently I allow the code to fail gracefully and pretend nothing happened, so that our ongoing code/work can not effect regular users in any way.

Did you:
`poetry install --with frontend --with speedups --with dev`

--with installs optional dependency groups 
The frontend group installs flask

**Comment by daviegravy** [comment]
I did that install command before I had the frontend checked out properly with git.  It complained initially, wanting me to run poetry lock --no-update to fix inconsistencies with pyproject.toml.  Once I did that, it let me run the install command and built out all the dependencies.  I then was able to see *Serving Flask app 'SickFlask' message on start up and port 8082 offered me up the following page:

image

Will the shows template not execute?
I see you have a little sample of code that should loop through and print out all the shows
`<block head %>
    <link rel="stylesheet" href="/static/shows.css">
    <title><block title %><endblock %></title>
<endblock %>
<block content %>
    <div class="row">
        <div class="col-md-12">
            <h1 class="header">Listing Shows</h1>
            {% for show in shows %}
            <p>{{ show.name }} ({{ show.startyear }})</p>
            <p>{tvdb: {{ show.indexerid }}</p>
            <p>imdb {{ show.imdb_id }}</p>
            {% endfor %}
        </div>
    </div>
<endblock %>
<%block footer %>
    <script src="/static/shows.js"></script>
<endblock %>`

BTW, thank you for your time.  I know it seems like you are babysitting a child here, but I promise you once I get all this set up and execution settled, I will be of use.  Thanks!

**Comment by daviegravy** [comment]
I documented this set up and installation process in a Word document.  This will allow me to follow all the necessary steps you helped me through in case I need to set up development on another computer (which I may have to do).  It will also allow you to get any other developers up to speed rather quickly if you onboard any others from here out (that are using Windows).  Take a look at the guide and just make sure I didn't overlook a step or so.  Feel free to use however you need (documentation, etc).
[sickchill_windows_developer_setup.pdf](https://github.com/SickChill/sickchill/files/9840601/sickchill_windows_developer_setup.pdf)

**Comment by miigotu** [comment]
If you want to, you can create a page on the wiki we are working on updating.

You can fork and check this out like a regular repository, make a markdown file and add and commit it. Or, you can use the GitHub web UI to create a file there too and it will guide you through a pull request adding the new file:
https://github.com/SickChill/SickChill.WikiTemp

**Comment by daviegravy** [comment]
Can you provide any feedback as to why the shows.html page will not load up above?  I'm reviewing the files necessary for shows and it looks like everything is there.  I see the template file, the jsx file, and the python script.  It tells me 
jinja2.exceptions.TemplateNotFound: shows.html
Any help will be greatly appreciated.  Thanks!

**Comment by daviegravy** [comment]
@miigotu Hey, I wanted to ping you on the error above and see if you could help resolve it.  I've taken a look at all the sourcings and everything seems to be in place according to https://flask.palletsprojects.com/en/2.2.x/quickstart/#rendering-templates
I'm not sure if something is up with our folder structure.  
https://stackoverflow.com/questions/23327293/flask-raises-templatenotfound-error-even-though-template-file-exists
Most say it's because the template file is not in the correct location, but everything I'm seeing shows ours to be correct.

**Comment by daviegravy** [comment]
@miigotu I've made some progress today on the flask server.  There seems to be some fundamental pathing issue with where the flask application is being instanced from.

I've been unable to resolve the TemplateNotFound issue using any form of relative pathing exhausting all variations of "templates", "frontend/templates", "../frontend/templates, "../../frontend/templates", etc. etc. trying to get back to the frontend subfolder so it can be properly pathed.

It wasn't until I told the flask server to use an absolute path that it started working correctly.

`        self.app = Flask("SickFlask", template_folder="C:/Users/Owner/Documents/sc/sickchill/frontend/templates", static_folder="C:/Users/Owner/Documents/sc/sickchill/frontend/static", static_url_path="/static")
`
I also had to do the absolute pathing for the static folder and all the css/js got sourced in correctly.  I have no idea where this relative path that flask is hosting is located.  If you any information for me to try, I know you'd want this using relative pathing.  There was some oscmd stuff that I think we could use to tell flask where to look.  I found some decent threads on this issue.  Once debugging tool I could not get implemented was the following:

> You can ask Flask to explain how it tried to find a given template, by setting the [EXPLAIN_TEMPLATE_LOADING option](https://flask.palletsprojects.com/config/#EXPLAIN_TEMPLATE_LOADING) to True. For every template loaded, you'll get a report logged to the [Flask app.logger](https://flask.palletsprojects.com/quickstart/#logging), at level INFO.

I thought this would be useful if I could get it enabled as it would show where flask is attempting to load templates from which would allow me to create the proper relative path. 

Any insight you may have on the issue is greatly appreciated.  

Either way, we can move forward with development as shows.html is rendering now

image

**Comment by miigotu** [comment]
Not sure, I've been messing with it the past few days, I'll try and check tonight

**Comment by daviegravy** [comment]
@miigotu Is there a space we can chat about development that is not tied to a thread?  I know you mentioned your roadmap ideas when I first mentioned helping with development.  I'd ready to kick the tires if you will.  Share your vision (documents, diagrams, ideas, etc.) and a space we can discuss in detail going forward and let's get it started.  Thanks!

**Comment by miigotu** [comment]
> @miigotu Is there a space we can chat about development that is not tied to a thread?  I know you mentioned your roadmap ideas when I first mentioned helping with development.  I'd ready to kick the tires if you will.  Share your vision (documents, diagrams, ideas, etc.) and a space we can discuss in detail going forward and let's get it started.  Thanks!

We have a developer only channel on the discord, we can talk there or in private chat there. The links are on the GitHub, pypi page, or in SickChill to join our discord, and pm me to get the developer role.

**Pull request merged**
