### PR TITLE
The js

### PR DESCRIPTION
**Pull request by BKSteve**
Some js BS, just guessing based on minimal reading.

not sure on this, particularly data-var to datavar.

This would probably require changing all `meta.data-var` to `meta.datavar` to be consistent

## Summary by CodeRabbit

- **Style Updates**
  - Adjusted editor configurations for improved code consistency.
  - Enhanced the visual style of the user interface with CSS property adjustments.

- **Documentation**
  - Updated README with correct URLs.
  - Revised contribution guidelines and developer documentation.

- **New Features**
  - Introduced a web interface for managing movies and shows.
  - Added a new configuration module and related views in the frontend.
  - Implemented workflows for Docker setup and version retrieval.

- **Bug Fixes**
  - Corrected funding information in the community profile.
  - Updated package dependencies and fixed related issues.

- **Refactor**
  - Streamlined service initialization scripts and variable naming.
  - Improved FlaskServer class and its configuration setup.

- **Chores**
  - Updated GitHub Actions to newer versions and modified workflows.
  - Cleaned up the .gitignore file for better maintainability.
  - Removed unnecessary pre-commit hooks.

- **Tests**
  - Added a test for release strings to ensure proper version formatting.

- **Revert**
  - Removed changes that were not contributing to functionality or stability.

### CODE REVIEW

**Comment by BKSteve** [comment]
@coderabbitai pause

**Comment by BKSteve** [comment]
something wrong with _Workflow_ and the code review run of black 23.11.1

**Comment by miigotu** [comment]
Need to take out the tests.js change for ava here and i can merge, the fix was to remove esm as a requirement to ava

**Comment by BKSteve** [comment]
Killing

**Pull request closed without merging**
