### PR TITLE
Fixed TMDB API key.

### PR DESCRIPTION
**Pull request by ofir123**
Fixes #

Proposed changes in this pull request:
TMDB API has changed.
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by sharkykh — APPROVED** [review]

**Comment by sharkykh** [comment]
Thanks

**Comment by OmgImAlexis** [comment]
@sharkykh @ofir123 who's account is that token from? We should really be using one from an account just setup for Sickrage instead of a personal account.

**Comment by sharkykh** [comment]
I don't know the answer to that.
But we do have `sickbeard.TMDB_API_KEY` set if needed (I think it still works).
This modification is intended to be in Subliminal so I think it'll be removed in the future

**Comment by ofir123** [comment]
I've created my own account and used that key..
But you're definitely right! I'll switch to sickbeard's and create a new PR.
(It'll be my key when it gets into subliminal, but until then...)
Thnx @OmgImAlexis @sharkykh

**Comment by sharkykh** [comment]
@ofir123 
Oh man, the amount of personal info you're required to enter when requesting an API key is too much...

**Comment by ofir123** [comment]
I know!
But I need my subtitles haha!
And... there you go: #3920

**Pull request merged**
