### PR TITLE
Added modal for testing the watchlist through a bootstrap modal

### PR DESCRIPTION
**Pull request by p0psicles**
- Added modal to mako template, js code in core.js and backend code for testing the watchlist through a bootstrap modal.
- Fixed bug when two watchlists where added. But one valid and one invalid. This made the mako template crash. Build in same checks for building the imdb watchlist select box.
- Removed the old commented out included js for imdbWatchlist.js.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
Since this is to a feature branch just ping one of the main devs and we'll merge it.
Once it goes into dev I'll have to look over a LOT of the js as you're not adding code in the same style as the rest of core.js and it'll mean we'll end up with a fragmented code base which I really don't want to have to deal with **AGAIN**.

**Comment by p0psicles** [comment]
Maybe it's a good idea to tell me what I'm doing different. Then I can try to adapt my style of coding.

**Comment by OmgImAlexis** [comment]
@p0psicles really I need to go through and rewrite it in order to explain. Just from looking at a bit of this it seems you're coming from a OOP background and applying that to code that isn't even close to OOP.

**Comment by p0psicles** [comment]
Wuut? Js is not OOP?

**Comment by OmgImAlexis** [comment]
Javascript CAN be but this code base isn't even close and you should be able to see that if you have a look at the other 3k+ lines.

**Comment by p0psicles** [comment]
Yeah know what you mean. Getting off topic here. But I'm writing code the way I do it, always to keep it modular and readable. And then I don't care if it's js, python, c# or java.

**Comment by OmgImAlexis** [comment]
We always get off-topic, not being rude but unless it conforms to the same style I've got the rest of the files into then it probably won't be merged as it's stupid to keep multiple different code styles in a single code base.

**Comment by labrys** [comment]
@OmgImAlexis agreed, unless you are determined to rewrite everything to the new style, then an interim period of incremental changes with both styles would be acceptable. You would, however, have to avoid falling into the trap of not finishing the changes and being stuck with both.  Ok enough off topic :grinning:

**Comment by p0psicles** [comment]
I agree. I think we're mostly talking about the js code for the variable text input where the watchlists can be added. Well my goal from the start was to create an element with some meta information in it with references to two hidden inputs. One for the '|' wl_enabled and one for the '|' wl_url input. Then you could create more of those controls all over your page. Where the Js is bind to element with meta info.

The solution now, is limited to one controll set.
@OmgImAlexis if you are going to rewrite it anyway. And you can realize that, I would be very happy!

**Comment by OmgImAlexis** [comment]
[This](https://github.com/SickRage/SickRage/compare/develop...imdb-watchlists#diff-5329b74ce808a7064dc3b930e52c97b6R367) is the main thing I was talking about and again [here](https://github.com/SickRage/SickRage/compare/develop...imdb-watchlists#diff-5329b74ce808a7064dc3b930e52c97b6R485). I'll try and rewrite some of this tomorrow to show you what I mean.

@p0psicles I want to rewrite everything but I first need ALL of the js including the other files we've got now either included with bower or added to core so I can clean it all up at once. That's the reason I don't want any OOP or anything like it in here as it'll just complicate things more than it needs to.

**Pull request merged**
