### PR TITLE
Fix coming episodes ordering. Fixes #3243

### LINKED ISSUE #3243: Schedule/ComingEpisodes is all out of whack when sort by date
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

Episodes/Days are out of order

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
@SickRage/moderators @SickRage/collaborators Could you check this on your show lists please?

**Comment by sharkykh** [comment]
Works for me.

I didn't seem to have any problem with it before, could you explain how it was out of order?
The only thing I can think of was that it was unordered for a second just until $.tablesorter() takes over the table and sorts it out.

**EDIT:** This is what my schedule looks like on develop and on this PR.
The differences I marked are only in the order of the shows - the times are correct.
For example, `The Fosters` and `The Flash` both air at the same time (3am local time).
[image](https://cloud.githubusercontent.com/assets/10238474/23403978/69823d58-fdbb-11e6-9aed-c18d90a4b7a4.png)

**Comment by miigotu** [comment]
With date or network sorting in poster and banner view if you followed the dates down the list they would jump back and forth, and you could have mutiple saturdays for example because of them being out of order.
Either way this code is much easier to read, less sql.

**Comment by sharkykh** [comment]
Oh, yeah, I see that now.
Either way, like you said the code is more readable.

**Pull request merged**
