### PR TITLE
change yggtorrent url

### PR DESCRIPTION
**Pull request by skillfr**
Or adapter for the code that it recovers the target https://yggtorrent.is

```
import requests
response = requests.get('https://yggtorrent.is')
print(response.url)
```

### CODE REVIEW

**Review by JoshuaArus — APPROVED** [review]
Worked for me

**Review by Dioperso — APPROVED** [review]
work for me

**Comment by ArthurGarnier** [comment]
Changed again to www...

**Comment by djoole** [comment]
Would be better to add a dialog in the torrent settings to let the user choose the url (which is changing to often to hardcode it).
I'll try to do that if I can find the time

**Review by ArthurGarnier — CHANGES_REQUESTED** [review]
Should be "www" now

**Comment by ArthurGarnier** [comment]
"requests" is also a good idea as main domain redirect to the right subdomain.

**Comment by JoshuaArus** [comment]
I agree on the "requests" feature. An input in the providers configuration to specify URL would not be as powerful because user need to notice the domain change, check the new one and update the configuration.

requests.get should work properly at every subdomain change.

**Pull request closed without merging**
