### PR TITLE
Multiple notifications & notifications on mobile browsers

### LINKED ISSUE #3469: Multiple Chrome Notification
Since some time i have observed that chrome has been showing multiple notifications for the sickrage, this happens with all the notifications, attached is the debug log & screenshot  of check update notification I have received. I am not sure this is bug or expected behaviour.

Branch/Commit: Master/949e0acc613e8cc14c7555a3f154f031a94a9768
OS:Linux-4.9.16-v7+-armv7l-with-debian-8.0 (Raspberry PI 3)
What you did: Check Update & Other Notification like manual search of episodes
What happened: Getting Multiple Notification (2, 3, 4 even 5 sometimes)
What you expected: Get Single Notification
Logs:
```
2017-03-22 18:56:48 DEBUG Thread-16 :: check_for_new_news: Checking GitHub for latest news.
2017-03-22 18:56:48 INFO Thread-16 :: No update needed
2017-03-22 18:56:48 DEBUG Thread-16 :: cur_commit = 949e0acc613e8cc14c7555a3f154f031a94a9768, newest_commit = 949e0acc613e8cc14c7555a3f154f031a94a9768, num_commits_behind = 0, num_commits_ahead = 0
2017-03-22 18:56:48 DEBUG Thread-16 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-03-22 18:56:48 DEBUG Thread-16 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/sickrage
2017-03-22 18:56:48 DEBUG Thread-16 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2017-03-22 18:56:48 DEBUG Thread-16 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/sickrage
2017-03-22 18:56:48 DEBUG Thread-16 :: git branch --set-upstream-to origin/master : returned successful
2017-03-22 18:56:48 DEBUG Thread-16 :: Executing git branch --set-upstream-to origin/master with your shell in /opt/sickrage
2017-03-22 18:56:48 DEBUG Thread-16 :: git fetch origin : returned successful
2017-03-22 18:56:46 DEBUG Thread-16 :: Executing git fetch origin with your shell in /opt/sickrage
2017-03-22 18:56:46 DEBUG Thread-16 :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
2017-03-22 18:56:46 DEBUG Thread-16 :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /opt/sickrage
2017-03-22 18:56:46 DEBUG Thread-16 :: git rev-parse HEAD : returned successful
2017-03-22 18:56:46 DEBUG Thread-16 :: Executing git rev-parse HEAD with your shell in /opt/sickrage
2017-03-22 18:56:46 DEBUG Thread-16 :: git symbolic-ref -q HEAD : returned successful
2017-03-22 18:56:46 DEBUG Thread-16 :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickrage
2017-03-22 18:56:46 INFO Thread-16 :: Checking for updates using GIT
2017-03-22 18:56:22 DEBUG Thread-16 :: check_for_new_news: Checking GitHub for latest news.
2017-03-22 18:56:22 INFO Thread-16 :: No update needed
2017-03-22 18:56:22 DEBUG Thread-16 :: cur_commit = 949e0acc613e8cc14c7555a3f154f031a94a9768, newest_commit = 949e0acc613e8cc14c7555a3f154f031a94a9768, num_commits_behind = 0, num_commits_ahead = 0
2017-03-22 18:56:22 DEBUG Thread-16 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-03-22 18:56:22 DEBUG Thread-16 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/sickrage
2017-03-22 18:56:22 DEBUG Thread-16 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2017-03-22 18:56:22 DEBUG Thread-16 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/sickrage
2017-03-22 18:56:22 DEBUG Thread-16 :: git branch --set-upstream-to origin/master : returned successful
2017-03-22 18:56:22 DEBUG Thread-16 :: Executing git branch --set-upstream-to origin/master with your shell in /opt/sickrage
2017-03-22 18:56:22 DEBUG Thread-16 :: git fetch origin : returned successful
2017-03-22 18:56:20 DEBUG Thread-16 :: Executing git fetch origin with your shell in /opt/sickrage
2017-03-22 18:56:20 DEBUG Thread-16 :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
2017-03-22 18:56:20 DEBUG Thread-16 :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in /opt/sickrage
2017-03-22 18:56:20 DEBUG Thread-16 :: git rev-parse HEAD : returned successful
2017-03-22 18:56:20 DEBUG Thread-16 :: Executing git rev-parse HEAD with your shell in /opt/sickrage
2017-03-22 18:56:20 DEBUG Thread-16 :: git symbolic-ref -q HEAD : returned successful
2017-03-22 18:56:19 DEBUG Thread-16 :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickrage
2017-03-22 18:56:19 INFO Thread-16 :: Checking for updates using GIT
```
sickrage

### PR DESCRIPTION
**Pull request by sharkykh**
- [x] ~Should fix #3469 - still waiting on @DDA78 to test if using `desktop.tag` fixes the issue of multiple notifications.~
### Moved to #3837
***

- [x] Bump PNotify to v3.2 (there seems to be no reason not to)
- [x] Change notifications fallback handling (currently there's none)
  * If user blocks desktop notifications, regular ones will be shown.
  * If user is using a mobile browser then use regular notifications
(no mobile browser currently support Notifications API, see [this](http://caniuse.com/#feat=notifications))
  * Also don't ask for notification permission on mobile browsers, for the same reason as above
- [ ] Style the regular notification to look nicer (light & dark styles)

---

@OmgImAlexis @miigotu 
About the change I made regarding fallback:
I still think we should show the same notifications.
If the user **blocks the notifications**, then we just show them within the browser instead of as a "Desktop" notification.
If you think that there might be users that don't want to see any notifications, we can:
- [ ] Add a config option to disable notifications completely,
then when we use `ui.notification` we just check that, and **log it** (probably as INFO) instead of showing the notification.

If you're still against 'fake' notifications on mobile devices, then we'll just disable them for now.

How's that?

### CODE REVIEW

**Comment by sharkykh** [comment]
There's no reason not to merge the multiple notifications fix.
I'll just create a different PR for it so it can be merged.
I'll leave the other stuff here for a later time.

**Comment by miigotu** [comment]
Why cant this one be merged as it is?

**Comment by sharkykh** [comment]
@miigotu 
I still need to style the non-desktop notifications, and add the config options to completely disable notifications.
Need to be in the mood lol

**Comment by sharkykh** [comment]
I have a local copy, I'll remake this another time.

**Pull request closed without merging**
