### PR TITLE
Tvdb3

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by jangrewe** [comment]
Thanks for working on this! 😘

**Comment by Parlane** [comment]
Thanks @miigotu , this fixes the issue where sickchill was trying to get the show banner from _cache/banner/ and getting a 404

**Comment by jangrewe** [comment]
I've checked out the `develop` branch, and while it does get metadata from TheTVDB, it seems to only download the info for the first episode of each season when doing a full refresh for a show. That happens for e.g. Messiah (2020), Fauda, Ray Donovan or Shameless.

**Comment by miigotu** [comment]
@jangrewe that is fixable. Metadata is the biggest thing I'm worried about.

**Comment by miigotu** [comment]
@jangrewe is that with nfo, xml, or on displayshow page? It would help to know which metadata provider if you mean bfo or xml for example

**Comment by jangrewe** [comment]
That's on the regular page when viewing a particular show (`/home/displayShow`), so probably the displayshow you mean.

**Comment by jangrewe** [comment]
Here's how e.g. Fauda looks:
Fauda

**Comment by jangrewe** [comment]
This is the log output for Messiah (2020) when doing a full refresh:
```
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E01 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E02 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E03 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E04 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E05 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E06 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E07 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E08 from the database
2020-01-07 00:36:08 INFO     SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E09 from the database
2020-01-07 00:36:11 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Messiah (2020)
2020-01-07 00:36:15 INFO     SHOWQUEUE-REFRESH :: 373186: Updating NFOs for show with new indexer info
2020-01-07 00:36:16 INFO     SHOWQUEUE-REFRESH :: Done cache check
```

**Comment by miigotu** [comment]
@jangrewe should be fixed ;)

**Comment by jangrewe** [comment]
@miigotu Unfortunately not, i think. I've updated to `dd08dc42b1cb15d6077eb39c78cb2d4de76e4a4e`, but still only the last episode of each season is shown correctly, all others have empty column fields except for the local filename/size.
(Just noticed that i said **first** episode in a previous comment, but it's the "first in the table", so actually the last of a season).

**Comment by miigotu** [comment]
@jangrewe delete the metadata files from the show folder and season folders, any xml or nfo

**Comment by miigotu** [comment]
I'll try some more tests here in a bit, I was using only one episode for my tests before so I might have something wrong.

**Comment by jangrewe** [comment]
Did that for one show, and they got recreated with what looks like valid data, but the airdate is still missing from the episode .nfo (except for the last episode). And while the right episode names are in all files i checked, SC doesn't display them (the names) on the page.

**Comment by Wally73** [comment]
i had to re-add most of my shows to get it showing normal again

**Comment by miigotu** [comment]
I'm getting the problem now too. Trying to investigate

**Comment by jangrewe** [comment]
Looks like your latest commit fixed it! <3

**Comment by miigotu** [comment]
@jangrewe thanks for confirming. I had to make a big dummy show and actually use a real debugger for once in my life to find this one haha.

**Comment by jangrewe** [comment]
hehe, the right tool for the job, nice one! and big thanks 😘

**Comment by jangrewe** [comment]
So while seem to be not harmful (at least for me), i guess i should also report these:
```
2020-01-07 17:47:46 ThreadPoolExecutor-0_18 :: there's a coding problem contact developer. It's needed to be provided at lest one of the two: data_show or show_obj
2020-01-07 17:40:35 SEARCHQUEUE-MANUAL-161511 :: there's a coding problem contact developer. It's needed to be provided at lest one of the two: data_show or show_obj
2020-01-07 17:40:11 ThreadPoolExecutor-0_14 :: there's a coding problem contact developer. It's needed to be provided at lest one of the two: data_show or show_obj
2020-01-07 17:38:02 SEARCHQUEUE-MANUAL-259866 :: there's a coding problem contact developer. It's needed to be provided at lest one of the two: data_show or show_obj
2020-01-07 17:37:27 ThreadPoolExecutor-0_23 :: there's a coding problem contact developer. It's needed to be provided at lest one of the two: data_show or show_obj
```
Those pop up for a couple of shows i refreshed.

**Comment by miigotu** [comment]
@jangrewe thats gonna be a difficult one, because I dont use trakt. that log line is coming from the update_watchlist method for trakt, and it was failing much worse before

**Comment by miigotu** [comment]
a debugging we will go! lol

**Comment by miigotu** [comment]
@jangrewe whats the log look like before those?

**Comment by miigotu** [comment]
lol nevermind I think I found it

**Comment by jangrewe** [comment]
yup, looking good! log stays clean when doing a refresh or other random things :-)

**Comment by miigotu** [comment]
I know as soon as I put it in master I'll get blasted with 50000 issues haha

**Comment by jangrewe** [comment]
hrhrhr... but you gotta do it anyways, sooner or later ;-)

well, on the upside: at least no new issues about TVDB not working anymore!

**Pull request merged**
