### PR TITLE
Add better test coverage to GenericProvider

### PR DESCRIPTION
**Pull request by leviable**
Fixes #N/A

Proposed changes in this pull request:
- Add better test coverage to GenericProvider class
## \- Add mock package to lib/
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)
  - Add better test coverage to GenericProvider class
  - Add mock library to lib directory

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by leviable** [comment]
I'd like to add many more tests to improve coverage, but before I do I woudl like to make sure my general approach isn't going to ruffle any feathers. Specifically, adding mock and mock dependencies to `lib/`

**Comment by miigotu** [comment]
About mock, that doesnt really need to be in lib since it isnt used during runtime for end users. To have it available for nosetests, add it to the pip line in the .travis.yml

I will look at this a bit more later.

Im interested in creating setup.py also, if not only for tests depends

**Comment by leviable** [comment]
Amended commit to remove additions to `lib/`, and instead updated `.travis.yml` to pip install mock.

**Pull request merged**
