### PR TITLE
add new pills to parsers

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Using an object means it's a lot easier to update in the future.

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis thanks ! didn't need to to the grunt stuff ??

**Comment by OmgImAlexis** [comment]
Nope, only core.js uses that for now.

**Comment by fernandog** [comment]
ahh sorry. If I knew I would changed

**Comment by fernandog** [comment]
@OmgImAlexis 

Can't understand why it's not working. I cleared browser cache and mako cache
image

**Comment by OmgImAlexis** [comment]
Maybe you gave me the incorrect text that's returned?

**Comment by OmgImAlexis** [comment]
Send me a gist of the page source.

**Comment by fernandog** [comment]
sent in IRC

**Pull request merged**
