### PR TITLE
Added option to choose which extensions to keep for PP

### PR DESCRIPTION
**Pull request by medariox**
Thanks to @fernandog for the mako stuff.
Also includes mislabled/fake file check with season comparison.

Feature request: http://feathub.com/SiCKRAGETV/SickRage/+43

### CODE REVIEW

**Comment by labrys** [comment]
Testing in progress: Win10x64

**Comment by fernandog** [comment]
@ripper1967

**Comment by labrys** [comment]
Fails with mako error:

```
Error !

AttributeError: 'module' object has no attribute 'POSTPONE_IF_NO_SUBS'

</label> </div> <div class="field-pair"> <input type="checkbox" name="postpone_if_no_subs" id="postpone_if_no_subs" ${('', 'checked="checked"')[bool(sickbeard.POSTPONE_IF_NO_SUBS)]}/> <label for="postpone_if_no_subs"> <span class="component-title">Postpone if no subtitle</span> <span class="component-desc">Wait to process a file until subtitles are present</span> <span class="component-desc">Language names are allowed in subtitle filename (en.srt, pt-br.srt, ita.srt, etc.)</span> </label>
H:/usr/local/sickrage.new/gui/slick/views/config_postProcessing.mako, line 108:
<input type="checkbox" name="postpone_if_no_subs" id="postpone_if_no_subs" ${('', 'checked="checked"')[bool(sickbeard.POSTPONE_IF_NO_SUBS)]}/>
H:/usr/local/sickrage.new/gui/slick/views/layouts/main.mako, line 276:
H:\usr\local\sickrage.new\lib\mako\runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by medariox** [comment]
^ above error not PR related, solved on irc. Needed to delete mako cache :)

**Comment by labrys** [comment]
yeah dumbass mistake on my part :D

**Comment by fernandog** [comment]
@djoole

**Comment by djoole** [comment]
Niiiice :-)
Thanks @fernandog for linking!

**Comment by medariox** [comment]
I tested this a few days, seems solid. Gonna merge for now.

**Pull request merged**
