### PR TITLE
Update tvdb api to v3  (credits to @BenjV)

### PR DESCRIPTION
**Pull request by Wally73**
update ShowUpdater to use api v3 from the tvdb 
made by @BenjV (i only edited the right api key)

Fixes # https://github.com/SickChill/SickChill/issues/5717

- [x ] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by mmhere — COMMENTED** [review]
This comment https://github.com/SickChill/SickChill/issues/5717#issuecomment-560034168 over in issue #5717 summarizes some issues I found.  They stem from pre-existing behaviour in this file (new thetvdb API V3 client changes here are good) that are revealed by thetvdb currently returning empty update lists with old fromTime= Paramters passed to the V3 API.

**Comment by Wally73** [comment]
updated the pull request with the updated version from @BenjV

**Comment by miigotu** [comment]
I'll try and look this over tomorrow. I have a ton of stuff I need to get done at home first.

**Comment by mmhere** [comment]
As an aside, note that thetvdb began presenting data at the `Updates.php` link again (in XML) so this takes the pressure off.  Their [status page](https://forums.thetvdb.com/viewtopic.php?f=122&t=60239) marks the change as released.  I haven't tested it yet in the context of SickChill, but a simple script [posted in thetvdb forum thread](https://forums.thetvdb.com/viewtopic.php?p=165741#p165741) does show it returning info as opposed to getting an HTTP 403 and no data.

Of course as several have commented, adapting to the new API would still be a good thing.

**Comment by miigotu** [comment]
Now to convert the rest of the tvdb stuff to v3. It's gonna be a PITA

**Comment by miigotu** [comment]
Seems to be some issues here.

**Pull request merged**
