### PR TITLE
check parent dir names in addition to current

### LINKED ISSUE #5318: Postprocessor not skipping directories in the process of being unpacked
Branch/Commit: master/v2019.01.06-1
OS: Ubuntu 18.04
Browser: Chrome

What you did:
Searched for episode and downloaded using sabnzbd.

What happened:
The auto postprocessor picked up the downloaded and beeing unpacked files and processed them befor sabnzbd finished.
Due to this the file is moved to the shows directory before completed and deleted in the download folder.
When SAB is finishing its processing the file actually is geting deleted and therfore gets lost.

What you expected:
The auto postprocessor should skip folders beeing upacked by SAB (Names "_UNPACK_***")
The folder is processed even if debug log actually shows a notice it's detected.

Logs:
```
2019-02-06 13:33:20 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: /Downloads/sabnzbdplus/complete/tv
2019-02-06 13:33:20 DEBUG    POSTPROCESSOR-AUTO :: Processing in folder /Downloads/sabnzbdplus/complete/tv
2019-02-06 13:33:20 INFO     POSTPROCESSOR-AUTO :: Processing /Downloads/sabnzbdplus/complete/tv
2019-02-06 13:33:20 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /Downloads/sabnzbdplus/complete/tv
2019-02-06 13:33:21 DEBUG    POSTPROCESSOR-AUTO :: Using cached parse result for: **MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264
2019-02-06 13:33:21 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1
2019-02-06 13:33:21 DEBUG    POSTPROCESSOR-AUTO :: The directory name indicates that this release is in the process of being unpacked.
2019-02-06 13:33:21 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264
2019-02-06 13:33:21 DEBUG    POSTPROCESSOR-AUTO :: Using cached parse result for: **MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264
2019-02-06 13:33:21 DEBUG    POSTPROCESSOR-AUTO :: Trying to find unpack **MyShow** on theTVDB
2019-02-06 13:33:22 DEBUG    POSTPROCESSOR-AUTO :: Parsed /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264 into UNPACK **MyShow** - S04E11 [GROUP: TVS.1] [ABD: False] [ANIME: False] [whichReg: [u'standard', u'standard']]
2019-02-06 13:33:22 INFO     POSTPROCESSOR-AUTO :: Processing /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264/**MyShow**-dd51-dl-7p-x264-411.mkv (None)

...

2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: Processing succeeded for /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264/**MyShow**-dd51-dl-7p-x264-411.mkv
2019-02-06 13:33:29 DEBUG    POSTPROCESSOR-AUTO :: Found unwanted files: ['**MyShow**-dd51-dl-7p-x264-411.mkv']
2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: Deleting folder: /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264
2019-02-06 13:33:29 WARNING  POSTPROCESSOR-AUTO :: Warning: unable to delete folder: /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264: error 16 : Device or resource busy
2019-02-06 13:33:29 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264
2019-02-06 13:33:29 DEBUG    POSTPROCESSOR-AUTO :: The directory name indicates that this release is in the process of being unpacked.
2019-02-06 13:33:29 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264
2019-02-06 13:33:29 DEBUG    POSTPROCESSOR-AUTO :: /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264 : No processable items found in folder
2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: Some items were not processed.
2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1 : Being unpacked
2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: /Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264 : Being unpacked
2019-02-06 13:33:29 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /Downloads/sabnzbdplus/complete/tv completed
```

I have been coming from an older SickRage Branch to this and there I never had this issue, the directories got skipped as expected.

### PR DESCRIPTION
**Pull request by embii74**
Fixes #5318

Proposed changes in this pull request:
- checking parent dir names in addition to the current dir name to exclude subdirs from being processed
-
-

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by embii74** [comment]
After having the issue for quite some time I tried finding a fix myself (not being an actual dev nor knowing python very well).
Not sure I did everything correct - sorry if not.

**Comment by miigotu** [comment]
Please show me some example dir names and release names and process path. There has to be a better way that wont break when releases inadvertently contain those words.

**Comment by embii74** [comment]
I fixed the syntax errors in my branch.

The checks I added always include the path separator to ensure the Keywords are either at the beginning or the end of the dir names, analogous as its done in the original tests.

I added the same additional tests to "_FAILED" and "_UNDERSIZED" checks as for "_UNPACK" as they would suffer from the same behavior.

The cases I have always look like "_UNPACK <nzbReleaseName>" as I only use SABNZBd.

**Comment by embii74** [comment]
cool, my email wasn't working - it's corrected again.

**Comment by miigotu** [comment]
Please show me some example dir names and release names and process path.

**Comment by embii74** [comment]
example taken from the bug report (no current example as I have to work around the issue): 

the dir **`/Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1`** is correctly detected as in the process of being unpacked.

the subdir **`/Downloads/sabnzbdplus/complete/tv/_UNPACK_**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264.1/**MyShow**.S04E11.**MyEpisode**.DD51.DL.720p.UHD.x264`** is incorrectly processed.

**Comment by JeremiahGillis** [comment]
The folder structure below is from SABnzbd version 2.3.4. It is not up to date. I see no settings in the config to adjust where the unpacking occurs. It currently unpacks to the same place where downloads complete.

In Download Finished folder:
`_UNPACK_**MyShow**.S02.1080p.WEB-DL.DD+.5.1.x264-TrollHD`

Once UNPACK is complete:
`**MyShow**.S02.1080p.WEB-DL.DD+.5.1.x264-TrollHD`

SickChill Build: 54aaf19ff076d5591c60e757135cdaf58d6cc31d

What ends up happening is that SickChill takes the current episodes even if the unpack of a specific episode isn't complete. So you end up getting episodes that aren't complete. SickChill will also delete the full unpacked episode because a partial one already exists.

**Pull request merged**
