### PR TITLE
Add UHD Qualities

### PR DESCRIPTION
**Pull request by labrys**
Test quality changes

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by labrys** [comment]
@SickRage/collaborators @SickRage/moderators 

Please test this... need a wide variety of downloads from different providers and at different qualities to make sure this is solid.

This is not just about adding the UHD qualities, it begins a process of migrating towards a tagging system for handling file qualities.

**Comment by neoatomic** [comment]
I cant checkout (not merged) commits on the Syno, it has to do how Git is installed, and the package is build....

**Comment by miigotu** [comment]
@labrys as soon as I get the providers back into a mergeable state and merge to master, we will make this the first merge into develop and watch it burn if it fails.

**Comment by labrys** [comment]
@miigotu Yeah wasn't planning on merging it until after a master merge.

**Comment by labrys** [comment]
Oh and then the assert should be removed before we merge it to master too.

**Comment by labrys** [comment]
Just a heads up for anyone watching this branch, this is going to require a change to the db to avoid breaking backwards compatibility of the database.

###### Proposed changes to db
- table `db_version`
  - [x] add `db_minor_version`: for tracking minor db changes - increment to 1 
- table `tv_shows`
  - [x] add `default_ep_status_extended`: stores  the new statuses and set `default_ep_status` to `UNKNOWN` if its not one of the old statuses.
- table `tv_episodes`
  - [x] add `status_extended`: same as for `tv_shows`
  - [ ] add `quality` and `quality_extended`: removes the need to split and composite statuses, makes logic for PP easier 
- table `history`
  - [x] add `quality_extended`: same as for `tv_shows`

All these changes should not affect backwards compatibility.

**Comment by labrys** [comment]
This PRs gonna be delayed a bit, updating all the SQL queries will take longer than expected.

**Comment by labrys** [comment]
Before this gets merged to master, or at least shortly after, we need to remove the verification checks on the qualities that validate new qualities with old and get rid of the old quality checks.  Until then we are doing double the checks on each file to verify files are correctly ID'd.

**Comment by labrys** [comment]
@OmgImAlexis Would you mind updating the js to add colors to the new 4k UHD and 8k UHD pills?

**Comment by OmgImAlexis** [comment]
@labrys isn't that part of the mako python stuff? Pretty sure none of that is js.

**Comment by labrys** [comment]
@OmgImAlexis I was under the impression it was done in js.  I guess ill take a look at the mako and see when I get a chance.

**Comment by OmgImAlexis** [comment]
@labrys from memory there's a python function in one of the files that is used as a "helper" class for it.

**Comment by miigotu** [comment]
inc_defs.mako, the colors come from css

**Pull request merged**
