### PR TITLE
moving some elements of DisplayShow to align and tighten the page lay…

### PR DESCRIPTION
**Pull request by wimpyrbx**
Fixes #

Proposed changes in this pull request:
- moved change show a bit up.
- moved element for episode selection a bit up.
- moved element for change episodes a bit up and to the right.
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

…out.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by wimpyrbx** [comment]
oh yeah and also resized and centered the logo as it was not looking all that nice with height:100%

**Comment by miigotu** [comment]
Have to wait for gui changes until the responsive-ui branch is done. #1591

**Comment by beschoenen** [comment]
@wimpyrbx Can this be closed?

**Comment by beschoenen** [comment]
These fixes have been implemented in Responsive 2

**Pull request closed without merging**
