### PR TITLE
Don't recreate tvshow.nfo if indexer id doesn't change

### LINKED ISSUE #4428: tvshow.nfo files being needlessly recreated
Branch/Commit: 4b69468cc
OS: Linux
What you did: Nothing
What happened: tvshow.nfo needlessly re-created
What you expected: if there is no reason to re-create (i.e. no new info), don't recreate
Logs:
```
2018-03-22 04:09:25 INFO     SHOWQUEUE-REFRESH :: Performing refresh on This Is Us
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: 311714: Loading all episodes from the show directory /Videos/This Is Us
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: 311714: Loading all episodes with a location from the database
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/fanart.jpg exists: True
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/poster.jpg exists: True
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/banner.jpg exists: True
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season-specials-poster.jpg exists: False
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for This Is Us
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season01-poster.jpg exists: True
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season02-poster.jpg exists: True
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season banners for This Is Us
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season-specials-banner.jpg exists: False
2018-03-22 04:09:25 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season01-banner.jpg exists: False
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season02-banner.jpg exists: False
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season-all-poster.jpg exists: True
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/season-all-banner.jpg exists: True
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: 311714: Writing NFOs for show
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/tvshow.nfo exists: True
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: 311714: Writing NFOs for all episodes
2018-03-22 04:09:26 INFO     SHOWQUEUE-REFRESH :: 311714: Updating NFOs for show with new indexer info
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if /Videos/This Is Us/tvshow.nfo exists: True
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ updating show indexer info metadata file for This Is Us
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking & filling cache for show This Is Us
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if we need any cache images for show 311714
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /SickRage/cache/images/311714.poster.jpg exists
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /SickRage/cache/images/311714.banner.jpg exists
2018-03-22 04:09:26 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /SickRage/cache/images/thumbnails/311714.poster.jpg exists
2018-03-22 04:09:27 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /SickRage/cache/images/thumbnails/311714.banner.jpg exists
2018-03-22 04:09:27 DEBUG    SHOWQUEUE-REFRESH :: Checking if file /SickRage/cache/images/311714.fanart.jpg exists
2018-03-22 04:09:27 DEBUG    SHOWQUEUE-REFRESH :: No new cache images needed, not retrieving new ones
```

I added some code to back up the tvshow.nfo file before re-creating it and as you can see, the file is the same after it was recreated as it was before:

```bash
# md5sum /Videos/This Is Us/tvshow.nfo*
2eeb6d0b3de4b5c225120dae531797c5  /Videos/This Is Us/tvshow.nfo
2eeb6d0b3de4b5c225120dae531797c5  /Videos/This Is Us/tvshow.nfo.bak
```

So why is `tvshow.nfo` being needlessly recreated?

### PR DESCRIPTION
**Pull request by brianjmurrell**
Fixes #4428 

Proposed changes in this pull request:
- if the indexer id doesn't actually change, don't re-write the `tvshow.nfo` file

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
This code does not do what you think it does, and you cannot use tabs in the code.

Also, tvshow.nfo is not just for the indexer id, you would need to check every bit of information to see if it has changed.  It is much simpler to just write the file, since it is only supposed to be written on a full show update afaik.

**Comment by brianjmurrell** [comment]
Tabs/spaces aside for the moment, of course I realise that `tvshow.nfo` has a lot more information in it than just the _indexer id_.  But in the `update_show_indexer_metadata()` method that I added the check to, the only thing that is being updated in the `tvshow.nfo` is the `<id>` element AFAICS.  Is there something else going on in that method that I am just not seeing?

**Comment by miigotu** [comment]
The thing I am confused on is, whats the point? Its already opening the file for read, so skipping the save wont stop the disk from waking. This method is only called if you add a new show or if you manually force an update/refresh.

**Comment by brianjmurrell** [comment]
> The thing I am confused on is, whats the point?

It's so that the metadata doesn't look like it's been refreshed when actually it hasn't been.

If an application is looking at `.nfo` files and their modification timestamps to determine if it needs to re-import the metadata, unnecessarily updating the `.nfo` file will make such a system unnecessarily re-import and process the metadata.

> Its already opening the file for read, so skipping the save wont stop the disk from waking.

Right.  This is not about saving a disk wake-up.

> This method is only called if you add a new show or if you manually force an update/refresh.

See #4428.

I have this happening at night when neither have I added a new show nor have I (knowingly) forced any update/refresh.  So I too would like to understand more about why this is happening.

**Comment by miigotu** [comment]
In order for it to be automatically written, SOME info has changed on tvdb, and the showUpdater triggers a forced update (and subsequent refresh)
What application would be looking at nfo files' timestamps for updates?

**Comment by brianjmurrell** [comment]
> In order for it to be automatically written, SOME info has changed on tvdb,

Would be interesting if they kept a change history that one can view just to see what is changing.

> and the showUpdater triggers a forced update (and subsequent refresh)

Wouldn't such a change result in something in the `tvshow.nfo` file being different?

> What application would be looking at nfo files' timestamps for updates?

Media presentation/playing apps.

**Comment by miigotu** [comment]
`Wouldn't such a change result in something in the tvshow.nfo file being different?`

It is dependant on which nfo type you are creating. One method just updates the ID and others update the whole file

`Media presentation/playing apps.`
Plex does a listdir if the folder has changed, but thats all

**Comment by brianjmurrell** [comment]
> It is dependant on which nfo type you are creating. One method just updates the ID

Right.  That's the method that I am fixing with this patch.

> and others update the whole file

Certainly, if there is a change in the actual content of the file, then it needs to be written -- I'm not trying to prevent that -- but if the change is a NOOP such that the actual content of file doesn't change, let's not erroneously indicate to consumers of this file that something has changed when it hasn't actually.

Ultimately, it just seems wrong to update the file when there is nothing to actually update.

**Comment by miigotu** [comment]
This is a really trivial thing, but ok. Please test it first now with my changes, because the way it was before `indexerid == show_obj.indexerid` would have always been false, since one was an etree element and the other was an integer.

EDIT: Confirmed:

```python
                    print('indexerid object {obj} has type {typ}, text is {txt} with type {typtxt}'.format(obj=indexerid, typ=type(indexerid),
                                                                                                          txt=indexerid.text, typtxt=type(indexerid.text)))
                    print('Type show_obj.indexerid is {typ} with value {val}'.format(typ=type(show_obj.indexerid), val=show_obj.indexerid))
                    if indexerid.text == str(show_obj.indexerid):
                        print('skipping nfo write')
                        return True
```

Output:
```bash
22:36:45 DEBUG::SHOWQUEUE-REFRESH :: Checking & filling cache for show Game of Silence
indexerid object <Element 'id' at 0x7fc668287c60> has type <type 'Element'>, text is 295641 with type <type 'str'>
Type show_obj.indexerid is <type 'int'> with value 295641
skipping nfo write
```

**Comment by miigotu** [comment]
I did this in my own branch because there was more to add to it.

**Pull request closed without merging**
