### PR TITLE
Add custom season names

### PR DESCRIPTION
**Pull request by beschoenen**
### Use case
This is mostly for anime.
Some anime that air with non-absolute numbering can't be downloaded by SickRage.

I have this problem with the show "New Game."
Season 1 is called 'New Game!', but season 2 is called 'New Game!!' and SickRage parses episodes from New Game!! as Season 1 episodes.

But this problem exists for all non-absolute airing anime with season > 1.

The custom names for the seasons have to manually be entered in `Show -> Edit -> Season exceptions`.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Don't we already have this by editing the [scene exceptions file](https://github.com/SickRage/sickrage.github.io/blob/master/scene_exceptions/scene_exceptions.json)?

**Comment by beschoenen** [comment]
OMG 😫

**Comment by OmgImAlexis** [comment]
Maybe we should add an option to the UI...

**Comment by beschoenen** [comment]
Is the JSON file saved locally? or is it downloaded from GitHub each time?

**Comment by OmgImAlexis** [comment]
I think it's pulled down once every 24 hours from memory.

**Comment by beschoenen** [comment]
So then how do you propose we make a UI for this?

**Comment by p0psicles** [comment]
It's pulled from gh every 24 hours and stored in the db.

**Comment by OmgImAlexis** [comment]
@beschoenen I meant keep the UI you've added but use it to allow users to override the global list locally.

**Comment by beschoenen** [comment]
Is the `cache.db` not emptied at some point? (assuming that's what you mean)

**Comment by p0psicles** [comment]
afaik sr doesn't empty the scene_exceptions table in cache.db.
I would start with at least visualizing the season exceptions that you have. Don't know if this PR already does that though.

**Comment by beschoenen** [comment]
This PR visualizes the data from the new table, but in about the same way as you'd want to display the data from the season exceptions in the `cache.db`, I'd just have to add support for multiple entries per season.

**Comment by p0psicles** [comment]
It's your project. But I wouldn't introduce a new table. As there is already one which can be easily used for custom exceptions. Just have to flag those.

**Comment by beschoenen** [comment]
I already made the new table, and it was a huge waste of time :P

**Comment by p0psicles** [comment]
Or you move everything to the new table?

**Comment by beschoenen** [comment]
@p0psicles Looks like the `scene_exceptions` table *is* emptied. This method is called when you press save in the editShow page.

https://github.com/SickRage/SickRage/blob/master/sickbeard/scene_exceptions.py#L278

**Comment by p0psicles** [comment]
Yes, but that's easily fixable. Just flag the custom exceptions. And only delete the GitHub exceptions. It's deleted to make sure you always have the same as on gh.

**Pull request closed without merging**
