### PR TITLE
Add provider Norbits

### PR DESCRIPTION
**Pull request by eriweb**
Proposed changes in this pull request:
- Adding provider 'Norbits'. Norbits is a tracker providing Norwegian content
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Just one small change here about the _get_*_search_strings overrides. We are trying to eliminate those overrides at all costs.

Can you think of a way to do it without those overrides? The search mode and ep_obj are available inside the search method itself

**Comment by eriweb** [comment]
Sure, let me take a look at it tonight.

Den lørdag 27. februar 2016 skrev miigotu notifications@github.com
følgende:

**Comment by eriweb** [comment]
@miigotu removed the get*_search_strings, and rewrote/cleaned up some more

**Comment by eriweb** [comment]
let me know if you want me to squash the commits or something

**Comment by miigotu** [comment]
Fantastic work.

**Comment by miigotu** [comment]
@terbolous, interested in helping update some of the other providers? btn and hdbits especially if you have access to those.

**Comment by eriweb** [comment]
Sure I can take a look, have access to both. What in particular are you looking for? Just getting rid of get*_search_strings or a rewrite?

**Comment by labrys** [comment]
@terbolous All of the providers are aiming to be designed like abnormal and alpharatio

**Comment by miigotu** [comment]
unicode literals, the "mode" layout without overriding `_get_*_search_strings`, single quotes for strings, etc

There are some that are really obvious I havent had the time to rewrite or even update in a pretty long time. Really just trying to get them all as similar as possible.

**Pull request merged**
