### PR TITLE
Qbittorrent apiv2

### LINKED ISSUE #5747: Sending torrents to qBittorrent 4.2.0 RC fails
It appears the webui API for qbittorrent has changed in version 4.2.0 RC. Haven't seen any documentation of this but can confirm the old command endpoint returns 404 while the v2 api works

Branch/Commit: master/2404f197697602a2bbfa8e6b39207229a94d37bb 
OS: Ubuntu
Browser: Firefox
What you did: Triggered a search for episode to be sent to qbittorrent 4.2.0 RC
What happened: torrent was found from rarbg but fails to be added to qbittorrent 4.2.0 RC
What you expected: torrent to be added to qbittorrent
Logs:
```
2019-12-05 21:37:26 WARNING  SEARCHQUEUE-MANUAL-311954 :: qbittorrent: Unable to send Torrent
2019-12-05 21:37:26 INFO     SEARCHQUEUE-MANUAL-311954 :: Request failed: 404 Client Error: Not Found for url: http://192.168.1.110:8082/command/download ()
2019-12-05 21:37:26 DEBUG    SEARCHQUEUE-MANUAL-311954 :: qbittorrent: Requested a POST connection to url http://192.168.1.110:8082/command/download and data: {u'urls': u'magnet:?xt=urn:btih:536ee09cbb8ce861f71137ddfef429a53bf9bc46&dn=Riverdale.US.S04E08.108...
2019-12-05 21:37:26 DEBUG    SEARCHQUEUE-MANUAL-311954 :: Calling qbittorrent Client
2019-12-05 21:37:26 INFO     SEARCHQUEUE-MANUAL-311954 :: Downloading Riverdale.US.S04E08.1080p.WEB.H264-TBS[rartv] from Rarbg
```

### PR DESCRIPTION
**Pull request by t-chab**
Fixes #5747 

Proposed changes in this pull request:
- Update qBittorrent API to  v2 [because v1 is now deprecated](https://github.com/qbittorrent/qBittorrent/blob/master/Changelog#L76)

### CODE REVIEW

**Comment by miigotu** [comment]
I imagine some people still need to be able to use v1? Should we make these into 2 separate clients?

**Comment by t-chab** [comment]
Thanks, it's a good idea.

**Comment by NinoFloris** [comment]
Thanks so much for fixing this so quickly @tchabaud 

One small nit, the icon sprite alignment (in search settings > torrent search) is missing because stylesheet rule for `add-client-icon-new-qbittorrent` (as opposed to v1 `add-client-icon-qbittorrent`) is not defined.

Switching to v1 gives the css rule block 
```css
.add-client-icon-qbittorrent {
    background-position: -138px 0;
}
```

Changing that to include v2 should do the trick
```css
.add-client-icon-qbittorrent, .add-client-icon-new-qbittorrent {
    background-position: -138px 0;
}
```

**Comment by joshmule** [comment]
When will these fixes be published to the main branch?  Right now sickchill as released doesn't work with qbittorrent.

**Comment by t-chab** [comment]
Can you be more specific ? What doesn't work ? Which version of the api are you using ?

**Comment by joshmule** [comment]
I'm talking about what is described here in this thread.  I'm not reporting a new problem, this is a problem that is thoroughly described and fixed here, but only in the SickChill::develop branch.  

I'm asking when those changes will be pushed to a new release.

**Comment by miigotu** [comment]
@joshmule develop has been pushed to master like 30 times since this change...

**Comment by joshmule** [comment]
Thank you.  I can't tell that from notes... all I see is "merged 5 commits into SickChill:develop" ... nothing about merging these specific updates to the master.

I'm seeing this as of two or three weeks ago when I upgraded qbittorrent from version 4.1.7 to 4.2.1:

2020-02-09 09:11:17 WARNING  SEARCHQUEUE-MANUAL- :: qbittorrent: Unable to send Torrent
2020-02-09 09:11:17 INFO     SEARCHQUEUE-MANUAL- :: Request failed: 404 Client Error: Not Found for url: http://127.0.0.1:8080/command/download ()
2020-02-09 09:11:17 INFO     SEARCHQUEUE-MANUAL- :: Downloading file.name from Rarbg

When I downgrade qbittorrent to 4.1.7 everything works again... which makes me think that this is the WebAPI bug described herein.

**Comment by t-chab** [comment]
@joshmule : you see this because qBitorrent latest version [deprecates](https://github.com/qbittorrent/qBittorrent/blob/master/Changelog#L76) web api v1

You should upgrade sickchill to latest master version, and choose the appropriate qbitorrent web api version you want to use in the settings.

**Comment by joshmule** [comment]
That worked, thank you.  I was missing the fact that there are now two different qbittorrent choices on the menu list.

**Pull request merged**
