### PR TITLE
Fix/bw list default setting

### PR DESCRIPTION
**Pull request by kyuuk**
recent changes caused BW list to behave like in this screenshot
image

Proposed changes in this pull request:
- fix BW list default settings save / load from config.ini

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

## Summary by CodeRabbit

- **New Features**
  - Enhanced the settings to handle default whitelist and blacklist options more effectively.

### CODE REVIEW

**Comment by BKSteve** [comment]
Interesting error kicked by the yarn test .
```
  sickchill/gui/slick/js/core.js:4027:23
  ✖  4027:23  The variable whitelistArray should be named includeArray. A more descriptive name will do too.  unicorn/prevent-abbreviations
  ✖  4028:23  The variable blacklistArray should be named excludeArray. A more descriptive name will do too.  unicorn/prevent-abbreviations
```
 
To add to exclude this? Or change to something like `whitegroupArray`?

**Comment by miigotu** [comment]
This is a social motivated change, to avoid using things like white for good and black for bad, like they also did with master/slave for branch names.

**Comment by miigotu** [comment]
> Interesting error kicked by the yarn test .
> ```
>   sickchill/gui/slick/js/core.js:4027:23
>   ✖  4027:23  The variable whitelistArray should be named includeArray. A more descriptive name will do too.  unicorn/prevent-abbreviations
>   ✖  4028:23  The variable blacklistArray should be named excludeArray. A more descriptive name will do too.  unicorn/prevent-abbreviations
> ```
>  
> To add to exclude this? Or change to something like `whitegroupArray`?

This is a social motivated change, to avoid using things like white for good and black for bad, like they also did with master/slave for branch names.

**Comment by BKSteve** [comment]
So are you suggesting we change this globally including mako pages? So all are Include / exclude?

**Comment by miigotu** [comment]
> So are you suggesting we change this globally including mako pages? So all are Include / exclude?

I'm not so sure, because include and exclude doesn't really fit here, it's more allowed and unallowed. I'm all for changing it, but I don't want it to be even more confusing for users than it already is, especially with changing something that's been there for a decade. So maybe it can be left black/white in mako for now while we make the backend changes and document it well. You can add an ignore for it now and start a separate PR for that

**Comment by BKSteve** [comment]
easier to adjust 2 variables, don't know enough to `allow` or ignore the lint rule.

This now has the `[expected fail] getMeta` from index.js `test.failing('getMeta', t => {`

**Comment by kyuuk** [comment]
a bit late, 
i would have suggested wanted/unwanted groups at least for this params

**Pull request merged**
