### PR TITLE
Add min/max values for check_setting_int/float

### PR DESCRIPTION
**Pull request by sharkykh**
It started out with trying to fix https://github.com/SickRage/SickRage/issues/1373#issuecomment-286937172
But there's so many other variables that need this, so I just added it to the function.

Users shouldn't edit config.ini values on their own, but for when they do,
we should check values are within the specified ranges.

**Note:** _This will **block** currently available workaround to change some settings, like autopostprocessor_frequency, to a value lower than the minimum of 10 minutes._

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
I dont think this fixes the issue, but I dont mind the change

**Comment by sharkykh** [comment]
I think the user changed the value in config.ini... I can't think of a different reason..

**Comment by miigotu** [comment]
@sharkykh you done with this one yet?

**Comment by miigotu** [comment]
@sharkykh cant use min or max as param/variable names. That overshadows the built-in min and max functions, rename them to min_val, max_val or something like that

**Comment by sharkykh** [comment]
Changed the parameters' names.
Yeah, I done. You can merge.

**Pull request merged**
