### PR TITLE
Newpct web restructure

### LINKED ISSUE #4115: Newpct provider changes web structure
Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3

Newpct has changed web structure, and it makes you cannot find anything since yesterday (11-2-17)

2017-11-03 15:50:04 INFO SEARCHQUEUE-MANUAL-328517 :: Unable to find a download for: [The Brave - S01E06 - The Seville Defection]
2017-11-03 15:49:46 INFO SEARCHQUEUE-MANUAL-328517 :: [Newpct] :: Performing e**sode search for The Brave

### PR DESCRIPTION
**Pull request by snamds**
Fixes #4115

Proposed changes in this pull request:
- New web structure

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by Erdk2 — COMMENTED** [review]
Works! 
Saved result to Supergirl.-.Temporada.3.720p.HDTV.x264[Cap.304][AC3.5.1.EspaÃ±ol.Castellano]-NEWPCT.torrent 2017-11-10 12:37:32 INFO SEARCHQUEUE-MANUAL-295759 :: Downloading a result from http://www.newpct.com/descargar-seriehd/supergirl/capitulo-34/hdtv-720p-ac3-5-1/ 2017-11-10 12:37:32 INFO SEARCHQUEUE-MANUAL-295759 :: Downloading Supergirl.-.Temporada.3.720p.HDTV.x264[Cap.304][AC3.5.1.EspaÃ±ol.Castellano]-NEWPCT from Newpct 2017-11-10 12:37:32 INFO SEARCHQUEUE-MANUAL-295759 :: [Newpct] :: Quality of Supergirl.-.Temporada.3.720p.HDTV.x264[Cap.304][AC3.5.1.EspaÃ±ol.Castellano]-NEWPCT is 720p HDT

**Review by Erdk2 — APPROVED** [review]
Working again

**Comment by juanpebalsa** [comment]
It does not work, I tried to download episodes of several series and I can not.

**Comment by snamds** [comment]
Newpct has been messing with url links. It's working again.
Try again and comment

**Comment by Erdk2** [comment]
@juanpebalsa you need to use branch newpct-web-restructure. It works for me since three days; only one problem with a long title, Ley y Orden True Crime El caso Menendez, fix it with scene exception, ley.y.orden.true.crime.el.caso.menendez

**Comment by egrueda** [comment]
Great, this is working. Thanks!

**Comment by juanpebalsa** [comment]
Ok, my problem is that I use the OpenMediaVault SickRage plugin and I can not put the newpct-web-restructure branch, I can only put master or debeloper branch. 
However, I have modified the /opt/sickbeard/sickbeard/sickbeard/providers/newpct.py file and put the snamds code  and I have restarted, but it still does not work.

**Comment by juanpebalsa** [comment]
I've tried the code that you left in this pastebin ([https://pastebin.com/raw/TG5pR77k](url)) in a Kodi forum and now it works perfectly ... even the search manual.

THANK YOU VERY MUCH

**Review by gmiranda — APPROVED** [review]
Backlist search will be way faster since it doesn't rely on the site's search functionality.

Adding the rss feed is a nice touch that also speeds up the daily searches.

**Comment by juanpebalsa** [comment]
Hi @gmiranda, I tried to add the newpct RSS feed as you said, but I get this error:

> "Torrent link is not a valid torrent file: not a valid bencoded string"


I have tried the following feeds:
```
http://feeds2.feedburner.com/newpctorrent
http://feeds.feedburner.com/newpctnew
http://www.newpct.com/feed
```
pantallazo-2017-11-28 09-48-36

**Comment by RmG152** [comment]
Manual updated in my installation, and its working like a charm.

Can this work with newpct1?  maybe it's a good idea include as backup

**Comment by gmiranda** [comment]
I see some trouble in my log:
`

AA AttributeError: 'NoneType' object has no attribute 'group'
AA download_id = re.search(r'http://tumejorserie.com/descargar/.+?(\d{6}).+?\.html', data, re.DOTALL).group(1)
AA File "/home/hefe/SickRage/sickbeard/providers/newpct.py", line 208, in get_url
AA result.content = result.provider.get_url(result.url, returns='content')
AA File "/home/hefe/SickRage/sickbeard/search.py", line 132, in snatchEpisode
AA self.success = search.snatchEpisode(result)
AA File "/home/hefe/SickRage/sickbeard/search_queue.py", line 145, in run
2017-12-19 20:35:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading REDACTED.-SPANISH.AUDIO.-NEWPCT from Newpct
2017-12-19 20:35:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: Quality of REDACTED.-SPANISH.AUDIO.-NEWPCT is 720p HDTV
2017-12-19 20:35:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: Found result REDACTED.-SPANISH.AUDIO.-NEWPCT at REDACTED`

**Comment by gmiranda** [comment]
Fast as a shark. It's now working. If only newpct would stop changing their website so often...

**Comment by egrueda** [comment]
I receive an error message: "Torrent file content is empty"
I've downloaded last upadted file to deal with download link change, and in fact it's looking in the right url, but doesn't seem to find it :-/

[edit] Sorry, it's something related with Vodafone's domain filtering (http://castor.vodafone.es/public/stoppages/stop.htmopt)

**Review by Erdk2 — APPROVED** [review]
Working

**Comment by RmG152** [comment]
6cb5028 Works like a charm

**Comment by snamds** [comment]
For those interested in newpct releases, this code has been moved to jackett.

**Pull request closed without merging**
