### PR TITLE
 	Changes to the Poster View Home Page - Smaller Posters

### PR DESCRIPTION
**Pull request by hernandito**
This is an edit to the Home Page Poster View Screen. The goal is to
create smaller posters, with all the pertinent info from the original
poster view, except you can now see more shows at once.

Changes were made only to the style.css file. I have added a background
texture as well, to make the poster cards visually pop.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Can you please rebase so only your changes are in the PR.

**Comment by hernandito** [comment]
@OmgImAlexis I dont know how to do what you are asking me about rebasing... Sorry I dont have a lot of experience collaborating on Gitub.

**Comment by duramato** [comment]
@hernandito see if this helps http://pastebin.com/bAk5atkk

**Comment by hernandito** [comment]
Tried a new PR. I hope it works. I followed the rebase guide.

**Pull request closed without merging**
