### PR TITLE
Add network logo

### PR DESCRIPTION
**Pull request by aboogerd**
Adding a logo for the AVROTROS network.

Hope I did it the correct way.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
It should only show your commits

**Comment by aboogerd** [comment]
Hmm strange... Can you do something with this pr or do I need to change it?

**Comment by duramato** [comment]
try this

```
Try opening a terminal on the project folder and do
git remote -v it should show 2 origins and 2 upstreams
if it doesnt show the upstream do : git remote add upstream https://github.com/SiCKRAGE/SickRage.git

after that do

git fetch upstream
git rebase -i upstream/develop
and
"leave your first commit as "pick" and the rest set to "fixup" or "squash", do not change anyone elses commits. Save and exit"
Finally do
git push origin yourbranchname -f
```

**Comment by aboogerd** [comment]
Think this should do the trick.

**Comment by duramato** [comment]
Thanks for the PR

**Comment by miigotu** [comment]
@duramato why merge a transparent logo?

**Comment by duramato** [comment]
Trasparent? Its grey
Not the dress color again lol

**Comment by aboogerd** [comment]
Yep not a fancy color this gray one. I just PR a version with a white inner.

**Comment by miigotu** [comment]
white/transparent network icons dont work well with the white SR theme.

**Comment by aboogerd** [comment]
Checked I noticed what you mean. This is the original network logo, but I going to change the color so it will work with the theme.

**Comment by miigotu** [comment]
Thanks.

**Comment by aboogerd** [comment]
I created a nice light-blue version of the logo.

light
dark

**Comment by miigotu** [comment]
much better, thanks

**Pull request merged**
