### PR TITLE
rTorrent update (#5118, #4865, #4793)

### PR DESCRIPTION
**Pull request by defaultsecurity**
**Goals:**
- Fix sending to rTorrent
- Make SickChill compatible with rTorrent 0.9

**Tested and Working:**
- Sending torrents via httprpc url: http://0.0.0.0:80/plugins/httprpc/action.php
- Sending torrents as torrent files
- Telling rTorrent to save torrent in a custom folder
- Telling rTorrent to add custom label to torrent
- Telling rTorrent to start download or not

**Not tested:**
- Sending torrent via scgi
- Authentication: Sending torrents to password protected rTorrent/ruTorrent
- Verify SSL certificates for HTTPS requests
- Sending torrents as magnet links

**Notes:**
- Based on develop branch
- Can be tested: (https://github.com/bolhaskutya/SickChill/tree/5118-rtorrent)
       - Git: https://github.com/bolhaskutya/SickChill.git
       - Branch: 5118-rtorrent

**Related Issues:**
- https://github.com/SickChill/SickChill/issues/5118
- https://github.com/SickChill/SickChill/issues/4865
- https://github.com/SickChill/SickChill/issues/4793

This is my first pull request. For example, I'm not sure what is: "continuous-integration/travis-ci/pr — The Travis CI build failed"

### CODE REVIEW

**Comment by miigotu** [comment]
First and foremost, thanks for your contribution.

Does this break rtorrent for anyone that may be stuck on an earlier version? The rtorrent docker image I use for testing worked with the before this PR, which tells me that the apt repository for some distros do not provide the newer release of rtorrent. If it does break something, we need to support both the old and the new version like we do with other clients.

Also, please remove those comments at the top of every file. It is one thing to credit the author, but keep it to the format we have set.
We do not need permission to share code, but we do have to give credit to the author. We don't put links to competing forks in our PR's
These comments are what is breaking the build, because `# coding=utf-8` has to be the first line on the files.

**Comment by defaultsecurity** [comment]
@miigotu 
Unfortunately, I can't test it with earlier versions, I could barely get a single ruTorrent release (docker, linuxserver, release 173) working on my synology, sadly.

I changed the header of the files to include the standard SickChill header, but I think we need to credit the Medusa team properly as a whole and include a link to their repo as requested by @medariox here: https://github.com/pymedusa/Medusa/pull/3333#issuecomment-443129582

SickChill isn't my code, Medusa isn't my code. I just want to fix this issue and give credit where it is due. Both teams have done an awesome job, I'm just glad to be here :) Please advise.

**Comment by miigotu** [comment]
@bolhaskutya the lib folder is supposed to stay as it comes from upstream. If the only place this modified librtorrent comes from is medusa, we need to break that out into a separate repo. The licenses in the lib folder stay as how they came from the source.

Putting a link to medusa is unacceptable, and seeing as we have shared code before both ways they know this.

**Comment by WebSpider** [comment]
Also, this breaks my current rutorrent/rtorrent production install, so it's at least not always backwards compatible.

**Comment by defaultsecurity** [comment]
@miigotu This is just sad. Create a new repo? Not credit Medusa with a few links in a few files? I can't fix the rTorrent bug with such conditions. I came here with the best intentions. I thought this repo was about the users, not the authors. Sorry, but I will take no part in this. I'm switching to Medusa. Best wishes fixing the rTorrent bug.

@WebSpider Thanks for the input. I believe the backwards compatibility can be fixed with version checking. The method names are different in the old and new rTorrent, thus two sets of method definitions would be needed.

**Comment by miigotu** [comment]
@bolhaskutya crediting the author is one thing. Linking to a competing fork is something totally different. medariox knows this, as we have shared code back and forth between forks before. In fact, he didnt even write the whole file, they just modified the one that we already had.

**Comment by miigotu** [comment]
And yes, when you modify a library that isnt part of the source code, you contribute back to the upstream librtorrent.

**Comment by defaultsecurity** [comment]
I understand. I guess you have a history. It would be a pity to leave this bug unfixed. Do as you see fit.

**Pull request closed without merging**
