### PR TITLE
Rewrite `libtrakt` to use `requests-oauthlib`

### LINKED ISSUE #1363: Trakt integration and PIN-code authentication not working anymore
I got warnings in Sick Rage about Trakt. I tested Trakt and it failed.
As a test, I wanted to reconnect Sick Rage with Trakt, so I revoked Sick Rage's access to my Trakt account. I wanted to reconnect, but I can't reconnect anymore, as per an API update on their side, the PIN-code authentication method is now deprecated. The page https://trakt.tv/pin for example isn't available anymore. Please update Sick Rage to use latest authentication methods. :)

See also their API docs:
http://docs.trakt.apiary.io/#reference/authentication-pin

### PR DESCRIPTION
**Pull request by sharkykh**
(My previous PR #3941 was completely broken after the DMCA stuff)

- Rewrite the TraktAPI class to use the requests-oauthlib package.
- Stop using deprecated PIN authentication and move to Device authentication. 
- Move the module out of the lib folder and into `sickrage.custom.libtrakt`

Closes #1363

### CODE REVIEW

**Comment by sharkykh** [comment]
@p0psicles why did you close this?

**Comment by p0psicles** [comment]
Ow sorry. Accidentally I think. I only checked it out Afaik.

**Comment by p0psicles** [comment]
You may remove my rights.

**Comment by sharkykh** [comment]
> Ow sorry. Accidentally I think. I only checked it out Afaik.

@p0psicles yeah it seemed like it. no worries. had to rebase it anyway :p

**Comment by miigotu** [comment]
@sharkykh can you fix conflicts please

**Comment by sharkykh** [comment]
@miigotu 
I already left the organization so I can't push, but this is the code, rebased onto develop (bba14cd6).
[rewrite-libtrakt-rebased-onto-develop-bba14cd6.zip](https://github.com/SickRage/SickRage/files/1267074/rewrite-libtrakt-rebased-onto-develop-bba14cd6.zip)

**Comment by miigotu** [comment]
@sharkykh why did you leave?

**Comment by sharkykh** [comment]
@miigotu 
I simply lost interest

**Comment by miigotu** [comment]
@sharkykh that's ok, I have lost some interest too, but you are welcome to remain on the team, if nothing more than as an honorary title for the contributions you have made. Just being a member of the team does not mean you are obligated to contribute further. I/we appreciate the help you have given here either way, but I would like to keep you on the team.  As a side note, I'll be looking for someone to help maintain this further, because I don't have much time. Before I knew you left I was going to offer you shared owner rights lol, because I respect your judgement and your work.  I will see about one of the other tenured team members maybe filling that role.

**Comment by h3llrais3r** [comment]
@miigotu  Please ignore my request for review... clicked on the wrong place... :man_facepalming: 

EDIT: any news on who will be helping for maintaining this further?

**Comment by miigotu** [comment]
No idea yet, I've been a bit busy

**Pull request closed without merging**
