### PR TITLE
Custom show images and name

### PR DESCRIPTION
**Pull request by miigotu**
Replaces #6650 
(same pr, I just couldnt push to your repo ;))

### From #6650 
Proposed changes in this pull request:
- New tab added to Edit Show view, "Customize"
  - Custom name: Allow to set a custom name for the show, to be used on display show, show list, episode name, etc. #5730 
  - Poster/Banner/Fanart image selector: You are able to select an image from any indexer supported by SickChill (currently only TheTVDB) and from Fanart.tv. Also you can upload it from computer. #5943 (is not really a refresh, but it allows to select the image as is also requested)

img0
img_1
img2

### CODE REVIEW

**Comment by miigotu** [comment]
@Nyaran you agree with my changes?
Also, the tvdb one is not working for me, we would have to download them all locally and display them and I think that's crazy.
image

EDIT: My adblocker blocking it? why.

**Comment by Nyaran** [comment]
I see it was merged after your changes, cool =)

About the adblock... I have it disabled for local network :(

Looking for info, I found this: https://stackoverflow.com/questions/36908023/why-does-adblock-block-my-images

Looks like, as the url contains the word "banner", the image is blocked. I will try to think for a solution, meanwhile... we can add a warning text about it.

**Comment by miigotu** [comment]
I figured we can PR any needed changes xD

**Comment by miigotu** [comment]
I think we might be able to proxy the request through the web server using a redirect

```
def wrap_url(self):
    url = self.get_query_argument('url')
    return self.redirect(url)

In mako:
/wrap_url?url=https://the-tvdb-image
```

**Comment by miigotu** [comment]
I'll add that in a bit =P

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/5728849ada8888888767df547002e009a89f3296

**Comment by miigotu** [comment]
@Nyaran can you fix this? 
image

Also, is it possible to move the dropdown into the dialog header so it doesn't scroll with the images? Or pin it to the top?

**Comment by Nyaran** [comment]
> @Nyaran can you fix this?
> image

That is happening also on drive browser, as is the same dialog box, but sure, I can check it
 
> Also, is it possible to move the dropdown into the dialog header so it doesn't scroll with the images? Or pin it to the top?

I will try to pin to the top

**Comment by Nyaran** [comment]
I think I got the problem, on `main.mako` I see this import
```html
        <link rel="stylesheet" type="text/css" href="${static_url('css/lib/jquery-ui-1.10.4.custom.min.css')}" />
```

look the version, it sais "1.10.4", but the jquery-ui version on bower is "~1.12.1", and some changes was made on the dialog classes.

I'm not really sure how to use the css from the bower package, but as a hotfix, I can add the needed CSS to hide the text on all dialogs (drive browser and image selector)

**Comment by miigotu** [comment]
I really really really want to get rid of bower and use webpack instead, but all my attempts fail lol

**Pull request merged**
