### PR TITLE
Adding T411.si as a torrent provider

### LINKED ISSUE #4021: Add t411.si as provider
The team that has done t411 is back in business, with a new domain. For what I found, it has a lot of content and is working very nice since severals weeks!

Should we add this provider back to sickrage?

The domain is https://t411.si/

### PR DESCRIPTION
**Pull request by jaytonic**
Fixes #4021 

Proposed changes in this pull request:
- Adding T411.SI as provider

It's my first contribution to SickRage, so if I did something wrong, please let me know and I will do my best to make it right.

I based my code on another tracker that also doesn't require any auth(cpasbien).

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jaytonic** [comment]
Is there somebody that could validate this pull request?

**Comment by Sylanorr** [comment]
+1 ... Please validate this pull request :)

Thanks

**Comment by miigotu** [comment]
https://travis-ci.org/SickRage/SickRage/builds/279807201#L562-L565

**Comment by jaytonic** [comment]
@miigotu It's not clear for me what is not working, could you maybe just point me in the right direction? I did my best but without documentation it's not very clear for me. 

Because this test seems to be ignored for other providers
"Test is programmatically disabled for provider LimeTorrents"

**Comment by miigotu** [comment]
The link I commented shows you, that your order of imports is out of order. follow the + and - in that link.

**Review by alemaitour — APPROVED** [review]

**Comment by lejudoka13** [comment]
nice let's grab this to devellop branch @miigotu

**Review by Jean-Mercier — APPROVED** [review]

**Review by lejudoka13 — APPROVED** [review]
Ok for me i tested it

**Comment by Asfalt-FR** [comment]
Bonjour je suis demandeur pour T411.si et yggtorent, y a t'il du nouveau ?

**Comment by jaytonic** [comment]
@adaur why did you close my pull request? Close it if it get merged or rejected...

**Comment by adaur** [comment]
T411.si is dead and has been merged with yggtorrent

**Comment by Sylanorr** [comment]
T411.si doesn’t exist anymore. Yggtorrent and T411  merged together.

**Comment by jgrossrieder** [comment]
@adaur Didn't see this. Ok then, has your PR been merged? Is SickRage dead too?

**Comment by adaur** [comment]
YggTorrent has been merged in dev but not in master. I am currently working on some providers there: https://github.com/pymedusa/Medusa/issues/3197

**Comment by jgrossrieder** [comment]
@adaur what is pymedusa? Should we move to it?

**Comment by adaur** [comment]
It's a fork of SR. You're free to try it.

**Comment by miigotu** [comment]
Don't promote here, Thanks.

**Pull request closed without merging**
