### PR TITLE
Bugfix/multiple notifications

### PR DESCRIPTION
**Pull request by OldskoolOrion**
Fixes #

Proposed changes in this pull request:
- bugfix of the update notification - "There is a newer version available (you're (you're 7 commits behind) behind)".

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by sharkykh** [comment]
1. This is not what the 'bugfix/multiple-notifications' branch is for
2. This is just a replica of #3693 
3. I opened a new PR that fixes the issue you described #3784

**Comment by OldskoolOrion** [comment]
I got confused.. pretty new to the git thingy and i def. didnt wanna break anything important.. so I went with you since you were active :-)  Sorry for that.. just wanted to pass it on, since it basically was just correcting a small non-urgent, non-critical typo :-)

**Comment by sharkykh** [comment]
I don't mean to be rude, but next time, if you're not sure, you can just open an issue about it instead.

**Comment by OldskoolOrion** [comment]
sure, but I wouldn't have learned nothing :-) but don't worry.. I won't
make you click again :-)

**Pull request closed without merging**
