### PR TITLE
Fixes issue #4546

### LINKED ISSUE #4546: [APP SUBMITTED]: 'list' object has no attribute 'lower'
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [9783c5f] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 259, in download_subtitles
    hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/providers/opensubtitles.py", line 81, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/subtitle.py", line 241, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

### PR DESCRIPTION
**Pull request by jackkiej**
Fixes #4546

Thanks to fishmongr:

[https://github.com/Diaoul/subliminal/pull/800](https://github.com/Diaoul/subliminal/pull/800)

### CODE REVIEW

**Comment by miigotu** [comment]
This cannot be added here until it is accepted in subliminal. Our libs are vanilla

**Comment by jackkiej** [comment]
Then please ask them to fix it.
It is an annoying bug which is easily fixed..

**Comment by miigotu** [comment]
or just make the PR there.

**Comment by jackkiej** [comment]
PR is already there for months, I just took the PR and added it here.

**Pull request closed without merging**
