### PR TITLE
Fix interface for qbittorrent client

### PR DESCRIPTION
**Pull request by lulandco**
Hide torrent path
Show anime's label and warning

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
can you squash commits?

**Comment by duramato** [comment]
little cheat sheet 

```
Try opening a terminal on the project folder and do
git remote -v it should show 2 origins and 2 upstreams
if it doesnt show the upstream do : git remote add upstream https://github.com/SiCKRAGE/SickRage.git

after that do

git fetch upstream
git rebase -i upstream/develop
and
"leave your first commit as "pick" and the rest set to "fixup" or "squash", do not change anyone elses commits. Save and exit"
Finally do
git push origin yourbranchname -f
```

**Comment by lulandco** [comment]
@duramato
Thank you because I have great difficulty with git and I have not found yet a tutorial for dummies ;)

**Comment by miigotu** [comment]
And why cant you send the torrent path (download location) to qBittorent?

**Comment by lulandco** [comment]
@miigotu 
Because API has never provided it. It came from my previous commit where a wrong line was deleted.

**Pull request merged**
