### PR TITLE
Added tnt usa network logo

### PR DESCRIPTION
**Pull request by neoatomic**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by 03397** [comment]
Any news on this request?

**Comment by miigotu** [comment]
It was merged into master 11 days ago

**Comment by 03397** [comment]
I am up to date.  What I need to in order for the show to get the icon?
On Jul 22, 2016 05:55, miigotu notifications@github.com wrote:its been in master for 11 days...

**Comment by 03397** [comment]
I have added a new show from tnt us network but still I got a ? in the place of the icon.

**Comment by miigotu** [comment]
its missing from https://github.com/SickRage/sickrage.github.io/blob/master/sb_network_timezones/network_timezones.txt

**Comment by 03397** [comment]
Is it supposed to be there? You are going to include it in the next commit?

**Comment by miigotu** [comment]
Need the exact text from it, case matters, as well as punctuation.

**Comment by 03397** [comment]
Does this help?

**Comment by neoatomic** [comment]
@03397 For what show.?
Need to know the exact network name if the icon is still missing.

**Comment by 03397** [comment]
I have attached a picture but it did not go through. The show is The Last Ship

**Comment by neoatomic** [comment]
@03397 The naming was wrong, it was `TNT (US)`.
I made a PR for the logo, as soon as @miigotu does merge it to master, it should work. : 

https://github.com/SickRage/SickRage/pull/2130

**Pull request merged**
