### PR TITLE
Update config_notifications.mako

### PR DESCRIPTION
**Pull request by fredleger**
Added a stupid precision on telegram notifications

Fixes #

Proposed changes in this pull request:
-
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
wtf is N.B.? lol

**Comment by fredleger** [comment]
Nota Bene

**Comment by miigotu** [comment]
Our default strings are in english, other languages go into the translations

**Comment by fredleger** [comment]
Nota Bene is kind of Latin locution  used in english also : http://www.wordreference.com/definition/nota%20bene <http://www.wordreference.com/definition/nota%20bene>

Means, "Note Well » but we can change it to « Hint » if you want

**Comment by miigotu** [comment]
Yeah, such a latin reference would normally only be used in something very formal like laws or dissertations, etc.  Just use "Note:" or "Hint:"

**Pull request merged**
