### PR TITLE
Fix get_needed_languages and new_subs calculation in subtitltes.py

### PR DESCRIPTION
**Pull request by miigotu**
Refactor a bit to use less for loops and branches
Replaces #494

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@miigotu got this just now in my log

No error, no warnings.

```
2015-12-17 14:32:22 DEBUG    FINDSUBTITLES :: Subtitle search for Da Vinci's Demons S03E10 delayed for 2 hours, 37 minutes
AA             with args [735949, '%pob%']
AA            AND e.location != '' ORDER BY age ASC
AA            WHERE s.subtitles = 1 AND e.subtitles NOT LIKE ?
AA            ON (e.showid = s.indexer_id)
AA            FROM tv_episodes AS e INNER JOIN tv_shows AS s
AA            e.subtitles_lastsearch AS lastsearch, e.location, (? - e.airdate) as age
AA            e.status, e.subtitles, e.subtitles_searchcount AS searchcount,
AA            SELECT s.show_name, e.showid, e.season, e.episode,
2015-12-17 14:32:22 INFO     FINDSUBTITLES :: Checking for missed subtitles
```

**Comment by miigotu** [comment]
And you assume that has something to do with this PR why?

**Comment by fernandog** [comment]
Only happened after the update.
Will git checkout  old commit to confirm

**Pull request merged**
