### PR TITLE
Fix and enhance content of email notification

### PR DESCRIPTION
**Pull request by CoRpO**
Proposed changes in this pull request:
- Display correct show name, episode number and quality where available.
- Fix footer html code

### CODE REVIEW

**Comment by miigotu** [comment]
What happens when show name or episode name includes a `-` ?

**Comment by CoRpO** [comment]
@miigotu well, it will fail to cut correctly the datas, as with the actual code. Still better than to get an array in the email in place of the show's name. To get the correct datas implies to change the whole notification chain (which is doable btw). But it seems to involve a lot of code change

**Comment by miigotu** [comment]
Actually `_parse_ep` needs to use the `re.search('.+ - (.+?-.+) -.+', ep_name)` to properly split it. This regex was added about a year ago for shows with `-` in the name. Of course that regex would need adjusted to be a full replacement but its the best way

**Comment by CoRpO** [comment]
Better rework the notification chain than to try to create the perfect fit-all-cases regex :/
Correct datas are available. Problem is that I cannot check every notification type.

I'll have a look at both cases (the .sort() in the actual _parseEp is so ugly ...)

**Pull request merged**
