### PR TITLE
Pytest 8.2.0 errors

### PR DESCRIPTION
**Pull request by BKSteve**
Per https://github.com/pytest-dev/pytest/issues/12263

Work around to avoid `AttributeError: property 'is_active' of 'Provider' object has no setter`
in test_snatch.

Plus ignore the `Warning` about `telnetlib` whilst looking why the build system was erroring

### CODE REVIEW

**Comment by BKSteve** [comment]
Seriously anybody still got a Popcorn Hour 200 series? It's like a 2011 media player.

Should just deprecate this one.

**Comment by twinden** [comment]
@BKSteve Yelp !
Hi Steve !
I can’t find where to report an issue with SickChill on this all new GitHub.
I installed the new SC package yesterday, and it won’t become running on my Synology Evansport DS214play on DSM 6.2.

Can you register a new issue for this and mention me there ?!
Can you please look into this ?

I’ll delete this here when read. Sorry for posting here, I just can’t find “new issue” anywhere.

**Comment by miigotu** [comment]
Instead of blocking pytest8.2.0, why not add the setter?

Under
```python
@attribute
def is_active(self): ...
```
Add something like
```python
@is_active.setter
def is_active(self, value):
    self.active = value
```

**Comment by BKSteve** [comment]
added to Develop via `guess2` merge. 
Closed

**Comment by miigotu** [comment]
> Instead of blocking pytest8.2.0, why not add the setter?
> 
> Under
> 
> ```python
> @attribute
> def is_active(self): ...
> ```
> 
> Add something like
> 
> ```python
> @is_active.setter
> def is_active(self, value):
>     self.active = value
> ```

I still want this fix, we don't want to block pytest 8.2.0, we want to fix the error (can't setattr to properties that don't have setters in testing, which is a good thing)

**Pull request closed without merging**
