### PR TITLE
Remove redundant 'Failed Download Handling' setting in PP config

### PR DESCRIPTION
**Pull request by medariox**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@medariox it's on purpose

user who don't use PP can enabled failed downloads
also user who use PP can enabled failed downloads

**Comment by medariox** [comment]
@fernandog 
Why?

**Comment by fernandog** [comment]
ok!

**Comment by duramato** [comment]
We should make failed downloads enabled by default ,doesnt make sense it beeing disabled.

**Comment by fernandog** [comment]
lol! we were discussing that in IRC

maybe disable option. should be always on - imo

**Pull request merged**
