### PR TITLE
Fix SickRage/sickrage-issues/issues/621

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SickRage/sickrage-issues/issues/621

@OmgImAlexis  Can you try please?

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
I'm not 100% sure why I got that error before but that should be fine since the only reason it would be failing was the capital K and this will fix it.

**Comment by miigotu** [comment]
@fernandog can you make it re.I instead of the long version?

**Comment by fernandog** [comment]
@miigotu done

**Pull request merged**
