### PR TITLE
Fixes issue #90

### PR DESCRIPTION
**Pull request by labrys**
This fixes sickrage/sickrage-issues#90.  Api was only showing show results if paused=1.

### CODE REVIEW

**Comment by tresni** [comment]
This is still broken, now it will never return paused shows :)  Additionally, it's an optional parameter and according to Sickbeard: `if not set then both paused and non paused are shown`

50ee052c599160 has the right code... It was "fixed" in a4374681c87477ece402e889 and it's been broken ever since...

This should reverted to the old code to get the right behavior.

**Comment by tresni** [comment]
@labrys not sure you saw the previous comment, but want to make sure you do.  There is currently no way to get paused shows at all.  You will always get _only_ unpaused shows.

**Comment by tresni** [comment]
So to be explicit (and based on the documentation of the [Sickbeard API](http://sickbeard.com/api/):
- `paused=1` should show _only_ paused shows
- `paused=0` should show _only_ unpaused shows
- If `paused` is not defined/present, then it should show _both_ paused and unpaused shows.

**Comment by labrys** [comment]
No I must have missed the previous comment.  I'll take a look at this right now.

**Pull request merged**
