### PR TITLE
Satreix feat nose

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by satreix** [comment]
:+1: Thanks for the fixes.

Does this mean we are moving towards `nose` for the future of testing SickRage?

**Comment by labrys** [comment]
@satreix yes, barring any issues with it.

**Comment by miigotu** [comment]
Yes, I rather use nose. I didnt realize you had it so close. I did have to add back the coverage though.

**Pull request merged**
