### PR TITLE
Removed unneeded sudo from .travis.yml

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
You actually want to keep that in, unless you _need_ root rights in the build. `sudo: false` there actually _disables_ `sudo` in the build, enabling you to build on the container infrastructure which starts about 10x faster than the regular builds: http://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

**Comment by MGaetan89** [comment]
@Arcanemagus :+1:

**Comment by Arcanemagus** [comment]
Although looking over the docs it looks like they have updated them to say this is now the default, so you are right that this isn't strictly necessary.

**Comment by OmgImAlexis** [comment]
@Arcanemagus if you check there's actually `sudo: false` already in there. There was a duplicate so I removed it :stuck_out_tongue:

**Comment by Arcanemagus** [comment]
Ha! That was hidden in the diff, carry on!

**Pull request merged**
