### PR TITLE
Update to match theTVDB network name Yomiuri TV

### PR DESCRIPTION
**Pull request by a10kiloham**
Fixes #
## 
## 
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

Remove JP to match theTVDB naming convention

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
You need to edit it here: https://github.com/SickRage/sickrage.github.io/blob/master/sb_network_timezones/network_timezones.txt
Also, dont change an existing one, add a new one

**Comment by a10kiloham** [comment]
There is only one show listed on the tvdb w this network and it's the way I
changed it to.

**Comment by a10kiloham** [comment]
Can you explain this directory structure? Last change I made to tz file
wasn't in this tree.

**Comment by miigotu** [comment]
The one in SR repo is just a fallback incase github is down. tz are updated from the other repo when SR starts, when searches are run, and when show updates are ran.

**Pull request closed without merging**
