### PR TITLE
Lime torrent BeautifulSoup call

### LINKED ISSUE #8076: [APP SUBMITTED]: __init__() got an unexpected keyword argument 'language'
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
No Log available with ERRORS:
### ERROR
```
Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\sickchill\\oldbeard\\providers\\limetorrents.py", line 55, in search\n    data = BeautifulSoup(data, language="xml")\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\__init__.py", line 254, in __init__\n    builder = builder_class(**kwargs)\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\builder\\_lxml.py", line 128, in __init__\n    super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

### PR DESCRIPTION
**Pull request by BKSteve**
Fixes #8076 

BeautifulSoup call updated, surprised this hasn't come up before??

### CODE REVIEW

**Comment by miigotu** [comment]
It should be language= though. What's the error you are seeing?

**Comment by BKSteve** [comment]
Everywhere else `BeautifulSoup4` is used there is no `language=` in the second parameter it's just the parameter.
"xml" or "html" 

> TypeError: __init__() got an unexpected keyword argument \'language\'

**Comment by miigotu** [comment]
If you are getting that TypeError there is an issue with which code is loading in your package.

https://github.com/SickChill/SickChill/blob/master/sickchill/oldbeard/bs4_parser.py#L8

**Comment by miigotu** [comment]
And if it's passing html or xml in the parser position rather than language anywhere that is broken on those.

**Comment by BKSteve** [comment]
Aren't they different?
One is `from subliminal.providers import ParserBeautifulSoup` using `ParserBeautifulSoup` in `BS4Parser`

Whereas the other is `from bs4 import BeautifulSoup` `data = BeautifulSoup(data, "xml")`

```
ERROR :: SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n File "/home/stephenr/PycharmProjects/SickChill/sickchill/oldbeard/providers/limetorrents.py", line 55, in search\n data = BeautifulSoup(data, language="xml")\n File "/home/stephenr/PycharmProjects/SickChill/.venv/lib/python3.10/site-packages/bs4/__init__.py", line 257, in __init__\n builder = builder_class(**kwargs)\n File "/home/stephenr/PycharmProjects/SickChill/.venv/lib/python3.10/site-packages/bs4/builder/_lxml.py", line 139, in __init__\n super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: TreeBuilder.__init__() got an unexpected keyword argument \'language\'\n'
```

**Comment by miigotu** [comment]
Aha. Limetorrents provider is using beautifulsoup directly. That should be reworked to use the context manager in bs4_parser, because I have that trying to use lxml or other parsers if they are present (they are faster) and falling back to pure python if they aren't installed. This is to reduce the number of c compiled dependencies.

**Comment by miigotu** [comment]
Please test this out

**Pull request merged**
