### PR TITLE
Make failed downloads enable by default

### PR DESCRIPTION
**Pull request by fernandog**
as we talked in the other PR
@medariox @duramato 

maybe we should consider remove this option and make it default behavior

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
@fernandog some of us really don't like having that enabled. When I added my original collection to SickRage it then attempted to downloaded 1,200+ episodes. Over 80% of them failed since I use put.io and I can't add that many at once. 

I don't see a reason to remove the option unless it's not being used and/or causing a LOT of issues.

**Comment by fernandog** [comment]
@OmgImAlexis 
hum. failed downloads only runs if you **manually** SET as failed or using **outside scripts** that set as failed like nzbtomedia

so how that happened for you?

**Comment by duramato** [comment]
Tbh when FDH will be 100% on SR this option will have to be enabled ,tjis is just a step in that direction. Furthermore on making a manual search you can chose to not mark as failed, most popular PPing scripts allow to not have FD afaik..

**Comment by miigotu** [comment]
Except FDH handling doesnt work completely yet.

**Comment by fernandog** [comment]
how come failed downloads doesn't work completely?

**Pull request closed without merging**
