### PR TITLE
Revert most consecutive `if`s fixes

### LINKED ISSUE #3463: Post processing fails to create hardlink
This just started happening after a recent update, it is failing to create a hardlink during post processing, tried with several different shows/files, all fail with same error:

"Failed to create hardlink. Error: 'module' object has no attribute 'link'. Copying instead"

(The file doesn't get copied either, I end up with a 0KB file in the source and the destination folder)

Branch/Commit: master / 949e0acc613e8cc14c7555a3f154f031a94a9768
OS: Windows 10 x64
What you did: Manual or automatic post processing 
What happened: Post processing fails to create hardlink
What you expected: Post processing creates hardlink
Logs:
```
2017-03-21 20:06:02 WARNING POSTPROCESSOR-MANUAL :: Failed to create hardlink of D:\new\stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket.mkv at D:\Sick\The Late Show with Stephen Colbert\The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes.mkv. Error: 'module' object has no attribute 'link'. Copying instead
2017-03-21 20:06:02 DEBUG POSTPROCESSOR-MANUAL :: Hard linking file from D:\new\stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket.mkv to D:\Sick\The Late Show with Stephen Colbert\The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes.mkv
2017-03-21 20:06:02 DEBUG POSTPROCESSOR-MANUAL :: Checking if the path D:\Sick\The Late Show with Stephen Colbert already exists
2017-03-21 20:06:02 DEBUG POSTPROCESSOR-MANUAL :: Destination folder for this episode: D:\Sick\The Late Show with Stephen Colbert
2017-03-21 20:06:02 DEBUG POSTPROCESSOR-MANUAL :: formatting pattern: %SN - S%0SE%0E - %EN -> The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes
2017-03-21 20:06:01 DEBUG POSTPROCESSOR-MANUAL :: Found codec for 'The Late Show with Stephen Colbert: Bryan Cranston, Audra McDonald, Greer Barnes'.
2017-03-21 20:06:01 DEBUG POSTPROCESSOR-MANUAL :: Using cached parse result for: stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket
2017-03-21 20:06:01 DEBUG POSTPROCESSOR-MANUAL :: Parsed D:\Sick\The Late Show with Stephen Colbert\The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes into The Late Show with Stephen Colbert - S02E116 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-21 20:06:01 DEBUG POSTPROCESSOR-MANUAL :: Folder name (new) appears to be a valid release name. Using it.
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Found release name stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket
2017-03-21 20:06:00 INFO POSTPROCESSOR-MANUAL :: Trying to clean any empty folders under D:\Sick\The Late Show with Stephen Colbert
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: No associated files for D:\Sick\The Late Show with Stephen Colbert\The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes.mkv were found during this pass
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Trying to determine free space on destination drive
2017-03-21 20:06:00 INFO POSTPROCESSOR-MANUAL :: This download is marked a priority download so I'm going to replace an existing file if I find one
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: File D:\Sick\The Late Show with Stephen Colbert\The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes.mkv doesn't exist so there's no worries about replacing it
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Is ep a priority download: True
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: This was manually downloaded but it appears to be better quality than what we have so I'm marking it as priority
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Quality of the episode we're processing: 720p HDTV
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Snatch history had a quality in it, using that: 720p HDTV
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Setter sets location to D:\Sick\The Late Show with Stephen Colbert\The Late Show with Stephen Colbert - S02E116 - Bryan Cranston, Audra McDonald, Greer Barnes.mkv
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Retrieving episode object for 2x116
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Looks like this is an air-by-date or sports show, attempting to convert the date to season/episode
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Parsed stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket into stephen colbert - S02E1162017-03-20 [GROUP: brisket] [ABD: True] [ANIME: False] [whichReg: [u'scene_date_format']]
2017-03-21 20:06:00 DEBUG POSTPROCESSOR-MANUAL :: Analyzing name stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket.mkv
2017-03-21 20:06:00 INFO POSTPROCESSOR-MANUAL :: Processing D:\new\stephen.colbert.2017.03.20.bryan.cranston.720p.hdtv.x264-brisket.mkv (None)
```

### LINKED ISSUE #3464: Invalid air-by-date naming config, not saving your air-by-date settings
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
master/949e0acc613e8cc14c7555a3f154f031a94a9768

OS:
Linux-3.10.102-x86_64-with-glibc2.2.5 (Synology DSM 6.1)

What you did:
Attempted to save post-processing configuration.

What happened:
Warning as shown in logs is given.

What you expected:
No errors or warnings. There are no custom naming-scheme configured for "Air-By-Date" or "Sports", for which the warnings are given.
Enabling "Custom Air-By-Date" and "Custom Sports" and then making sure it's set to one of the pre-configured options still gives the warnings.

Logs:
```
2017-03-22 01:07:42 Thread-17 :: You tried saving an invalid air-by-date naming config, not saving your air-by-date settings
2017-03-22 01:07:42 Thread-17 :: You tried saving an invalid sports naming config, not saving your sports settings
2017-03-22 01:00:33 Thread-15 :: You tried saving an invalid air-by-date naming config, not saving your air-by-date settings
2017-03-22 01:00:33 Thread-15 :: You tried saving an invalid sports naming config, not saving your sports settings
2017-03-22 01:00:17 Thread-17 :: You tried saving an invalid air-by-date naming config, not saving your air-by-date settings
2017-03-22 01:00:17 Thread-17 :: You tried saving an invalid sports naming config, not saving your sports settings
2017-03-22 00:59:47 Thread-14 :: You tried saving an invalid air-by-date naming config, not saving your air-by-date settings
2017-03-22 00:59:47 Thread-14 :: You tried saving an invalid sports naming config, not saving your sports settings
```

### PR DESCRIPTION
**Pull request by sharkykh**
Looks like #3451 broke some stuff 😞 see [my next comment](https://github.com/SickRage/SickRage/pull/3467#issuecomment-288335203)

This fixes #3464 - broken naming validity checker
and fixes #3463 - broken hard-linking on Windows, which for some weird reason was deleted from GitHub as soon as I changed its labels 😕 
But anyway I could confirm it was happening because of this my changes so I reverted them...

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by sharkykh** [comment]
### I just reverted most of my changes because I realized the big mistake I've made.
I went over all my changes again to check which of the would cause the same issues as above.
Some were okay, most weren't.

The ones that I deemed as okay were set up like this:
```python
# before:
if sickbeard.TRAKT_SYNC_WATCHLIST:
    if sickbeard.TRAKT_REMOVE_SERIESLIST:
        trakt_api.traktRequest("sync/watchlist/remove", data, method='POST')

# after:
if sickbeard.TRAKT_SYNC_WATCHLIST and sickbeard.TRAKT_REMOVE_SERIESLIST:
    trakt_api.traktRequest("sync/watchlist/remove", data, method='POST')
```
When the first `if` has no `else`\`elif` then it won't cause an issue...
```python
# before:
if result.resultType == 'torrent':
    if sickbeard.TORRENT_PATH:
        data['destination'] = sickbeard.TORRENT_PATH
elif sickbeard.SYNOLOGY_DSM_PATH:
    data['destination'] = sickbeard.SYNOLOGY_DSM_PATH

# after:
if result.resultType == 'torrent' and sickbeard.TORRENT_PATH:
    data['destination'] = sickbeard.TORRENT_PATH
elif sickbeard.SYNOLOGY_DSM_PATH:
    data['destination'] = sickbeard.SYNOLOGY_DSM_PATH
```

I wish I had realized that before changing everything according to QC's suggestion. 
Speaking of, either QC's Anti-Patterns are incorrectly detecting this as an issue,
or there is another way to write these `if`'s that I don't know about.

**Comment by miigotu** [comment]
AAARG...
```bash
Running "exec:git_get_last_tag" (exec) task

Running "exec:git_list_changes" (exec) task

Running "_get_next_tag" task

Running "exec:git_tag_new" (exec) task
>> /bin/sh: 1: Syntax error: end of file unexpected
>> Exited with code: 2.
>> Error executing child process: Error: Process exited with code 2.
Warning: Task "exec:git_tag_new" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by sharkykh** [comment]
Maybe making a bash script and calling it using grunt would've worked better.

**Comment by miigotu** [comment]
I have one, it just doesnt do tagging
```bash
#!/bin/bash -
# Copy to SR dir, ./genchanges.sh > path/to/sickrage.github.io/sickrage-news/CHANGES.md

REGEX="^v20[12][0-9]\.[0-9][0-9].[0-9][0-9]-[0-9]+"
REFS=`git tag --sort=-refname`
for i in $REFS; do
  if [[ ! $i =~ $REGEX ]]; then
    BS=$(git push origin :refs/tags/$i)
    BS=$(git tag -d $i)
    BS=
    continue
  fi
  echo '###' $i
  echo ''
  prev=$(git log $i^ | head -n1 | sed 's/\(commit \| (.*$\)//g')
  echo '[full changelog](https://github.com/SickRage/SickRage/compare/'$prev'...'$i')'
  echo ''
  git cat-file tag $i | tail -n+6 | sed 's/^/* /g' | sed '/-----BEGIN PGP SIGNATURE-----/,+9 d'
  echo ''
done
```

**Comment by sharkykh** [comment]
Yeah I know, I used it to build the grunt tasks...
I was just thinking, would it have worked better if I implemented more of the process into the bash script then called it using grunt

**Comment by miigotu** [comment]
I like the grunt task besing self-contained, the kinks just need to be worked out =P

**Pull request merged**
