### PR TITLE
TVDB API v2

### PR DESCRIPTION
**Pull request by sharkykh**
WIP to replace TVDB API v1 with TVDB API v2
If anyone else wants to give it a shot.

**Official API reference:** https://api.thetvdb.com/swagger
**Uploaded the generated docs to:** [/lib/tvdb_api_v2/docs](https://github.com/SickRage/SickRage/tree/38c7728af3c449742ee824d8d4a08d3e7468064d/lib/tvdb_api_v2/docs)

**Note:** The Swagger API client uses urllib. It needs to be using `requests`, or `requests.packages.urllib3`

### CODE REVIEW

**Comment by sharkykh** [comment]
Official sunset date for TVDB API v1: **October 1st, 2017**
https://forums.thetvdb.com/viewtopic.php?f=3&t=36557

**Review by stfrbrntyu — APPROVED** [review]

**Comment by thezoggy** [comment]
or you could just update the tvdb api module from the original source from dbr... https://github.com/dbr/tvdb_api

**Comment by sharkykh** [comment]
@thezoggy The **vendored** tvdb_api module [is heavily modified](https://github.com/SickRage/SickRage/commits/4706c47a88ec74c296fe749d2bceadcacca04c0f/lib/tvdb_api), so I'm guessing it's not as simple as just updating.
Plus, he hasn't released a new version official just yet.

**Comment by p0psicles** [comment]
You can also take a look at  own swagger client.
https://github.com/./tvdbv2

Your free to use it.
It has some nice features, like it's requests based and supports lazy token authentication.

**Comment by thezoggy** [comment]
~@p0psicles the new tvdb_api version from dbr also uses requests and is python 3.x compatible (if you guys were ever thinking of going that route)~

never heard of swagger, looks neat

**Comment by p0psicles** [comment]
Im not a fan of that lib. Also these changes have been made recently, while the lib where using has proven it self for more then 6 months. Also making sure . lib supports python 2 and 3 would not be much work if required. But I know that currently not a priority for sickrage or ..

**Pull request closed without merging**
