### PR TITLE
Add number of seeders/leecher to existing log message

### PR DESCRIPTION
**Pull request by fernandog**
helps debug the seed/leechers. compare with torrent client

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
The providers that dont have seeders/leechers dont need it like btdigg ,but there are others

**Comment by fernandog** [comment]
@duramato done

**Comment by duramato** [comment]
Ok seems all good now. This will help alot when ppl complain SR doesnt download ep, and doesnt add any aditional log lines :p

**Comment by fernandog** [comment]
will help us find possible parsing errors about seed/leechers too
Don't know if is worth to add size too to log

**Comment by medariox** [comment]
I think this is a good idea and agree with the comments above.
Approved

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/791/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Pull request merged**
