### PR TITLE
Implemented changes needed to rate-limit / throttle requests made to …

### PR DESCRIPTION
**Pull request by loonielongbottom**
As suggested in irc by miigotu this is to rate limit / throttle newznab requests based on cpu_presets

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
:+1:

**Comment by labrys** [comment]
@loonielongbottom This needs to be rebased to update instead of clicking the update button.  It creates an unecessary merge commit

**Comment by loonielongbottom** [comment]
@labrys anything I need to do from my end at this point, sorry it's my first time using github.

**Comment by labrys** [comment]
@loonielongbottom read https://github.com/SickRage/SickRage/blob/master/contributing.md and the included link to rebasing.

**Comment by loonielongbottom** [comment]
@labrys I think that did it, I am using sourcetree for git on windows.
You live you learn :)
Please let me know if this was done right, I will fix it.

**Comment by labrys** [comment]
@loonielongbottom Personally I prefer git-extensions.  But you can tell it's not done correctly yet because you should only see your own commit and it should contain only the files you changed.

**Comment by loonielongbottom** [comment]
Yeah now I see that Merge branch commit, okay ill just make another branch and try again with another pull request done properly.

**Comment by labrys** [comment]
@loonielongbottom You don't need to do that.. just rebase this one then force push

**Comment by labrys** [comment]
@loonielongbottom if you can't figure it out join us in irc and we'll see if we can get you pointed in the right direction

**Pull request merged**
