### PR TITLE
replaced banner.png

### PR DESCRIPTION
**Pull request by shnabz**
Fixes #

Proposed changes in this pull request:
- Updated banner to better quality. Original image was stretched and generally awful. Uploaded a hi res version of the shark mascot and text.
- [✓] PR is based on the DEVELOP branch
- [✓] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [✓] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by MGaetan89** [comment]
Nice!
I would suggest to also update [poster.png](https://github.com/SickRage/SickRage/blob/master/gui/slick/images/poster.png), [sickrage.png](https://github.com/SickRage/SickRage/blob/master/gui/slick/images/sickrage.png) and [sickrage-shark-mascot.png](https://github.com/SickRage/SickRage/blob/master/gui/slick/images/sickrage-shark-mascot.png). They could also use better quality.

**Comment by shnabz** [comment]
Yes I was going to change them also, but I do not have the original blue background wallpaper. Do you think it would be ok to change it to a new wallpaper that is similar? @MGaetan89

**Comment by MGaetan89** [comment]
Considering the improvement, I don't mind if the background is not exactly the same.
Maybe those who are more invested in the project have other opinion?

**Comment by miigotu** [comment]
As long as it fits with the theme well idc about changing the background.

**Pull request merged**
