### PR TITLE
Update french fansub 2

### PR DESCRIPTION
**Pull request by FireBladeNooT**
Fixes #
## 
## 
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

My debug report show that "anime_french_fansub" does not find properly the show in this sentence:
2016-04-24 08:33:20 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NyaaVostfr] :: Unable to match [Kaerizaki-Fansub]_One_Piece_737_[VOSTFR][HD_1280x720].mp4 to a show in your database

So I propose a new version that I've tested on https://regex101.com/ which should works.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by FireBladeNooT** [comment]
Hello,
Just about tests fails, some of them can't be OK as the field "release_group" is at the start of sentence and not at the end as expected by test.
So, could it be merge even with tests fails?

Here https://regex101.com/r/xQ0fX2/7 we can find the result of the parser.

Thanks

**Comment by FireBladeNooT** [comment]
Hello @miigotu,
could you help me? I don't know how to do to progress this update.

Thanks

**Comment by miigotu** [comment]
The regex you are changing breaks name detection for `No season multi-ep`
https://travis-ci.org/SickRage/SickRage/builds/142846175

**Pull request closed without merging**
