### PR TITLE
Use HTTPS for project URLs

### PR DESCRIPTION
**Pull request by cjthornton**
Proposed changes in this pull request:
- Updates all `http://` URLs to be `https://` where the URL now uses HTTPS by default.  All URL changes have been manually tested to ensure working.
- This improves security and speed of accessing the URLs
- Updates several URLs to their new hostname (eg sourceforge.io), which is where the old URL now redirects to

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
This needs to be done in small PRs, where it can be checked it doesn't break anything easily.

**Comment by cj-thornton** [comment]
@miigotu Where would you like the PR splitted up?  By file, file types, backend/frontend?  Thanks

**Comment by WebSpider** [comment]
At the very least providers, notifications and frontend need to be seperate

**Comment by miigotu** [comment]
@cj-thornton yes

**Pull request closed without merging**
