### PR TITLE
change kat.cr to kickass.cd

### PR DESCRIPTION
**Pull request by yoyos**
Replace all kat.cr to kickass.cd

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
There's no real kickasstorrents site right now so this is just a fake mirror.

**Comment by yoyos** [comment]
I tought it wasn't a mirror actually. but ok !

**Comment by linakis** [comment]
could be a fake but the content is pretty much real... not seing why this cannot be merged!

**Pull request closed without merging**
