### PR TITLE
Leechtime

### PR DESCRIPTION
**Pull request by BKSteve**
Add minimum poll time to torrent leech

### CODE REVIEW

**Comment by miigotu** [comment]
The default cache time is 10 minutes: https://github.com/SickChill/sickchill/blob/master/sickchill/oldbeard/tvcache.py#L177

We arent spamming TL, searches are being re-done (cache is being broken) because of the bdecode error they caused with bad cloudfare config and a lack of an api.

Maybe set theirs to 30 minutes. I don't care if their provider is slow if they are talking trash about us rather than communicating with us. They don't want our users then we don't need to help their torrents stay seeded.

**Comment by godofjesters** [comment]
instead of hardcoding a timeout, could a variable be set by the user to help randomize the timing and calm down the spamming? set minimum to 10 minutes and gof rom there

**Comment by BKSteve** [comment]
There's already a user setting this is a backup so it uses the cache results. Ipt and td already have this setting I just duplicated it for tl

**Comment by miigotu** [comment]
> There's already a user setting this is a backup so it uses the cache results. Ipt and td already have this setting I just duplicated it for tl

You didnt change anything though, the default value is 10 minutes (min_time is 10 if it isnt passed in, for ALL providers. The class defines the default value.) We use caching for every provider, and also respect etags and do not re-request a provider before the min_time AND the etags expire for the same search.

Really its most likely pirate admins who know little about how their backend works and probably dont even know what etags are lol

**Comment by miigotu** [comment]
> instead of hardcoding a timeout, could a variable be set by the user to help randomize the timing and calm down the spamming? set minimum to 10 minutes and gof rom there

Just going to start setting it really high for unfriendly providers. Their reputation and traffic will falter when they punish an entire class of users over a handful of excessive users that run multiple instances of SC and thousands of shows. I'm not fond of people who do that myself.

**Comment by BKSteve** [comment]
Especially when the added hits come from their messing up the coding of files to have `\n` at the back of them.

**Pull request merged**
