### PR TITLE
Add join notifier

### PR DESCRIPTION
**Pull request by duramato**
@joaomgcd looks good?, also could you perhaps add a way to get the device id more easly?
 like a button or similiar
Also if someone could do the core.min.js i would appreciate

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by joaomgcd** [comment]
Thank you for the Join integration! :+1:

**Comment by miigotu** [comment]
Approved

@duramato why did you use urllib instead of requests here? I'll merge it as-is but that should change sometime.

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/1588/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Comment by duramato** [comment]
Tbh i dont remeber lol

**Pull request merged**
