### PR TITLE
An attempt to fix postprocess issues

### PR DESCRIPTION
**Pull request by sharkykh**
It's an attempt to fix:
- #3231 
- #3230 
- #3220 
- #3216 
- #3052 
- #3235

I tested it with:
- Normal downloaded folder that contained extra files and extra folder within it.
- RAR file in downloads directory.
- RAR file in downloads directory and it's extracted directory (like if it was extracted already)

But still needs much more tests.
@HPMSGEN8 @briped @devenashani @BKSteve @papampi @crowaust @udochrist
Please test this fix.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by HPMSGEN8** [comment]
@sharkykh since i am using Docker how do i change this to Devlop Branch

**Comment by sharkykh** [comment]
Should be as easy as setting your Github username and password in SickRage General Config under Advanced Settings, saving then refreshing.
You should be able to switch in the same config section between master and develop branches. Select develop and click on Checkout Branch.
[As you can see here.](https://cloud.githubusercontent.com/assets/10238474/23356949/6d90c5a4-fce4-11e6-9470-9a48edfe8a22.jpg)

**But this fix still isn't on develop.**

**Comment by HPMSGEN8** [comment]
@sharkykh Thanks that worked will test this today and get back to you.

**Comment by sharkykh** [comment]
@HPMSGEN8 I'll say again, my fix _**will be**_ on the develop **when it merges**.
But, remain on develop so when you update SickRage you'll be able to help with the fix for this.

After everything will be merged to master you can go back to master (the same way)

**Comment by sharkykh** [comment]
@miigotu Could we merge the PR / commits to a new branch on this repo?
So people can checkout this fix and test it?

**Comment by miigotu** [comment]
Merged into implement-tests branch with a few more fixes, to be merged into develop soon.

**Pull request closed without merging**
