### PR TITLE
Update "Help & Info" section

### PR DESCRIPTION
**Pull request by MGaetan89**
A small update to the "Help & Info" section that I wanted to do for a while now.
- Add SickRage's version if it is available
- Add links to the current branch/commit/version
- Remove all "SR" prefixes and rename the page "SickRage configuration"

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Maybe add the origin url?

**Comment by MGaetan89** [comment]
What do you mean by that?

**Comment by miigotu** [comment]
`Origin: https://github.com/SickRage/SickRage.git`

**Comment by MGaetan89** [comment]
But there is already this line https://github.com/SickRage/SickRage/pull/617/files#diff-c5cac42d4cf259b18d6688748e82ce76R85
Wouldn't that be redundant?

**Comment by miigotu** [comment]
Yeah I guess so, lol.

**Comment by huush** [comment]
Awesome.

**Pull request merged**
