### PR TITLE
Group french team fansub

### PR DESCRIPTION
**Pull request by FireBladeNooT**
I've tested all examples with regular expression website. They works but i'm not sure about `.*` to ignore end of file characters.

I remove `anime_Kaerizaki-Fansub` and `anime_ISLAND` because they work with this regular expression (as well as they works before).

An improvement can be done for `[Z-Team][DBSuper.pw] Dragon Ball Super - 028 (VOSTFR)(720p AAC)(MP4)` because extra_info take `720p AAC` and it should be better with only `720p` I guess (Quality will be unknown?).

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by labrys** [comment]
@FireBladeNooT This needs to be rebased on the current develop branch.  See [SickRage\contributing.md](https://github.com/SickRage/SickRage/blob/master/contributing.md) for details

**Comment by FireBladeNooT** [comment]
It is, the part I've removed is wanted.

**Comment by medariox** [comment]
@FireBladeNooT You need to squash the commits.

**Comment by FireBladeNooT** [comment]
How I did this?

**Comment by medariox** [comment]
@FireBladeNooT 
Try this: https://davidwalsh.name/squash-commits-git

**Comment by FireBladeNooT** [comment]
ok thanks,
but I'm sorry it's first time I'm commit modifications and I'm not sure about what you want I do.
The only things I want to do it's to only propose one modification on a file, not to do integration of it.
And the file I take is the last revision.

**Comment by medariox** [comment]
@FireBladeNooT 
I made a new PR for you here: https://github.com/SickRage/SickRage/pull/901

**Comment by FireBladeNooT** [comment]
Thank you ;)

**Pull request closed without merging**
