### PR TITLE
Fix for accents on elitetorrent

### PR DESCRIPTION
**Pull request by macaju**
Fix for accents on titles but not in a very proper way.

**I didn't do a good pull request since I did it from a master clone. The only file I changed was elitetorrent.py**

**Proposed changes in this pull request:**
- Fix for accents on titles on this provider reencoding the string.

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
The data is supposed to already be unicode. There is no way you will be allowed to encode data to latin1 to suit your (likely windows) install and screw everyone else. It must stay unicode and search with unicode.

**Comment by macaju** [comment]
Weird, since I use xbian on a raspberry pi 3... and I installed as:
sudo git clone https://github.com/SiCKRAGE/SickRage.git /opt/sickrage

**Comment by miigotu** [comment]
Everything in SR is unicode, response.text is unicode. If you force encode it to latin1 string then everyone with utf-8 locale will have unicode_decode exceptions popping up. Doing that doesnt help anyone.

**Comment by macaju** [comment]
I understand what you mean and I'm not trying to tell you "accept my proposition" even more since I don't know a lot about how sickrage is built. I just found that this helped me and I wanted to share it.

What I mean with my last comment was that I'm not using windows, I didn't, as far as I know, do anything that could give me a hint about why I have this problem. I realised that if I look for "una serie de catastróficas desdichas" I get as title "una serie de catrastrÃ³ficas desdichas" from this provider.

If you have an idea of how could I fix this or what could be the problem I'll be very grateful for that. If not, thank you anyway and I'll keep this change on my own installation since I didn't find any other way to make it work. 

Thanks.

**Comment by miigotu** [comment]
With your change you wont get that result at all, since it will throw an exception and just skip the result altogether.

```python
>>> l = u"una serie de catastróficas desdichas"
>>> l.encode('utf-8')
'una serie de catastr\xc3\xb3ficas desdichas'
>>> print l.encode('utf-8')
una serie de catastróficas desdichas
>>> print l.encode('utf-8').decode('latin-1')
una serie de catastrÃ³ficas desdichas
>>> print l.decode('utf-8').encode('latin-1')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dusted/Envs/sickrage/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 20: ordinal not in range(128)
>>> print l.decode('utf-8')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dusted/Envs/sickrage/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 20: ordinal not in range(128)
```

**Comment by macaju** [comment]
What `row.find('a', class_='nombre')['title']` give me is the text I put on l :
```python
>>> l = "una serie de catrastrÃ³ficas desdichas"
>>> l.decode('utf-8').encode('latin-1')
'una serie de catrastr\xc3\xb3ficas desdichas'
>>> print l.decode('utf-8').encode('latin-1')
una serie de catrastróficas desdichas
```

I got it putting logs. I wrote `decode('utf-8').encode('latin-1')` after testing several combinations looking at logs.

Edit:
Without that, I get that it doesn't match at `parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)` on GenericProvider.py 

Do you think that could be something wrong at my system?

**Comment by miigotu** [comment]
The text is unicode, not bytes.
`l = u"una serie de catrastrÃ³ficas desdichas"`

**Comment by miigotu** [comment]
The correct way would be to do this (your encode/decode is in the wrong order, so it ends up being bytes instead of unicode as it is supposed to be):
```python
title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))
```
See:
```python
>>> l = u"una serie de catrastrÃ³ficas desdichas"
>>> l
u'una serie de catrastr\xc3\xb3ficas desdichas'
>>> print l
una serie de catrastrÃ³ficas desdichas
type(l.encode('latin-1'))
<type 'str'>
>>> print l.encode('latin-1').decode('utf-8')
una serie de catrastróficas desdichas
>>> type(l.encode('latin-1').decode('utf-8'))
<type 'unicode'>
>>> print l.decode('utf-8').encode('latin-1')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dusted/Envs/narrative/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)

```

**Comment by macaju** [comment]
I see what you say, it's because of that that I don't understand what's going on exactly and I call this a trick.

Here my log (renamed to txt because github doesn't let me attach .log files).

the code I changed from the original:
```python
rowTitle = row.find('a', class_='nombre')['title']
logger.log(u"TESTING: rowTitle as is - rowTitle: {0}".format(rowTitle), logger.INFO)
title = self._processTitle(rowTitle.decode('utf8').encode('latin1'))
logger.log(u"TESTING: rowTitle tricked - rowTitle: {0}".format(rowTitle.decode('utf8').encode('latin1')), logger.INFO)
```

As you can see I get the torrent with the trick, I can upload a log without the trick showing that there is nothing to download.

Any idea?

[sickrage.log.txt](https://github.com/SickRage/SickRage/files/785304/sickrage.log.txt)

**Comment by miigotu** [comment]
Try it with this:
```python
title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))
```

If that works, change your pr to that and I will merge it, since this way it remains unicode.

**Comment by macaju** [comment]
Didn't work :(

Here my log (renamed to 2.txt)

The code:

````python
rowTitle = row.find('a', class_='nombre')['title']
logger.log(u"TESTING: rowTitle as is: {0}".format(rowTitle), logger.INFO)
#title = self._processTitle(rowTitle.decode('utf8').encode('latin1'))
title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))
logger.log(u"TESTING: rowTitle tricked: {0}".format(rowTitle.encode('latin-1').decode('utf8')), logger.INFO)
````
It seems that it crash at `title = self._processTitle(rowTitle.rowTitle.encode('latin-1').decode('utf8'))` since the next log doesn't appear on the log.

[sickrage.log2.txt](https://github.com/SickRage/SickRage/files/785323/sickrage.log2.txt)

Edited: I put a wrong code here, I corrected it and I'm going to check if I used the good code.

**Comment by miigotu** [comment]
Then you can try changing this line:
```python
data = self.get_url(self.urls['search'], params=search_params, returns='text')
```
to:
```python
data = self.get_url(self.urls['search'], params=search_params, returns='content').decode('latin-1')
```
and the process title to:
```python
title = self._processTitle(rowTitle)
```

**Comment by miigotu** [comment]
This is really a problem with the elitetorrent site, because they have text in latin-1 but on their page source they have `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`

**Comment by macaju** [comment]
That's the first thing I checked, that they used charset=utf-8. If you open with a brower the web page source, you see everything in utf8 as expected, at least on google chrome.

I thought do that you are suggesting at the beggining but i didn't try finally because I don't know python and SR own classes so I decided to change a little part. 

I'm goint to try you change and I let you know. Thanks.

**Comment by macaju** [comment]
With the las changes:

```python
data = self.get_url(self.urls['search'], params=search_params, returns='content').decode('latin-1')
```
```python
rowTitle = row.find('a', class_='nombre')['title']
logger.log(u"TESTING: rowTitle as is: {0}".format(rowTitle), logger.INFO)
#title = self._processTitle(rowTitle.decode('utf8').encode('latin1'))
#title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))
title = self._processTitle(rowTitle)
#logger.log(u"TESTING: rowTitle tricked: {0}".format(rowTitle.encode('latin-1').decode('utf8')), logger.INFO)
#logger.log(u"TESTING: rowTitle tricked: {0}".format(rowTitle.decode('utf8').encode('latin1'), logger.INFO)
```
The log:
[sickrage.log4.txt](https://github.com/SickRage/SickRage/files/785362/sickrage.log4.txt)

With the code (the test that I didn't do well before):
```python
data = self.get_url(self.urls['search'], params=search_params, returns='text')
```
```python
rowTitle = row.find('a', class_='nombre')['title']
logger.log(u"TESTING: rowTitle as is: {0}".format(rowTitle), logger.INFO)
#title = self._processTitle(rowTitle.decode('utf8').encode('latin1'))
title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))
#title = self._processTitle(rowTitle)
logger.log(u"TESTING: rowTitle tricked: {0}".format(rowTitle.encode('latin-1').decode('utf8')), logger.INFO)
#logger.log(u"TESTING: rowTitle tricked: {0}".format(rowTitle.decode('utf8').encode('latin1'), logger.INFO)
```
Seems to work.

**Comment by miigotu** [comment]
`With the code (the test that I didn't do well before):` Huh?

**Comment by macaju** [comment]
When you suggested me to write `title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))` i didn't tested well.

Either I write `title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))` or `title = self._processTitle(rowTitle.decode('utf8').encode('latin1'))` it works

**Comment by miigotu** [comment]
Like I said, make it `title = self._processTitle(rowTitle.encode('latin-1').decode('utf8'))` and I will allow the PR.  The order is very important.

```python
>>> rowTitle = 'Random'
>>> type(rowTitle.decode('utf8').encode('latin1'))
<type 'str'>
>>> type(rowTitle.encode('latin-1').decode('utf8'))
<type 'unicode'>
```

**Comment by macaju** [comment]
Done at #3176 

Thank you very much for your help!

**Pull request closed without merging**
