### PR TITLE
fix footer date issue

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by fernandog** [comment]
it will show GMT value?

**Comment by OmgImAlexis** [comment]
@fernandog should do

**Comment by fernandog** [comment]
thanks

**Comment by labrys** [comment]
And it breaks on windows.... just kidding :stuck_out_tongue:

**Comment by OmgImAlexis** [comment]
@labrys we really need a windows ci

**Comment by Amadeus-** [comment]
It shows the same time as it did prior to this commit; however, now it formats it based upon your setting in general -> Interface -> "Date Style" and "Time Style".

**Pull request merged**
