### PR TITLE
Use certifi to enforce usage of the correct ca-certificates

### PR DESCRIPTION
**Pull request by vdweegen**
Fixes #

Proposed changes in this pull request:
- Use certifi to enforce the usage of correct ca-certicates bundles.
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
Wouldn't it be better to do this in the app-wide urllib opener?

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/blob/23ad7189c5c3b310c041f087a7059f47e0cbdd9d/sickchill/oldbeard/helpers.py#L53

**Comment by miigotu** [comment]
Let me know if my change makes this PR unnecessary. Re-open if needed.

**Comment by vdweegen** [comment]
The change in 4ebd016 makes this PR unnecessary, great work.

**Pull request closed without merging**
