### PR TITLE
Enabled ItaSa Subtitle Provider, fixed format detection

### LINKED ISSUE #1608: Italian Subs Addicted Sub provider disappeared
Sorry to reopen it but I did as you said, post an issue on subliminal repo and they told me to get back to SickRage...

Here the original Issue on SickRage

https://github.com/SickRage/SickRage/issues/1602

And here the thread on Subliminal

https://github.com/Diaoul/subliminal/issues/649

Thanks again.

### PR DESCRIPTION
**Pull request by Elettronik**
Fixes #1608, #1457

Proposed changes in this pull request:
- Enabled itasa subtitle provider
- Fixed the case subliminal cannot get file metadata like resolution and format, using SR metadata.
- [x] PR is based on the DEVELOP branch
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
This is not allowed, we use a vanilla subliminal so you need to get it merged there.

**Comment by Elettronik** [comment]
Sorry to bother, but it's a week I have submitted a PR to Subliminal but in a week I had no feedback from Diaoul. Looking in code of SR seems that subliminal is not capable to detect the  format if the filename doesn't contain the metadata like 'hdtv', 'webdl', etc or the file resolution if is not a movie file. 
So part of this pull request is to 'fix'  or better complete the video object passed to subliminal find the correct subtitle. 
Do you want a separate PR for the changes on SR?

**Comment by miigotu** [comment]
The changes to subtitles.py seem plausible.  PR to subliminal take longer to get in, like most projects. not everyone can swallow in nearly every PR like SR does =P.

Tainting a library is bad juju

**Comment by Elettronik** [comment]
I know is bad to tamper some library, but since is same code that hopefully will be included in upstream, I'd thought it could be included in SR.
ItaSa is the only provider option for Italian people, since other are slow or don't have the many formats that itaSa got.
Another point is that, actually the only software that is integrating and benefiting from itaSa, so enabling it, could be the best way to find potential, problems and solving them, since the developer rarely could manage all corner cases.

**Pull request closed without merging**
