### PR TITLE
add fonts to bower

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This fixes the issues added by https://github.com/SickRage/SickRage/pull/711

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
@miigotu can you try and clean up this PR, no clue why it won't merge.

**Comment by miigotu** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/713/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Comment by OmgImAlexis** [comment]
@miigotu any idea why my commit from before was added to this PR? I thought I merged that already.

**Comment by miigotu** [comment]
Trying out a new approval system, so we maybe can merge sickrage-issues back to this repo, and be able to stop merges when we are trying to get to a releasable base.

**Comment by OmgImAlexis** [comment]
Yeah I saw that, sounds good. Merge?

**Comment by miigotu** [comment]
sure, thats what the "Approve" is for xD

**Comment by OmgImAlexis** [comment]
The other commit is from https://github.com/SickRage/SickRage/pull/712

That's why I was asking if I should merge or try and fix it.

**Comment by miigotu** [comment]
Does this also fix the colors in the file browser?

**Comment by OmgImAlexis** [comment]
It "may" not sure though. Still need to play around with more of the CSS.

**Comment by miigotu** [comment]
well, fixing the fonts is a big step so I say go ahead and merge it

**Comment by OmgImAlexis** [comment]
I might try and get the CSS converted to SASS so we can remove a lot of the hassle with it.

**Comment by fernandog** [comment]
@OmgImAlexis 
fonts are wrong again. The only thing had need to be done is remove font family from jquery.
why not use SR font for everything?! Each part has a diff font.

Before:
image

After:
image

**Comment by OmgImAlexis** [comment]
"why not use SR font for everything", what are you talking about?

Also they're all using the same font?

**Comment by fernandog** [comment]
checkout a very old commit from SR and compare with now.
you will see the difference.
I give up trying to explain, sorry.

**Comment by OmgImAlexis** [comment]
They're all using Open Sans, there's only one font on SickRage.

**Comment by fernandog** [comment]
Dont you see any diff in my screenshots?

**Comment by huush** [comment]
The fonts appear to be the same. Only the size is different been your
screen shots.

**Comment by OmgImAlexis** [comment]
@fernandog it just looks like one is missing the bold fonts.

**Comment by duramato** [comment]
That isnt best page to compare ,but on that page where you can the diference the best is on the logs config

**Pull request merged**
