### PR TITLE
DisplayShow background

### PR DESCRIPTION
**Pull request by wimpyrbx**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

some changes in CSS files (dark.css & style.css).
set opacity to 0.8 on summary and displayShowTable.display_show classes
only did changes to dark skin now. once we land on something i can do the same changes to the light.css file.

one new file backstretch.js in js/
this is the one called backstretch.min.js from the source of that project.

5 line block added in DisplayShow.mako to load backstretch.js and set background to fanart.
if no background exists for a show in cache folder the background will be like before.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
Can we see a screenshot before and after? It may be an idea to add an option to turn this off as some people may not want it.

**Comment by wimpyrbx** [comment]
miigotu added this branch so that we can work on it seperately from develop.
i'm also in favor of being able to turn it on/off in the interface config.

here is an image showing before/after.
http://www.fshare.it/image.jpeg?i=1n1460878jy

**Comment by miigotu** [comment]
@OmgImAlexis that was the reason I made this branch, so I could add the code for enable/disable it for him =P

**Pull request merged**
