### PR TITLE
Changes to Poster View - Light Theme

### PR DESCRIPTION
**Pull request by hernandito**
Misc changes to modify various views. These include:

Home Page - Poster view. Smaller icons and more packed interface to show
more shows at once.

Calendar - More compact.

Show Info Page. smaller size fonts and more compact view to see more
info at once.

### CODE REVIEW

**Comment by miigotu** [comment]
@hernandito You need to make your PR against the develop branch.

I will close this one, but can you make the PR to develop branch so we can review it?

Also, adding the screenshots to the PR of all the changes would be helpful in reviewing.

**Comment by OmgImAlexis** [comment]
This completely overrides a LOT of stuff. I think for now we'll hold off on merging anything like this. Sorry.

**Comment by fernandog** [comment]
@hernandito 
Why not create others views instead of change the existing ones?

**Comment by hernandito** [comment]
Guys, I am not an expert programmer. It would be ideal to add a new view option. I just dont have the know-how to do this. Thus I was hoping the real experts can implement this.

**Comment by OmgImAlexis** [comment]
@hernandito I'd suggest you mainly add stuff to the style.css instead of overriding old styles in light.css

**Comment by hernandito** [comment]
@OmgImAlexis I will do my best by just editing the style.css file. I will need a couple of days to re-figure it out again.

**Comment by hernandito** [comment]
@miigotu @OmgImAlexis I think I have managed to make the changes ONLY to style.css. I will make a PR to the Development branch. I hope this is the way to do it.

**Pull request closed without merging**
