### PR TITLE
Get trakt trending show images from tvdb

### LINKED ISSUE #2961: Traktlist Not Showing Posters Of Shows
Hi All

I have noticed that when you try to add shows from "traktList=popular" there are no posters that loads with the shows.

I wonder if this is related to `https://github.com/SickRage/SickRage/issues/2653` OR is this an different issue.

If this is an WIP or are aware please close this if not is there an eta at all. 

Thanks a lot again :) 

Branch/Commit: master / a3ce318f2c3b207da474db4c8e3cf62bb9032e0e
OS: Synology
What you did: Tried to add shows from - https://IPADDRESS:PORT/addShows/trendingShows/?traktList=popular
What happened: No Posters Loaded
What you expected: Posters Loaded
Logs:
```
No Logs To Provide As None Was Generated As No Errors In Logs. 
```

### PR DESCRIPTION
**Pull request by miigotu**
Fixes #2961

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by h3llrais3r** [comment]
Implemented the async load and updated the tvdb api to v1.10 (not v2).
It now seems to work a lot better. Will push it tomorrow to this branch. 😄

**Comment by sharkykh** [comment]
@h3llrais3r I'm waiting... :stuck_out_tongue:

**Comment by h3llrais3r** [comment]
Done, can you check?
However, I have the impression that when there are a lot of images (like we have for most anticipated list) the images are only shown when every call has finished...
Although every `src` is set in each ajax call separately.
When limiting the list to a lower size (f.e. 25) it seems to show them individually.

EDIT: hmm, I now seems to work as it should... :roll_eyes: 

For now I did not yet upgrade the tvdb api to v1.10... because I had to modify some things and I don't want to break other functionality. 😄 

PS: I did not yet generate a core.min.js, so you'll need to test with the `developer=1` option in your config.ini.

**Comment by miigotu** [comment]
I see some changes this needs, I'll review it later.

**Comment by sharkykh** [comment]
I see the same issue as you - all the calls have to finish before it shows the images.
I'll take a look in the code later (miigotu might already know how to fix...)

But hey! I works! :laughing: 

Did you do this for debugging?
```
WARNING logs

2017-03-10 23:42:36 Thread-25 :: Unable to look up show with id 323791 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/323791/en.xml
2017-03-10 23:42:22 Thread-26 :: Unable to look up show with id 323354 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/323354/en.xml
2017-03-10 23:42:14 Thread-25 :: Unable to look up show with id 322655 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/322655/en.xml
2017-03-10 23:42:14 Thread-24 :: Unable to look up show with id 322931 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/322931/en.xml
2017-03-10 23:42:00 Thread-26 :: Unable to look up show with id 318689 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318689/en.xml
2017-03-10 23:41:52 Thread-24 :: Unable to look up show with id 324852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml
2017-03-10 23:41:42 Thread-25 :: Unable to look up show with id 318852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml
2017-03-10 23:41:36 Thread-26 :: Unable to look up show with id 294196 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294196/en.xml
2017-03-10 23:41:30 Thread-24 :: Unable to look up show with id 323791 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/323791/en.xml
2017-03-10 23:41:20 Thread-25 :: Unable to look up show with id 323354 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/323354/en.xml
2017-03-10 23:41:08 Thread-24 :: Unable to look up show with id 322655 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/322655/en.xml
2017-03-10 23:41:08 Thread-26 :: Unable to look up show with id 322931 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/322931/en.xml
2017-03-10 23:40:58 Thread-25 :: Unable to look up show with id 318689 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318689/en.xml
2017-03-10 23:40:38 Thread-26 :: Unable to look up show with id 324852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml
2017-03-10 23:40:35 Thread-24 :: Unable to look up show with id 294196 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294196/en.xml
```
This should be either silenced or in DEBUG logger level...

**Comment by sharkykh** [comment]
Another thing we need to fix is shows that are deleted on TVDB throw an exception when you click Add Show. I'll open an issue on that because it is unrelated to the images. (#3379)

**Comment by h3llrais3r** [comment]
Perhaps we just need to filter them out in the list... 😉

**Comment by h3llrais3r** [comment]
About the logging: I copied it partially from `generic.py` where we get the show image in `_retrieve_show_image`.
We can indeed remove them or at least make it debug.

**Comment by sharkykh** [comment]
>Perhaps we just need to filter them out in the list... 😉 

Yep.

Another thing that we should do is somehow keep it from calling TVDB again on the images that aren't cached because it would cause a lot of traffic for no reason.

-------
<del>Found something on StackOverflow that **may or may not help** with the loading issue:
http://stackoverflow.com/a/17904856/7597273</del>

**Comment by sharkykh** [comment]
My commit feels like a really hacky way to accomplish async-ajax with .each() / forEach() .

Javascript functions are synchronous, except for setTimeout and setInterval.
I couldn't find a way to make it work with either of them, so I searched some more and found [this](http://stackoverflow.com/a/13252018).

I also had to comment out the `@retry()` decorator on the loadUrl function in tvdb_api.

This is **definitely NOT** the way to go, but maybe it'll spark a better idea in you.

**Comment by h3llrais3r** [comment]
Hi @miigotu, @sharkykh , I'm back after quite some time. 😄 
I did a small refactoring (without the request queue) to get the images loaded.
Can you verify and merge it if ok?

**Comment by sharkykh** [comment]
Hey @h3llrais3r 
w/o going into the code (just running SickRage) it looks good and fast.

However I don't think we can merge it in this current state.

1. Log is filled with warnings. We still need to find a way to stop it from happening, but only on Trending Shows.
```
00:56:05 WARNING::Thread-28 :: Unable to look up show with id 294196 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294196/en.xml
00:56:05 WARNING::Thread-26 :: Unable to look up show with id 318852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml
00:56:07 WARNING::Thread-29 :: Unable to look up show with id 324852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml
00:56:08 WARNING::Thread-26 :: Unable to look up show with id 323354 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/323354/en.xml
00:56:10 WARNING::Thread-26 :: Unable to look up show with id 318689 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318689/en.xml
00:56:42 WARNING::Thread-27 :: Unable to look up show with id 294196 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294196/en.xml
00:56:42 WARNING::Thread-29 :: Unable to look up show with id 318852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318852/en.xml
00:56:43 WARNING::Thread-29 :: Unable to look up show with id 324852 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/324852/en.xml
00:56:43 WARNING::Thread-28 :: Unable to look up show with id 323354 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/323354/en.xml
00:56:44 WARNING::Thread-29 :: Unable to look up show with id 318689 on theTVDB, not downloading images: error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318689/en.xml
```
-----------

2.
> I also had to comment out the `@retry()` decorator on the loadUrl function in tvdb_api.

My solution is a bad solution, we shouldn't edit tvdb_api.

You said some time ago:
> Implemented the async load and updated the tvdb api to v1.10 (not v2).

But you never actually pushed it.
What about that? Maybe it will solve our issue for the time being?

Speaking of the API:
We actually really need to use TVDB API v2...
I generated the API code for python using swagger-codegen,
but I tried to implement it into SickRage several times,
and had no success. I just don't know how or where to begin.

@miigotu @h3llrais3r 
Do you want me to just push the TVDB API v2 code (lib) to a branch,
open a PR and you can give it a try?

**Comment by h3llrais3r** [comment]
If I update to v1.10, the retry is removed from the code, so that's a possible solution.
But I'll have to add it again, because it also broke some other things, so I'll need to retest it.

But like you said, we should update to v2, so a new branch for it is not a bad idea. 😉

**Comment by h3llrais3r** [comment]
I've just tried the update to 1.10, but it also requires too much changes... 
The `getAttr(show_indexer_obj, 'key', None)` does not work anymore (`__getattr__` removed from within tvdb api) after the upgrade and it's used all over the place. I'll not invest time to replace this while we should upgrade to v2 of tvdb.
So perhaps we should really investigate some time in upgrading to tvdb api v2 instead.
Meanwhile, I can live with the current implementation of the trakt images, the manual remove of retry decorator and with the warnings in the logfile. (Or we can make them debug?)

**Comment by miigotu** [comment]
We need api v2 very badly =P

**Comment by sharkykh** [comment]
I just looked at the code again, I was wrong about the warnings.
I guess I got confused with the warnings we had from TVDB (that were caused by `retry()`)

**Review by h3llrais3r — APPROVED** [review]
I think we have an acceptable version now.

**Comment by sharkykh** [comment]
I've changed my mind, and I'm ready to settle on it too, for now.
@h3llrais3r Did you get a chance to add shows or do a full-update to a show after my change to tvdb_api? (the removal of `@retry()`)

**Comment by h3llrais3r** [comment]
Both adding of new show and force full update are working.
PS: the `@retry` is just a decorator to retry when there is a connection problem.
The current version on github (1.10) has this `@retry` also removed, so I think it's not a problem that we have removed it.
We can still put it again in case it would give some other problems.

**Comment by h3llrais3r** [comment]
@miigotu ok to merge it?

**Review by sharkykh — APPROVED** [review]

**Comment by miigotu** [comment]
I don't care =P
As long as the @retry being commented out doesnt hurt show updates then this cant hurt anyone.

**Comment by sharkykh** [comment]
It would only hurt if TheTVDB.com isn't stable. And we can't control that, can we? :stuck_out_tongue:

**Comment by h3llrais3r** [comment]
Ok, I would go even further... the retry decorator was never part of the api...
Apparently in the past there were some manual changes in the api (see f54a6e25b258151ab00c1b724069166665f2bf44) so we weren't using the actual api. :rofl:

**Comment by sharkykh** [comment]
## We need to run grunt before merging to master!

**Pull request merged**
