### PR TITLE
Add new jquery form

### PR DESCRIPTION
**Pull request by adaur**
It was deleted in https://github.com/SickRage/SickRage/commit/0c5993def21dfc8b3243b88760e0e79514c98953 and not re-added

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis

**Comment by OmgImAlexis** [comment]
@adaur where do we use that?

**Comment by OmgImAlexis** [comment]
@medariox please don't merge thing into dev that add files to the lib directory without asking me next time. I've been trying to get things removed from there not add them :disappointed:

**Comment by medariox** [comment]
Sorry @OmgImAlexis, kinda needed this working yesterday to test a few things out with post processing. Will make sure to ask you first the next time. I can revert that change if you wish.

That file is needed here: https://github.com/SickRage/SickRage/blob/master/gui/slick/js/core.js#L185
and it affects a few pages. For example the Search Providers settings.

**Comment by OmgImAlexis** [comment]
@medariox all's good, I actually removed it as I was in the middle of converting it all over to "real" ajax forms and then we merged into master. Leave it as is and I'll just fix it tonight. :+1:

**Pull request merged**
