### PR TITLE
Cleanup, fix add from trakt lists

### PR DESCRIPTION
**Pull request by miigotu**
Fixes #

Proposed changes in this pull request:
-
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by BKSteve** [comment]
added to this the `massEditUpdate in home` but it's a stretch of my skills.
`core.js` added lines in manage code area is copy of items from config to make the `Save Changes` button work on the `Mass Edit` page.
Also as location wasn't part of the data but needed for a show update, the `get_argument("location")` was crashing with `tornado.web.MissingArgumentError: HTTP 400: Bad Request (Missing argument location)` so bypassed it if coming from the `massEditSubmit` mako.
This however isn't redirecting back to `manage` after submitting - out of my skill level.

**Comment by miigotu** [comment]
> added to this the `massEditUpdate in home` but it's a stretch of my skills. `core.js` added lines in manage code area is copy of items from config to make the `Save Changes` button work on the `Mass Edit` page. Also as location wasn't part of the data but needed for a show update, the `get_argument("location")` was crashing with `tornado.web.MissingArgumentError: HTTP 400: Bad Request (Missing argument location)` so bypassed it if coming from the `massEditSubmit` mako. This however isn't redirecting back to `manage` after submitting - out of my skill level.

To make an argument not required, give it a default value:
`self.get_argument("location", None)`

**Comment by miigotu** [comment]
I'm still confused which page the submit wasn't working, is it the mass update page where you select the "edit" column on the left with checkboxes for all the shows you want to edit? There's an "edit selected" button and a "submit" button top right of that page, and bottom left and right of that page. For edit, only "edit selected" works, and submit for all the rest. It's silly how that is if that's the place you mean.

**Comment by BKSteve** [comment]
After `edit selected` you get the mass edit page with `save changes` at the bottom. That one. 
Sorry meant to drop a screen shot

**Comment by BKSteve** [comment]
It's this `save changes` button that doesn't redirect to the /manage/ properly.
image

The parameters from urljoin in `sickchill/views/manage/index.py > def massEditSubmit`  `return self.redirect("/manage/")` is passed correctly at least at the return statement.

Just when it goes back to the browser it doesn't refresh to `/manage/` but to `/manage/massEdit`

**Comment by miigotu** [comment]
I'll check it out, maybe it's calling finish or something and exiting early from the call.

**Pull request merged**
