### PR TITLE
Remove bitsoup

### PR DESCRIPTION
**Pull request by duramato**
Remove strike file, now defunct and remove bitsoup, pay for a tracker? no thank you
image

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
Why remove a tracker just because you don't like the idea of it?

**Comment by duramato** [comment]
@OmgImAlexis ask any one that uses trackers they will agree with me, direct profiting, plus no one uses it anymore not since it went pay only

**Comment by ripper1967** [comment]
I have to agree with  duramato on this. extortion  of there users, http://i.imgur.com/KDLvlan.png from there site. so why have a link to them?

**Comment by miigotu** [comment]
Being private is one thing, being pay-only is another. We dont support people forcing a profit off of piracy (donations are a totally different thing). I guess you might need to be in your 30's to understand how badly this goes against the pirate code.

**Comment by miigotu** [comment]
Btw, @duramato I called that getstrike one months ago =P

**Comment by duramato** [comment]
I was waiting to see if a "clone" would appear since the source is avaiable like the OldPirateBay but nothing turned out, guess ive waited too long lol

**Comment by miigotu** [comment]
We will always have that source file in git history, so if something turns up we can add it back in with custom_url option,

**Pull request merged**
