### PR TITLE
Fixes SickRage/sickrage-issues/issues/750

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SickRage/sickrage-issues/issues/750

https://github.com/SickRage/sickrage-issues/issues/763

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
:+1:

**Comment by fernandog** [comment]
@miigotu @OmgImAlexis 

why is failing?

```
` /home/travis/build/SickRage/SickRage/.build/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'remy/npm-tree' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'snyk-resolve-deps'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

**Comment by miigotu** [comment]
@OmgImAlexis can you update the build depends?
https://s3.amazonaws.com/archive.travis-ci.org/jobs/106783265/log.txt

**Comment by OmgImAlexis** [comment]
@miigotu that shouldn't be happening as the node_modules directory should be cached.

**Comment by OmgImAlexis** [comment]
Done https://github.com/SickRage/SickRage/pull/927

**Comment by OmgImAlexis** [comment]
Any idea why travis only fails on the push and not the pr?
Trying to track down why the `npm install` command is failing.

**Pull request merged**
