### PR TITLE
Add total show size column to homepage

### PR DESCRIPTION
**Pull request by miigotu**
@Thraxis thanks, dunno how I overlooked using SUM
@OmgImAlexis

### CODE REVIEW

**Comment by labrys** [comment]
@miigotu gives you sum-thing to think about :wink:

**Comment by OmgImAlexis** [comment]
@VinceVal The js will also need fixing since this changes the column count again.

**Comment by fernandog** [comment]
@miigotu when SR calculates the size? every page load or when displayShow is open or when SR starts?

**Comment by labrys** [comment]
@fernandog I would guess if its added to the mako then every page load, but I haven't looked at the commit yet.

**Comment by Thraxis** [comment]
@fernandog the sizes are grabbed from the database at the same time it grabs the air-date for display on the index.  All of the episodes have the file sizes stored in the database and an SQL query SUM is very fast.  

This is an on the fly query that's done each time the index page is displayed

**Comment by fernandog** [comment]
So it get updated when: refresh show or show update threads. Nice. Thanks

**Comment by Thraxis** [comment]
http://feathub.com/SickRage/SickRage/+301

**Comment by fernandog** [comment]
@sandervdhoek

**Pull request merged**
