### PR TITLE
Improve quality pills and fix SickRage/sickrage-issues/issues/144

### PR DESCRIPTION
**Pull request by fernandog**
Fixes SickRage/sickrage-issues/issues/144

and create 3 more pills:

HDTV: all sources from all qualities (allowed and preferred) are HDTV
WEB-DL: all sources from all qualities (allowed and preferred) are WEB-DL
BLURAY: all sources from all qualities (allowed and preferred) are BLURAY
1080p: all resolutions from all qualities (allowed and preferred) are 1080p
720p: all resolutions from all qualities (allowed and preferred) are 720p

image

### CODE REVIEW

**Comment by fernandog** [comment]
sorting of the Quality column in HOME and MANAGE page doesn't work with this pills. It should work are they are TEXT
@OmgImAlexis can you help me please?

**Comment by fernandog** [comment]
@VinceVal

**Comment by fernandog** [comment]
@OmgImAlexis please?

**Comment by OmgImAlexis** [comment]
@fernandog what qualities did you add? They're converted in js using this.

```
return s.replace('hd1080p', 5).replace('hd720p', 4).replace('hd', 3).replace('sd', 2).replace('any', 1).replace('best', 0).replace('custom', 7);
```

**Comment by fernandog** [comment]
I created this. maybe I could add this between those in the replace
'HDTV',
'WEB-DL'
'BLURAY'
'1080p'
'720p'

@miigotu suggestions to the sorting?

**Comment by OmgImAlexis** [comment]
Is that the exact text that's on the page?

@miigotu what order **EXACTLY** should they be in?

**Comment by fernandog** [comment]
Yes

**Comment by miigotu** [comment]
We dont have a 480p quality. SDTV/SDDVD != 480p.

**Comment by fernandog** [comment]
SD resolution isn't 480p ? I thought so. Will remove then

**Comment by labrys** [comment]
@miigotu doesn't 480p get tagged as SD TV currently as per:

``` python
if check_name([r"480p|web.?dl|web(rip|mux|hd)|[sph]d.?tv|dsr|tv(rip|mux)|satrip", r"xvid|divx|[xh].?26[45]"], all) and not check_name([r"(720|1080)[pi]"], all) and not check_name([r"hr.ws.pdtv.[xh].?26[45]"], any):
    ret = Quality.SDTV
```

and for anime:

``` python
sd_options = check_name([r"360p", r"480p", r"848x480", r"XviD"], any)
```

Of course that isn't a 480p quality, it's an SD TV quality.  But SD TV is not only 480p.

**Comment by fernandog** [comment]
@miigotu @labrys @OmgImAlexis 
this is my suggestion:

```
return s
.replace('custom', 11)
.replace('BLURAY', 10) # Custom: Only bluray
.replace('hd1080p', 9) # 
.replace('1080p', 8) # Custom: Only 1080p
.replace('HDTV', 7) # Custom: 1080p and 720p (only HDTV)
.replace('WEB-DL', 6) # Custom: 1080p and 720p (only WEB-DL)
.replace('hd720p', 5)
.replace('720p', 4) # Custom: Only 720p
.replace('hd', 3)
.replace('sd', 2)
.replace('any', 1)
.replace('best', 0)
```

**Comment by miigotu** [comment]
all 480p is SDTV, but not all SDTV is 480p....

Inclusion is not equality =P

@fernandog you fubar the rebase.

Also, why would you need 720p and hd720p and hdtv? those ARE all the same. Same thing with 1080p and hd1080p

**Comment by fernandog** [comment]
fixed! =)

**Comment by fernandog** [comment]
@OmgImAlexis Should I merge and you edit parsers.js after ?

**Comment by miigotu** [comment]
`Also, why would you need 720p and hd720p and hdtv? those ARE all the same. Same thing with 1080p and hd1080p`

**Comment by fernandog** [comment]
They are diff things. Custom works for allowed/preffered. the profiles don't. That's the reason of the issue # 144

**Comment by labrys** [comment]
@fernandog UI suggestion instead of using a candy-striped pill, which imo looks a little ugly, how bout a single diagonal division, top-left half blue, bottom-right half green.  You could also split it in half vertically, but that might potentially interfere with the text.

**Comment by fernandog** [comment]
@OmgImAlexis what do you think? I don't know how to change that.

**Comment by fernandog** [comment]
@medariox fixed up the new variables names. thanks!

**Comment by OmgImAlexis** [comment]
@labrys I think we should leave it for now and just focus on bug fixes. We can focus on the UI later. We've been changing it too much lately. :-1:

**Comment by fernandog** [comment]
@OmgImAlexis about parsers.js, can you change it after I merge this please?

**Comment by OmgImAlexis** [comment]
@fernandog yes

**Comment by fernandog** [comment]
@OmgImAlexis done. thanks!

**Comment by OmgImAlexis** [comment]
Done https://github.com/SickRage/SickRage/pull/440

**Pull request merged**
