### PR TITLE
Use bs4 for newznab parsing and category getting

### PR DESCRIPTION
**Pull request by miigotu**
…s atm

Might fix Newznab categories @neoatomic 
Should fixup https://github.com/SickRage/sickrage-issues/issues/13

Not sure if this is the solution we want. feedparser is just sucking hardcore.

### CODE REVIEW

**Comment by neoatomic** [comment]
@miigotu Just tested, and its working. :)

However some small improvements we could make. : 
- Enable a custom added nzb provider by default. (If a users adds one we can be sure that he plans to use it. Its currently not done.)  
- By default enable daily&backlog search for that provider custom provider. (That is currently not done.)
- When creating the provider add automatically the 5030&5040 categories. (To prevent a user forgets to set a category at all.)

I'm sure those additions will prevent some support issues.

**Comment by miigotu** [comment]
@neoatomic see if this commit catches your api limit problem for nzbplanet

**Comment by neoatomic** [comment]
Seems to be working.:) 

```
2015-11-19 16:23:08 SEARCHQUEUE-BACKLOG-81275 :: [nzbplanet.net] :: Authentication error: Your account for nzbplanet.net has reached the api limit
2015-11-19 16:23:08 SEARCHQUEUE-BACKLOG-81275 :: [althub.co.za] :: Authentication error: Your API key for althub.co.za is incorrect, check your config.
```

**Comment by miigotu** [comment]
Ok, so this is starting to look VERY nice.

```
Log info when fetched data is invalid instead of raising an exception
Add docstrings for all methods and coding declaration
Free bs4 memory when done getting categories
Remove self.last_search (unused anymore, spam is gone)
Dont even try to search or get caps if a key is required and missing
Initialize cache after all provider attributes are set, not before
Make a few attribute accesing more safe
General cleanup and making it easier to follow
TODO: Store caps attributes and dont add parameters to the search that arent supported, such as using search instead of tvsearch if tvsearch is unsupported, or omitting tvdbid if unsupported
TODO: Skip search if epObj is for sports or anime but the corresponding category is not enabled for that provider.
```

I'd like to implement those 2 TODO and be tested before this is merged. Can we test here again before I go any further?

**Comment by labrys** [comment]
@miigotu I'll switch to this tomorrow

**Comment by miigotu** [comment]
@labrys just learned that this method requires lxml -.- Seeing if there is a way for this to be avoided

**Comment by labrys** [comment]
yeah saw that in irc

**Comment by miigotu** [comment]
@labrys @neoatomic @VinceVal can you guys test this? I will rebase once I know it is good to go.

Also I was curious, since @VinceVal didnt have lxml and the other implementation didnt work, is it also possible someone might not have html5lib?

http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser

**Comment by labrys** [comment]
@miigotu I'm currently setting up a Freenas VM so I can test the plugin... once I have a handle on that I'll look into this might not be until tomorrow though depending on how long this takes me

**Comment by neoatomic** [comment]
I have it running for 6 hours or so. Seems to be working fine.
Did a backlog search for an episode that wasn't found yet, and it got snatched.
My first unaired episodes are in 2-3 days so cant tell any more yet. (I also pm'd you the log for review.)

**Pull request merged**
