### PR TITLE
Fix notification responsiveness

### LINKED ISSUE #2274: Mobile views on small viewport
On an iPhone regardless of the browser the UI cuts off key bits. For example, when deleting a show the checkbox to permanently delete files is off screen and not clickable since resizing the window doesn't work it seems.

### PR DESCRIPTION
**Pull request by beschoenen**
Fixes #2274

image

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
light theme is ok and doesnt need changed too?

**Comment by beschoenen** [comment]
It's fine, no colors have been changed.

**Comment by miigotu** [comment]
I meant is the layout also broken in the light theme? The layout should be in style.css and the colors only in light.css/dark.css afaik, but when something is changed in dark.css generally light.css and/or style.css also needs updated.

**Comment by beschoenen** [comment]
It should be like that, yeah, but it isn't atm.
dark.css is always loaded and light.css gets loaded after to overwrite the colors. dark.css does contain a lot of non-color styles though.

The light theme is fine, It can be merged.

**Pull request merged**
