### PR TITLE
Fixed two visual bugs in 'Missed Subtitle Management'

### PR DESCRIPTION
**Pull request by medariox**
Needs minimization, someone please? :) @SickRage/collaborators

### CODE REVIEW

**Comment by felipesalomao** [comment]
Updated core.js via ssh, then restarted SR, cleaned cache and subtitle button on TV show page continue not show.. Also half of subtitles are marked as pending in manage missed subtitles, but all them have subs.. Already tried rescan files it also don't download subtitles automatically, in debug log it say that already have subtitles.. But I don't have..

**Comment by felipesalomao** [comment]
Here is screenshot..
b5d840ec-9bc6-11e5-9701-9c644a4914fb

And also full debug log when it tried seach for subtitle (after i updated to the latest commit on 02:27 06/12/15..
https://gist.github.com/felipesalomao/5b26783f705f9063521b

**Comment by medariox** [comment]
@felipesalomao 
This has nothing to do with your issue. We will inform you in your issue report as soon as we fix it, please have some more patience.

**Comment by felipesalomao** [comment]
Sure.. Fernandog that asked me to post here result of test.. CC button
(search subtitles in tv show SR page) here also isnt working (don't show).
This pull request isn't about it? Sure will wait and can test anything..
Just ask me.. Thank you for hard work!

Em segunda-feira, 7 de dezembro de 2015, Dario notifications@github.com
escreveu:

**Comment by miigotu** [comment]
this pr isn't about the subtitle button. and without the js minimized you can't even see the result of this.

**Comment by felipesalomao** [comment]
Ok. Just forget..

Will see progress on another issue

Em segunda-feira, 7 de dezembro de 2015, miigotu notifications@github.com
escreveu:

**Comment by OmgImAlexis** [comment]
@medariox check these out
https://github.com/SickRage/sickrage-issues/issues/146
https://github.com/SickRage/sickrage-issues/wiki/How-to-setup-a-development-enviroment

**Comment by miigotu** [comment]
@medariox we cant fix it, because you made it on your develop branch and it isnt upstream lol

**Comment by miigotu** [comment]
Will make another PR

**Pull request closed without merging**
