### PR TITLE
Add provider YggTorrent

### PR DESCRIPTION
**Pull request by adaur**
Fixes #

Finally managed to make a proper commit.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adaur** [comment]
Anyone?

**Comment by ahyear** [comment]
i would be interested also by this merge!!

**Comment by phathak** [comment]
Me too!

**Comment by Jens84** [comment]
It doesn't work anymore because they added the NFO column (and they forgot to include it in the table headers) which shifts the size/seeders/leechers columns index.

I would also recommand to fetch the column indexes from the table headers if you don't want to make a pull request each time they do some changes on the search engine (such as reordering columns).

Anyway, they announced an advanced search engine and I guess we should wait for it before pushing any YggTorrent provider to SickRage.

**Comment by lejudoka13** [comment]
what about the dev to merging that ? we need this provider

**Comment by Matsumot0** [comment]
+1 :-(

**Comment by adaur** [comment]
PyMedusa has it merged in dev branch if you really want it

**Comment by lejudoka13** [comment]
yeah but what about the guy who is in charge of merging ? cause it feel like it's one month the last merging thing but the community create some new things and resolves some issues

**Comment by p0psicles** [comment]
@miigotu can you help these guys out? Just need to guide this Pr a little.

**Comment by B2i** [comment]
+1 :-(

**Comment by miigotu** [comment]
Sorry, just been busy. Has tests been added for this?

**Comment by croftman** [comment]
Need it too ! :)

**Comment by theobarrague** [comment]
@miigotu check my pull request, it's working for me #4034

**Review by Jean-Mercier — COMMENTED** [review]
Look good need your approuvement

**Comment by lejudoka13** [comment]
we all wait the dev to merges all changes

**Comment by lejudoka13** [comment]
answers : When will the changes be merges to master and t411.si added too

**Pull request merged**
