### PR TITLE
Update TNTVillage URL

### LINKED ISSUE #5111: TNT Village has new URL
http://www.tntvillage.scambioetico.org/?releaselist
the URLs in tntvillage.py are not working

### PR DESCRIPTION
**Pull request by WebSpider**
Fixes #5111 

Proposed changes in this pull request:
- Change all URL's for TNTVillage to www and not forum

This change will have to be tested by someone who has a tntvillage account. I don't have TNTVillage set up.

- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
Both urls seem to be not working for me?

**Comment by WebSpider** [comment]
The urls do work for me (I see some content that seems relevant on them), however I don't have an account to check full functionality

**Comment by Usura666** [comment]
for some time now the TNT Village forum is open only during certain time slots. for this reason it is not possible to search using username and password. administrators of the site, however, have made available a release list available at this address:

http://www.tntvillage.scambioetico.org/?releaselist

from this page it is possible to carry out searches to download magnets or .Torrent.
in this way you can search at any time of the day .
I hope someone can implement this search in the TNT village provider.

**Comment by Usura666** [comment]
the forum is open only during the night hours. Only at night you can search using your username and password to log in.

**Pull request closed without merging**
