### PR TITLE
Quick'n'dirty, return true rather than false when PP finds `exists sa…

### PR DESCRIPTION
**Pull request by miigotu**
…me size` so it is added to the DB as processed.

Fixes https://github.com/SickRage/sickrage-issues/issues/483

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
@miigotu if you run manual PP this will still process, correct?

**Comment by miigotu** [comment]
Yes, this doesnt change anything other than removing the error. This used to return true way back and is the only reason you see this error now. It happens when the history gets trimmed on SR startup, it can forget that it has processed this file before and try it again. When it returns true it just adds it back to the cache. In this case, I think thats sort of db thrashing that we trim the db and then add the same data back on PP. Thoughts @labrys?

**Comment by labrys** [comment]
@miigotu I think the log line is terrible :grinning: but I think your logic is sound.

**Comment by miigotu** [comment]
@labrys it can be changed, I was just being a smart ass because I think its a bad solution =P. This is how it originally was though and we didnt have issue reports the lol.

**Pull request merged**
