### PR TITLE
Delta Time #2 Add New Fix

### PR DESCRIPTION
**Pull request by BKSteve**
Proposed changes in this pull request:
add new show functionality such that a new show add will conform to the selected Previous Episode status.
add existing will apply new delta time setting

### CODE REVIEW

**Comment by BKSteve** [comment]
One day I'll remember to set base branch to develop before clicking submit.

**Comment by miigotu** [comment]
I'm not so sure about this, almost need to have a date the show was added to the database stored in the database to do this correctly

**Comment by BKSteve** [comment]
This change is for adding new show effectively disable the date delta and follow the chosen settings. 
Existing shows add same as any daily changes would be treated as if already there and date delta applied. 
When testing this change has S1E1 set as wanted others with date delta.

**Comment by miigotu** [comment]
I don't think this or the last PR was the place to make the change. The setting is right, but it should be used where episodes are checked for allowed/preferred if a better version needs downloaded. If the episode is any of downloaded/skipped/ignored/archived and the episode is older than this setting then it should be left alone. If it is wanted/failed, allow it to be wanted and searched for.

We also should set a longer interval for show updates when a show is ended for the show updater.

**Comment by BKSteve** [comment]
Tv.py change from previous and this one interact. 
`1641 elif self.status in [UNAIRED, UNKNOWN]:`
So only these 2 status are affected by the timer everything else remains as before. 
The issue here is when you add a new show as everything is new they are unknown. By setting the timer to 0 temporarily the add new sequence avoids the timer and adds like it used to. Add existing has timer applied for all unknown unaired episodes.
Will need to do some more testing in regards unaired to ensure they do get set to wanted correctly. Or just make a new if for unaired and process the two separately. 
Open to suggestions or an alternate method.

**Comment by miigotu** [comment]
There has to be a better way to do this, it just doesn't feel right.

Maybe adding an argument `force` to `loadEpisodesFromIndexer` and `loadFromIndexer` instead. That way if a user clicks the force update on the UI you can force all episodes to be updated later also.

**Comment by BKSteve** [comment]
Yeah, it needs something that says we're adding either a new or existing show to the database so apply the configured settings of the page, otherwise use time delta on any other `unknown` status at all other times.

**Comment by miigotu** [comment]
I think it works better this way, because the automatic updater will respect the settings, but forcing a show to update in the displayshow or massupdate will force a full update.

**Pull request merged**
