### PR TITLE
Remove torrents from Transmission on file post processing

### PR DESCRIPTION
**Pull request by fireph**
This adds the functionality to remove torrents from Transmission (but can be added to other clients) where the files in the torrent match the file being post processed. It gets the list of torrents, then checks if the torrent is finished, and then checks each file in the torrent for a match to the post processed file. If there is a match and post processing is successful, the torrent will be removed (but files will remain intact).

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read contribution [guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by beschoenen** [comment]
It might be a good idea to move the UI part to `config -> search settings -> $torrent_client`. What do you think @OmgImAlexis?

Does this also remove torrents that are broken at 99.% (this happens often when you have move files turned on).

**Comment by fireph** [comment]
I don't think it will remove torrents that are broken like that. The way it is designed now, it will only remove the torrent if it has finished seeding when the post processing happens.

I would have to test out how to detect if a torrent is broken like that in the transmission rpc api (if it is possible).

**Comment by Gelioks** [comment]
Is it going to be pushed into Dev/Master anytime soon? Or the project is almost dead?

**Comment by arantes555** [comment]
I'd love to see this too !

**Comment by fireph** [comment]
I'll try to update this again in a bit with the feature request to remove torrents that are in broken states/at 99.9%

**Comment by Gelioks** [comment]
@DungFu Did you have a chance to look at this? Thanks.

**Pull request closed without merging**
