### PR TITLE
Split Overview.SNATCHED into seperate SNATCHED_BEST and SNATCHED_PROP…

### PR DESCRIPTION
**Pull request by miigotu**
…ER, add selector and SNATCHED to backlogOverview

Still need to handle when show doesnt have any preferred qualities (would only be set as SNATCHED not SNATCHED_BEST I think)
Possible to also assign different css to these to color them different, but need to be careful not to break the selector id's on displayShow
Replaces #213

### CODE REVIEW

**Comment by miigotu** [comment]
@fernandog this is how it needs to be done, however there are still some small things to do for this (or at least check)

I might move .QUAL to another value so that SNATCHED can carry it's real common.SNATCHED value as well.

EDIT: Did those two things, test it out please. Could still change the Overviewstrings for proper and best and add some css to distinguish them

**Comment by fernandog** [comment]
@miigotu 

Seems ok The low snatched appeared OK.
But on show is showing as "Snatched (Low Quality)" but it has archived first match enabled, so its not low quality.

About the color I would keep the yellow too and keep the pink for "last" snatch. what do you think?

**Comment by miigotu** [comment]
Yellow doesnt belong for anything snatched regardless of quality. yellow means you have a file already to watch.

**Comment by fernandog** [comment]
Ok. Do you need more info about the other one? 
Allowed 1080 web
Preferred 1080p hdtv
Archive first match enabled
Ep status: snatched 1080 web

**Comment by miigotu** [comment]
@fernandog and now?

**Comment by fernandog** [comment]
Its ok now! Maybe others should test too.
Are you going to change displayShow too or just backlogOverview?

**Comment by miigotu** [comment]
displayshow just shows them as they are, no real reason to split them without css for special colors, but that would also add 2 more selectors at the top of the page.

**Pull request merged**
