### PR TITLE
Force set release date to files on Show and Mass Update

### PR DESCRIPTION
**Pull request by Nyaran**
Added button on Show view and Mass Update to force set the date of video file to release date (Like post-processing)

### CODE REVIEW

**Comment by Nyaran** [comment]
Hi,

I think that errors are not related with my PR, it's about Torrent9 provider. please, can you check?

Regards

**Comment by miigotu** [comment]
this will take a bit of manual review, ill try and get to it in the next few days

**Comment by miigotu** [comment]
Why not just check the `update` box and run that?

**Comment by Nyaran** [comment]
The "Force full update" button also changes the date of downloaded files? I try it, but the "redate" function is not called :/

**Pull request closed without merging**
