### PR TITLE
Back to .li

### PR DESCRIPTION
**Pull request by djoole**
Someone changed the domain to .lv but it is .li

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by djoole** [comment]
@OmgImAlexis WTF??? This NEEDS to be merged, someone messed up the site domain.
People need to check stuff before merging..

**Comment by OmgImAlexis** [comment]
Closed since I opened a proper revert.

**Comment by OmgImAlexis** [comment]
@miigotu is offline and made it that someone else needs to approve via pull approve before it'll merge. It shouldn't be the biggest issue anyways since it's only in develop and not master.

Ref: https://github.com/SickRage/SickRage/pull/3075

**Comment by djoole** [comment]
OK.
For my info, what was wrong in my PR ?

**Comment by OmgImAlexis** [comment]
You should have reverted instead of just committing new changes. There's a revert button in the PR.

**Comment by djoole** [comment]
OK, I wasn't aware of that, sorry and thanks for the tip :)

**Pull request closed without merging**
