### PR TITLE
Rewrite xthor to use api

### LINKED ISSUE #1593: Rewrite Xthor provider to use API
Sorry for my english ,Thanks to google Translate ;-).
There is a new API for the Xthor provider.
The site search "system" (scraping) that SR uses still works, but is heavily taxed with bonus point when a number of searches is reached. 
They want to promote the use of their API, on 3rd party apps instead of scrapping

English docs :
 
> The Xthor API work with your passkey at this adress :
>  https://api.xthor.bz/?passkey=&search=&category=&freeleech=&tmdbid=
> The passkey is generated the first time you download a .torrent
> 
> Parameters description
> - Without parameter, the API return the last 30 torrents uploaded on Xthor
> - 'search', allow you to perform a search with keywords
> - 'tmdbid' parameter is more reliable, for each movie or tv show, an www.themoviedb.org id is set on the torrent table, verified by the staff
> - "freeleech" 1= only freeleech torrent, 0=only non freeleech torrent, parameter not set return both
> - "category" , search only into specified categories (?&category=4+5+6)
> 
> JSON result:
> 
> error
> 
> - int code , 0 = all is ok, 1 = passkey not found, 2 = no result
> 
> user
> 
> Your account stats:
> - int id
> - varchar username
> - bigint uploaded, in byte
> - bigint downloaded, in byte
> - int class
> - decimal(10,1) bonus_point
> - int hits_and_run
> - varchar avatar_url
> - boolean can_leech, 1=you can download, 0= you can't download, proly cause your ratio is below 0.5
> 
> torrents
> 
> - int id
> - int category
> - int seeders
> - int leechers
> - varchar name
> - int times_completed,
> - bigint size, in byte
> - int added, timestamp
> - int freeleech
> - int numfiles
> - varchar release_group, NULL, p2p or scene
> - varchar download_link
> - int tmdb_id, www.themoviedb.org id
> 
> 
> Example:
> For example if you want to retrieve The Walking Dead SUBFRENCH HD torrents
>  https://api.xthor.bz/?passkey=Your_Passkey_Here&category=17&tmdbid=1402

French doc :

> Requête GET

> Vous pouvez effectuer des requêtes via cette url : https://api.xthor.bz/?passkey=*********&search=&category=&freeleech=&tmdbid=
> 
> - En l'absence de paramètre l'API vous transmettra les 30 derniers torrents uploadés sur Xthor.
> - Le paramètre "search" vous permet d'effectuer une recherche avec un ou plusieurs mots clés.
> - Le paramètre "tmdbid" permet d'effectuer une recherche en fonction de l'id de www.themoviedb.org
> - Le paramètre "freeleech" permet d'obtenir 3 résultats différents, si le paramètre n'est pas définit la requête retournera les torrents en freeleech et ceux qui ne le sont pas, si le paramètre est 0 seul les torrents qui ne sont pas en freeleech seront retournés, si le paramètre est sur 1 seul les torrents en freeleech seront retournés.
> - Le paramètre "category" vous permet d'effectuer une recherche dans une ou plusieurs catégories (?&category=4+5+6), par défaut la recherche s'applique à toutes les catégories.
> Films / BluRay = 1
> Films / Remux = 2
> Films / Encode 3D = 3
> Films / 1080p x264 = 4
> Films / 1080p x265 = 100
> Films / 720p = 5
> Films / SD x264 = 7
> Films / XviD = 6
> Films / DVD = 8
> Films / WEBDL = 94
> Films / WEBRiP = 95
> Films / Documentaire = 12
> Films / Spectacle = 33
> Films / Dessins Animés = 31
> Films / VOSTFR = 9
> Séries / Pack VF = 13
> Séries / HD FR = 15
> Séries / TV FR = 14
> Séries / Dessins Animés = 32
> Séries / Emission TV = 30
> Séries / Sport = 34
> Séries / Pack VOSTFR = 98
> Séries / HD VOSTFR = 17
> Séries / TV VOSTFR = 16
> Musique / Concerts, Clips = 20
> Livres / Romans = 24
> Livres / Magazines = 96
> Livres / BD = 99
> Logiciels / Jeux PC = 25
> Logiciels / Playstation = 27
> Logiciels / XboX = 26
> Logiciels / Wii = 28
> Logiciels / NDS = 29
> Logiciels / Applis PC = 21
> Logiciels / Applis Mac = 22
> Logiciels / Smartphone = 23
> Films / XxX = 36
> 
> Résultat JSON
> L'API retourne un résultat sous forme de JSON, il y a 3 principaux tableaux:
> 
> error
> - int code , 0 = Aucune erreur, 1 = passkey introuvable dans la bdd, 2 = aucun résultat, 3 = power saver, seulement la requête en cache sans paramètre est disponible, 4 = DDOS attack, API désactivée
> - string descr , description de l'erreur.
> 
> user
> retourne les informations de votre compte:
> - int id
> - varchar username
> - bigint uploaded, valeur en octets
> - bigint downloaded, valeur en octets
> - int class
> - decimal(10,1) bonus_point
> - int hits_and_run
> - varchar avatar_url
> - boolean can_leech, 1=vous pouvez télécharger, 0= vous ne pouvez pas télécharger sûrement à cause d'un faible ratio
> 
> torrents
> retourne un tableau contenant les torrents
> - int id
> - int category
> - int seeders
> - int leechers
> - varchar name
> - int times_completed, nombre de fois complété.
> - bigint size, valeur en octets
> - int added, timestamp
> - int freeleech
> - int numfiles, nombre de fichiers
> - varchar release_group, NULL, p2p ou scene
> - varchar download_link
> - int tmdb_id, www.themoviedb.org id

Thanks for you work!

### PR DESCRIPTION
**Pull request by miigotu**
Fixes #1593

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fana13** [comment]
Hi @miigotu, seems some problems on backlog search with the new rewrite of xthor.
I've this SEARCHQUEUE-BACKLOG-277165 :: [XThor] :: no result  on my warning log
It repeat in each backlog search since the new rewrite.
Thanks.

**Comment by miigotu** [comment]
fixed

**Comment by fana13** [comment]
You're the best @miigotu, thanks so much :)

**Pull request merged**
