### PR TITLE
Avoid run 2 or more PP threads at the same time

### PR DESCRIPTION
**Pull request by fernandog**
Use the same logic as DAILYSEARCHER
https://github.com/SickRage/SickRage/blob/develop/sickbeard/dailysearcher.py#L44-L45

Fixes: https://github.com/SickRage/sickrage-issues/issues/1028

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@OmgImAlexis

**Comment by OmgImAlexis** [comment]
From the looks of that it just stops manual PP when the auto is still running, right?

I need it to not allow the auto to start if the manual is already going.

**Comment by fernandog** [comment]
its exactly what it does: if self.amActive (running), return False (don't run)

I only log message if is force(manual)

feel free to try it! =)

**Comment by miigotu** [comment]
Fixed with #1067

**Pull request closed without merging**
