### PR TITLE
Split core.js

### PR DESCRIPTION
**Pull request by beschoenen**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by beschoenen** [comment]
@miigotu I'd like your feedback on this.

**Comment by miigotu** [comment]
@beschoenen It actually used to be in separate files, and it was difficult to maintain that way. We are/were actually in the process of moving everything into core.js as part of a full js rewrite. This allowed for one minified  request from the server to be cached as well.

**Comment by OmgImAlexis** [comment]
This won't work and it'll add around 0.5s of load for every single file you have that hooks into a document load event. That's the reason it was all added to a single file. If you're going to steal the idea of splitting it like I did for Pymedusa you should at least see how I did it so you don't end up with a slower load time.

**Comment by beschoenen** [comment]
@OmgImAlexis I didn't steal anything, we just think alike, I guess ;). I'll have a look at your repo.

**Comment by miigotu** [comment]
@beschoenen no angular.js please, thanks ha

**Comment by beschoenen** [comment]
@miigotu wasn't planning on anything that drastic :P, I just think that there should be a better way than 1 huge-ass file.

**Comment by OmgImAlexis** [comment]
Loading a single file is actually not that bad since it's quicker to load a single file's e-tag, etc. and then load it from cache than it is to load multiple files and their respective e-tags, etc.

If you're going to split it then you need to use the current loading system and drop all of the document loads otherwise you'll end up with race conditions that load the main section before the common code.

Take a look at what we did in pymedusa and you'll see what I'm on about.

**Pull request closed without merging**
