### PR TITLE
Better support for show names with apostrophes

### PR DESCRIPTION
**Pull request by MaximusCub**
Proposed changes in this pull request:
- Better support for show names with apostrophes - eg. Also search for "RuPaul's Drag Race" as "RuPauls Drag Race".

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by beschoenen** [comment]
Isn't replacing with `\'` better? @miigotu

**Comment by MaximusCub** [comment]
The problem isn't that we are sending unescaped apostrophes, it is that people actually upload shows to indexers with the apostrophe dropped. 

Searching with the apostrophe only, means that you will not find matches where uploaders decided to omit it. 

This change will make it so that we try to search both with and without. In my tests this helped find shows in the indexers where we previously reported no matches/hits.

**Comment by OmgImAlexis** [comment]
If you're doing this you might as well also add a check for things like `mr.` vs `mr`.

**Comment by MaximusCub** [comment]
I can happily change this so that we have a defined list of characters that we do this for. Would that be preferable ?
If so, it raises the question of how to handle show names with multiple types of such characters. Do we just have one intact search and one fully stripped of these characters? Or do we have every combination in between?

**Comment by miigotu** [comment]
These changes are not needed, since on the search provider end they generally ignore the punctuation in the search and return items with and without the punctuation regardless. If they dont you simply add a scene exception for the show. We cant add an extra search call for every episode/show automatically when most of the time it isnt needed. We have enough trouble with providers not liking how hard we hit them.

**Comment by MaximusCub** [comment]
I tried using the scene exception feature, but could not get it to work. Haven't had a chance to dig in a debug.

**Comment by miigotu** [comment]
you add the scene exception just as it appears on the provider. If your show is `Marvel's Agents of S.H.I.E.L.D` and the indexer has `Marvels Agents of S.H.I.E.L.D.S01E01.RLS` you add a scene exception `Marvels Agents of S.H.I.E.L.D`. It isn't rocket science.

**Comment by MaximusCub** [comment]
The problem isn't that we are sending unescaped apostrophes, it is that
people actually upload shows to indexers with the apostrophe dropped.

Searching with the apostrophe only means that you will not find matches
where uploaders decided to omit it.

This change will make it so that we try to search both with and without. In
my tests this helped find shows in the indexers where we previously
reported no matches/hits.

**Comment by duramato** [comment]
And a Scene exception is just for that, it ads to the search strings.

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/pull/2530#issuecomment-255940004

My comment has nothing to do with unescaped apostrophes. Scene exceptions are to add additional names to try with the search.

**Pull request closed without merging**
