### PR TITLE
Some random cleaning

### PR DESCRIPTION
**Pull request by miigotu**
Rename initial to preferred in quality pill text
Normalize all InvalidShowException and invalidNameException log lines by using the string passed with the exception

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by medariox** [comment]
Why not start using speaking names for variables? aquality > allowed_quality

**Comment by miigotu** [comment]
I don't mind that, but I wasn't really going for that in this PR.

Im simply correcting the mislabel atm.

**Comment by miigotu** [comment]
@SickRage/collaborators @SickRage/moderators 
Can you guys try this out and see if it breaks anything?

EDIT: the part that I am concerned about is from this line down:
https://github.com/SickRage/SickRage/pull/954/files#diff-7d601cb9cf37419c442e260e16686cb0L211

**Comment by neoatomic** [comment]
It would need to be in a branch for me to test it on the Syno.

**Comment by miigotu** [comment]
@neoatomic it is in a branch =P, `cleaning`

**Comment by neoatomic** [comment]
uggh, it doesnt allow me to change to the cleaning branch from the GUI...
`2016-02-07 17:27:44 Thread-48 :: git checkout -f cleaning returned : error: pathspec 'cleaning' did not match any file(s) known to git. [02badb0]`

**Comment by miigotu** [comment]
yeah, click the check for updates first

**Comment by duramato** [comment]
@neoatomic you need to change via git now

**Comment by miigotu** [comment]
@duramato im gonna revert that change fernandog did. Preventing ppl from being able to test branches easily is not ok.

**Comment by duramato** [comment]
@miigotu the error when new branches are created should be catched then

**Comment by miigotu** [comment]
That error happened 1 time, when I force pushed on a feature branch after one person had checked it out. Never wondered why that error didnt happen before? It was a one time thing not worth changing the code over.

**Comment by neoatomic** [comment]
Manual is a pita with the syno... I'm in favor to give users that option in the GUI. Many are not able to access the root or GIT... 

Check for update didn't work btw, nor a restart.

**Pull request merged**
