### PR TITLE
Clean up telegram notifier.

### PR DESCRIPTION
**Pull request by labrys**
Refactored the apiKey param to api_key as part of this.  If that causes problems we can go back to apiKey.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by labrys** [comment]
@duramato

**Comment by fernandog** [comment]
@labrys should we test "bot API token" and "USERID" like said here?

https://github.com/SickRage/sickrage-issues/issues/507#issuecomment-172009733

**Comment by labrys** [comment]
@fernandog I would think that the error message should be sufficient for now.  In the future possibly not allow use of a notifier until initial test passes, but that would need to be a notifier-wide change.

**Pull request merged**
