### PR TITLE
Revert "Check for login in BLUETIGERS"

### PR DESCRIPTION
**Pull request by miigotu**
Reverts SickRage/SickRage#85

Breaks BlueTigers according to @adaur

### CODE REVIEW

**Comment by adaur** [comment]
:+1: 

throws SEARCHQUEUE-DAILY-SEARCH :: [BLUETIGERS] :: Unable to connect to provider

**Comment by fernandog** [comment]
should  "return False" not "return results"

**Comment by adaur** [comment]
Same error

**Comment by labrys** [comment]
@fernandog results is set to [ ].  An empty list (just like an empty string, zero, or None, etc...) evaluates to False.

**Pull request merged**
