### PR TITLE
Add putio client and update search providers templates

### PR DESCRIPTION
**Pull request by miigotu**
Still needs changes, just rebased on develop and fixed conflicts before it gets lost in the updates.

Replaces #1468 
From code it looks like it never logs in, needs tested.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by devclinton** [comment]
If you want, I have to test my changes this evening, but I have an updated branch based on development. I went out of town last week so just now getting back to updating it. Here is my new branch at moment, but I have not tested changes. https://github.com/oudenmallon/SickRage-1/tree/feature-putio-develp

**Comment by miigotu** [comment]
@oudenmallon im going to merge this to develop, you can test/adjust it there.

**Comment by bshep** [comment]
If anyone is wondering you can get it to work by logging into put.io and then opening link below and clicking authenticate, I suppose eventually this will be rolled into the app but for now this works.  Be aware you still have to manually download the files from put.io locally.

> http://api.put.io/v2/oauth2/authenticate?redirect_uri=https%3A%2F%2Fsickrage.github.io&response_type=token&client_id=2392

**Pull request merged**
