### PR TITLE
Add new provider: BJ-Share (Brazillian)

### PR DESCRIPTION
**Pull request by uilton-oliveira**
Proposed changes in this pull request:
- Add new provider: BJ-Share (Brazillian)

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
https://gist.github.com/miigotu/eccef7d16c3998a936f2887dbac1d435#file-bj-share-patch

**Comment by uilton-oliveira** [comment]
Do you need me to apply that patch?

**Comment by miigotu** [comment]
Yes, and then the build will pass @DarkSupremo

**Comment by uilton-oliveira** [comment]
@miigotu done

**Pull request merged**
