### PR TITLE
Update boxcar2.py to new-style classes and PEPs 8 and 263

### PR DESCRIPTION
**Pull request by labrys**
##### Code changes:
- Convert to new style class with explicit object subclassing   33b4e64
##### Formatting changes:
- PEP 0008: Fix multiple imports on one line    d39a9d2
- PEP 0008: Fix white space, blank lines, and indentation   956f2e8
- PEP 0263: Add encoding declaration    0beddc1

### CODE REVIEW

**Comment by labrys** [comment]
@miigotu @WebSpider Did something change with the checks?  The builds are now failing with the same failure I mentioned in sickrage/sickrage-issues#2

**Comment by miigotu** [comment]
github.io request limit being hit, because of so many PR so fast

**Comment by miigotu** [comment]
Actually, I lie. I am messing with the site at sickrage.github.io and it is overriding the gh-pages -.-

It will start working once I get all of the repo's combined there

**Comment by labrys** [comment]
hehe.  Well I'll hold off on pushing the rest for a bit then. :grinning:

**Comment by miigotu** [comment]
Ok, builds are fixed, but almost all of these need rebasing xD

**Comment by labrys** [comment]
Yeah I know :grimacing: ... I'll rebase as I go.

**Pull request closed without merging**
