### PR TITLE
Regex anime

### PR DESCRIPTION
**Pull request by lulandco**
Fixes #

Proposed changes in this pull request:
- Update 'fov' regex to prevent extra score with anime
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Review by OmgImAlexis — CHANGES_REQUESTED** [review]
Remove yourself from the pullapprove file. There's no reason you need to be in that. Also why did you invite me to your repo?

**Comment by lulandco** [comment]
Because I 've messed understanding how pullapprove works :( File corrected and Invitations removed.

**Comment by miigotu** [comment]
You need to provide titles that it used to match and ones that it should also match now, and add tests to make sure previous matches still match.

**Pull request closed without merging**
