### PR TITLE
Poetry export fix in init_helpers.py

### LINKED ISSUE #7767: Sickchill exits with "install.py:34: SetuptoolsDeprecation' does not exist."
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / latest

OS: Linux  on Raspberry Pi (Linux raspberrypi 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux)

Browser: NA
What you did: Fresh install of Bullseye 64bits raspi os
What happened: After a fresh install Sickchill extis with an error "SetuptoolsDeprecation' does not exist."
What you expected: Sickchill to start
Logs:
```
Checking poetry
Can write to /usr/local/lib/python3.9/dist-packages: False
Can write to /home/pi/.local/lib/python3.9/site-packages: True
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.9', './SickChill.py']
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.9/site-packages: True
Can write to /home/pi/.local/lib/python3.9/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU /opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation   warnings.warn( appdirs==1.4.4 babelfish==0.6.0; 

<SNIP>

Command result: ERROR: Invalid requirement: '/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation'
Hint: It looks like a path. File '/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: 

Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Traceback (most recent call last):
  File "/opt/sickchill/./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'
```
I've tried a fix I've used before with the 32bit OS:

".venv/bin/python3 -m poetry lock --no-update -vvv"

But this gives almost the same error:

/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Using virtualenv: /opt/sickchill/.venv

### PR DESCRIPTION
**Pull request by BKSteve**
Fixes #7767 

add the SETUPTOOLS_USE_DISTUTILS=stdlib to the poetry export line.

Tested with 59.8.0 and 60.2.0
without the 60.0.0 + versions would throw the warnings.warn error.

### CODE REVIEW

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/pull/7757#issuecomment-1021322708

**Comment by miigotu** [comment]
Maybe we need to try it without, catch the error, and add the stdlib argument?

**Comment by BKSteve** [comment]
I had closed this in favour of #7757 but here's a way to do the setuptools parameter for syno DSM

**Comment by BKSteve** [comment]
this one resolves only synology and not taking forward

**Pull request closed without merging**
