### PR TITLE
Added check for mislabled/fake files in PP

### PR DESCRIPTION
**Pull request by medariox**

### CODE REVIEW

**Comment by miigotu** [comment]
I think the should be checking `ep_obj.scene_season` because with scene exceptions a released file might have a higher scene number than tvdb says, only to be converted to the right season later

**Comment by medariox** [comment]
I would say the ep_obj.season is already the parsed season number, as I think that happens in _finalize(). So it would be safe to use that season number. I really need some real world cases tho for some proper testing. If anyone know some, please let me know (they are so rare!). 

@SickRage/moderators

**Comment by medariox** [comment]
@labrys 
Some debug log for me please? :)

**Comment by labrys** [comment]
yeah one minute

**Comment by labrys** [comment]
Found the issue.

**Comment by labrys** [comment]
The ones that are giving the warning are ones that arent in SickRage.  I run multiple instances of sickrage that all DL to the same directory... Apparently post-processing is just saying it doesn't like that.

**Comment by labrys** [comment]
gist is acting stupid for me right now so i cant post a full log

```
2015-11-18 18:14:12 DEBUG    POSTPROCESSER :: Unable to parse, skipping: Unable to parse download
2015-11-18 18:14:12 DEBUG    POSTPROCESSER :: Analyzing name G:\tmp\download\From.Dusk.Till.Dawn.S02E10.480p.HDTV.x264.upload-hero.mkv
2015-11-18 18:14:12 DEBUG    POSTPROCESSER :: Trying to find from dusk till dawn on theTVDB
2015-11-18 18:14:12 DEBUG    POSTPROCESSER :: Unable to parse, skipping: Unable to parse G:\tmp\download\From.Dusk.Till.Dawn.S02E10.480p.HDTV.x264.upload-hero
2015-11-18 18:14:12 DEBUG    POSTPROCESSER :: Analyzing name download From.Dusk.Till.Dawn.S02E10.480p.HDTV.x264.upload-hero.mkv
2015-11-18 18:14:12 DEBUG    POSTPROCESSER :: Trying to find download from dusk till dawn on theTVDB
2015-11-18 18:14:13 DEBUG    POSTPROCESSER :: Unable to parse, skipping: Unable to parse download From.Dusk.Till.Dawn.S02E10.480p.HDTV.x264.upload-hero
2015-11-18 18:14:13 INFO     POSTPROCESSER :: This show isn't in your list, you need to add it to SR before post-processing an episode
2015-11-18 18:14:13 WARNING  POSTPROCESSER :: Processing failed for G:\tmp\download\From.Dusk.Till.Dawn.S02E10.480p.HDTV.x264.upload-hero.mkv: 
2015-11-18 18:14:13 DEBUG    POSTPROCESSER :: Processing folder Arrow.S04E06.HDTV.x264-LOL[rarbg]
2015-11-18 18:14:13 DEBUG    POSTPROCESSER :: Arrow.S04E06.HDTV.x264-LOL[rarbg] : No processable items found in folder
2015-11-18 18:14:13 DEBUG    POSTPROCESSER :: Processing folder Ash.vs.Evil.Dead.S01E03.HDTV.x264-FLEET
2015-11-18 18:14:14 DEBUG    POSTPROCESSER :: Ash.vs.Evil.Dead.S01E03.HDTV.x264-FLEET : No processable items found in folder
2015-11-18 18:14:14 DEBUG    POSTPROCESSER :: Processing folder Blindspot.S01E09.HDTV.x264-LOL[ettv]
2015-11-18 18:14:14 DEBUG    POSTPROCESSER :: Blindspot.S01E09.HDTV.x264-LOL[ettv] : No processable items found in folder
```

**Comment by medariox** [comment]
So is this related to the PR or not? :cold_sweat: 
Without the debug log I can't really tell...

**Comment by labrys** [comment]
I'm not able to post the log till tomorrow, but I don't think its really an issue with the PR.  It's doing something that makes sense, it sees a video file that it doesn't recognize from the show list and is letting the user know that it's not going to do anything with it.  Maybe it could use a reword so the information in the warning that appears makes that more clear or maybe it could be changed from a warning to just info or to debug.

**Pull request closed without merging**
