### PR TITLE
Detect yggtorrent url automatically, but only when it is enabled and …

### PR DESCRIPTION
**Pull request by miigotu**
…used and a login is attempted

Add custom url functionality to the provider
Fixes #4914
Fixes #4931

Signed-off-by: miigotu <miigotu@gmail.com>

Fixes #

Proposed changes in this pull request:
-
-
-

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by nathelas** [comment]
Hello,
yggtorrent switched to yggtorrent.to
I don't sse how I can change the adress on the provider setting.
What's "when it is enabled " means ?
Thanks in advance for feedback

**Comment by miigotu** [comment]
It automatically will change the URL to the correct one, once it is out of maintenance. It is obvious to me that they have been changing the URL to block SR. They dont want us using their site (even though we drastically increase their seeders).


Ask when it comes back up.

**Comment by nathelas** [comment]
Yggtorrent.to is up, I can log directeurs the website with my account.
My SR is up to date and stil unable to connect to the provider.
Too bad if the URL switches is only to prevent SR use...

**Comment by miigotu** [comment]
I dont think you are using our fork then?

```
19:42:21 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: GET URL: https://www.yggtorrent.is/engine/search?category=2145&do=search&sub_category=2184&name= [Status: 301]
19:42:22 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: GET URL: https://yggtorrent.to/engine/search?category=2145&do=search&sub_category=2184&name= [Status: 200]
19:42:22 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: Refreshing cookies
19:42:22 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: POST URL: https://www.yggtorrent.is/user/login [Status: 301]
19:42:22 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: With post data: id=*******&pass=********
19:42:22 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: GET URL: https://yggtorrent.to/user/login [Status: 200]
19:42:22 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: Changing base url from https://www.yggtorrent.is/ to https://yggtorrent.to/
19:42:23 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: POST URL: https://yggtorrent.to/user/login [Status: 200]
19:42:23 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: With post data: id=*******&pass=********
19:42:23 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: GET URL: https://yggtorrent.to/ [Status: 200]
19:42:23 DEBUG::SEARCHQUEUE-MANUAL-78901 :: [YggTorrent] :: Unable to match Gotham.S04E03.FRENCH.720p.BluRay.x264-FRATERNiTY to a show in your database. Parser result: Gotham - S04E03 [GROUP: FRATERNiTY] [ABD: False] [ANIME: False] [whichReg: [u'standard']]

```

**Comment by nathelas** [comment]
My bad, you're right.
After checking, I'm using other fork and mismatch the git repo .
Sorry about that and will consider a switch if your workaround is working

**Comment by AdrienR** [comment]
Nice feature :)
About changing URLs, i don't think it's to avoid SR from scrapping, otherwise they would use reCaptcha or similar like others some others providers ... I think url change is more about DNS censorship, like we have in France :/

**Comment by miigotu** [comment]
@AdrienR Its possible to be domain seizures and censorship, but we have seen many of these sites use subdomain changes to thwart SickRage before since it causes a considerable amount of traffic. Imagine 200k users hitting your server with requests a couple hundred times a day. Some have used recaptcha before, but we actually solve recaptcha here on many sites so it isn't a good deterrent.

Changing domain from yggtorrent.is to yggtorrent.to for example makes sense for censorship (if the original domain was shut down), but the old domains still redirect to the new domains which means they still control them, and a change from www.yggtorrent.is to ww1.yggtorrent.is is most definitely not for censorship, its to avoid scrapers.

**Pull request merged**
