### PR TITLE
Remove FNT, add ABNormal, add PhxBit, fix Xthor

### PR DESCRIPTION
**Pull request by adaur**
FNT closed and no longer needs to be in SR.
ABNormal and PHXBit are added.
Xthor wouldn't snatch anything because it would not find the current seeders and leechers + updated the try/except

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by adaur** [comment]
Updated description

**Comment by miigotu** [comment]
rebase/squash and I will merge.

**Comment by duramato** [comment]
@adaur my little cheat sheet for squashing/rebasing :P

```
Try opening a terminal on the project folder and do
git remote -v it should show 2 origins and 2 upstreams
if it doesnt show the upstream do : git remote add upstream https://github.com/SiCKRAGE/SickRage.git

after that do

git fetch upstream
git rebase -i upstream/develop
and
"leave your first commit as "pick" and the rest set to "fixup" or "squash", do not change anyone elses commits. Save and exit"
Finally do
git push origin yourbranchname -f
```

**Comment by adaur** [comment]
Thanks, it will be useful for next time :)

**Pull request closed without merging**
