### PR TITLE
Anime Warning if not in snatch history.

### PR DESCRIPTION
**Pull request by BKSteve**
Fixes nothing. Start a discussion.

### CODE REVIEW

**Comment by BKSteve** [comment]
@miigotu I've played with this and if the filename has no `.` in it then it will kick a Warning #8042 but if it has then there is no warning.
Put some log lines in the 2 files so they are in this pull request.

I was trying to understand the `show_name_helpers.py` line `return release_name.rpartition(".")[0]` and what it was to achieve.

Tested examples with tuple result `hell` 
`[GM-Team] Swallowed Star. 30.mkv` processes without Warning. `('[GM-Team] Swallowed Star', '.', ' 30') return rpartition`
`[GM-Team] Swallowed Star 45.mkv` processes with Warning `('', '', '[GM-Team] Swallowed Star 45') return rpartition`

**Comment by BKSteve** [comment]
Is this a valid answer?
Just playing around. If there are no `.` then use the full string [2] else use [0]
Not that it makes any difference as the next log line uses the full string anyway.

**Comment by miigotu** [comment]
The release name can either be an actual release name, or a file name in the format release_nam.mkv for example. The file name will not match the release name with the extension, and we also want to match release names that have the extension, with the same release from another tracker that happens to not have the extension on it, so we don't download the same release in a few situations, such as if that particular is marked as failed.

**Comment by miigotu** [comment]
`release_name.rpartition(".")[0]` will always contain the full string of the string does not contain an extension. But it becomes a problem if the release name has no extension but it has dots. We need to check if it's a media file name first, and only repartition if it is to drop the extension. helpers.remove_extension also does this.

I don't have internet right now, unscheduled isp maintenance bs. So I can't search really easily on my phone. I was working on improving the gruntfile for releases when they did this to me smh.

**Comment by BKSteve** [comment]
I looked up str.rpartition it doesn't  give full string in [0] if not found 
(https://docs.python.org/3/library/stdtypes.html#str.rpartition)
Split the string at the last occurrence of sep, and return a 3-tuple containing the part before the separator, the separator itself, and the part after the separator. If the separator is not found, return a 3-tuple containing `two empty strings, followed by the string itself.`

Add: The values passed to the `determine_release_name` already has the extension removed. Thus I ask the question.

**Comment by miigotu** [comment]
Wow, you are right. You might have just found a major oversight by me and this might solve a big problem. This is actually to drop nzb/nzb (or any media file extension). I'll need to look at the code also on my laptop, but if you want to you can make a PR for it, and see if I made the same mistake on rpartition anywhere else. 

I want to do a git blame and follow it back and see if I was the first one to do this lol.

**Comment by BKSteve** [comment]
I think a simple change from rpartition to rsplit will give the desired [0] with string.
`return release_name.rsplit('.', 1)[0]`

**Comment by BKSteve** [comment]
Crashed and burned. One line so created new one.

**Pull request closed without merging**
