### PR TITLE
Check if providers are already logged

### PR DESCRIPTION
**Pull request by fernandog**
transmitthenet will fix in my other PR

Possible fix for: https://github.com/SickRage/sickrage-issues/issues/687

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
You are missing the dict_from_cookiejar import on all of those.

**Comment by fernandog** [comment]
F**

Will do later when get home

**Comment by fernandog** [comment]
@miigotu done. hdspace already had

**Pull request merged**
