### PR TITLE
displaying totals below each season showing found episode count + tot…

### PR DESCRIPTION
**Pull request by wimpyrbx**
Fixes #

Proposed changes in this pull request:
displaying totals below each season showing found episode count + total filesize.
this line can also be expanded to display whatever other season information we'd want in the future.
for now it's just a basic <td> around the information as it's only episode count + filesize.
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by wimpyrbx** [comment]
http://www.fshare.it/image.jpeg?i=h3146280410

**Comment by wimpyrbx** [comment]
pre-mature PR. can be removed.

**Comment by miigotu** [comment]
Premature how? =P

**Comment by wimpyrbx** [comment]
it was unfinished. it did not show the summary line on the last season. i'll do a new PR today.

**Pull request closed without merging**
