### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by RHITNL**
Fixes #
## 
## 
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
Did you even try if it even works? It isn't as simple as changing urls

**Comment by miigotu** [comment]
do we know that torrentz2 isnt ran by someone **malicaious**? lol

**Comment by duramato** [comment]
lol it's another one not just a clone, has way more indexed sites and torrents

**Comment by RHITNL** [comment]
I did try but did not noticed any issues until now. Sorry for my useless contribution :-1:

**Comment by miigotu** [comment]
@RHITNL It wasnt useless, but next you should try the changes out locally and make sure they work (in this case checking that it could snatch torrents), and also `python setup.py test`.

I just fixed it for you so that it works and pushed it in another commit/pr

**Pull request closed without merging**
