### PR TITLE
Add movie release name to subtitle ID for Opensubtitle

### PR DESCRIPTION
**Pull request by fernandog**
@medariox @duramato 

```
19:22:10 DEBUG::FINDSUBTITLES :: [opensubtitles] Subtitle score for  H* - 05x09 - The Litvinov Ruse.KILLERS.Portuguese (Brazilian).C.updated.Addic7ed.com(1954989638) is: 111 (min=132)
19:22:10 DEBUG::FINDSUBTITLES :: [opensubtitles] Subtitle score for H*.S05E09.HDTV.x264-KILLERS(1954989953) is: 115 (min=132)
19:22:11 DEBUG::FINDSUBTITLES :: No subtitles found for /media/M*.C*.S04E15.1080p.HDTV.X264-DIMENSION.mkv
19:22:13 DEBUG::FINDSUBTITLES :: [opensubtitles] Subtitle score for  M*.F*.S07E07.INTERNAL.XviD-AFG(1954974883) is: 111 (min=132)
19:22:13 DEBUG::FINDSUBTITLES :: [opensubtitles] Subtitle score for HDTV.x264-FLEET-720p.FLEET(1954974885) is: 115 (min=132)
19:22:14 DEBUG::FINDSUBTITLES :: [opensubtitles] Subtitle score for T*.G*.W*.S07E09.HDTV.x264-LOL(1954990049) is: 121 (min=132)
```

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/Diaoul/subliminal/pull/540

**Comment by miigotu** [comment]
@fernandog this needs to be done upstream before it can be done here. You cant really change stuff subliminal uses internally to identify subtitles properly (as you saw from the build failing on subliminal tests)

**Comment by fernandog** [comment]
I did upstream. It only for debug the min_score until we are sure 132 its the optimal value.
Then we will remove this change in the lib

**Comment by miigotu** [comment]
It cant complete the process with this change, it breaks completely after your log lines are used

**Comment by miigotu** [comment]
If you want to use it locally or in a separate branch for testing thats fine, it just cannot go into develop and break subtitles.

**Comment by fernandog** [comment]
It doesnt break. Its running fine here but ok

**Comment by miigotu** [comment]
if it makes tests fail it breaks it, just saying. You may not have noticed caught exceptions or errors in the lib that subliminal specifically tests for.

**Comment by fernandog** [comment]
Which test failed? Upstream?
SR is running without issues. Downloaded several subtitles. But ok. This will come upstream then

**Comment by miigotu** [comment]
Just because you dont SEE a problem doesnt mean there isnt a problem. This patch changes values that subliminal uses internally to match subtitles.
https://travis-ci.org/Diaoul/subliminal/jobs/94739065

**Comment by fernandog** [comment]
Ofc I saw. I commented in the upstream PR

**Comment by miigotu** [comment]
So are you arguing that this PR DOES break subliminal or that it DOESNT? Pick one or the other.

**Pull request closed without merging**
