### PR TITLE
Merge branch 'master' into 'develop'

### PR DESCRIPTION
**Pull request by sharkykh**
Should fix 'develop' branch being 3 commits behind 'master'

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by sharkykh** [comment]
Still shows it's behind. =/

**Comment by sharkykh** [comment]
@miigotu 
I was able to do this locally:

image

Local branch `develop-merge-master`'s tracked branch is (origin/)SickRage:master
**I pulled `origin/master` into `develop(-merge-master)`**

It just needs a **direct push** to develop. You told me not to push to directly to develop, so I'm only showing you this (develop is a protected branch  - I won't be able to push anyway)

**Comment by sharkykh** [comment]
I was able to do it locally. I didn't use command line, but basically...
```
> git checkout develop
  < Your branch is up-to-date with 'origin/develop'.
  < Switched to branch 'develop'
> git merge master
  < Already up-to-date!
  < Merge made by the 'recursive' strategy.
> git merge develop
  < Updating 41d7d9d8f..<new merge commit on develop>
  < Fast-forward
```
[This worked for me.](https://cloud.githubusercontent.com/assets/10238474/23671673/d1195942-0374-11e7-8065-5b3f1852a5ad.png)
Then all you need to do a push directly to each branch...

**Comment by miigotu** [comment]
Yeah I know how to do it haha. It's not a big deal, it's from my cherry-picks. I'll fix it on next master merge

**Comment by sharkykh** [comment]
silly me, ofc you do :P

**Pull request merged**
