### PR TITLE
Work on Gruntfile.js

### PR DESCRIPTION
**Pull request by sharkykh**
- Removed unused jQuery plugins and an unused node/grunt package
- Work on Gruntfile.js
  - Reorganize
  - Add new publish task (admin only)
   This also fixes the "full changelog" link (it was only comparing one commit back).

**The new grunt tasks are:**
`grunt newrelease`
pulls develop and merges it into master
creates a new tag based on today's date and the last tag and pushes it to the repo.

`grunt genchanges --file=/path/to/sickrage.github.io/sickrage-news/CHANGES.md`
generates an updated change log based on the tags and their messages
and pushes it to sickrage.github.io repo.

`grunt publish` combines the two new tasks into one continuous task.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by sharkykh** [comment]
I couldn't test everything, but `genchanges` worked perfectly up to the push...
For `newrelease` I could only test local stuff - so I know creating a tag works.
It also checks if you already created a release for today
and chooses the next "patch" digit (the last digit in the version I mean)

**Comment by miigotu** [comment]
Doesnt underscore use jquery.json?
And maybe qunit should still be used? Or is chai enough?

**Comment by sharkykh** [comment]
>Doesnt underscore use jquery.json?

I did a search in all the files and the only plugin that was still using jquery.json was that cookiejar one, which was also not used and unmaintained.

>And maybe qunit should still be used? Or is chai enough?

Chai is barely doing anything right now. It wasn't even working until I fixed it earlier this week.
I was just pruning things that looked like they weren't being used, don't really know what's better between the two.

**Comment by miigotu** [comment]
Yeah the js tests just barely got started, they need to be improved by someone who knows how to do that (or has the patience to figure out how to do it right =P)

**Comment by sharkykh** [comment]
I have neither. My Python tests are basically coverage whores lol

**Comment by miigotu** [comment]
You still need a `travis` task in grunt, or change the call to it in .travis-ci.yml

**Comment by sharkykh** [comment]
That's not the issue, didn't delete travis. I have syntax errors.
I'll push as soon as I finish testing the updated locale/messages.json handler

**Pull request merged**
