### PR TITLE
Fix naming anime pattern. 

### LINKED ISSUE #6703: Can no longer use "Season %0S/%RN" as Episode Naming Name Pattern
SickChill Info:
 Branch: master
 Commit: 64e55244d9bdc6d9012eaff214f3b254dc16df1f
 Database Version: 44.2
  Python Version:3.8.5 (default, Aug 22 2020, 01:15:22) [Clang 8.0.0 (tags/RELEASE_800/final 356365)]
  SSL Version:OpenSSL 1.0.2s-freebsd 28 May 2019
  OS:FreeBSD-11.3-RELEASE-p11-amd64-64bit-ELF
  Locale:None.None

SickChill used to work with the Episode Name Pattern of "Season %0S/%RN" for a long time but now it doesn't accept this anymore.  I try to end up with the original episode/filename within the appropriate season folder but end up with the following warning: "You tried saving an invalid normal naming config, not saving your naming settings".

### PR DESCRIPTION
**Pull request by Nyaran**
Fixes #6703

Proposed changes in this pull request:
- Fix incorrect use of input boxes on anime function

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
I'll review in the morning. Need some ZzZzz

**Comment by miigotu** [comment]
Thanks for looking into this

**Comment by miigotu** [comment]
I can't see the surrounding js on my phone haha, but this looks great. I appreciate your skills.

**Comment by Nyaran** [comment]
> I can't see the surrounding js on my phone haha, but this looks great. I appreciate your skills.

just were some wrong jquery selectors (using shown pattern input instead of anime pattern input), and using an anime variable on shown pattern...

Anime needs a big rework I think, and probably the best could be to rewrite it separating from the "normal" shows, as you said previously. I will try to think how organize all of it, but probably we will need to create some abstract classes, to share, at least, the base structure for each type of media items

**Pull request merged**
