### PR TITLE
Update UI statistics labels

### PR DESCRIPTION
**Pull request by labrys**
- Rename Low Quality => Allowed
- Rename Downloaded => Preferred
- Fix backlog mako timezone error

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@labrys 

confusing! Its better the other way. Whats wrong with "Low quality" ?

image

**Comment by labrys** [comment]
@fernandog Problem with `Low Quality` is since we no longer download progressively higher qualities it is no longer an accurate name.  As for your screenshot, there are still more that needs to be tweaked to avoid discrepancies like that, however I think this is a step in the right direction.  Ive tried out different wordings and `Allowed` / `Preferred` was the most concise while still being fairly representative.  I also considered `Interim` / `Final` but figured I'd try this out first since its similar to settings that already exist so should cause less confusion once the other details are ironed out.

**Comment by OmgImAlexis** [comment]
Preferred and Allowed make sense if you look at it this way.
I'll **allow** SickRage to download any of these but I'd **prefer** it replace with one from the preferred list.

`Interim / Final` would work if everyone using it knew what they meant and I doubt a lot of people would understand off the bat so it's best to just keep it as @labrys said.

**Pull request merged**
