### PR TITLE
Use format() and episode_num(), prefer single quotes

### PR DESCRIPTION
**Pull request by medariox**
Replaces https://github.com/SickRage/SickRage/pull/781

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by medariox** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/783/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Comment by OmgImAlexis** [comment]
@miigotu shouldn't someone else have to approve this? Isn't that the whole point of approvals that someone other than to person that's created the PR has to approve the code being merged?

**Comment by miigotu** [comment]
I can make it that way, but the reason I added it was actually so that we could move issues back into main repo. AKA all moderators would be able to create branches and moderate issues/wiki, but they wouldnt be able to merge PR or push to master/develop.

**Comment by medariox** [comment]
@OmgImAlexis 
This PR is the same as PR https://github.com/SickRage/SickRage/pull/781 (see first comment), which was approved by @labrys. I just made this new PR because I messed up the rebase on the other one.

**Pull request merged**
