### PR TITLE
Parser exception

### PR DESCRIPTION
**Pull request by snamds**
Weird characters in newpct provider results made parser raise an exception while trying to formatting to sys encoding (cp1252).

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by Alien003** [comment]
Nice to see this solved ...but I'm really disappointed that we were having this issue for more than a month with nyaa and all 5 related issues were closed without doing anything other than manual code change workarounds. And the issue needed to appear on a non-anime provider to get looked at :(

**Comment by miigotu** [comment]
Anyone disappointed in free software that they didn't write shouldn't be using that software or they should fix it themselves.  That sense of entitlement you have is the real problem.  You don,t employ any of us, we do not cash a check signed by you, we do this for free, so you have no right to be disappointed or give such negative criticism.

Instead be happy that a 3rd party contributor found **the single character** that helped your issue.

**Comment by Alien003** [comment]
I'm sorry, I didn't mean to offend. I'm very grateful of your work, it's really amazing.
I should have explained better.

What I was disappointed was not the absence of a fix.
Was just that I didn't agree with the issues being closed instead of being kept open as known problem.

I actually even researched on[ it and proposed one of the code workarounds](https://github.com/SickRage/SickRage/issues/2170), but my python skills are not great, so as proud developer I was not comfortable as suggesting that "workaround" as a final fix.

**Comment by miigotu** [comment]
If you think that closing an issue means it isnt an issue thats where the misconception is. We only need one issue open per issue, and even if an issue is closed we still get notifications of what is still being reported.

**Pull request merged**
