### PR TITLE
Add torrent9.biz provider

### PR DESCRIPTION
**Pull request by magicseb**
Proposed changes in this pull request:
- Add torrent9.biz provider, french torrent provider. All job done by djang0 and me.

https://github.com/Djang0/SickRage-1

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Still undecided about this provider. I mean `.biz` doesn`t really give them the image of a serious provider....

Replaces #2673

**Comment by magicseb** [comment]
torrent9.biz/torrent9.me is exactly like cpasbien.me

Probably the same team is behind this provider.

Actually, cpasbien is not updating anymore, and become useless soon. torrent9 is an alternative.

**Comment by miigotu** [comment]
Alternative as in mirror or alternative as in replacement? That's what I'm questioning.  We only want top-level sites, not their mirrors, and not amateur sites.

**Comment by magicseb** [comment]
Torrent9.biz is not a mirror of cpasbien.me.

It's a replacement of cpasbien.me.

http://nextwarez.com/torrent9-remplacant-cpasbien/
http://www.xn--torrentfranais-qjb.fr/smartorrent-lun-des-sites-de-torrents-francais-les-plus-connus/

It's in french.

http://www.alexa.com/siteinfo/torrent9.biz

Alexa say 128 as rank in france.

**Comment by Jamyz** [comment]
Bonjour, est ce que j'attend qu'il le mettent sur le master ou j'utilise https://github.com/Djang0/SickRage-1
@+

**Comment by Jamyz** [comment]
Thanks !!! I try with https://github.com/Djang0/SickRage-1

**Comment by Djang0** [comment]
I would advice not to switch your repo to https://github.com/Djang0/SickRage-1 ... I'm confident in the fact that this change will soon be merged to master. If they granted cpasbien, there is no reason not to accept torrent9.

**Comment by Jamyz** [comment]
That's work with https://github.com/Djang0/SickRage-1.
I wait in branch master.
Good work @magicseb and @Djang0

**Comment by miigotu** [comment]
Don't repo bomb. You asked me to merge it here and I did.

**Pull request merged**
