### PR TITLE
Rtorrent changes, forces 0.9.0 - Needs more work

### PR DESCRIPTION
**Pull request by miigotu**
Replaces #5216

### CODE REVIEW

**Comment by fwoelffel** [comment]
Any ETA on this?

**Comment by chinedu40** [comment]
any eta on getting this merged?

**Comment by beltoft** [comment]
Still no ETA on this bugfix?

**Review by fwoelffel — COMMENTED** [review]
Looks good according to https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/update_commands_0.9.sed

However I haven't had the time to test these changes.

**Comment by xelgand** [comment]
I just updated my seedbox to rtorrent 0.9.7 and tested this branch.
The basic functionality of sending the torrent seems to be working, but I get this warning (debug level doesn't show anything else):

> 2019-04-21 12:59:21 WARNING SEARCHQUEUE-MANUAL-348545 :: Error while sending torrent: 'bool' object has no attribute 'set_custom'

And I notice the torrent doesn't come with the specific Label in rtorrent.

**Comment by flyingdan** [comment]
Just tested this branch as well. No issues to report, can this PR get merged into the master branch?

**Comment by miigotu** [comment]
Nope, it is incomplete and breaks support for older rtorrent implementations.

**Comment by xelgand** [comment]
Any way to help with this?

**Comment by WebSpider** [comment]
You could help with this for instance by finding a way to detect the rtorrent version and making the changes version dependant

**Comment by defhead** [comment]
@WebSpider  Well, one way to detect rtorrent version is to call "system.client_version" RPC method. It's already done when you "Test connection" on SickChill "Search Settings/Torrent Search" page.

For example: 
```
---DUMP---
<?xml version='1.0'?>
<methodCall>
<methodName>system.client_version</methodName>
<params>
</params>
</methodCall>

---END---
1566142055 scgi
---DUMP---
Status: 200 OK
Content-Type: text/xml
Content-Length: 152

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><string>0.9.7</string></value></param>
</params>
</methodResponse>

---END---
```

I've never worked with python, but is it possible to have multiple implementations and some kind of "factory" to use one of them?

**Comment by miigotu** [comment]
Yes, you can have both the old module and a new one.

**Comment by defhead** [comment]
I hope this "issue" is not abandoned

**Pull request closed without merging**
