### PR TITLE
Fix rpartition bug in replace_extension and remove_extension, using p…

### PR DESCRIPTION
**Pull request by miigotu**
@BKSteve I think I want to do it this way, rather than using older string manipulation methods. This way we can re-use functions for other purposes. Want to help test it this way?

### CODE REVIEW

**Comment by BKSteve** [comment]
Don't know how much I can help. I'll run a few files through the processor.
I've just done a couple of Anime - working
I'll do some rar files and normal shows.
Use your house example too.

**Comment by BKSteve** [comment]
Did a rar file and put a different name of ep in the rar file. Processed as rar filename and not as name of file in rar. (it did have full S01E05 and inside S01E04)
~~After processing the rar file, it removed the temporary folder things were extracted into but the rar still remained.~~

~~`srt` in rar and also with the mkv in the process folder are not being processed. They aren't being deleted with the move, but not recognised as they should based on config.~~
It works if you have the config set right. :stuck_out_tongue_winking_eye:

**Comment by BKSteve** [comment]
Process a file with name to fail.
If it's a solo file in the folder being process then the following doesn't happen, it only occurs when second file is in the folder to process.

```
2022-07-29 22:05:48 INFO :: POSTPROCESSOR-AUTO :: Processing /home/stephenr/TVShow/[GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P].mp4 (None)
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name [GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P].mp4
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: helpers remove groups NAME: [GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P]
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Trying to find ['['] on theTVDB
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Could not find item on the indexer: (Indexer probably does not have this item) [expected string or bytes-like object]
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/wrappers.py", line 25, in wrapper
    result = target(*args, **kwargs)
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/tvdb.py", line 110, in search
    if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
  File "/home/stephenr/Python-3.10.5/Lib/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Failed to find ['['] on theTVDB
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: There was a problem when attempting to find [ in SickChill. Error: 'NoneType' object has no attribute 'id'
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/oldbeard/helpers.py", line 901, in get_show
    showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AttributeError: 'NoneType' object has no attribute 'id'

2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Unable to match [GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P] to a show in your database. Parser result: [ -  [ABS: [2021]] [ANIME VER: -1] [GROUP: GM-Team] [ABD: False] [ANIME: True] [whichReg: ['anime_codec_crc']] Score: -4
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name TVShow
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: helpers remove groups NAME: TVShow
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Unable to match TVShow to a show in your database. Parser result:  [ABD: False] [ANIME: False] [whichReg: []] Score: 0
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name /home/stephenr/TVShow/[GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P].mp4
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: helpers remove groups NAME: /home/stephenr/TVShow/[GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P]
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Trying to find ['['] on theTVDB
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Could not find item on the indexer: (Indexer probably does not have this item) [expected string or bytes-like object]
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/wrappers.py", line 25, in wrapper
    result = target(*args, **kwargs)
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/tvdb.py", line 110, in search
    if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
  File "/home/stephenr/Python-3.10.5/Lib/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Failed to find ['['] on theTVDB
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: There was a problem when attempting to find [ in SickChill. Error: 'NoneType' object has no attribute 'id'
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/oldbeard/helpers.py", line 901, in get_show
    showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AttributeError: 'NoneType' object has no attribute 'id'

2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Unable to match /home/stephenr/TVShow/[GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P] to a show in your database. Parser result: [ -  [ABS: [2021]] [ANIME VER: -1] [GROUP: GM-Team] [ABD: False] [ANIME: True] [whichReg: ['anime_codec_crc']] Score: -4
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name TVShow [GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P].mp4
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: helpers remove groups NAME: TVShow [GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P]
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Trying to find ['tvshow [gm team][国漫][吞噬星空][swallowed star]['] on theTVDB
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Could not find item on the indexer: (Indexer probably does not have this item) [expected string or bytes-like object]
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/wrappers.py", line 25, in wrapper
    result = target(*args, **kwargs)
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/tvdb.py", line 110, in search
    if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
  File "/home/stephenr/Python-3.10.5/Lib/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Failed to find ['tvshow [gm team][国漫][吞噬星空][swallowed star]['] on theTVDB
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: There was a problem when attempting to find TVShow [GM-Team][国漫][吞噬星空][Swallowed Star][ in SickChill. Error: 'NoneType' object has no attribute 'id'
2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/oldbeard/helpers.py", line 901, in get_show
    showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AttributeError: 'NoneType' object has no attribute 'id'

2022-07-29 22:05:48 DEBUG :: POSTPROCESSOR-AUTO :: Unable to match TVShow [GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P] to a show in your database. Parser result: TVShow [GM-Team][国漫][吞噬星空][Swallowed Star][ -  [ABS: [2021]] [ANIME VER: -1] [ABD: False] [ANIME: True] [whichReg: ['anime_codec_crc']] Score: -4
2022-07-29 22:05:48 INFO :: POSTPROCESSOR-AUTO :: This show isn't in your list, you need to add it to SC before post-processing an episode
2022-07-29 22:05:48 WARNING :: POSTPROCESSOR-AUTO :: Processing failed for /home/stephenr/TVShow/[GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P].mp4: 
2022-07-29 22:05:48 WARNING :: POSTPROCESSOR-AUTO :: Processing Failed
2022-07-29 22:05:48 INFO :: POSTPROCESSOR-AUTO :: Some items were not processed.
2022-07-29 22:05:48 INFO :: POSTPROCESSOR-AUTO :: /home/stephenr/TVShow/[GM-Team][国漫][吞噬星空][Swallowed Star][2021][39][AVC][GB][1080P].mp4 : Processing failed: 
```

**Comment by miigotu** [comment]
Yeah the PR isn't quite ready, but those files are anime and shouldn't be parsed with thetvdb at all (they are supposed to fail) and the groups at the beginning have to be in the anime whitelist.

**Comment by BKSteve** [comment]
I'll have to spend some more time understanding the workflow.

Is it time for `guessit` or leave to later?

**Comment by miigotu** [comment]
Probably need to break guessit into a separate PR, maybe write an entirely brand new post processor, and allow people to choose between the old and new one for awhile so it can be tested.

All of the old threads are strapped by a decade of patches and quick fixes, and were written for python2. Postprocessing, search, backlog, everything. We should do one at a time, and allow people to choose the new version if they have debug and developer (or a new alpha/beta tester setting)

**Comment by BKSteve** [comment]
Noticed if a file has `[` after showname it doesn't get cleaned off.
Add `name.removesuffix("[")` to name cleaners instead of reworking the regexes. 

Add:
Still have `def poetry_install()` section in `init_helpers.py`

**Comment by BKSteve** [comment]
Did you change any access I can't push to SC from PyCharm anymore

**Comment by miigotu** [comment]
> Did you change any access I can't push to SC from PyCharm anymore

No, you probably did not set developer = yes in your config.ini, so when the updater ran in your clone it updated the origin from ssh to https.

**Comment by miigotu** [comment]
@BKSteve I think thos PR is ready btw, we are well on the way to using pathlib everywhere like I want to, which will clean up code ridiculously.

**Comment by BKSteve** [comment]
I'll run some basic checks and see if I can crash the processing.

**Comment by BKSteve** [comment]
I did a few tests on my Debian PyCharm install and processing `~/TVShow/House/S02E01.mkv` did not work.
The string `House S02E01.mkv` was never searched.
~~It didn't ever get to the `def _find_info(self)` in `postProcessor`~~ not part of initial analysis in file renaming.

Update:
Needs both `sub folder` and `sub folder + file name`

**Comment by BKSteve** [comment]
~~still can't get pycharm to push, set `developer` to 1 but it still says pending OAuth from SC.~~

Git credentials not properly linking b/w git and pycharm, installed GCM and fixed it

**Comment by BKSteve** [comment]
Last change has the follow test files and folders all processed.
```
./House.S02E03.mkv
./House/House.S02E04.mkv
./House/S02E06.mkv
./House S02E05/dumbname.mkv

./[GM-Team][国漫][吞噬星空] Swallowed Star 35 [AVC][GB][1080P].mkv
```

**Comment by BKSteve** [comment]
Would again like to propose the 2 lines of changes in #7981 with `Allow anime processing` push.
Devaluing the regex result when there is no name with -=20
And if the show is found in db and is anime id pass the show name into the `best result`

Add: tested 
```
./House/S02E07.mkv  [whichReg: ['standard']] Score: 5 using "House S02E07"
./[Judas] One Piece - 1015.mkv [whichReg: ['anime_bare']] Score: -13
```
processed both at the same time and both success.

**Comment by BKSteve** [comment]
loaded the changes to my DSM 7 VM and it connected, downloaded just like normal.
Processed a robot chicken from snatch to post processed. All good. Seems faster.

**Comment by miigotu** [comment]
> I did a few tests on my Debian PyCharm install and processing `~/TVShow/House/S02E01.mkv` did not work. The string `House S02E01.mkv` was never searched. ~It didn't ever get to the `def _find_info(self)` in `postProcessor`~ not part of initial analysis in file renaming.
> 
> Update: Needs both `sub folder` and `sub folder + file name`

Yes, if it's a file name like that it's already in the show folder, so the show folder name is used in conjunction with the file name. Working as intended, we have tests built for it 🙂

**Comment by BKSteve** [comment]
Just some info.
When post processing files that aren't named for regexes the post processor often hits theTVDB for the name.
This is when the filename has failed regexes and then the foldername added from the lambda.

```
2022-08-14 17:45:07 DEBUG :: POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2022-08-14 17:45:07 INFO :: POSTPROCESSOR :: Auto post processing task for /home/stephenr/TVShow was added to the queue
2022-08-14 17:45:09 INFO :: POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/stephenr/TVShow
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Processing in folder /home/stephenr/TVShow
2022-08-14 17:45:09 INFO :: POSTPROCESSOR-AUTO :: Processing /home/stephenr/TVShow
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder /home/stephenr/TVShow
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Found episode by absolute number 58 which is S03E12
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parsed [Hall_of_C] FanRenXiuXianZhuan_58.mkv into FanRenXiuXianZhuan - S03E12 [ABS: [58]] [ANIME VER: 1] [GROUP: Hall_of_C] [ABD: False] [ANIME: True] [whichReg: ['anime_bare']] Score: -13
2022-08-14 17:45:09 INFO :: POSTPROCESSOR-AUTO :: Processing /home/stephenr/TVShow/[Hall_of_C] FanRenXiuXianZhuan_58.mkv (None)
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name [Hall_of_C] FanRenXiuXianZhuan_58.mkv
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Using cached parse result for: [Hall_of_C] FanRenXiuXianZhuan_58
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result not sufficient (all following have to be set). will not save release name
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(series_name): FanRenXiuXianZhuan
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(season_number): None
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(episode_numbers): []
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO ::  or Parse result(air_date): None
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(release_group): Hall_of_C
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name TVShow
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Unable to match TVShow to a show in your database. Parser result:  [ABD: False] [ANIME: False] [whichReg: []] Score: 0
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name /home/stephenr/TVShow/[Hall_of_C] FanRenXiuXianZhuan_58.mkv
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Using cached parse result for: /home/stephenr/TVShow/[Hall_of_C] FanRenXiuXianZhuan_58
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result not sufficient (all following have to be set). will not save release name
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(series_name): FanRenXiuXianZhuan
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(season_number): None
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(episode_numbers): []
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO ::  or Parse result(air_date): None
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Parse result(release_group): Hall_of_C
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name TVShow [Hall_of_C] FanRenXiuXianZhuan_58.mkv
2022-08-14 17:45:09 DEBUG :: POSTPROCESSOR-AUTO :: Trying to find ['tvshow [hall of c] fanrenxiuxianzhuan'] on theTVDB
2022-08-14 17:45:24 DEBUG :: POSTPROCESSOR-AUTO :: Could not find item on the indexer: (Indexer probably does not have this item) [expected string or bytes-like object]
2022-08-14 17:45:24 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/wrappers.py", line 25, in wrapper
    result = target(*args, **kwargs)
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/show/indexers/tvdb.py", line 110, in search
    if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
  File "/home/stephenr/Python-3.10.5/Lib/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

2022-08-14 17:45:25 DEBUG :: POSTPROCESSOR-AUTO :: Failed to find ['tvshow [hall of c] fanrenxiuxianzhuan'] on theTVDB
2022-08-14 17:45:25 DEBUG :: POSTPROCESSOR-AUTO :: There was a problem when attempting to find TVShow [Hall of C] FanRenXiuXianZhuan in SickChill. Error: 'NoneType' object has no attribute 'id'
2022-08-14 17:45:25 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/home/stephenr/PycharmProjects/SickChill/sickchill/oldbeard/helpers.py", line 901, in get_show
    showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AttributeError: 'NoneType' object has no attribute 'id'

2022-08-14 17:45:25 DEBUG :: POSTPROCESSOR-AUTO :: Unable to match TVShow [Hall_of_C] FanRenXiuXianZhuan_58 to a show in your database. Parser result: TVShow [Hall of C] FanRenXiuXianZhuan -  [ABS: [58]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_bare']] Score: -13
2022-08-14 17:45:25 INFO :: POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
2022-08-14 17:45:25 WARNING :: POSTPROCESSOR-AUTO :: Processing failed for /home/stephenr/TVShow/[Hall_of_C] FanRenXiuXianZhuan_58.mkv: 
2022-08-14 17:45:25 WARNING :: POSTPROCESSOR-AUTO :: Processing Failed
2022-08-14 17:45:25 INFO :: POSTPROCESSOR-AUTO :: Some items were not processed.
2022-08-14 17:45:25 INFO :: POSTPROCESSOR-AUTO :: /home/stephenr/TVShow/[Hall_of_C] FanRenXiuXianZhuan_58.mkv : Processing failed: 
2022-08-14 17:45:25 INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for /home/stephenr/TVShow completed
```

**Comment by miigotu** [comment]
Echelon had that fallback to try indexers if we couldn't determine a release name way back in 2014. Maybe we should just fail there and not spam indexers? Its always been how we do it, and then we store that result in memory so we dont hit the indexers again in the name_cache

Do we need to check scene_names somewhere? I am not familiar with that anime or if that is in your show list or if thats an alternate scene name SC already knows or what?

**Comment by miigotu** [comment]
I fixed some of those tracebacks just now btw, in fe56fd0da8dc6f48973df1feabcdbe3461c87595

**Comment by BKSteve** [comment]
IMO when parsing a file in post processing it shouldn't hit tvdb at all. 
Definitely check scene names, which it does, when spelt correctly. 
I was testing an incorrectly named file to get the error and send it to tvdb.
The `lambda` should be inhibited from adding the default folder as prefix but haven't worked out how yet.

**Pull request merged**
