### PR TITLE
Fixes #2809

### LINKED ISSUE #2809: [APP SUBMITTED]: u'Name' is not in list
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@cc61b4cc955369d58354bc984cf119576f84b2fe
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-294417 :: [TorrentBytes] :: [cc61b4c] Exception while searching TorrentBytes. Error: ValueError("u'Name' is not in list",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by miigotu** [comment]
@sharkykh any idea why tests are failing all of a sudden?

**Comment by sharkykh** [comment]
Not a clue

**Comment by sharkykh** [comment]
@miigotu 
**Nyaa.si:** I think it's caused by the Cloudflare service.
I deleted then regenerated the test cassette for nyaa.si on my computer,
it recorded CF's `Checking your browser before accessing nyaa.si` page,
then a `503, Service Temporarily Unavailable` error.

Could be that Cloudflare changed their method, in that case we might be out of luck (the most updated cloudflare-scrape [now requires Node interpreter](https://github.com/Anorov/cloudflare-scrape#warning))
If that's not the case, I'm not sure what else to try.

**SkyTorrents:** Looks like the connection times out every time, even though it works locally for me (using a browser), maybe they blocked the CI's IP addresses?
I can't replicate this locally!

**LimeTorrents**: I'm guessing site error?
As this actually returns `200 None`: https://www.limetorrents.cc/searchrss/tv/Game%20of%20Thrones%20S05E08/
Looks like the RSS search is just broken.

**Comment by miigotu** [comment]
Disable them then I guess, by removing them from the import line.

**Pull request merged**
