### PR TITLE
Log the exception when starting the web server fails

### PR DESCRIPTION
**Pull request by NickMolloy**
Helps to solve confusion seen in #3528.

### CODE REVIEW

**Review by sharkykh — COMMENTED** [review]
I don't think Traceback is necessary in this case, should just display the error message.
```
15:46:59 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8082/
15:46:59 ERROR::TORNADO :: [1908114] Could not start webserver on port 8082: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
Traceback (most recent call last):
  File "C:\Github\SickRage-Dev\SickRage\sickbeard\webserveInit.py", line 150, in run
    xheaders=sickbeard.HANDLE_REVERSE_PROXY, protocol=protocol)
  File "C:\Github\SickRage-Dev\SickRage\lib\tornado\web.py", line 1850, in listen
    server.listen(port, address)
  File "C:\Github\SickRage-Dev\SickRage\lib\tornado\tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "C:\Github\SickRage-Dev\SickRage\lib\tornado\netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by NickMolloy** [comment]
It is not possible to log to Error and not have it print a traceback, so it will have to be logged to info (or maybe warning).

**Comment by sharkykh** [comment]
@NickMolloy I think that's fine, it was like this before too.

**Comment by sharkykh** [comment]
I might be picky, but if I'm honest,
I think we should still have that nice "already in use!" one.
It's simple and people would understand it better.

```diff
--- a/sickbeard/webserveInit.py
+++ b/sickbeard/webserveInit.py
@@ -5,6 +5,8 @@ from __future__ import print_function, unicode_literals
 import os
 import threading
 
+from socket import error as SocketError
+
 from tornado.ioloop import IOLoop
 from tornado.routes import route
 from tornado.web import Application, RedirectHandler, StaticFileHandler
@@ -148,10 +150,16 @@ class SRWebServer(threading.Thread):  # pylint: disable=too-many-instance-attrib
         try:
             self.server = self.app.listen(self.options['port'], self.options['host'], ssl_options=ssl_options,
                                           xheaders=sickbeard.HANDLE_REVERSE_PROXY, protocol=protocol)
+        except SocketError as ex:
+            if ex[0] == 10048:  # "Only one usage of each socket address (protocol/network address/port) is normally permitted"
+                if sickbeard.LAUNCH_BROWSER and not self.daemon:
+                    sickbeard.launchBrowser('https' if sickbeard.ENABLE_HTTPS else 'http', self.options['port'], sickbeard.WEB_ROOT)
+                    logger.log("Launching browser and exiting")
+                logger.log("Could not start webserver on port {0}, already in use!".format(self.options['port']))
+            else:
+                logger.log("Could not start webserver on port {0}: {1}".format(self.options['port'], ex))
+            os._exit(1)  # pylint: disable=protected-access
         except Exception as ex:
-            if sickbeard.LAUNCH_BROWSER and not self.daemon:
-                sickbeard.launchBrowser('https' if sickbeard.ENABLE_HTTPS else 'http', self.options['port'], sickbeard.WEB_ROOT)
-                logger.log("Launching browser and exiting")
             logger.log("Could not start webserver on port {0}: {1}".format(self.options['port'], ex))
             os._exit(1)  # pylint: disable=protected-access
 

```

**Comment by NickMolloy** [comment]
`if ex[0] == 10048` is not cross-platform.
For instance on Linux the equivalent error code is 98: `[Errno 98] Address already in use`.

**Comment by sharkykh** [comment]
Thank you for pointing that out.

**Review by sharkykh — APPROVED** [review]
I think we should still wait for @miigotu's approval.

**Comment by NickMolloy** [comment]
It seems instead of hardcoding the error code, [socket.errno](https://docs.python.org/2/library/errno.html#module-errno) can be used to do error code comparsions:

```
from socket import errno
...
except SocketError as ex:
    if ex.errno == errno.EADDRINUSE:
    ...
```

**Comment by sharkykh** [comment]
That works for me, do you want me to push this?

**Comment by NickMolloy** [comment]
Sure, sounds good.

**Review by miigotu — APPROVED** [review]

**Comment by miigotu** [comment]
@sharkykh there is an as ex in retrySearchSubtitles

**Comment by sharkykh** [comment]
@miigotu  Sorry, what?

**Comment by sharkykh** [comment]
If you're talking about the GitHub Exception, this isn't the same thing. 
Because webserve.py doesn't import anything 'as ex'.

**Comment by miigotu** [comment]
But it does import the ex function:
```python
from sickrage.helper.exceptions import CantRefreshShowException, CantUpdateShowException, ex
```

**Comment by sharkykh** [comment]
So I don't know what caused the error in #3585

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/commit/6e875d4977deb0b0a5af0b7e5c505451d08c1a05

**Comment by miigotu** [comment]
It was catching like `github.GithubException.RateLimitExceededException`, which doesnt exist

**Comment by sharkykh** [comment]
Oh so I imported the wrong module
damn lol

BTW
I don't think you need this line too now, https://github.com/SickRage/SickRage/commit/6e875d4977deb0b0a5af0b7e5c505451d08c1a05#diff-1716b2a4b5a6b712365fc5f089022831R40

**Pull request merged**
