### PR TITLE
Icon for CBS All Access

### LINKED ISSUE #4047: Missing Icon for CBS All Access
There is an icon missing for specific show namely CBS All Access.
The snow is named  Star Trek: Discovery http://www.imdb.com/title/tt5171438/.

### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

### PR DESCRIPTION
**Pull request by TurnrDev**
Fixes #4047 

Proposed changes in this pull request:
- Adds icon for CBS All Access

### CODE REVIEW

**Comment by TurnrDev** [comment]
For clarification, I looked at the files in the folder and found that they are all 64x32, which is super small. As the CBS All Access logo is mostly text with a fancy A in a box at the right side, I submitted the A as the logo, at the right dimensions. If this isn't clear enough, I can resubmit with a  CBS (eye) [A] dealeo

**Comment by OmgImAlexis** [comment]
I'd go for something like this https://image.roku.com/developer_channels/prod/d6e805dc84423422610b69a38da50813f9eb2143c85136931c6b66f9d59fe071.png

@miigotu can we larger images? I think we have a CSS constraint for the frontend to resize them anyways.

**Comment by TurnrDev** [comment]
@OmgImAlexis That's actually better! I can make that text CBS blue and the background transparent
@miigotu If I can put in larger images that are the 1:2 scale, I think it would be best to have them on a larger scale in terms of high-dpi displays etc especially as most the time people are viewing SickRage from a local machine so internet speed isn't an issue with load time. Willing to put a couple hours into upscaling these logos.

**Comment by miigotu** [comment]
I dont want to go much larger on the image sizes. Downscaling with js/css client side doesn't prevent a full size image from being transmitted.  If an image cache was built up in the backend to handle thumbnailing then it wouldnt be an issue, but for now I think leave them small?

**Comment by miigotu** [comment]
rebase please, on develop branch

**Comment by TurnrDev** [comment]
ngl I'm confused on what just happened

**Comment by miigotu** [comment]
You based your PR on the master branch, I changed it to merge into the develop branch where its supposed to go, and there are extra commits in it now.  Needs rebased on SickRage:develop

**Comment by miigotu** [comment]
repo deleted, I cant rebase it.

**Comment by TurnrDev** [comment]
Sorry about that.

**Pull request closed without merging**
