### PR TITLE
Fix notification to Plex via hostname

### PR DESCRIPTION
**Pull request by mpatton125**
Fixes #

Proposed changes in this pull request:
- Fix issue where notification to Plex via hostname (rather than IP) results in "401 - Unauthorized" error.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
This PR makes no sense to me, it works with both IP and with a hostname.

EDIT: Unless you mean by like `RasPlex.local` but idk

**Comment by mpatton125** [comment]
Hey there,

The problem turned out to be a small change on the Plex end that probably only affected my setup (our very few others).

I have fixed it via a minute config change (to plex), so no fault of SickRage. :)

I'll close the request.

Thanks!

M.

**Comment by miigotu** [comment]
NP, It might help someone if you noted the config change you made in plex here.

**Pull request closed without merging**
