### PR TITLE
Improve manual search table. SickChill/SickChill#6879

### PR DESCRIPTION
**Pull request by Nyaran**
Improve manual search table. SickChill/SickChill#6879
Proposed changes in this pull request:
 - Add filtering option
 - Stylize quality column
 - Improve sort order for quality column
 - Improve sort order for file size column

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
How familiar are you with webpack? I want to get rid of bower and just use yarn/webpack if possible but I keep failing 😥

**Comment by Nyaran** [comment]
> How familiar are you with webpack? I want to get rid of bower and just use yarn/webpack if possible but I keep failing disappointed_relieved

Never used it, but I can try it, let me read a bit about it

**Comment by Nyaran** [comment]
> > How familiar are you with webpack? I want to get rid of bower and just use yarn/webpack if possible but I keep failing disappointed_relieved
> 
> Never used it, but I can try it, let me read a bit about it

ok @miigotu I think now I understood a bit how webpack works. Do you have a branch on your personal fork with your current steps on this?

btw, if you prefer, we can create an "issue" about this task, so we can talk there about the migration and also, any other can join to help.

**Comment by miigotu** [comment]
@Nyaran sorry I did not answer sooner, but you can just create a feature branch and PR it, and we can discuss it on the PR page or discord

**Pull request merged**
