### PR TITLE
Make submodules to split up nzb and torrent providers

### PR DESCRIPTION
**Pull request by miigotu**
`R  sickrage/providers/NZBProvider.py -> sickrage/providers/nzb/NZBProvider.py`
`R  sickrage/providers/TorrentProvider.py -> sickrage/providers/torrent/TorrentProvider.py`

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
@MGaetan89 agree this is a good way to go?

**Comment by MGaetan89** [comment]
Yes, I'm fine with that.
But why put `GenericProvider`, `NZBProvider` and `TorrentProvider` in `__init__.py` instead of their own files?

**Comment by labrys** [comment]
@MGaetan89 lol thats what I said in IRC

**Comment by miigotu** [comment]
They can go in their own files, was just trying to separate them from the actual providers.
Mostly was interested in the separate dirs

**Comment by MGaetan89** [comment]
Why not move `NZBProvider` in `sickrage/providers/nzb` and `TorrentProvider` in `sickrage/providers/torrent`?
Splitting the directories is a good idea.

**Comment by miigotu** [comment]
`from sickrage.providers.torrent.TorrentProvider import TorrentProvider` is ridic lol

**Comment by labrys** [comment]
@miigotu no you put TorrentProvider in the init as the interface so it would be 
from sickrage.providers.torrent import TorrentProvider

**Pull request merged**
