### PR TITLE
Add "Scrambled" to removeWordsList

### PR DESCRIPTION
**Pull request by Aikurn**
Add the suffix "Scrambled" to the remove words list as it has become popular on Usenet files.

Proposed changes in this pull request:
- Add a new suffix to removeWordsList

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Isnt that a release group?

**Comment by Aikurn** [comment]
I don't think so. But who knows with group names these days. I haven't found any release claimed by a group "Scrambled". It's being used to replace the other popular Usenet suffix "Obfuscated". A quick search on NZBGeek shows hundreds of recent uploads with this word appended.

**Comment by miigotu** [comment]
Ok, =P

**Pull request merged**
