### PR TITLE
feat: Slack Icon options

### PR DESCRIPTION
**Pull request by chronicrebellion**
**Slack Config**
slack config

**Slack Test Message**
test message

Proposed changes in this pull request:
- Default SC png as the icon for slack messages
- Allows custom emoji icons for slack notifications
Reference: https://api.slack.com/custom-integrations/incoming-webhooks

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by chronicrebellion** [comment]
@miigotu just wondering if there were any tests I should update or if this is satisfactory?

**Comment by miigotu** [comment]
Why not just send the SC icon like it's supposed to?

**Comment by chronicrebellion** [comment]
I was considering using: https://github.com/SickChill/SickChill/blob/master/gui/slick/images/sickchill-sc.png

I was not sure if this was going to change or not, I did notice that in the sickchill subreddit that there was talk about getting a new logo.

I thought people might want to have a custom icon :)

If we wanted to just allow only custom icon with emoji, I can just set the url to the SC png so it would be the default icon. If no emoji is set, then the url icon will show up.

If you think just using SC is the way to go I can totally do that as well... just let me know!

**Comment by miigotu** [comment]
Yes I think url icon from that url as the default is best, and probably do not need the emoji but you already added it so let that be an override.

**Comment by chronicrebellion** [comment]
> Yes I think url icon from that url as the default is best, and probably do not need the emoji but you already added it so let that be an override.

@miigotu I have updated the PR to default to the SC icon and allowing users to provide a custom emoji icon (screenshots updated above)

**Pull request merged**
