### PR TITLE
Don't delete .stfolder

### LINKED ISSUE #3518: Syncthing problem
Hi

I'm on Windows 10, last commit on master branch. 

I use syncthing to get my TV shows. When an episode is finish, it download the episode to D:/finish/TVShows/

It create a file name .Stfolder

I use sickrage to post process this folder, it work well. 

The only problem is sickrage delete my .stfolder file so syncthing stop sync. 

How do I prevent sickrage from deleting .Stfolder ?

I try to set this file read-only, I try to change postprocessTV.py but nothing work. 

Any idea ??

Thank

### PR DESCRIPTION
**Pull request by sharkykh**
Fixes #3518

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
I really want to finish that post processing PR... What we have right now is not good, but also the PR isnt ready I think.

**Comment by sharkykh** [comment]
I can't really help with that :/

IMO, it would be much easier if we had tests for post processing, but I'm not sure how to set it up.
With all of the file and nameparser functions it needs to do.

**Comment by miigotu** [comment]
First we need one of each: a tiny mp4, wmv, mkv, torrent, nzb

From that test data we can make zips, nzb's, pp structures, etc for testing.
Its not too difficult.  Someday soon hopefully ill get some time to do this.

**Comment by miigotu** [comment]
Why revert that? Im sure it didnt break anything either way but the var isnt used also.

**Comment by sharkykh** [comment]
I think it does.
I think it interferes with [`from sickrage.helper.exceptions import ex`](https://github.com/sharkykh/SickRage/blob/0ba7a39505979487cb65cc80829a4806f7b52ebc/sickbeard/logger.py#L50)

I moved it into #3586 that's why I reverted it.

**Comment by miigotu** [comment]
I see...

**Pull request merged**
