### PR TITLE
Whitespace fix

### LINKED ISSUE #1591: Responsive UI
Pass one: (Initial responsiveness)
 - done

Pass two:
 - [ ] Login
 - [x] Api builder
 - [ ] Home
 - [ ] Show
 - [ ] Show edit
 - [ ] Show rename
 - [ ] Add show
 - [ ] Add new show (needs rewrite)
 - [ ] Add new show Trakt
 - [ ] Add new show IMBD
 - [ ] Add existing show
 - [ ] Manual post-process
 - [ ] Schedule
 - [ ] History
 - [ ] Mass update table
 - [ ] Mass update
 - [ ] Backlog overview
 - [ ] Manage searches
 - [ ] Episode Status Management
 - [ ] Manage torrents
 - [ ] Failed downloads
 - [ ] Help & Info
 - [ ] Config general
 - [ ] Config backup/restore
 - [ ] Config search
 - [ ] Config providers
 - [ ] Config subtitles
 - [ ] Config post processing
 - [ ] Config notifications
 - [ ] Config anime
 - [ ] News
 - [ ] IRC
 - [ ] Changelog
 - [ ] Error log
 - [ ] Log
 - [ ] Server status
 - [ ] 404 error
 - [ ] 500 error
 - [ ] Anime Subgroup picker
 - [ ] Quality picker
 - [ ] Show options
 - [ ] Root directory selector
 - [ ] uniform config look (position checkboxes etc.)

To be edited:
 - Mass update should use POST instead of GET
 - Give the subtitle providers page the same look as search providers

### PR DESCRIPTION
**Pull request by beschoenen**
Fixes #1591 s whitespace issue

welp, sorry the line endings have changed again.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
This is still adding tabs instead of spaces, and CRLF instead of LF. What editor are you using? We have an editorconfig that most ide/editors suitable for mixed languages support http://editorconfig.org/

**Comment by beschoenen** [comment]
@miigotu That should fix it.
My git global config forces CRLF line endings, so that was the problem. And I guess my Intellij config was overriding the `.editconfig` file.

**Comment by beschoenen** [comment]
@neoatomic Better? :D

Should I just reverse the menu items? Or should they be in any particular order?

**Pull request merged**
