### PR TITLE
add filter to manage

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by fernandog** [comment]
http://feathub.com/SickRage/SickRage/+291

@syrys

**Comment by syrys** [comment]
@OmgImAlexis  @fernandog not sure if the featurehub comments alert you, but there is a slight bug/issue on the implementation, check the last comment on featurehub. but thanks so much for the feature.

**Comment by labrys** [comment]
@syrys They are Y or N.  We're looking at implementing tooltips to make this more clear.

**Comment by syrys** [comment]
@labrys ahhh, awesome. i tried yes/no, true/false, but didnt think to try y/n.

I think the dropdown solves the problem much better than having tool tips doesnt it? Probably a lot simpler to implement too :P

**Comment by syrys** [comment]
also might be related to this update, but the bottom right submit button is no longer working, the top one works fine. Not a big deal, but confused me a bit just earlier till i realized that there is now a submit button at the top.

**Comment by OmgImAlexis** [comment]
The bottom one "should" be working. :disappointed: Open an issue for this please.

**Comment by OmgImAlexis** [comment]
Also a dropdown would just clutter the page and really can't be added because of the way the table is generated.

**Pull request merged**
