### PR TITLE
Clients qbittorrent api2+

### PR DESCRIPTION
**Pull request by lulandco**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by lulandco** [comment]
Hi,
Sorry but I don't figure out to base my topic branch on my develop branch. I've red a lot of tuto and the FAQ but it does'nt work. My default branch is developp. My topic branch is made from my develop branch but it seems always based on the master branch (commits are seen ahead from the master branch). So when I do a PR it is rejected. What is my misunderstanding ? Do I have to only use the git cli ?

**Comment by labrys** [comment]
Just do an interactive rebase and fix your commits... for example all those merges dont need to be there.  Follow the guide in contributing.md.

**Comment by labrys** [comment]
@lulandco You don't need to close and reopen the PRs just fix and force push it back up your branch.  Another day I'll talk you through some of it if I have the time, but that may be a while with the holidays coming up.

**Pull request closed without merging**
