### PR TITLE
Fixes SickRage/sickrage-issues#113

### PR DESCRIPTION
**Pull request by labrys**
Fixes SickRage/sickrage-issues#113

### CODE REVIEW

**Comment by fernandog** [comment]
@labrys
Why not logger.ERROR so user can submit?

**Comment by labrys** [comment]
Because a None type object isn't really an error, it's invalid input.  Basically for the same reason that we downgraded SickRage/sickrage-issues#53 SickRage/sickrage-issues#54 SickRage/sickrage-issues#55 to a debug statement.

**Comment by fernandog** [comment]
Ah ok!

**Comment by labrys** [comment]
Ideally adba would gracefully handle a None type object and return a None, but that's not what happens.  We could plausibly raise an issue-request to their repository, but it may be their intended design.

**Comment by fernandog** [comment]
can't remember that last time we updated adba.... lol

**Pull request merged**
