### PR TITLE
New provider : Elite Tracker

### PR DESCRIPTION
**Pull request by barraudf**
Fixes nothing

Proposed changes in this pull request:
- New french provider ( https://elite-tracker.net/ )

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by barraudf** [comment]
I don't know what's failing, If anybody has a clue please?

**Comment by barraudf** [comment]
So this is correctly ordered :

```
(abnormal, alpharatio, archetorrent, binsearch, bitcannon, btn, cpasbien, danishbits, elitetorrent, filelist, gftracker,
hd4free, hdbits, hdspace, hdtorrents, hdtorrents_it, horriblesubs, hounddawgs, ilcorsaronero, immortalseed, iptorrents,
limetorrents, morethantv, ncore, nebulance, newpct, norbits, nyaa, omgwtfnzbs, pretome, rarbg, scc, scenetime, shazbat,
skytorrents, speedcd, thepiratebay, tntvillage, tokyotoshokan, torrent9, torrentbytes, torrentday, torrentleech,
torrentproject, torrentz, tvchaosuk, xthor)
```

And this is not :
```
(abnormal, alpharatio, archetorrent, binsearch, bitcannon, btn, cpasbien, danishbits, elitetorrent, elitetrackerfr, filelist, gftracker,
hd4free, hdbits, hdspace, hdtorrents, hdtorrents_it, horriblesubs, hounddawgs, ilcorsaronero, immortalseed, iptorrents,
limetorrents, morethantv, ncore, nebulance, newpct, norbits, nyaa, omgwtfnzbs, pretome, rarbg, scc, scenetime, shazbat,
skytorrents, speedcd, thepiratebay, tntvillage, tokyotoshokan, torrent9, torrentbytes, torrentday, torrentleech,
torrentproject, torrentz, tvchaosuk, xthor)
```

(from [the travis CI log, line 359](https://travis-ci.org/SickRage/SickRage/builds/269342204#L359))
???

cc @sharkykh please

**Comment by sharkykh** [comment]
@barraudf Line length of 160 characters is probably exceeded.

**Comment by barraudf** [comment]
Ok, thank you for pointing me out!

**Comment by barraudf** [comment]
I'll submit a new PR with a single commit

**Comment by AlexMihe** [comment]
Could someone re-open this pull request?

Thank you!

**Comment by barraudf** [comment]
@AlexMihe another pull request had been opened (see #4013 ), but it hasn't been merged then and now it fails at automated checks

**Pull request closed without merging**
