### PR TITLE
Discusion 8149

### PR DESCRIPTION
**Pull request by ghost**
Fixes [#8149](https://github.com/SickChill/SickChill/discussions/8149)
Proposed changes in this pull request:
- FIxes 404 error when clicking on `Checkout Branch` in view config -> General -> Advanced Settings -> GitHub
- N.B: there is a mako error from master to develop atm

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
It probably needs sc_root, not default page, I could be wrong. I'll try and take a look later

**Comment by kyuuk** [comment]
yes `settings.DEFAULT_page` may be something other than `home` it can be changed on `/config/general/`, will that still work ?

**Comment by ghost** [comment]
> yes `settings.DEFAULT_page` may be something other than `home` it can be changer on `/config/general/`, will that still work ?

I missed `Initial page` setting.
Seems to work now, also tested with web_root for reverse proxy configuration.

Still redirect to /undefined/ from this branch or develop to master or SickChill-rage, so it does not fix issues when js variables are modified

image

Fine from this branch to develop

**Comment by miigotu** [comment]
This code has been removed altogether, so this isnt needed anymore. Thanks.

**Pull request closed without merging**
