### PR TITLE
Fix responsive style

### PR DESCRIPTION
**Pull request by kingmotley**
Fixes #
## 
## 
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
@beschoenen should this be merged? I have no clue what it changes, since the OP didnt tell us anything in the PR.

**Comment by Arcanemagus** [comment]
It's also 6 commits for 3 lines of code :stuck_out_tongue:.

**Comment by kingmotley** [comment]
Sorry, it was just a quick fix to the responsive style on the show page.

**Comment by miigotu** [comment]
@Arcanemagus number of commits doesnt matter anymore since github now has a "squash and merge" option.

@kingmotley that comment still doesnt tell me what it changes about the show page or what was broken. We tested the responsive ui for 2 weeks and no-one had any issues with it so you need to be more specific.

**Comment by kingmotley** [comment]
untitled

The next/prev arrows break bad around the show dropdown.

**Comment by kingmotley** [comment]
Feel free to close/reject this PR.  My quick fix doesn't fully fix it, just partially.

**Comment by beschoenen** [comment]
I'll try to work on a "better" solution this weekend.

**Comment by miigotu** [comment]
@kingmotley thanks for pointing out the problem, i'll close this and let @beschoenen handle it since he is the one doing most of the responsive-ui.

**Comment by kingmotley** [comment]
Feel free to look at my develop branch which fixes it much better. https://github.com/SickRage/SickRage/compare/master...kingmotley:develop

**Pull request closed without merging**
