### PR TITLE
Update torrent9.py

### PR DESCRIPTION
**Pull request by Hoskar2ben**
Fixes #

Proposed changes in this pull request:
-
-
-

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Kubilai12** [comment]
i Change the line on my file but nothing happens, i still can t dowload something from Torrent9

**Comment by TristBella** [comment]
> i Change the line on my file but nothing happens, i still can t dowload something from Torrent9

Torrent9 is no longer working. Nothing sickchill does will work.
https://torrentfreak.com/torrent9s-disappearing-downloads-boosted-vpn-referrals-181120/

**Comment by Hoskar2ben** [comment]
Torrent9 changed .ph in .ch.

The site in the link is a fake torrent9

**Comment by miigotu** [comment]
Torrent.ph works here, and this build is failing. What is the status?

**Comment by Kubilai12** [comment]
Im not a developper just a simple user, so Hoskar2Ben when you change line on torrent9.py is it running for you ?

**Comment by pluzun** [comment]
@miigotu, .ph does not work: there is a banner showing that there is no torrent links anymore.
Like I said here #5190, .ch is a fake site. I'm looking for the new one, but I don't think it exists...

**Comment by Kubilai12** [comment]
@pluzun it's exist lok here https://www.torrent9.ch/ 

I can download manually but for moment Sichill can'tdownload on it

**Comment by Kubilai12** [comment]
Hi 

I did the update and i have this error message : 

> `2018-11-24 17:28:20 SEARCHQUEUE-MANUAL-295759 :: [Torrent9] :: [43ec1dd] Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies. ()`

**Comment by miigotu** [comment]
So follow the directions...

**Comment by Kubilai12** [comment]
yep it s ok now thanks and sorry

**Comment by Kubilai12** [comment]
It s seem torrent9 change again now i have redirect adresse to https://www.torrents9.pw

Other person can confirm it s the good one ?

**Pull request closed without merging**
