### PR TITLE
Enhance show search

### PR DESCRIPTION
**Pull request by VinceVal**
- If term contains a leading article, remove it.
- If there is a trailing year, enclose it in ().

### CODE REVIEW

**Comment by VinceVal** [comment]
@miigotu thoughts?

**Comment by fernandog** [comment]
Why not search with and without year? The show name in the another language may not have the year.

**Comment by OmgImAlexis** [comment]
@fernandog we don't really support anything but English so I'm not really sure how this will break anything?

**Comment by fernandog** [comment]
Cant you choose language while adding show?

**Comment by OmgImAlexis** [comment]
"\* This will only affect the language of the retrieved metadata file contents and episode filenames.
This DOES NOT allow SickRage to download non-english TV episodes!"

So this shouldn't effect anything like that.

**Comment by fernandog** [comment]
What are you talking about?!
Im saying the Show name!
In english: The Blacklist (2014)
In french: Blacklist

Just an example

**Comment by duramato** [comment]
@OmgImAlexis you are wrong it searches in the title that is in that language ,I've found myself having to add a scene exception with the English title because it searched the title in PT ..

**Comment by miigotu** [comment]
I think it should be done a little different. It should first search for the inputted string as is, and if no results but contains a|an|the or \d{4}$ search again with the string fixed. Otherwise you will have shows you wouldnt be able to find anymore. Ex: Mystery Science Theater 3000

**Comment by VinceVal** [comment]
Hmm, I think there is some confusion here. It actually creates a list of multiple search terms and searches for all of them. It still searches for exactly what you typed also. Per @miigotu I'll add 'a' and 'an'.

**Comment by miigotu** [comment]
looks great!

**Comment by miigotu** [comment]
Not so concerned with waiting for a squash on this one, just gonna merge it =P

**Pull request merged**
