### PR TITLE
Update extratorrent.py

### PR DESCRIPTION
**Pull request by ShiiroSan**
Fixes #

Proposed changes in this pull request:
- Changed URL

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by snowwing** [comment]
Why has this changed? extratorrent.cc is still the official domain as far as I am aware and extra.to is just a mirror.

**Comment by ShiiroSan** [comment]
extratorrent.cc got DDoS-attacked for several days. Seems to be over know. I don't Python enough to make it but it could be interesting to use the mirror link if main link isn't working.

**Comment by miigotu** [comment]
It was down for a few days, feel free to PR it back to the official domain.

**Pull request merged**
