### PR TITLE
Change log size in UI to MB not bytes

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
You would have to also correct it when loading config in sickbeard.**init**.py, or people are going to have gigabyte plus log files =P

**Comment by fernandog** [comment]
@miigotu like this? if is ok I will squash

**Comment by miigotu** [comment]
Nope, it needs done on boot in `__init__`, exactly where I said, or users with pre-existing config.ini will end up with log files up to 1048576MB (10GB)

**Comment by labrys** [comment]
How about leave the config unchanged and instead divide by 1048576 for the UI display?

**Comment by fernandog** [comment]
@miigotu done

**Comment by miigotu** [comment]
@labrys either way works ofc.

**Comment by labrys** [comment]
@miigotu True but leaving the config unchanged and changing the UI has the added benefit that its less likely to cause an issue like you mentioned with 10GB logs.

**Pull request merged**
