### PR TITLE
fixed restart.js not reloading after restart

### PR DESCRIPTION
**Pull request by miigotu**
Replaces #830

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
You needed `git rebase -i upstream/develop` there were several conflicts.

**Comment by OmgImAlexis** [comment]
That's exactly what I tried and it rebased but changed nothing.

**Comment by miigotu** [comment]
Oddly, vender.min.js was changed in the other Pr but not this one. Was there supposed to be vendor changes?

**Comment by OmgImAlexis** [comment]
Nope. They should be the same. We've had this issue before with other devs changing stuff and not running grunt. That may have been why.

I'll look at getting travis to update our min.js files soon.

**Pull request merged**
