### PR TITLE
Add nzbindex and nzbfriends providers

### PR DESCRIPTION
**Pull request by Comptezero**
backported from https://github.com/cytec/SickRage

### CODE REVIEW

**Comment by miigotu** [comment]
Both of these are in the wrong format for SickRage. CopyPasta doesn't work with SR anymore.

**Comment by mcarbonneaux** [comment]
what the good format ?

**Comment by miigotu** [comment]
the same as all of our other providers...

**Comment by labrys** [comment]
@Comptezero do you plan on updating this to the new format?

**Comment by miigotu** [comment]
@labrys I just left this open to remind me and be able to use it as a reference, it is based on master ^

**Comment by miigotu** [comment]
nzbindex rss no longer works, and nzbfriends is random on what words in the q term it uses and is not giving proper nzb names. I have an nzbfriends provider here that may work better in the future.

**Comment by noodle-** [comment]
Just wanted to mention that nzbindex + rss is working smoothly now. No more 503's!

I'll try to tinker with the provider script if nobody else has made one by next week.

**Pull request closed without merging**
