### PR TITLE
Try to fix new tag message

### PR DESCRIPTION
**Pull request by sharkykh**
**Untested** - just copied from the `_genchanges` task
Supposed to fix tag messages being like https://github.com/SickRage/SickRage/releases/tag/v2017.03.24-2

But it probably needs more work, because it's **not supposed to be the title of the tag**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Review by miigotu — APPROVED** [review]
Looks correct to me!

**Comment by miigotu** [comment]
I checked it after the last commit, seems to be correct =P

**Comment by sharkykh** [comment]
:)

**Pull request merged**
