### PR TITLE
Fix ygg url

### PR DESCRIPTION
**Pull request by pluzun**
Fixes #

Proposed changes in this pull request:
- Fix YGG url
- Replace the "2184" sub category to "all" because anime are not set in the good category in ygg, so they never match...

- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
?

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/blob/master/sickbeard/providers/yggtorrent.py#L150

**Comment by pluzun** [comment]
Hey, 
I need to rebase first from master before make this PR again, i'm still before the SickChill rename.
The problem with the subcategory 2179 is that sometime, the upload don't set the subcategory when he uploads an anime. So torrents never matche... Set the subcategory to "all" fix the problem.

**Comment by pluzun** [comment]
Hey, 
I need to rebase first from master before make this PR again, i'm still before the SickChill rename.
The problem with the subcategory 2179 is that sometime, the upload don't set the subcategory when he uploads an anime. So torrents never matche... Set the subcategory to "all" fix the problem.

**Pull request closed without merging**
