### PR TITLE
Add "Total Disk Usage" to main page footer

### PR DESCRIPTION
**Pull request by Amadeus-**
I found myself wondering the total disk usage by SR, and thought it would be a nice feature to have included in the webUI "footer".    It turns out that it was a VERY easy thing to add (and I think the additional data added to Show.overall_stats() might be useful in the future anyway.)

Here is a screenshot of how it looks:  http://bit.ly/1ZtcSuy

I'm happy to change the label from "Total Disk Usage" to something else, but I couldn't think of anything better to use.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by Amadeus-** [comment]
It seems I made it too simple! :)   Sorry, I need to take into account episodes that were deleted/archived/etc.    So, closing this PR.    I will submit a new PR when it's ready.

**Comment by fernandog** [comment]
Did you see server status page? It shows size of shows folder

**Comment by Amadeus-** [comment]
Actually, it shows the free space, not the usage :)

I have it done now.  But, before doing another PR, I was going to try and fix the bug on the main page where it shows the size of files marked as archived or downloaded....even if they were manually deleted from the disk.

**Pull request closed without merging**
