### PR TITLE
Add ability to change logs folder

### PR DESCRIPTION
**Pull request by kyuuk**
Proposed changes in this pull request:
- add a field to change settings.LOG_DIR 

also i had to add things in the gui, so i have a dumb question : how do i update the locales files *.po ?

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by miigotu** [comment]
You'll need to rebase and run grunt again, to fix the conflict

**Comment by miigotu** [comment]
I'll check this out, and maybe change it a bit to use pathlib instead of os.path since I want to sort of do that everywhere.

**Comment by miigotu** [comment]
Also, you don't edit the po files or translations manually. They are extracted and uploaded to crowdin automatically by the crowdin integration and crowdin is supposed to create a PR for it back into the repo. The integration might currently be broken, but soon the whole release process is going to be redone (grunt won't be doing release or changelog or translations)

**Comment by kyuuk** [comment]
well i've been trying for 2h to make this work  😆 
```
:~/sickchill $ poe update_translations
Poe => pybabel extract --project=sickchill --mapping-file=.github/babel-mapping.cfg --width=80 --charset=utf-8 --output-file=sickchill/locale/messages.pot --input-dirs=sickchill --keywords=_n:1,2 --copyright-holder=SickChill --msgid-bugs-address=miigotu@gmail.com --add-comments=TRANSLATORS: --sort-output
extracting messages from sickchill/__init__.py
extracting messages from sickchill/certgen.py
extracting messages from sickchill/init_helpers.py
extracting messages from sickchill/logger.py
extracting messages from sickchill/movies.py
extracting messages from sickchill/settings.py
extracting messages from sickchill/show_updater.py
Traceback (most recent call last):
  File "/home/kyuk/sickchill/.venv/bin/pybabel", line 8, in <module>
    sys.exit(main())
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/frontend.py", line 1031, in main
    return CommandLineInterface().run(sys.argv)
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/frontend.py", line 955, in run
    return cmdinst.run()
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/frontend.py", line 521, in run
    for filename, lineno, message, comments, context in extracted:
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/extract.py", line 165, in extract_from_dir
    yield from check_and_call_extract_file(
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/extract.py", line 222, in check_and_call_extract_file
    for message_tuple in extract_from_file(
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/extract.py", line 258, in extract_from_file
    return list(extract(method, fileobj, keywords, comment_tags,
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/extract.py", line 340, in extract
    for lineno, funcname, messages, comments in results:
  File "/home/kyuk/sickchill/.venv/lib/python3.9/site-packages/babel/messages/extract.py", line 496, in extract_python
    value = eval(code, {'__builtins__': {}}, {})
  File "<string>", line 2, in <module>
NameError: name 'str' is not defined
Error: Sequence aborted after failed subtask 'babel_extract'
```

so i'll keep this PR as draft until you're ready to use pathlib

**Comment by miigotu** [comment]
Still some issues with this, crowdin-cli-py has a bug also.

**Comment by miigotu** [comment]
There's more missing parameter names in the str format changes, I did changes in bulk and haven't gone over every line of it manually yet.

**Comment by miigotu** [comment]
For the pathlib, I'd like to change DATA_DIR to a Path, then it becomes `settings.DATA_DIR / logdir`

But that is going to bring a ton of changes I think lol

**Comment by kyuuk** [comment]
> There's more missing parameter names in the str format changes, I did changes in bulk and haven't gone over every line of it manually yet.

oh i thought i checked them xD

**Comment by kyuuk** [comment]
> For the pathlib, I'd like to change DATA_DIR to a Path, then it becomes `settings.DATA_DIR / logdir`
> 
> But that is going to bring a ton of changes I think lol

About this i was thinking of creating a new branch to do a big refactor & get rid of all `os.path` but that will take time 😣 
What do you think ?

**Comment by miigotu** [comment]
Need to run `poe format` on this and commit changes. Then check the build.

**Comment by miigotu** [comment]
> > For the pathlib, I'd like to change DATA_DIR to a Path, then it becomes `settings.DATA_DIR / logdir`
> > But that is going to bring a ton of changes I think lol
> 
> About this i was thinking of creating a new branch to do a big refactor & get rid of all `os.path` but that will take time 😣 What do you think ?

Yes I agree. Probably revert the pathlib commits on this branch, because the string format changes are already muddying the purpose of this PR.

**Comment by kyuuk** [comment]
i reverted the commit, i'll create a branch and a draft PR so we can discuss how to do this :)

**Comment by kyuuk** [comment]
> There's more missing parameter names in the str format changes, I did changes in bulk and haven't gone over every line of it manually yet.

i just tried fixing it all, i hope i didn't miss any

**Comment by ghost** [comment]
I noticed this seems to break add shows on develop, with Indexer "theTVDB", works when "All indexers" is selected:

https://github.com/SickChill/SickChill/blob/f0a1d8e2d51cda3211725fbd29dd4eec344720d4/sickchill/views/manage/add_shows.py#L64-L69

Console:
```
2022-09-19 11:42:06 INFO :: WEBSERVER-ADDSHOWS_0 :: A mako error occurred: 'NoneType' object has no attribute 'name'
```
Ui:
search timed out, try again or try another indexer

**Comment by miigotu** [comment]
I'll try to take a look soon. I spent all night trying to get python-semantic-release working 😭 (and ofc I got sidetracked a bunch of times)

**Comment by miigotu** [comment]
I actually want to move that logic out of there and into the indexer handler, it makes more sense to be there.

Indexers handler needs either rewritten again (my last attempt kind of sucks) or add tvmaze

**Comment by miigotu** [comment]
913d0b95d

**Pull request merged**
