### PR TITLE
Try to fix SickRage/sickrage-issues/issues/504

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu is it ok 3 digits for absolute number ? `E%03d`

in the future we need a helper to check this info. Maybe passing the showObj

season or scene_season
episode or scene_episode
absoute_number or scene_absolute_number

to display all info correctly in UI and logs

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Except that doesnt fix anything. Anything which has an absolute number gets converted to season/ep in the indexer lookup.

This PR results in the ep not showing up at all.

**Comment by fernandog** [comment]
so `epCats['S%02dE%02d' % (curResult['season'] or 0, curResult['episode'] or 0 )] = curEpCat`

**Comment by miigotu** [comment]
No. They should never make it in without season and ep to begin with.

**Comment by labrys** [comment]
@fernandog guessit2 will help with this a lot.  it will also give us the ability to do episode title matching so we can verify that the numbering is correct.

**Pull request closed without merging**
