### PR TITLE
Warn about SSL error instead of raise error

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu updated code

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@miigotu @labrys 

```2015-07-26 12:55:06 WARNING SEARCHQUEUE-MANUAL-SEARCH :: URL error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590) while loading URL https://<redacted>```

I find re.sub wont work.
can't we do match instead?

**Comment by fernandog** [comment]
@miigotu what about now

**Comment by miigotu** [comment]
Nope, wont work

**Comment by fernandog** [comment]
@miigotu why? What I missed?

**Comment by fernandog** [comment]
@miigotu why? What I missed?

**Comment by fernandog** [comment]
@miigotu rebased/squashed

**Pull request merged**
