### PR TITLE
Fix Javascript on Safari

### PR DESCRIPTION
**Pull request by beschoenen**
Fixes JS errors in Safari

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@sharkykh is there anything we still use those hidden fields for?

**Comment by beschoenen** [comment]
@OmgImAlexis They have no `name` nor `value` attribute, so my guess is no.

**Comment by sharkykh** [comment]
They are still being used, as [plot tooltip is now broken](https://user-images.githubusercontent.com/10238474/29489803-d5131ddc-8531-11e7-8444-59d1628dcabb.png).
A search of `#srRoot` in `gui/slick/js` revealed the following,
so I'm guessing scene exceptions tooltip and manual episode search are broken as well.

1. https://github.com/SickRage/SickRage/blob/1fb932804c803040f5b6429431b985cfc5f94499/gui/slick/js/core.js#L2469
2. https://github.com/SickRage/SickRage/blob/1fb932804c803040f5b6429431b985cfc5f94499/gui/slick/js/core.js#L3671
3. https://github.com/SickRage/SickRage/blob/1fb932804c803040f5b6429431b985cfc5f94499/gui/slick/js/core.js#L3675
4. https://github.com/SickRage/SickRage/blob/1fb932804c803040f5b6429431b985cfc5f94499/gui/slick/js/plotTooltip.js#L8
5. https://github.com/SickRage/SickRage/blob/1fb932804c803040f5b6429431b985cfc5f94499/gui/slick/js/sceneExceptionsTooltip.js#L8

Also, @beschoenen 
> They have no name nor value attribute, so my guess is no.

All three deleted fields had both `id` and `value` attributes...

**Comment by beschoenen** [comment]
@sharkykh The value was always empty after rendering. That's what I meant.

**Comment by sharkykh** [comment]
@beschoenen Oh, okay. That's because you probably don't use the `web_root` config var.

**Pull request merged**
