### PR TITLE
Export LANG* env vars in runfiles to help avoid locales issues

### PR DESCRIPTION
**Pull request by Twanislas**
Hi !

I added this to fix locales issues in my FreeNAS box and it worked well. Thought I'd share it with others... :)

Cheers !
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
What happens with people wanting another language than English? Pretty sure this is why it's currently not set this way.

**Comment by Twanislas** [comment]
Hi OmgImAlexis :)

I guess not everyone on earth is a native English speaker... Or maybe they want to download shows for their relatives who don't speak English and have the metadata + file names in their own language ?

**Comment by OmgImAlexis** [comment]
That's what I'm saying, I think that's why we currently don't specifically set it in the init scripts. @miigotu correct?

**Comment by Twanislas** [comment]
Oh I got you wrong ! Sorry :D

Actually clean install with the FreeBSD runfile had sickrage running with locale "none", which caused issues with all the accented chars in my library. Having it run under en/utf8 fixes it. I guess it's because this locale, even if the language does not use accents, is able to display and understand them.

**Comment by miigotu** [comment]
We can't force a language. User has to do this on their own

**Comment by Twanislas** [comment]
Well that's one fair point :/ :).
Would it be better to detect if any locale is set, and if not only, set it to en utf8 ?

**Comment by miigotu** [comment]
@Twanislas the problem with locale being none is an environment problem, it is fixed in newer versions of linux.

**Comment by Twanislas** [comment]
Good to know miigotu ! Thank you ! Any link to documentation about the issue somewhere ?

Cheers !

**Comment by miigotu** [comment]
There are tons, just goofle 14.04 locale issue.

Anyways, I think the fix is supposed to be the below (but it doesnt always work):

```
sudo nano /etc/default/locale 
```

make sure it has this line:

```
LC_ALL=en_US.UTF-8
```

Then

```
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
```

You can also add

```
LC_ALL="en_US.utf8"
```

to

```
/etc/environment
```

Afterwards, reboot

**Comment by Twanislas** [comment]
Thanks miigotu !

Strange that I still have the issue using SickRage on FreeNAS 9.10 :/
I'll dig :)

**Pull request closed without merging**
