### PR TITLE
Fix saving subtitles plugins selection

### PR DESCRIPTION
**Pull request by miigotu**
Rebased on develop
From #190

### CODE REVIEW

**Comment by miigotu** [comment]
@OmgImAlexis if this breaks something, please revert. Need to get it tested before merge to master today.

**Comment by eucalyptus30** [comment]
@miigotu this doesn't braak anything. :smile: 
Trrruuusssttt mmeeeeeee

**Comment by OmgImAlexis** [comment]
@eucalyptus30 all js changes go through me, that's why he pinged me.

**Comment by eucalyptus30** [comment]
@OmgImAlexis i know. i was joking :smile:

**Pull request merged**
