### PR TITLE
detect damaged sickbeard.db files that have been produced by recent v…

### PR DESCRIPTION
**Pull request by coderbone**
…ersions of SRTV

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by coderbone** [comment]
dammit... I obviously still haven't got the rebase thing right... please hold off bouncing this while I try to get this into my noggin

**Comment by duramato** [comment]
Is it always v.1 ?

**Comment by coderbone** [comment]
Damn, yes, I should look more closely at where the 1 comes from.

**Comment by coderbone** [comment]
Hmmm, after trying several different commits of SRTV I can't get it to corrupt a good file so I can't say for sure how a 1 got in db_version.  I do have a file that is damaged in this way and SRTV must have done it recently (otherwise it's previously working version detection would have kicked in and fixed the file).

Do not merge seems like the correct resolution for this PR.  Thanks guys for making me do the work properly w.r.t. analysis of the problem.  Not that you care but I did PR a fix for checkDBVersion back to SRTV so at least some people may benefit.

**Comment by coderbone** [comment]
without tackling the wider issue of upgrading SB databases this PR is no good... closing it off

**Pull request closed without merging**
