### PR TITLE
Refactor home

### LINKED ISSUE #2902: Tabbed show list
I split my shows in normal shows and anime shows.
But I find it a bit annoying that I always have to scroll down to see my anime list.
Perhaps you could consider having a tabbed show list?
So when the flag 'split show lists' is enabled, 2 tabs are shown instead of splitting then on the same screen.
Just an idea. What do you think?

### PR DESCRIPTION
**Pull request by h3llrais3r**
Fixes #2902 but now with option to have a tabbed split or not (to not impact other users).
This is a temporary solution until we refactor the complete view options as discussed in https://github.com/SickRage/SickRage/pull/2904

- [x] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
I see you removed some conversions of airdates and localtimes, among other things.
If I merge this, you will fix anything that pops up because of that right?

**Comment by miigotu** [comment]
My bad man, github collapsed the file so find in page didnt show it -.-

**Comment by miigotu** [comment]
Merged manually do to conflict

**Pull request closed without merging**
