### PR TITLE
Added Amazon SNS Notifier

### PR DESCRIPTION
**Pull request by benburkhart1**
Fixes #

Proposed changes in this pull request:
- Adds a Amazon AWS SNS Notifier to SickRage

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
You'll need to include boto3 in libs/

**Comment by benburkhart1** [comment]
Done.

**Comment by miigotu** [comment]
Man, those dependencies are a bit much. There is no other way to use SNS __SIMPLY__?

**Comment by OmgImAlexis** [comment]
@miigotu you may want to look at redoing this yourself so 500k+ lines aren't added without being verified. No offense @benburkhart1 just overall miigotu has only add around 800k lines and there could be anything in this commit since it's so large.

**Comment by miigotu** [comment]
Exactly why I asked that question =P. With 2 existing SMS notifiers (among the dozens of other way for notifications) there is no way we can justify 500k+ lines to get SMS notifications that we already have.

**Comment by benburkhart1** [comment]
Let me take a look tonight. I was going to add a general webhook as well, which if we had that, I could do the SNS stuff in my own infrastructure.

**Comment by benburkhart1** [comment]
Also these are not SMS notifiers. SNS is a general notification system. It can later run a lambda function, email, sms, etc.

**Pull request closed without merging**
