### PR TITLE
Fix broken HorribleSubs provider (#4810 & #4841).

### LINKED ISSUE #4810: 404 Client Error when searching with HorribleSubs
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d
OS: Linux-4.4.19-unRAID-x86_64-with
Browser: Chrome
What you did: Did a manual search for an episode.
What happened: Got a request failed: 404 Client Error
Logs:
```
2018-07-07 01:30:00 INFO SEARCHQUEUE-MANUAL-346948 :: Unable to find a download for: [Harukana Receive - 001 - We Don't Need Aces]
2018-07-07 01:30:00 INFO SEARCHQUEUE-MANUAL-346948 :: [HorribleSubs] :: Request failed: 404 Client Error: Not Found for url: https://www.horriblesubs.info/lib/search.php?nextid=0&value=Harukana+Receive+01
2018-07-07 01:30:00 INFO SEARCHQUEUE-MANUAL-346948 :: [HorribleSubs] :: Request failed: 404 Client Error: Not Found for url: https://www.horriblesubs.info/lib/search.php?nextid=0&value=Harukana+Receive+001
2018-07-07 01:30:00 INFO SEARCHQUEUE-MANUAL-346948 :: [HorribleSubs] :: Performing episode search for Harukana Receive
2018-07-07 01:30:00 INFO SEARCHQUEUE-MANUAL-346948 :: Beginning manual search for: [Harukana Receive - 001 - We Don't Need Aces]
```

### PR DESCRIPTION
**Pull request by Anras573**
Fixes #4810 and #4841 

HorribleSubs had changed urls and structure, so I updated the HorribleSubs provider.

Please be aware that I'm not a Python developer, so if there is any issues, please tell me, and I'll try to correct them 👍 

Proposed changes in this pull request:
-
- New URLs for RSS feed and search API
- New structure for both search and RSS feed

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by spudsrus** [comment]
How long do these usually take to get approved? O.o

**Comment by HappyChubbs** [comment]
Great job.

Made the changes to the file and everything is working.

2018-09-09 04:02:43 INFO SEARCHQUEUE-MANUAL-294002 :: Downloading [HorribleSubs].Overlord.III.-.08.[1080p:] from HorribleSubs
2018-09-09 04:02:43 INFO SEARCHQUEUE-MANUAL-294002 :: [HorribleSubs] :: Quality of [HorribleSubs].Overlord.III.-.08.[1080p:] is 1080p HDTV
2018-09-09 04:02:43 INFO SEARCHQUEUE-MANUAL-294002 :: [HorribleSubs] :: Quality of [HorribleSubs].Overlord.III.-.08.[1080p:] is 1080p HDTV
2018-09-09 04:02:40 INFO SEARCHQUEUE-MANUAL-294002 :: [HorribleSubs] :: Performing episode search for Overlord

**Review by Sungray — APPROVED** [review]

**Comment by Sungray** [comment]
Let's merge this please.

**Review by HappyChubbs — APPROVED** [review]

**Comment by miigotu** [comment]
:+1:

**Pull request merged**
