### PR TITLE
Adding Slack notification for snatches and downloads

### PR DESCRIPTION
**Pull request by forge33**
Fixes #

Proposed changes in this pull request:
- Ability to configure Slack notifier for when a snatch or download happens
- Based on Slack Incoming WebHooks
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by RolfKoenders** [comment]
Nice thanks! I was about to start on this today haha :+1: When will this be merged to master?

**Comment by miigotu** [comment]
as soon as I get some time i will merge it, can you make sure its working well for you first?

**Comment by forge33** [comment]
I've tested it thoroughly already, however I realize I didn't add an option for subtitle downloads/etc. Also code coverage.

**Comment by RolfKoenders** [comment]
@miigotu I can test it sunday, so maybe you want to merge already before.
@forge33 I think its nice to add the subtitle download notifications as well.

**Comment by miigotu** [comment]
@forge33 Its just usually preferable to get a second person to test it, because we as developers sometimes might miss some small detail that someone else sees. Alas, i'll merge it to master anyways since it cant break anything important even if it did have a bug. (Plus I looked the code over before I merged it into develop and it looks solid, good work!)

**Comment by forge33** [comment]
Sweet, may in the future add Web API integration as well, the Webhook was a low hanging fruit

**Pull request merged**
