### PR TITLE
Fix SickRage/sickrage-issues/issues/480

### PR DESCRIPTION
**Pull request by fernandog**
Fixes https://github.com/SickRage/sickrage-issues/issues/480

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by fernandog** [comment]
@medariox @miigotu

**Comment by miigotu** [comment]
This doesnt fix anything. Using `is` for True/False/None is exactly the same behavior as `==`

@labrys ?

**Comment by fernandog** [comment]
@miigotu sorry, lost that in my rebase (i removed the 'add ssl' commit)

need to add another ehlo() after starttls()

**Comment by miigotu** [comment]
Your rebase script sucks lol, you swallowed my commits on the other PR as your own

**Comment by fernandog** [comment]
I just rebased the commits! keept your commit name

**Comment by miigotu** [comment]
The ssl_warning one.

Anyways, the second ehlo is the correct fix for this, but only that.

```
S: 220 smtp.server.com Simple Mail Transfer Service Ready
C: EHLO client.example.com
S: 250-smtp.server.com Hello client.example.com
S: 250-SIZE 1000000
S: 250-AUTH LOGIN PLAIN CRAM-MD5
S: 250-STARTTLS
S: 250 HELP
C: STARTTLS
S: 220 TLS go ahead
C: EHLO client.example.com *
S: 250-smtp.server.com Hello client.example.com
S: 250-SIZE 1000000
S: 250-AUTH LOGIN PLAIN CRAM-MD5
S: 250 HELP
C: AUTH LOGIN
S: 334 VXNlcm5hbWU6
C: adlxdkej
S: 334 UGFzc3dvcmQ6
C: lkujsefxlj
S: 235 2.7.0 Authentication successful
C: MAIL FROM:<mail@samlogic.com>
S: 250 OK
C: RCPT TO:<john@mail.com>
S: 250 OK
C: DATA
S: 354 Send message, end with a "." on a line by itself
C: <The message data (body text, subject, e-mail header, attachments etc) is sent>
S .
S: 250 OK, message accepted for delivery: queued as 12345
C: QUIT
S: 221 Bye

*) The client sends the EHLO command again to the e-mail server and starts the communication from the beginning, but this time the communication will be encrypted until the QUIT command is sent.
```

**Comment by fernandog** [comment]
should I revert to "is True" ?

**Comment by medariox** [comment]
@fernandog 
As far as I can see we don't even need that comparison, use_tls is either 1 or 0.

**Comment by fernandog** [comment]
@miigotu @medariox done

**Comment by miigotu** [comment]
You have to leave the `use_tls is True`

Why is it so hard to just add the second ehlo?

**Pull request merged**
