### PR TITLE
Partialy fix SickRage/sickrage-issues/issues/196

### PR DESCRIPTION
**Pull request by fernandog**
Avoid thread crash if anything goes wrong with sql results

added try:except:continue

@miigotu @medariox ok?

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu @labrys so how come the thread crashes?

with this PR I get the log error and FINDSUBTITLES continues:

```
FINDSUBTITLES :: Error while searching subtitles for The Originals S02E08. Error: "time data 'al (imdb display ti' does not match format '%Y-%m-%d %H:%M:%S'"
```

without I get:
image

**Comment by miigotu** [comment]
What does that have to do with our comments on the PR?

Just remove these lines

``` python
                # http://bugs.python.org/issue7980#msg221094
                # I dont think this needs done here, but keeping to be safe (Recent shows rule)
                datetime.datetime.strptime('20110101', '%Y%m%d')
```

**Comment by miigotu** [comment]
Now, when that exception is thrown, you should update that episode's last search time to something like:

``` python
from sickrage.helper.common import dateTimeFormat
datetime.datetime(2015, 1, 1).strftime(dateTimeFormat)

```

That way the next time the subtitle finder is ran, the subs for that ep will be searched.

**Comment by fernandog** [comment]
@miigotu can you commit this in this PR? need more code than that isn't?

**Pull request merged**
