### PR TITLE
Fix for #1773 IMDB Popular show sorting by votes

### LINKED ISSUE #1773: Popular IMDB Shows aren't sorted correctly
The Add Show from IMDB page doesn't sort correctly when sorting by number of votes,

Example:
```
Sense8
84% 61,197 votes
```
Is seen as 61 votes

### PR DESCRIPTION
**Pull request by stephenknoth**
Fixes #1773 

Proposed changes in this pull request:
- Changed votes sorting to use a callback that strips all non-numeric characters and returns an int of the number of votes to be used in sorting

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Hi, please rebase on develop and PR to develop branch, thanks.

**Comment by miigotu** [comment]
Also the correct fix is in mako, not cluttering the js more than it already is =P (it could also be fixed in the show object when loading info from imdb)

@beschoenen 
gui/slick/views/trendingShows.mako:

```
- data-rating="${cur_show['show']['rating']}" data-votes="${cur_show['show']['votes']}">
+ data-rating="${cur_show['show']['rating']}" data-votes="${cur_show['show']['votes'].replace(',', '')}">
```

gui/slick/views/addShows_popularShows.mako: 

```
- data-votes="${cur_votes}">
+ data-votes="${cur_votes.replace(',', '')}">
```

**Comment by beschoenen** [comment]
2805780

**Pull request closed without merging**
