### PR TITLE
Cookie sessions for torrent client (qbittorrent API >=2) 

### PR DESCRIPTION
**Pull request by lulandco**

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [ ] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by labrys** [comment]
@lulandco please use a topic branch when you do a PR instead of pushing your dev branch

**Comment by lulandco** [comment]
Sorry, not familiar with the rules in use. I close this one.

**Comment by fernandog** [comment]
not a rule. But if you are going create more than one PR you will have trouble/conflict
PR should always be based on latest develop. not another PR

**Comment by labrys** [comment]
@lulandco take a look at https://github.com/SickRage/SickRage/blob/master/contributing.md

**Pull request closed without merging**
