### PR TITLE
Some changes to the help & info page.

### PR DESCRIPTION
**Pull request by neoatomic**
- Created one singe sprites file for all the icons.
- Changed the width back to 100%.
- Changed the locale & wiki icons.
- Changed names in the code to be more clear.
- Changed the names a little so they stay on one line instead of two.
- Removed the two old icon files.

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by duramato** [comment]
The arguments look wierd

**Comment by neoatomic** [comment]
Think its because the long arguments the Syno uses for starting SR. The code itself looks ok to me.

**Comment by miigotu** [comment]
Im not a fan of the name changes, they make less sense now. `Path:`?

**Comment by neoatomic** [comment]
If i make them longer, they will use two lines, witch doesn't look very good...
As i didn't know another way, i just shorted the names. Is there another way to get that done, so i can use longer names.?

Anyway i was also thinking about moving all icons to a singe icon folder. Any thoughts on that.?

**Comment by OmgImAlexis** [comment]
I'd suggest we add this CSS to align the headers to the top.

```
.infoTableHeader {
    vertical-align: top;
}
```

screen shot 2016-01-31 at 11 07 52 am

**Comment by neoatomic** [comment]
@OmgImAlexis Thanks, that does fix the `arguments` line-out. :)

But i'm still looking for a way to get the `width` correctly, so longer text stays on one line.

**Comment by neoatomic** [comment]
Another try. :

**Comment by OmgImAlexis** [comment]
That looks fine, I think we should just merge as is. Approved!

**Comment by miigotu** [comment]
Approved has to be at the start of the line =P

[Approved with PullApprove](https://pullapprove.com/SickRage/SickRage/pull-request/890/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=SickRage/SickRage)

**Comment by OmgImAlexis** [comment]
Well that's silly.. :-1:

**Pull request merged**
