### PR TITLE
Update french translations

### PR DESCRIPTION
**Pull request by delphiki**
Fixes #

Proposed changes in this pull request:
- Fix a few typos in french translations (I did not read the whole file, just covered the first ~25% for now)
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Hey, all translations are handled on http://crowdin.com/projects/sickrage

**Comment by miigotu** [comment]
Translations should be edited on http://crowdin.com/project/sickrage

**Comment by delphiki** [comment]
My bad, I'll report my corrections over there. Thanks!

**Pull request closed without merging**
