### PR TITLE
new domain

### PR DESCRIPTION
**Pull request by darkvadehors**
Fixes #
## 
## 
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
normally this should be based on the develop branch, but I will allow it this time and merge it into develop myself.

Thanks.

**Comment by darkvadehors** [comment]
thank,i'm sorry it's my first commit,  it just a little change for a french domain.

**Comment by miigotu** [comment]
yeah, its no problem. I already pulled it into develop also.  Just for next time, PR's should be based on the develop branch, and PR'd to the develop branch, because we usually incubate changes for a while in develop before pushing them out to users.

**Pull request merged**
