### PR TITLE
Fix test in Windows

### PR DESCRIPTION
**Pull request by MGaetan89**
Waiting on @labrys's feedback until this can be merged.

https://github.com/SickRage/SickRage/pull/350

### CODE REVIEW

**Comment by labrys** [comment]
Missed one

```
======================================================================
FAIL: test_get_default_media_name (sickrage_tests.media.show_network_logo_tests.ShowNetworkLogoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python\sick.dev\tests\sickrage_tests\media\show_network_logo_tests.py", line 46, in test_get_default_media_name
    self.assertEqual(ShowNetworkLogo(0, '').get_default_media_name(), 'network/nonetwork.png')
AssertionError: 'network\\nonetwork.png' != 'network/nonetwork.png'
```

**Comment by MGaetan89** [comment]
I updated the PR. I'll merge it if there is nothing else to fix related to Windows.

**Comment by labrys** [comment]
Looks good.

**Comment by MGaetan89** [comment]
Thanks. Tests are fixed in `develop` now ;)

**Pull request merged**
