### PR TITLE
Fix schedule table layout

### PR DESCRIPTION
**Pull request by h3llrais3r**
Fixes https://github.com/SickRage/SickRage/issues/2526

### CODE REVIEW

**Comment by h3llrais3r** [comment]
@sharkykh @miigotu Can we merge?

**Comment by sharkykh** [comment]
~I'm not seeing any difference on the page?~

~There's still a horizontal scrollbar.~
~https://cloud.githubusercontent.com/assets/10238474/24831127/9c016150-1c9c-11e7-95a8-931e0244c639.png~

---

Edit: Was looking at this the wrong way. I'll check again later.

**Comment by sharkykh** [comment]
Still not seeing a change. It works fine for me as it is - without any changes [on a27ef187afda4399f39b076bfbbc4157e2fbd156]

**Comment by h3llrais3r** [comment]
@sharkykh  you only have the problem when you have series with long names. Then you have an overflow and scrollbars are shown. With the fix, the long names are wrapped an no scrollbars are shown.

**Comment by miigotu** [comment]
iirc making it not wrap was intentional.

**Comment by h3llrais3r** [comment]
I think it's still better to wrap it and have no scrollbars...
But feel free to merge it or not... I never use the schedule anyway. :rofl:

**Comment by miigotu** [comment]
I prefer to not have scroll bars too, I just cannot remember why they wanted it to not wrap

**Pull request merged**
