### PR TITLE
change yggtorrent url

### PR DESCRIPTION
**Pull request by skillfr**
Fixes #

Proposed changes in this pull request:
-
-
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by lediabolo** [comment]
Hi
New URL for yggtorrent is:
https://ww3.yggtorrent.is

regards

**Comment by skillfr** [comment]
Merge please ! Ygg does not work anymore

**Comment by lediabolo** [comment]
Hi
Since few day, new URL for yggtorrent is:
https://ww3.yggtorrent.is

Currently, the change seem don't works. 

> 2018-08-09 19:13:14 SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: Invalid username or password. Check your settings

My settings seem correct. Username/password are right.

regards

**Comment by skillfr** [comment]
@lediabolo it's normal the developer has not merged yet

**Comment by lediabolo** [comment]
Thanks. Wait the merged :)

**Pull request merged**
