### PR TITLE
Change to DisplayShow to display fanart as background and banner image

### PR DESCRIPTION
**Pull request by wimpyrbx**
Fixes #

Proposed changes in this pull request:
- display background fanart and banner on DisplayShow page
- to do this a new js called backstretch is utilized
- only dark.css edited so far. will do light.css if this is picked up.
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
1. This should be based on the `develop` branch, not `master`.
2. Unless there's an option to disable this I can't see any of the other devs merging it since most people like the current view and this would drastically change it.

**Comment by miigotu** [comment]
@wimpyrbx we are definitely interested in this, but as @OmgImAlexis said there should be a few changes to it first.

Im unsure how possible it would be to make it configurable, but if there is a way it should be done.
It must be based on develop and PR'd to develop
The backstretch js should be concat and minified along with the other js via bower I think.

**Comment by wimpyrbx** [comment]
ok i'm fairly new to git and all so i must apologize if my attempts to contribute are noobish in the start.
i'll keep trying to do some stuff locally to see if i can make it better as it looks like this is a "backburner" feature at the time being, which is fine :) I'm just eager to help in any way i can :+1:

**Pull request closed without merging**
