### PR TITLE
Fix pretty_file_size...

### PR DESCRIPTION
**Pull request by labrys**
...and lint common_tests 10/10

Fixes SickRage/sickrage-issues#104

### CODE REVIEW

**Comment by MGaetan89** [comment]
What's the point if splitting the tests like that?

**Comment by Arcanemagus** [comment]
Maybe so it's easier to pinpoint whether it's failing due to a bug in the logic, or due to unicode handling?

**Comment by labrys** [comment]
@MGaetan89 I split the dict because the unicode strings weren't being tested.  The dict had the same key as both a unicode and non-unicode string, which it sees as the exact same key.  While not all of the unicode strings may be duplicates in all of the places I split the tests, I did so to ensure that if additional tests were added later we didn't run into the same issue.

**Comment by labrys** [comment]
If you run the test prior to the `pretty_file_size` fix you will see that the test fails, and if you run the test prior to me splitting them, you will see the test does not fail, because of the duplicate key issue (which is related to how Python 2 does some behind the scenes conversion of strings).

**Pull request merged**
