### PR TITLE
Fix tablesorter

### PR DESCRIPTION
**Pull request by h3llrais3r**
Fixes tablesorter undefined error when calling toLowerCase() in certain cases. (Fixes https://github.com/SickRage/SickRage/issues/3579)
Fix sorting for quality.

### CODE REVIEW

**Comment by miigotu** [comment]
You have to keep the lowercase.

**Comment by sharkykh** [comment]
@miigotu I disagree: https://github.com/SickRage/SickRage/issues/3579#issuecomment-290999083

**Comment by miigotu** [comment]
How does it not affect the filtering?

**Comment by miigotu** [comment]
Also, ignoreCase is not set anywhere as far as I can tell.

**Comment by miigotu** [comment]
Ok, seems you are right. ignoreCase became default in v2.2, filter_ignoreCase became default in 2.3.4
```
filter_ignoreCase	Boolean	true	Filter widget: Set this option to false to make the column content search case-sensitive, so typing in "a" will not find "Albert". (v2.3.4)
```

**Comment by sharkykh** [comment]
Yep.
You figured it out by the time it took me to [find it](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#options) using my phone... :)
I simply remembered that I checked it once some time ago and it worked out of the box.

**Comment by miigotu** [comment]
Anyways, I will have to test because I know the search/replace for the quality extractor does not work on all of those.  We use the text because that is what people search by

**Comment by sharkykh** [comment]
I just remembered that I checked it one time some time ago and it worked out of the box.

**Comment by h3llrais3r** [comment]
@miigotu I fixed the search on quality :rofl: 
It's part of the PR because I saw it was not working on all tables.

**Comment by OmgImAlexis** [comment]
This is just bound to create issues later on, use data attributes like the docs state.

**Comment by h3llrais3r** [comment]
You're right, but this is just a quick fix for something that was not working as it should.

**Comment by h3llrais3r** [comment]
@sharkykh @miigotu Can we still merge?

**Comment by OmgImAlexis** [comment]
@h3llrais3r adding quick fixes is the reason sickrage ends up with so much broken code. If you're going do it you might as well just do it right from the start.

**Pull request closed without merging**
