### PR TITLE
Add torrent provider nCore

### PR DESCRIPTION
**Pull request by wroadd**
Fixes #
Added torrent provider nCore with RSS and Episode search.

Proposed changes in this pull request:
-
-
-

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Review by wroadd — COMMENTED** [review]
the missing line was fixed (ncore.py line 34)

**Review by wroadd — COMMENTED** [review]
truncated lines fixed in ncore.py

**Comment by miigotu** [comment]
hehe why no whitespace?

**Comment by wroadd** [comment]
You mean the segmentation of the code?

**Comment by miigotu** [comment]
Blank lines after returns, and before class methods and 2 blanks lines before a class definition. Also after a break/continue and after logic contained in an if block
https://www.python.org/dev/peps/pep-0008/#blank-lines

**Comment by miigotu** [comment]
Also, please change the target branch to develop please.

**Review by wroadd — COMMENTED** [review]
Whitespace added

**Pull request merged**
